SELECT
ID
,IS_DELETED
,NAME
,SETUP_OWNER_ID
,CREATED_DATE
,CREATED_BY_ID
,LAST_MODIFIED_DATE
,LAST_MODIFIED_BY_ID
,SYSTEM_MODSTAMP
,PAYOUT_PROFILE_NAME_C
,_FIVETRAN_SYNCED
FROM {{ source('salesforce_msec', 'payout_tab_access_to_profile_c') }}