SELECT
ID
,IS_DELETED
,NAME
,SETUP_OWNER_ID
,CREATED_DATE
,CREATED_BY_ID
,LAST_MODIFIED_DATE
,LAST_MODIFIED_BY_ID
,SYSTEM_MODSTAMP
,PAYOUT_CLIENT_ID_C
,PAYOUT_CLIENT_SECRET_C
,PAYOUT_ENDPOINT_C
,PAYOUT_PASSWORD_C
,PAYOUT_USERNAME_C
,_FIVETRAN_SYNCED
FROM {{ source('salesforce_msec', 'payout_ofac_cs_c') }}