SELECT
ID
,IS_DELETED
,NAME
,CREATED_DATE
,CREATED_BY_ID
,LAST_MODIFIED_DATE
,LAST_MODIFIED_BY_ID
,SYSTEM_MODSTAMP
,CONNECTION_RECEIVED_ID
,CONNECTION_SENT_ID
,PAYOUT_STATE_LICENSE_C
,_FIVETRAN_SYNCED       
FROM {{ source('salesforce_msec', 'payout_line_of_authority_c') }}