SELECT
ID
,OWNER_ID
,IS_DELETED
,NAME
,CREATED_DATE
,CREATED_BY_ID
,LAST_MODIFIED_DATE
,LAST_MODIFIED_BY_ID
,SYSTEM_MODSTAMP
,LAST_VIEWED_DATE
,LAST_REFERENCED_DATE
,ORG_ID
,PARENT_ID
,_FIVETRAN_SYNCED
FROM {{ source('salesforce_msec', 'business_brand') }}