SELECT
ID
,OWNER_ID
,IS_DELETED
,NAME
,CREATED_DATE
,CREATED_BY_ID
,LAST_MODIFIED_DATE
,LAST_MODIFIED_BY_ID
,SYSTEM_MODSTAMP
,LAST_VIEWED_DATE
,LAST_REFERENCED_DATE
,CONNECTION_RECEIVED_ID
,CONNECTION_SENT_ID
,_FIVETRAN_SYNCED
FROM {{ source('salesforce_msec', 'payout_nipr_update_c') }}