SELECT
ID
,IS_DELETED
,NAME
,SETUP_OWNER_ID
,CREATED_DATE
,CREATED_BY_ID
,LAST_MODIFIED_DATE
,LAST_MODIFIED_BY_ID
,SYSTEM_MODSTAMP
,PAYOUT_VALUE_CURRENCY_C
,PAYOUT_VALUE_STRING_C
,_FIVETRAN_SYNCED
FROM {{ source('salesforce_msec', 'payout_create_payments_settings_c') }}