SELECT
ID
,IS_DELETED
,NAME
,CREATED_DATE
,CREATED_BY_ID
,LAST_MODIFIED_DATE
,LAST_MODIFIED_BY_ID
,SYSTEM_MODSTAMP
,CONNECTION_RECEIVED_ID
,CONNECTION_SENT_ID
,PAYOUT_ADVISOR_C
,_FIVETRAN_SYNCED
,LAST_REFERENCED_DATE
,LAST_VIEWED_DATE
FROM {{ source('salesforce_msec', 'payout_regulatory_action_c') }}