select
    mstarid                                as mstarid
    , cusip                                as cusip
    , ticker                               as ticker
    , fundstandardname                     as fundstandardname
    , fundname                             as fundname
    , securitytype                         as securitytype
    , shareclasstype                       as shareclasstype
    , globalcategoryname                   as globalcategoryname
    , categoryname                         as categoryname
    , marketcapital                        as marketcapital
    , equitystylebox                       as equitystylebox
    , equitystyleboxname                   as equitystyleboxname
    , equitystyleboxshort                  as equitystyleboxshort
    , equitystyleboxshortname              as equitystyleboxshortname
    , fixedincomestylebox                  as fixedincomestylebox
    , fixedincomestyleboxname              as fixedincomestyleboxname
    , percentilerank3mth                   as percentilerank3mth
    , percentilerankytd                    as percentilerankytd
    , percentilerank5yr                    as percentilerank5yr
    , percentilerank10yr                   as percentilerank10yr
    , percentilerank15yr                   as percentilerank15yr
    , return1mth                           as return1mth
    , return3mth                           as return3mth
    , return5yr                            as return5yr
    , return10yr                           as return10yr
    , return15yr                           as return15yr
    , bondlong                             as bondlong
    , bondnet                              as bondnet
    , bondshort                            as bondshort
    , cashlong                             as cashlong
    , cashnet                              as cashnet
    , cashshort                            as cashshort
    , convertiblelong                      as convertiblelong
    , convertiblenet                       as convertiblenet
    , convertibleshort                     as convertibleshort
    , otherlong                            as otherlong
    , othernet                             as othernet
    , othershort                           as othershort
    , portfoliodate                        as portfoliodate
    , preferredlong                        as preferredlong
    , preferrednet                         as preferrednet
    , preferredshort                       as preferredshort
    , stocklong                            as stocklong
    , stocknet                             as stocknet
    , stockshort                           as stockshort
    , largeblend                           as largeblend
    , largegrowth                          as largegrowth
    , largevalue                           as largevalue
    , midblend                             as midblend
    , midgrowth                            as midgrowth
    , midvalue                             as midvalue
    , smallblend                           as smallblend
    , smallgrowth                          as smallgrowth
    , smallvalue                           as smallvalue
    , netmargin                            as netmargin
    , totalmarketvaluelong                 as totalmarketvaluelong
    , totalmarketvaluenet                  as totalmarketvaluenet
    , totalmarketvalueshort                as totalmarketvalueshort
    , totalyieldlong                       as totalyieldlong
    , fundnetassets                        as fundnetassets
    , netassetsdate                        as netassetsdate
    , normalizedfundnetassets              as normalizedfundnetassets
    , countryexposure_country              as countryexposure_country
    , countryexposure_value                as countryexposure_value
    , countryexposure_country_2            as countryexposure_country_2
    , countryexposure_value_2              as countryexposure_value_2
    , countryexposure_country_3            as countryexposure_country_3
    , countryexposure_value_3              as countryexposure_value_3
    , countryexposure_country_4            as countryexposure_country_4
    , countryexposure_value_4              as countryexposure_value_4
    , countryexposure_country_5            as countryexposure_country_5
    , countryexposure_value_5              as countryexposure_value_5
    , countryexposurebond_country          as countryexposurebond_country
    , countryexposurebond_value            as countryexposurebond_value
    , countryexposurebond_country_2        as countryexposurebond_country_2
    , countryexposurebond_value_2          as countryexposurebond_value_2
    , countryexposurebond_country_3        as countryexposurebond_country_3
    , countryexposurebond_value_3          as countryexposurebond_value_3
    , countryexposurebond_country_4        as countryexposurebond_country_4
    , countryexposurebond_value_4          as countryexposurebond_value_4
    , countryexposurebond_country_5        as countryexposurebond_country_5
    , countryexposurebond_value_5          as countryexposurebond_value_5
    , countryexposureconvertible_country   as countryexposureconvertible_country
    , countryexposureconvertible_value     as countryexposureconvertible_value
    , countryexposureconvertible_country_2 as countryexposureconvertible_country_2
    , countryexposureconvertible_value_2   as countryexposureconvertible_value_2
    , countryexposureconvertible_country_3 as countryexposureconvertible_country_3
    , countryexposureconvertible_value_3   as countryexposureconvertible_value_3
    , countryexposureconvertible_country_4 as countryexposureconvertible_country_4
    , countryexposureconvertible_value_4   as countryexposureconvertible_value_4
    , countryexposureconvertible_country_5 as countryexposureconvertible_country_5
    , countryexposureconvertible_value_5   as countryexposureconvertible_value_5
    , countryexposureequity_country        as countryexposureequity_country
    , countryexposureequity_value          as countryexposureequity_value
    , countryexposureequity_country_2      as countryexposureequity_country_2
    , countryexposureequity_value_2        as countryexposureequity_value_2
    , countryexposureequity_country_3      as countryexposureequity_country_3
    , countryexposureequity_value_3        as countryexposureequity_value_3
    , countryexposureequity_country_4      as countryexposureequity_country_4
    , countryexposureequity_value_4        as countryexposureequity_value_4
    , countryexposureequity_country_5      as countryexposureequity_country_5
    , countryexposureequity_value_5        as countryexposureequity_value_5
    , mtype                                as mtype
    , _created_at                          as record_date
    , _created_at::timestampntz            as record_datetime
    , effective_date                       as effective_date
    , _created_at::timestampntz            as _created_at
    , _source_file                         as _source_file
    , _id                                  as _id
from {{ ref('morningstar_history__stg_fund') }}
