select
    'tamarac' as pms
    , 'state_college' as pms_location
    , 'mwa' AS firm_source
    , effective_date
    , account__net_worth_category
    , account__ownership_type
    , account__primary_owner_email
    , account_current_value
    , account_long_term_realized_gain_loss
    , account_name
    , account_number
    , account_short_term_realized_gain_loss
    , account_total_realized_gain_loss
    , account_type
    , accounts_not_to_be_billed
    , address1
    , address2
    , address3
    , address4
    , address5
    , address6
    , advisor
    , advisor_1
    , advisor_2
    , advisor_3
    , advisor_4
    , advisor_5
    , advisor_view
    , amortization_calculation_enabled
    , annual_turnover
    , annualized_gross_irr
    , annualized_gross_twr
    , annualized_net_irr
    , annualized_net_twr
    , aum_indicator
    , average_daily_balance
    , benchmark
    , benchmark_start_date
    , beneficial_billing_rate_tier_treatment
    , billing_closed_date
    , billing_definitions
    , billing_groups
    , billing_inception_date
    , birthday
    , broker_dealer
    , calculate_performance
    , city
    , closed_date
    , closing_value
    , commissions
    , compute_billing_closed_date
    , compute_billing_inception_date
    , compute_performance_inception_date
    , cons_assets_pc_assignment
    , cons_assets_pc_assignment_3
    , cons_assets_pc_assignment2
    , country
    , cumulative_turnover
    , current_cash
    , custodian
    , default__billed_account
    , default_template
    , description
    , direct_bill
    , discretionary
    , display_accrued_interest
    , display_preference
    , distribution
    , dollar_variance
    , entity_type
    , exceptions
    , exclude_all_securities_from_billing
    , exclude_all_securities_from_performance
    , exclude_from_portal_upload
    , expenses_excluding_revenue
    , expenses_percent_of_account
    , first_name
    , fiscal_year_end
    , fiscal_year_end_date_use_for_reporting
    , gross_irr
    , gross_twr
    , household
    , household_advisor
    , household_assignments
    , include_accrued_dividends
    , include_accrued_gains
    , include_for_13f_reporting
    , include_in_advisor_rebalancing
    , inflows
    , initial_value
    , interest__dividends
    , internal_commissions
    , last_name
    , last_rebal_date
    , last_reconciliation_date
    , last_sync_start_date
    , last_sync_time
    , managed_account_value_preveod
    , management_fees
    , management_fees_and_commissions
    , manual_performance_history_end_date
    , manual_performance_return_behavior
    , manual_performance_value_behavior
    , margin
    , margin_expense
    , master_account
    , net_flows
    , net_investment_gain
    , net_irr
    , net_twr
    , new_accounts
    , new_accounts__trading
    , next_sync_start_date
    , number_of_trades
    , objective
    , objective_start_date
    , orion_transfers
    , out_of_tolerance
    , outflows
    , ownership_account_type
    , ownership_parent_account
    , paper
    , paper_appraisals
    , paper_reports_exceptions
    , paper_reports_jmlv
    , pc_modelset
    , pc_performance_set2
    , pc_performance_set3
    , pc_performance_set4
    , pc_performance_set5
    , pc_performance_set6
    , pc_static_set
    , pcadvisor_name
    , pcsetid
    , percent_variance
    , performance
    , performance_date
    , performance_inception_date
    , portfolio_yield
    , prev_eod_date
    , previous_12_months_turnover
    , primary_advisor
    , primary_household_id
    , primary_household_primary_advisor
    , primary_household_primary_advisor_id
    , purchases
    , rebalancing_model_name
    , reconciliation_status
    , sales
    , service_team_compliance
    , service_team_csa
    , service_team_name
    , service_team_operations
    , service_team_primary_advisor
    , service_team_secondary_advisor
    , service_team_soliciter
    , service_team_trade_approver
    , service_team_trader
    , short_name
    , sma
    , sma_asset_class
    , sma_description1
    , sma_description2
    , sma_description3
    , sma_sector
    , sma_subsector
    , sma_tas_security
    , source_of_record_for_realized_gain_loss_is_custodian
    , specific_trading_instructions
    , state
    , state_of_primary_residence
    , tamarac_upload
    , target_allocation
    , taxable
    , total_account_value_preveod
    , total_cash_reserves
    , traded_away_commissions
    , trailing_3_years_net_return_annualized
    , trailing_5_years_net_return_annualized
    , unmanaged_account_value_preveod
    , upload_account_id
    , use_primary_household_address
    , zip
    , {{ col_is_head(reference=source('tamarac_state_college', 'financial_accounts')) }}
    , {{ col_is_current(date_col='effective_date') }}
    , record_datetime as _source_loaded_at
from {{ source('tamarac_state_college', 'financial_accounts') }}