select
    location_name
    ,start_date
    ,end_date
    ,location_code
    ,active
    ,office_name
    ,legal_name
    ,region_name
    ,market_name
    ,division
    ,general_access
    ,location_city
    ,location_state
    ,accounting_id
    ,accounting_id_description
    ,acquisition_name
    ,acquisition_type
    ,_created_at
from {{ref('build__int_locations')}}