
select
    recordtype
    ,custodianid
    ,mstracctnumber
    ,masteraccountname
    ,businessdate
    ,accountid
    ,accounttitle1
    ,accounttitle2
    ,accounttitle3
    ,accountregis
    ,accounttype
    ,prodcode
    ,prodcatgcode
    ,taxcode
    ,lyst
    ,tickersymbol
    ,industrytickersymbol
    ,cusip
    ,schwabsecnbr
    ,itemissueid
    ,rulstsufid
    ,isin
    ,sedol
    ,optionsdisplaysymbol
    ,underlyingtickersymbol
    ,underlyingindustrytickersymbol
    ,underlyingcusip
    ,underlyingschwabnmbr
    ,underlyingitmissid
    ,unrulsufid
    ,underlyingisn
    ,underlyingsedol
    ,mnymkcode
    ,trcd
    ,sbcd
    ,transactioncategory
    ,transrccde
    ,transactionsourcecodedesc
    ,transactiondetaildescription
    ,tradetypecd
    ,tc
    ,tradedate
    ,settlementdate
    ,traddate
    ,eddivdnddate
    ,quantity
    ,price
    ,grossamount
    ,debitcredit
    ,netamount
    ,commission
    ,exchangeprocessingfee
    ,brokerservicefee
    ,primebrokerfee
    ,tradeawayfee
    ,redemptionfee
    ,otherfee
    ,federaltefrawithholding
    ,statetaxwithholding
    ,sttx
    ,accruedinterest
    ,accountingrulecode
    ,ordersrcd
    ,ordernumber
    ,tradeorderentrytimestamp
    ,tradeorderexecutiontimestamp
    ,brokercode
    ,brokername
    ,swbfromaccount
    ,swbtoaccount
    ,s1check
    ,si
    ,stockexchg
    ,ie
    ,distributionrate
    ,cashinlieushareqty
    ,divintshareqty
    ,cashinlieurate
    ,assetbackedfactor
    ,srsy
    ,jntp
    ,dm
    ,cashieringid
    ,recipmakername1
    ,recipmakername2
    ,recipmakername3
    ,frequency
    ,disbursechecknum
    ,federalbankrefnum
    ,recipmakeracctnum
    ,bankaccttype
    ,banknamepart1
    ,banknamepart2
    ,bankaba
    ,intermedname
    ,checkmemo1
    ,checkmemo2
    ,retfedincometax
    ,retstateinctax
    ,rttx
    ,pubtimestamp
    ,versmrkr1
    ,tipsfactor
    ,closingprice
    ,versmrkr2
    ,transmemo
    ,versmrkr3
    ,closingpriceunfactored
    ,factor
    ,factordate
    ,case when effective_date::date = (select max(effective_date::date) from {{ source('schwab_mwa', 'transactions') }}) then 1 else 0 end as is_current
    ,effective_date::date           as effective_date
    ,record_datetime::timestamp     as record_datetime
    ,record_date::date              as record_date
from {{ source('schwab_mwa', 'transactions') }}