select
    'tamarac' as pms
    , 'new_albany' as pms_location
    , 'mwa' AS firm_source
    , prev_eod_date as effective_date
    , account_number
    , account_name
    , account_type
    , address1
    , address2
    , address3
    , address4
    , address5
    , address6
    , city
    , closed_date
    , country
    , custodian
    , date_created
    , default_template
    , description
    , discretionary
    , dmsp_asset_allocation
    , first_name
    , last_name
    , primary_advisor
    , short_name
    , state
    , state_of_primary_residence
    , taxable
    , test_template
    , upload_account_id
    , use_primary_household_address
    , zip
    , account_current_value
    , advisor
    , benchmark
    , benchmark_2
    , benchmark_2_start_date
    , benchmark_3
    , benchmark_3_start_date
    , benchmark_4
    , benchmark_4_start_date
    , benchmark_5
    , benchmark_5_start_date
    , benchmark_start_date
    , calculate_performance
    , closing_value
    , composite_reporting_group
    , compute_performance_inception_date
    , current_cash
    , display_preference
    , dollar_variance
    , entity_type
    , exclude_all_securities_from_billing
    , exclude_all_securities_from_performance
    , fiscal_year_end
    , fiscal_year_end_date_use_for_reporting
    , household_assignments
    , inception_to_date_net_return_annualized
    , initial_value
    , last_sync_start_date
    , last_sync_time
    , manual_performance_history_end_date
    , manual_performance_return_behavior
    , manual_performance_value_behavior
    , master_account
    , next_sync_start_date
    , objective
    , objective_start_date
    , out_of_tolerance
    , percent_variance
    , performance_date
    , performance_inception_date
    , primary_household_id
    , primary_household_primary_advisor
    , primary_household_primary_advisor_id
    , service_team_name
    , service_team_compliance
    , service_team_csa
    , service_team_operations
    , service_team_primary_advisor
    , service_team_secondary_advisor
    , service_team_trade_approver
    , service_team_trader
    , target_allocation
    , year_to_date_net_return
    , account__net_worth_category
    , account__ownership_type
    , account__primary_owner_email
    , amortization_calculation_enabled
    , beneficial_billing_rate_tier_treatment
    , billing_closed_date
    , billing_definitions
    , billing_groups
    , billing_inception_date
    , compute_billing_closed_date
    , compute_billing_inception_date
    , display_accrued_interest
    , include_accrued_dividends
    , include_accrued_gains
    , last_reconciliation_date
    , ownership_account_type
    , ownership_parent_account
    , reconciliation_status
    , sma
    , sma_asset_class
    , sma_description1
    , sma_description2
    , sma_description3
    , sma_sector
    , sma_subsector
    , source_of_record_for_realized_gain_loss_is_custodian
    , account_level
    , allow_rebalancing
    , initial_model_deviation
    , last_order_date
    , last_trade_reconciliation_date
    , post_rebalance_model_deviation
    , reason_for_trade
    , rebalance_approved_by
    , rebalance_status
    , rebalanced_by
    , rebalancing_account_value
    , rebalancing_group_account_number
    , rebalancing_group_name
    , rebalancing_model_name
    , total_account_value
    , total_assets_excluding_cash
    , total_cash_reserve_actual_dollar
    , total_cash_reserves
    , total_initial_security_value
    , total_post_rebalance_security_value
    , allocation_preference
    , allow_buying_and_selling_of_same_slm
    , cash_to_raise
    , initial_cash_dollar
    , initial_cash_percent
    , margin_account
    , post_rebalance_cash_dollar
    , post_rebalance_cash_percent
    , sweep_cash
    , t1_cash
    , total_cash_dollar
    , total_cash_percent
    , total_cash_reserve_actual_percent
    , total_cash_reserve_goal_dollar
    , total_cash_reserve_goal_percent
    , tradeable_cash
    , uploaded_cash
    , account_status
    , asset_location_preference
    , commission_maximum_number_of_shares
    , custodian_fee_schedule
    , days_to_hold_buys
    , dvp_number
    , equity_dividend_reinvestment
    , equity_round_lot_size
    , equity_trade_file_format
    , hold_duplicate_trades
    , mutual_fund_buy_type
    , mutual_fund_capital_gains_reinvestment
    , mutual_fund_dividend_reinvestment
    , mutual_fund_round_lot_size
    , mutual_fund_sell_type
    , mutual_fund_trade_file_format
    , per_share_commission
    , per_trade_commission
    , prospect_account
    , rebalancing_funding_account_number
    , rebalancing_sma
    , trading_id
    , allow_redemption_fees
    , allow_short_term_gains
    , allow_violation_of_wash_sale_rule
    , default_rebalance_setting
    , equities_with_fees_minimum_holding_size_dollar
    , equities_with_fees_minimum_holding_size_percent
    , equities_with_fees_minimum_trade_size_dollar
    , equities_with_fees_minimum_trade_size_percent
    , maximum_gain_amount
    , minimum_trade_size_tolerance_dollar
    , minimum_trade_size_tolerance_percent
    , non_fee_securities_minimum_holding_size_dollar
    , non_fee_securities_minimum_holding_size_percent
    , non_fee_securities_minimum_trade_size_dollar
    , non_fee_securities_minimum_trade_size_percent
    , only_buy_existing_holdings
    , only_warn_for_st_gain_violations
    , restrict_all_securities
    , sell_based_on_tax_optimization
    , short_term_gain_restriction_boundary
    , short_term_maximum_gain_amount_dollar
    , short_term_maximum_gain_amount_percent
    , transaction_fee_fund_minimum_holding_size_dollar
    , transaction_fee_fund_minimum_holding_size_percent
    , transaction_fee_fund_minimum_trade_size_dollar
    , transaction_fee_fund_minimum_trade_size_percent
    , closing_method
    , long_term_carryover_ytd
    , long_term_tax_rate
    , realized_long_term_gain_loss_ytd
    , realized_short_term_gain_loss_ytd
    , short_term_carryover_ytd
    , short_term_tax_rate
    , state_tax_rate
    , tax_loss_harvesting_minimum_dollar
    , tax_loss_harvesting_minimum_percent
    , turnover_ytd
    , wash_sale_group_id
    , account_long_term_realized_gain_loss
    , account_short_term_realized_gain_loss
    , account_total_realized_gain_loss
    , annual_turnover
    , annualized_gross_irr
    , annualized_gross_twr
    , annualized_net_irr
    , annualized_net_twr
    , average_daily_balance
    , commissions
    , cumulative_turnover
    , expenses_excluding_revenue
    , expenses_percent_of_account
    , gross_irr
    , gross_twr
    , inflows
    , interest__dividends
    , internal_commissions
    , management_fees
    , management_fees_and_commissions
    , margin_expense
    , net_flows
    , net_investment_gain
    , net_irr
    , net_twr
    , number_of_trades
    , outflows
    , portfolio_yield
    , previous_12_months_turnover
    , purchases
    , sales
    , traded_away_commissions
    , client_contrib_401k
    , spouse_contrib_401k
    , billing_401k
    , active_clients
    , actively_managed
    , actively_managed_groups
    , asset_allocation
    , billable_account
    , billing_cycle
    , billing_month
    , cash_buffer
    , cash_flow_frequency
    , client_segment
    , comment
    , date_of_death
    , default__billed_account
    , distribution_amount
    , distribution_frequency
    , household
    , inception_month
    , inception_year
    , life_ins__client_contributes
    , life_ins__spouse_contributes
    , line
    , migration__account_status
    , migration__group_name_1
    , migration__group_name_2
    , migration__keywords
    , migration__rebalancing_group_id
    , new_account
    , not_billed
    , payment_method
    , periodic_cash_flow_amount
    , receives_paper_bill
    , receives_paper_statement
    , recieves_bill
    , regular_distribution
    , review_month
    , secondary_advisor
    , tamarac_portal
    , temp_billing
    , type_of_account
    , managed_account_value_preveod
    , unmanaged_account_value_preveod
    , total_account_value_preveod
    , source_file
    , {{ col_is_head(reference=source('tamarac_new_albany', 'stg_financial_accounts'), reference_date_col='prev_eod_date') }}
    , {{ col_is_current(date_col='effective_date') }}
    , record_datetime as _source_loaded_at
from {{ source('tamarac_new_albany', 'stg_financial_accounts') }}