select
    'tamarac'                                      as system_name
    , 'savant'                                     as system_instance
    , concat(system_name , '__' , system_instance) as system_key
    , 'mwa'                                        as firm_source
    , effective_date
    , account_number
    , accrual_method
    , accrued_income
    , allow_updates
    , always_report_as_irr
    , amortize_accrete_to
    , annual_dividend
    , annual_income
    , as_of_date
    , call_date
    , call_price
    , call_put
    , cash_invested
    , compounding_frequency
    , cost_basis
    , cumulative_income
    , current_price
    , current_yield
    , current_yield_to_worst_market
    , cusip
    , days_to_long_term
    , display_accrued_interest_security
    , divident_income_rate_per
    , dollar_gain_loss
    , effective_duration
    , exclude_from_billing
    , exclude_from_performance
    , expiration_date
    , extended_description1
    , extended_description2
    , federal_taxable
    , final_coupon_date
    , first_coupon_date
    , first_payment_date
    , fitch_bond_rating
    , fitch_bond_rating_effective_date
    , fitch_bond_rating_previous_value
    , fitch_bond_rating_previous_value_effective_date
    , fund_inception_date
    , globally_exclude_from_billing
    , globally_exclude_from_performance
    , holdings_current_value
    , income_frequency
    , interest_rate
    , issue_date
    , issue_state
    , long_term_unrealized_gain_loss
    , market_cap
    , maturity_date
    , moodys_bond_rating
    , moodys_bond_rating_effective_date
    , moodys_bond_rating_previous_value
    , moodys_bond_rating_previous_value_effective_date
    , next_capital_call_date
    , next_dividend_amount
    , next_dividend_date
    , next_exdividend_date
    , next_exincome_date
    , next_income_amount
    , next_income_date
    , open_date
    , percent_dollar_gain_loss
    , percent_gain_loss
    , prerefund_date
    , prerefund_price
    , price
    , qualified_status
    , quantity
    , report_gains_and_losses_on_the_realized_gains_losses_report
    , sector
    , security_annual_income
    , security_benchmark
    , security_description
    , security_type
    , shares_per_contract
    , short_term_unrealized_gain_loss
    , sp_bond_rating
    , sp_bond_rating_effective_date
    , sp_bond_rating_previous_value
    , sp_bond_rating_previous_value_effective_date
    , state_taxable
    , strike_price
    , subsector
    , symbol
    , total_unrealized_gain_loss
    , treat_as_committed_capital_security
    , treat_security_as_cash
    , treat_transactions_as_end_of_day
    , underlying_security
    , unit_cost
    , upload_account_id
    , upload_security_id
    , weight
    , yield_at_cost
    , sig_asset_class
    , sig_security_type
    , sig_subasset_class
    , {{ col_is_head(reference=source('tamarac_savant', 'assets')) }}
    , {{ col_is_current(date_col='effective_date') }}
    , record_datetime                              as _source_loaded_at
from {{ source('tamarac_savant', 'assets') }}
