{{ config(
    materialized='incremental',
    unique_key='bill__pk',
    incremental_strategy='delete+insert',
    on_schema_change='sync_all_columns'
) }}

select
    b.system_name                      as system_name
    , b.system_instance                as system_instance
    , b.system_key                     as system_key
    , b.firm_source                    as firm_source
    , b.effective_date                 as effective_date
    , b.clientname                     as bill_clientname
    , b.fkalclient                     as bill_fkalclient
    , b.pkbill                         as bill_pkbill
    , b.fkbillclient                   as bill_fkbillclient
    , b.fkbilltransmitmethod           as bill_fkbilltransmitmethod
    , b.fkblob                         as bill_fkblob
    , b.dtcalcdate                     as bill_dtcalcdate
    , b.billediteddate                 as bill_billediteddate
    , b.billeditedby                   as bill_billeditedby
    , b.billcreateddate                as bill_billcreateddate
    , b.billcreatedby                  as bill_billcreatedby
    , b.isvalid                        as bill_isvalid
    , b.oldinvoiceno                   as bill_oldinvoiceno
    , b.billtype                       as bill_billtype
    , b.fkbillinstance                 as bill_fkbillinstance
    , b.fkclientstamp                  as bill_fkclientstamp
    , b.fkbillaccountitem              as bill_fkbillaccountitem
    , b.createddate                    as bill_createddate
    , b.effective_date                 as bill_effective_date
    , b._pk                            as bill__pk
    , b._extracted_at                  as bill__extracted_at
    , b.is_head                        as bill_is_head
    , b.is_current                     as bill_is_current
    , b._is_full                       as bill__is_full
    , b._created_at                    as bill__created_at
    , b._source_file                   as bill__source_file
    , b._checksum                      as bill__checksum
    , bi.clientname                    as billinstance_clientname
    , bi.fkalclient                    as billinstance_fkalclient
    , bi.pkbillinstance                as billinstance_pkbillinstance
    , bi.binstancecreateddate          as billinstance_binstancecreateddate
    , bi.binstancecreatedby            as billinstance_binstancecreatedby
    , bi.status                        as billinstance_status
    , bi.perccomplete                  as billinstance_perccomplete
    , bi.billtype                      as billinstance_billtype
    , bi.fkblobpayablereport           as billinstance_fkblobpayablereport
    , bi.ismockbill                    as billinstance_ismockbill
    , bi.runfor                        as billinstance_runfor
    , bi.runforkeylist                 as billinstance_runforkeylist
    , bi.asofdate                      as billinstance_asofdate
    , bi.billfrequency                 as billinstance_billfrequency
    , bi.billstyle                     as billinstance_billstyle
    , bi.enddateoverride               as billinstance_enddateoverride
    , bi.valuedateoverride             as billinstance_valuedateoverride
    , bi.hangfirejobid                 as billinstance_hangfirejobid
    , bi.hangfirejobtype               as billinstance_hangfirejobtype
    , bi.entityoptions                 as billinstance_entityoptions
    , bi.statusvalue                   as billinstance_statusvalue
    , bi.correlationid                 as billinstance_correlationid
    , bi.fktrinstancefee               as billinstance_fktrinstancefee
    , bi.nickname                      as billinstance_nickname
    , bi.includecashflows              as billinstance_includecashflows
    , bi.allowduplicatemockbills       as billinstance_allowduplicatemockbills
    , bi.isfinalbill                   as billinstance_isfinalbill
    , bi.excludeadjustments            as billinstance_excludeadjustments
    , bi.runforaccounts                as billinstance_runforaccounts
    , bi.createddate                   as billinstance_createddate
    , bi.effective_date                as billinstance_effective_date
    , bi._pk                           as billinstance__pk
    , bi._extracted_at                 as billinstance__extracted_at
    , bi.is_head                       as billinstance_is_head
    , bi.is_current                    as billinstance_is_current
    , bi._is_full                      as billinstance__is_full
    , bi._created_at                   as billinstance__created_at
    , bi._source_file                  as billinstance__source_file
    , bi._checksum                     as billinstance__checksum
    , bt.clientname                    as billtype_clientname
    , bt.fkalclient                    as billtype_fkalclient
    , bt.pkbilltype                    as billtype_pkbilltype
    , bt.stype                         as billtype_stype
    , bt.stypedesc                     as billtype_stypedesc
    , bt.createddate                   as billtype_createddate
    , bt.effective_date                as billtype_effective_date
    , bt._pk                           as billtype__pk
    , bt._extracted_at                 as billtype__extracted_at
    , bt.is_head                       as billtype_is_head
    , bt.is_current                    as billtype_is_current
    , bt._is_full                      as billtype__is_full
    , bt._created_at                   as billtype__created_at
    , bt._source_file                  as billtype__source_file
    , bt._checksum                     as billtype__checksum
    , bai.clientname                   as billacctitem_clientname
    , bai.fkalclient                   as billacctitem_fkalclient
    , bai.pkbillaccountitem            as billacctitem_pkbillaccountitem
    , bai.fkbillaccount                as billacctitem_fkbillaccount
    , bai.fkbillstatus                 as billacctitem_fkbillstatus
    , bai.fkbilltype                   as billacctitem_fkbilltype
    , bai.fkbillinstance               as billacctitem_fkbillinstance
    , bai.fkpayforaccount              as billacctitem_fkpayforaccount
    , bai.fkhighasset                  as billacctitem_fkhighasset
    , bai.cinitialamt                  as billacctitem_cinitialamt
    , bai.cbalancedue                  as billacctitem_cbalancedue
    , bai.dtcalcdate                   as billacctitem_dtcalcdate
    , bai.isvalid                      as billacctitem_isvalid
    , bai.ctotalmktvalue               as billacctitem_ctotalmktvalue
    , bai.dailyaccrualperc             as billacctitem_dailyaccrualperc
    , bai.dtstartdate                  as billacctitem_dtstartdate
    , bai.dtenddate                    as billacctitem_dtenddate
    , bai.idaysincycle                 as billacctitem_idaysincycle
    , bai.oldreceivableid              as billacctitem_oldreceivableid
    , bai.asofdate                     as billacctitem_asofdate
    , bai.basis                        as billacctitem_basis
    , bai.aggregateval                 as billacctitem_aggregateval
    , bai.feeperc                      as billacctitem_feeperc
    , bai.error                        as billacctitem_error
    , bai.feeschedule                  as billacctitem_feeschedule
    , bai.buildcomplete                as billacctitem_buildcomplete
    , bai.payforperc                   as billacctitem_payforperc
    , bai.fktempaccountitem            as billacctitem_fktempaccountitem
    , bai.appliedadj                   as billacctitem_appliedadj
    , bai.daysinyear                   as billacctitem_daysinyear
    , bai.billfrequency                as billacctitem_billfrequency
    , bai.paymethod                    as billacctitem_paymethod
    , bai.fkaccountstamp               as billacctitem_fkaccountstamp
    , bai.flatfee                      as billacctitem_flatfee
    , bai.howbilled                    as billacctitem_howbilled
    , bai.lastcollectattempt           as billacctitem_lastcollectattempt
    , bai.payoutaggval                 as billacctitem_payoutaggval
    , bai.payoutbasis                  as billacctitem_payoutbasis
    , bai.transfermktvalue             as billacctitem_transfermktvalue
    , bai.indirectlink                 as billacctitem_indirectlink
    , bai.receivableguid               as billacctitem_receivableguid
    , bai.note                         as billacctitem_note
    , bai.fkbilladjtype                as billacctitem_fkbilladjtype
    , bai.fkbillentity                 as billacctitem_fkbillentity
    , bai.fkbillpayment                as billacctitem_fkbillpayment
    , bai.cprevbalance                 as billacctitem_cprevbalance
    , bai.ccurrbalance                 as billacctitem_ccurrbalance
    , bai.cchangeamt                   as billacctitem_cchangeamt
    , bai.dtdateoccured                as billacctitem_dtdateoccured
    , bai.fkpaidforbyaccount           as billacctitem_fkpaidforbyaccount
    , bai.fkgeneralaccountdetailsrc    as billacctitem_fkgeneralaccountdetailsrc
    , bai.fkgeneralaccountdetailadj    as billacctitem_fkgeneralaccountdetailadj
    , bai.addlannualamt                as billacctitem_addlannualamt
    , bai.addlannualamttype            as billacctitem_addlannualamttype
    , bai.fktraderequest               as billacctitem_fktraderequest
    , bai.fktransaction                as billacctitem_fktransaction
    , bai.billaiediteddate             as billacctitem_billaiediteddate
    , bai.billaieditedby               as billacctitem_billaieditedby
    , bai.billaicreateddate            as billacctitem_billaicreateddate
    , bai.billaicreatedby              as billacctitem_billaicreatedby
    , bai.islocked                     as billacctitem_islocked
    , bai.createddate                  as billacctitem_createddate
    , bai.effective_date               as billacctitem_effective_date
    , bai._pk                          as billacctitem__pk
    , bai._extracted_at                as billacctitem__extracted_at
    , bai.is_head                      as billacctitem_is_head
    , bai.is_current                   as billacctitem_is_current
    , bai._is_full                     as billacctitem__is_full
    , bai._created_at                  as billacctitem__created_at
    , bai._source_file                 as billacctitem__source_file
    , bai._checksum                    as billacctitem__checksum
    , ba.clientname                    as billacct_clientname
    , ba.fkalclient                    as billacct_fkalclient
    , ba.pkbillaccount                 as billacct_pkbillaccount
    , ba.fkbillregistration            as billacct_fkbillregistration
    , ba.fkbillpaymethod               as billacct_fkbillpaymethod
    , ba.fkbillfeeschedule             as billacct_fkbillfeeschedule
    , ba.fkaccount                     as billacct_fkaccount
    , ba.fkbillpayoutschedule          as billacct_fkbillpayoutschedule
    , ba.editeddate                    as billacct_editeddate
    , ba.editedby                      as billacct_editedby
    , ba.billacctcreateddate           as billacct_billacctcreateddate
    , ba.billacctcreatedby             as billacct_billacctcreatedby
    , ba.scustodialacctnum             as billacct_scustodialacctnum
    , ba.sabanumber                    as billacct_sabanumber
    , ba.sbankacctnum                  as billacct_sbankacctnum
    , ba.sbankname                     as billacct_sbankname
    , ba.snameonacct                   as billacct_snameonacct
    , ba.screditcardnumber             as billacct_screditcardnumber
    , ba.icyclemonth                   as billacct_icyclemonth
    , ba.ibillfrequency                as billacct_ibillfrequency
    , ba.sexpdate                      as billacct_sexpdate
    , ba.snameoncard                   as billacct_snameoncard
    , ba.scardtype                     as billacct_scardtype
    , ba.snmacctnum                    as billacct_snmacctnum
    , ba.snmacctname                   as billacct_snmacctname
    , ba.snmclientname                 as billacct_snmclientname
    , ba.isactive                      as billacct_isactive
    , ba.ibillingstyle                 as billacct_ibillingstyle
    , ba.fkbillmasterpayoutschedule    as billacct_fkbillmasterpayoutschedule
    , ba.acceptslist                   as billacct_acceptslist
    , ba.feeformcount                  as billacct_feeformcount
    , ba.lastperfbilldate              as billacct_lastperfbilldate
    , ba.isperformancebilled           as billacct_isperformancebilled
    , ba.fkperffeeschedule             as billacct_fkperffeeschedule
    , ba.fkperfmasterpayoutschedule    as billacct_fkperfmasterpayoutschedule
    , ba.billstartdate                 as billacct_billstartdate
    , ba.useminfee                     as billacct_useminfee
    , ba.valuemethod                   as billacct_valuemethod
    , ba.addlannualamt                 as billacct_addlannualamt
    , ba.addlannualamttype             as billacct_addlannualamttype
    , ba.fkbilladjtype                 as billacct_fkbilladjtype
    , ba.fkbillentity                  as billacct_fkbillentity
    , ba.creditcardnoencryption        as billacct_creditcardnoencryption
    , ba.addr1                         as billacct_addr1
    , ba.addr2                         as billacct_addr2
    , ba.addr3                         as billacct_addr3
    , ba.city                          as billacct_city
    , ba.state                         as billacct_state
    , ba.zip                           as billacct_zip
    , ba.includeinaggregate            as billacct_includeinaggregate
    , ba.fkbillaccountstatus           as billacct_fkbillaccountstatus
    , ba.tieredfeepriority             as billacct_tieredfeepriority
    , ba.usefeehierarchy               as billacct_usefeehierarchy
    , ba.createddate                   as billacct_createddate
    , ba.effective_date                as billacct_effective_date
    , ba._pk                           as billacct__pk
    , ba._extracted_at                 as billacct__extracted_at
    , ba.is_head                       as billacct_is_head
    , ba.is_current                    as billacct_is_current
    , ba._is_full                      as billacct__is_full
    , ba._created_at                   as billacct__created_at
    , ba._source_file                  as billacct__source_file
    , ba._checksum                     as billacct__checksum
    , a.clientname                     as acct_clientname
    , a.fkalclient                     as acct_fkalclient
    , a.pkaccount                      as acct_pkaccount
    , a.fkregistration                 as acct_fkregistration
    , a.fkfundfamily                   as acct_fkfundfamily
    , a.fkshareclass                   as acct_fkshareclass
    , a.fkplatform                     as acct_fkplatform
    , a.fkcustodian                    as acct_fkcustodian
    , a.isactive                       as acct_isactive
    , a.issweepacct                    as acct_issweepacct
    , a.acctcreateddate                as acct_acctcreateddate
    , a.acctcreatedby                  as acct_acctcreatedby
    , a.editeddate                     as acct_editeddate
    , a.editedby                       as acct_editedby
    , a.provider                       as acct_provider
    , a.canceldate                     as acct_canceldate
    , a.cancelvalue                    as acct_cancelvalue
    , a.istradingblocked               as acct_istradingblocked
    , a.tradinginstr                   as acct_tradinginstr
    , a.outsideid                      as acct_outsideid
    , a.groupnum                       as acct_groupnum
    , a.fksubadvisor                   as acct_fksubadvisor
    , a.importkey                      as acct_importkey
    , a.acctstartdate                  as acct_acctstartdate
    , a.acctstartvalue                 as acct_acctstartvalue
    , a.isorigsmcacct                  as acct_isorigsmcacct
    , a.fkplan                         as acct_fkplan
    , a.accountstatus                  as acct_accountstatus
    , a.isphoneauthorized              as acct_isphoneauthorized
    , a.fkaccounthistory               as acct_fkaccounthistory
    , a.fksweepasset                   as acct_fksweepasset
    , a.initialpurchasedate            as acct_initialpurchasedate
    , a.fkaccounthistoryunique         as acct_fkaccounthistoryunique
    , a.ismanaged                      as acct_ismanaged
    , a.fkdownloadsource               as acct_fkdownloadsource
    , a.fkaccounthistorybilling        as acct_fkaccounthistorybilling
    , a.iswrapmanaged                  as acct_iswrapmanaged
    , a.isdiscretionary                as acct_isdiscretionary
    , a.riskscore                      as acct_riskscore
    , a.fkportfoliogroupcomposite      as acct_fkportfoliogroupcomposite
    , a.fkaccounthistorybillingunique  as acct_fkaccounthistorybillingunique
    , a.ispositiononlyrecon            as acct_ispositiononlyrecon
    , a.signaturestatus                as acct_signaturestatus
    , a.eclipsefirmid                  as acct_eclipsefirmid
    , a.ishistorical                   as acct_ishistorical
    , a.currentdownloaderror           as acct_currentdownloaderror
    , a.prevdownloaderror              as acct_prevdownloaderror
    , a.isunfunded                     as acct_isunfunded
    , a.isbundled                      as acct_isbundled
    , a.isexcludedfromfirmassets       as acct_isexcludedfromfirmassets
    , a.hassloa                        as acct_hassloa
    , a.sloadate                       as acct_sloadate
    , a.thirdparty                     as acct_thirdparty
    , a.isaffiliated                   as acct_isaffiliated
    , a.isadvreportable                as acct_isadvreportable
    , a.is13freportable                as acct_is13freportable
    , a.iswrapsponsored                as acct_iswrapsponsored
    , a.isops                          as acct_isops
    , a.isauareportable                as acct_isauareportable
    , a.custodialrepcode               as acct_custodialrepcode
    , a.fkadvcustodytype               as acct_fkadvcustodytype
    , a.primebrokerageagreement        as acct_primebrokerageagreement
    , a.marginagreement                as acct_marginagreement
    , a.optionlevel                    as acct_optionlevel
    , regexp_replace(
        ltrim(upper(replace(a.acctcode , '-' , '')) , '0')::text(200)
        , '\\s{2,}' , ' '
    )                                  as account_number
    , a.acctcode                       as acct_acctcode
    , a.secondaryacctcode              as acct_secondaryacctcode
    , a.pkmdlaccount                   as acct_pkmdlaccount
    , a.rebalanceyn                    as acct_rebalanceyn
    , a.isoutsidemodel                 as acct_isoutsidemodel
    , a.mincashbalance                 as acct_mincashbalance
    , a.mdlacctcreateddate             as acct_mdlacctcreateddate
    , a.mdlacctcreatedby               as acct_mdlacctcreatedby
    , a.mdlacctediteddate              as acct_mdlacctediteddate
    , a.mdlaccteditedby                as acct_mdlaccteditedby
    , a.oldclientid                    as acct_oldclientid
    , a.fkmodelagg                     as acct_fkmodelagg
    , a.fundlist                       as acct_fundlist
    , a.mincashbalancetype             as acct_mincashbalancetype
    , a.fkmodelaggnewmoney             as acct_fkmodelaggnewmoney
    , a.autorebalfreq                  as acct_autorebalfreq
    , a.autorebalmonth                 as acct_autorebalmonth
    , a.autorebalday                   as acct_autorebalday
    , a.lastrebalanced                 as acct_lastrebalanced
    , a.replenishmincash               as acct_replenishmincash
    , a.fkdollarmodel                  as acct_fkdollarmodel
    , a.dollarmodelamount              as acct_dollarmodelamount
    , a.cashliability                  as acct_cashliability
    , a.expiremincash                  as acct_expiremincash
    , a.expiremincashtype              as acct_expiremincashtype
    , a.expiremincashdate              as acct_expiremincashdate
    , a.targetallocation               as acct_targetallocation
    , a.contributionallocation         as acct_contributionallocation
    , a.distributionallocation         as acct_distributionallocation
    , a.corporateactionallocation      as acct_corporateactionallocation
    , a.toleranceupper                 as acct_toleranceupper
    , a.tolerancelower                 as acct_tolerancelower
    , a.sleeveacctcreatedby            as acct_sleeveacctcreatedby
    , a.sleeveacctcreateddate          as acct_sleeveacctcreateddate
    , a.sleeveaccteditedby             as acct_sleeveaccteditedby
    , a.sleeveacctediteddate           as acct_sleeveacctediteddate
    , a.master                         as acct_master
    , a.sleevetype                     as acct_sleevetype
    , a.autotradetypes                 as acct_autotradetypes
    , a.autotraderequested             as acct_autotraderequested
    , a.autotraderequestedby           as acct_autotraderequestedby
    , a.autotradeprocessed             as acct_autotradeprocessed
    , a.suspendautocontribuntil        as acct_suspendautocontribuntil
    , a.targetbalancetype              as acct_targetbalancetype
    , a.donottrade                     as acct_donottrade
    , a.iscustomized                   as acct_iscustomized
    , a.fksleevestrategydetail         as acct_fksleevestrategydetail
    , a.fksleevestrategy               as acct_fksleevestrategy
    , a.sleevestrategytoleranceupper   as acct_sleevestrategytoleranceupper
    , a.sleevestrategytolerancelower   as acct_sleevestrategytolerancelower
    , a.fkbusinessline                 as acct_fkbusinessline
    , a.fkpersonalbusinessline         as acct_fkpersonalbusinessline
    , a.businesslineemployeecount      as acct_businesslineemployeecount
    , a.businesslinestartdate          as acct_businesslinestartdate
    , a.issma                          as acct_issma
    , a.eclipsesma                     as acct_eclipsesma
    , a.fksmaasset                     as acct_fksmaasset
    , a.smacreatedby                   as acct_smacreatedby
    , a.smacreateddate                 as acct_smacreateddate
    , a.smaeditedby                    as acct_smaeditedby
    , a.smaediteddate                  as acct_smaediteddate
    , a.createddate                    as acct_createddate
    , a.effective_date                 as acct_effective_date
    , a._extracted_at                  as acct__extracted_at
    , a.is_head                        as acct_is_head
    , a.is_current                     as acct_is_current
    , a._is_full                       as acct__is_full
    , a._created_at                    as acct__created_at
    , a._source_file                   as acct__source_file
    , a._checksum                      as acct__checksum
    -- META ---------------------------------------------------------------------
    , b.is_head                        as is_head
    , b.is_current                     as is_current
    , current_timestamp::timestamp_ntz as _created_at
    , b._extracted_at::timestamp_ntz   as _source_loaded_at
    , b._source_file::varchar(200)     as _source_file
from {{ ref('orion__base_vw_bill') }} as b
-- Billing run.
-- Big billing run every quarter and smaller ones throughout the quarter.
left join {{ ref('orion__base_vw_billinstance') }} as bi
    on b.fkalclient = bi.fkalclient
    and b.fkbillinstance = bi.pkbillinstance
    and bi.is_head = 1
    -- ...
left join {{ ref('orion__base_vw_billtype') }} as bt
    on b.fkalclient = bt.fkalclient
    and b.billtype = bt.pkbilltype
    and bt.is_head = 1
    -- Linking a billing statement to a financial account.
left join {{ ref('orion__base_vw_billaccountitem') }} as bai
    on b.fkalclient = bai.fkalclient
    and b.fkbillaccountitem = bai.pkbillaccountitem
    and bai.is_head = 1
    -- ...
left join {{ ref('orion__base_vw_billaccount') }} as ba
    on b.fkalclient = ba.fkalclient
    and bai.fkbillaccount = ba.pkbillaccount
    and ba.is_head = 1
left join {{ ref('orion__base_vw_account') }} as a
    on b.fkalclient = a.fkalclient
    and ba.fkaccount = a.pkaccount
    and a.is_head = 1
where b.is_head = 1
    {%- if target.name not in ["prod"] %}
        and b.billcreateddate >= current_date() - 185
    {%- endif %}
    {%- if is_incremental() %}
        and b.createddate > coalesce((select max(a.bill_createddate) from {{ this }} as a) , b.createddate - interval '1 day')
    {%- endif %}
