
select
    value:c1::string          as custodial_id,
    value:c2::date            as business_date,
    value:c3::string          as account_number,
    value:c4::string          as account_type,
    value:c5::string          as security_type,
    value:c6::string          as symbol,
    value:c7::double          as current_quantity,
    value:c8::decimal(19, 6)  as cost_basis,
    value:c9::decimal(19, 6)  as adjusted_cost_basis,
    value:c10::decimal(19, 6) as unrealized_gain_loss,
    value:c11::boolean        as cost_basis_fully_known,
    value:c12::string         as certified_flag,
    value:c13::date           as original_purchase_date,
    value:c14::decimal(19, 6) as original_purchase_price,
    value:c15::string         as wash_sale_indicator,
    value:c16::decimal(19, 6) as disallowed_amount,
    value:c17::decimal(19, 6) as averaged_cost,
    value:c18::decimal(19, 6) as book_cost,
    value:c19::string         as book_proceeds,
    value:c20::decimal(19, 6) as fixed_income_cost_adjustment,
    value:c21::string         as id,
    value:c22::string         as security_name,
    value:c23::string         as covered,
    value:c24::string         as unknown_total,
    case when effective_date::date = (select max(effective_date::date) from {{ source('tda_mwa', 'cost_basis') }}) then 1 else 0 end as is_current,
    effective_date::date      as effective_date,
    file_type::string         as file_type
from {{ source('tda_mwa', 'cost_basis') }}