select
    'orion'                                        as system_name
    , 'mps'                                        as system_instance
    , concat(system_name , '__' , system_instance) as system_key
    , 'mps'                                        as firm_source
    , effective_date
    , client_id
    , registration_id
    , account_id
    , first_name
    , last_name
    , client_name
    , reg_name
    , reg_l_name
    , reg_f_name
    , rep_name
    , rep_number
    , address1
    , address2
    , address3
    , city
    , state
    , zip
    , email
    , phone_home
    , phone_business
    , statement_transmit_method
    , reg_description
    , fund_name
    , account_number
    , mgmt_style
    , fee_schedule
    , fee_type
    , master_payout_schedule
    , pay_method_instruction
    , bill_frequency
    , bill_style
    , custodian
    , outside_id
    , subadvisor_name
    , is_performance_billed
    , last_performance_bill_date
    , created_date
    , edited_date
    , investment_objective
    , plan_name
    , plan_sponsor
    , plan_administrator_name
    , account_start_date
    , bill_start_date
    , fkplan
    , current_value
    , minimum_cash_balance
    , pkacct_that_does_paying
    , percent_paid_by_account
    , acct_value_that_does_paying
    , acct_no_that_does_paying
    , time_horizon
    , return_objective
    , stock_percentage
    , risk_tolerance
    , model_name
    , bd_name
    , valuation_method
    , credit_remaining
    , salutation
    , net_worth
    , cycle_month
    , isqual
    , trade_instruction
    , business_line
    , custodian_code
    , plan_number
    , mgmt_style_code
    , sub_advisor_code
    , additional_charge_credit_amount
    , additional_charge_credit_type
    , model_group_num
    , minimum_inception_date
    , true_account_start_date
    , reponsible_party
    , account_status
    , include_in_qpe
    , include_in_twr
    , ismanaged
    , billing_nonmgd_acct_no
    , billing_nonmgd_acct_name
    , billing_nonmgd_client
    , ssn
    , is_account_active
    , branch_id
    , client_created_date
    , last_trx_date
    , last_invoice_creation_date
    , fkaccounthistory
    , first_invest_date
    , reg_is_active
    , acct_cancel_date
    , is_discretionary
    , include_in_aggregate
    , exclude_from_orion_cost_basis
    , aum_classification
    , trading_blocked
    , {{ col_is_head(reference=source('orion_mps', 'audit_all_accounts_1922_history')) }}
    , {{ col_is_current(date_col='effective_date') }}
    , record_datetime                              as _source_loaded_at
from {{ source('orion_mps', 'audit_all_accounts_1922_history') }}
