# Specify the connection params to the test database.
[database.dev]
driver = "snowflake"
account = "mariner.us-east-2.privatelink"
user = "gkilber"
authenticator = "externalbrowser"
database = "DBT"
schema = "DBT_GKILBER"
warehouse = "WH_ENGINEERING"
role = "ENGINEERING"

[database.edw]
driver = "snowflake"
account = "mariner.us-east-2.privatelink"
user = "gkilber"
authenticator = "externalbrowser"
database = "EDW"
schema = "BUILD"
warehouse = "WH_ENGINEERING"
role = "ENGINEERING"

# Specify the default run params
[run.default]
update_column = "_source_loaded_at"
verbose = true

# Specify params for a run 'test_diff'.
[run.test_diff]
verbose = true
# Source 1 ("left")
1.database = "dev"
1.table = "NML_CUSTODIAN_ACCOUNT_LINKS_FIDELITY"
2.database = "edw"
2.table = "NML_CUSTODIAN_ACCOUNT_LINKS_FIDELITY"

# reladiff "snowflake://gkilber@mariner.us-east-2.privatelink/DBT/DBT_GKILBER?warehouse=WH_ENGINEERING&role=ENGINEERING&authenticator=externalbrowser" NML_CUSTODIAN_ACCOUNT_LINKS_FIDELITY NML_CUSTODIAN_ACCOUNT_LINKS_FIDELITY
