select
    'tamarac' as pms
    , 'emerson' as pms_location
    , 'mwa' AS firm_source
    , effective_date
    , primary_household_id
    , custodian
    , discretionary
    , as_of_date
    , cost_basis
    , cusip
    , account_number
    , upload_account_id
    , closed_date
    , holdings_current_value
    , price
    , security_description
    , security_type
    , symbol
    , quantity
    , asset_class
    , accrual_method
    , accrued_income
    , allow_updates
    , always_report_as_irr
    , amortize_accrete_to
    , annual_dividend
    , annual_income
    , call_date
    , call_price
    , call_put
    , cash_invested
    , compounding_frequency
    , cumulative_income
    , current_price
    , current_yield
    , current_yield_to_worst_market
    , days_to_long_term
    , display_accrued_interest_security
    , dividend_income_rate_per
    , dollar_gain_loss
    , effective_duration
    , exclude_from_billing
    , exclude_from_performance
    , expiration_date
    , extended_description1
    , extended_description2
    , federal_taxable
    , final_coupon_date
    , first_coupon_date
    , first_payment_date
    , fitch_bond_rating
    , fitch_bond_rating_effective_date
    , fitch_bond_rating_previous_value
    , fitch_bond_rating_previous_value_effective_date
    , fund_inception_date
    , globally_exclude_from_billing
    , globally_exclude_from_performance
    , income_frequency
    , interest_rate
    , issue_date
    , issue_state
    , long_term_unrealized_gain_loss
    , market_cap
    , maturity_date
    , moodys_bond_rating
    , moodys_bond_rating_effective_date
    , moodys_bond_rating_previous_value
    , moodys_bond_rating_previous_value_effective_date
    , next_capital_call_date
    , next_dividend_amount
    , next_dividend_date
    , next_exdividend_date
    , next_exincome_date
    , next_income_amount
    , next_income_date
    , open_date
    , percent_dollar_gain_loss
    , percent_gain_loss
    , prerefund_date
    , prerefund_price
    , qualified_status
    , report_gains_and_losses_on_the_realized_gains_losses_report
    , sector
    , security_annual_income
    , security_benchmark
    , shares_per_contract
    , short_term_unrealized_gain_loss
    , sp_bond_rating
    , sp_bond_rating_effective_date
    , sp_bond_rating_previous_value
    , sp_bond_rating_previous_value_effective_date
    , state_taxable
    , strike_price
    , subsector
    , total_unrealized_gain_loss
    , treat_as_committed_capital_security
    , treat_security_as_cash
    , treat_transactions_as_end_of_day
    , underlying_security
    , unit_cost
    , upload_security_id
    , weight
    , yield_at_cost
    , suppress_yield_and_duration
    , yield_to_call_cost
    , yield_to_call_market
    , yield_to_maturity_cost
    , yield_to_maturity_market
    , custom_round_lot_size
    , custom_trade_price
    , default_holdings_buy_date
    , default_holdings_buy_price
    , do_not_buy_in_accounts_below
    , do_not_buy_in_tax_deferred_accounts
    , do_not_buy_in_taxable_accounts
    , maximum_percentage_to_hold
    , open_close_status
    , restriction_type
    , sell_all_trading_cushion
    , trade_price
    , use_market_value
    , yield
    , payment_delay
    , unused_security
    , unused_security_effective_date
    , unused_security_previous_value
    , unused_security_previous_value_effective_date
    , account_name
    , account_type
    , address1
    , address2
    , address3
    , address4
    , address5
    , address6
    , city
    , country
    , date_created
    , default_template
    , description
    , first_name
    , last_name
    , primary_advisor
    , short_name
    , state
    , state_of_primary_residence
    , taxable
    , use_primary_household_address
    , zip
    , account_current_value
    , advisor
    , benchmark
    , benchmark_start_date
    , calculate_performance
    , closing_value
    , composite_reporting_group
    , compute_performance_inception_date
    , current_cash
    , display_preference
    , dollar_variance
    , entity_type
    , exclude_all_securities_from_billing
    , exclude_all_securities_from_performance
    , fiscal_year_end
    , fiscal_year_end_date_use_for_reporting
    , household_assignments
    , initial_value
    , intragroup_flow_auto_matching_enabled
    , last_sync_start_date
    , last_sync_time
    , manual_performance_history_end_date
    , manual_performance_return_behavior
    , manual_performance_value_behavior
    , master_account
    , next_sync_start_date
    , objective
    , objective_start_date
    , out_of_tolerance
    , percent_variance
    , performance_date
    , performance_inception_date
    , primary_household_primary_advisor
    , primary_household_primary_advisor_id
    , service_team_name
    , service_team_compliance
    , service_team_csa
    , service_team_operations
    , service_team_primary_advisor
    , service_team_secondary_advisor
    , service_team_trade_approver
    , service_team_trader
    , target_allocation
    , year_to_date_net_return
    , account__net_worth_category
    , account__ownership_type
    , account__primary_owner_email
    , amortization_calculation_enabled
    , beneficial_billing_rate_tier_treatment
    , billing_closed_date
    , billing_definitions
    , billing_groups
    , billing_inception_date
    , compute_billing_closed_date
    , compute_billing_inception_date
    , display_accrued_interest
    , include_accrued_dividends
    , include_accrued_gains
    , last_reconciliation_date
    , ownership_account_type
    , ownership_parent_account
    , reconciliation_status
    , sma
    , sma_asset_class
    , sma_description1
    , sma_description2
    , sma_description3
    , sma_sector
    , sma_subsector
    , source_of_record_for_realized_gain_loss_is_custodian
    , account_level
    , allow_rebalancing
    , initial_model_deviation
    , last_order_date
    , last_trade_reconciliation_date
    , post_rebalance_model_deviation
    , reason_for_trade
    , rebalance_approved_by
    , rebalance_status
    , rebalanced_by
    , rebalancing_account_value
    , rebalancing_group_account_number
    , rebalancing_group_name
    , rebalancing_model_name
    , total_account_value
    , total_assets_excluding_cash
    , total_cash_reserve_actual_dollar
    , total_cash_reserves
    , total_initial_security_value
    , total_post_rebalance_security_value
    , allocation_preference
    , allow_buying_and_selling_of_same_slm
    , rebalancing_group_annual_capital_gains_tax_budget
    , rebalancing_group_annual_capital_gains_tax_budget_per_used
    , rebalancing_group_annual_capital_gains_tax_budget_value_type
    , cash_to_raise
    , initial_cash_dollar
    , initial_cash_percent
    , margin_account
    , post_rebalance_cash_dollar
    , post_rebalance_cash_percent
    , sweep_cash
    , "T+1_CASH" as t_plus_1_cash
    , total_cash_dollar
    , total_cash_percent
    , total_cash_reserve_actual_percent
    , total_cash_reserve_goal_dollar
    , total_cash_reserve_goal_percent
    , tradeable_cash
    , uploaded_cash
    , account_status
    , commission_maximum_number_of_shares
    , custodian_fee_schedule
    , days_to_hold_buys
    , dvp_number
    , equity_dividend_reinvestment
    , equity_round_lot_size
    , equity_trade_file_format
    , hold_duplicate_trades
    , mutual_fund_buy_type
    , mutual_fund_capital_gains_reinvestment
    , mutual_fund_dividend_reinvestment
    , mutual_fund_round_lot_size
    , mutual_fund_sell_type
    , mutual_fund_trade_file_format
    , per_share_commission
    , per_trade_commission
    , prospect_account
    , rebalancing_funding_account_number
    , rebalancing_sma
    , trading_id
    , allow_redemption_fees
    , allow_short_term_gains
    , allow_violation_of_wash_sale_rule
    , asset_location_preference
    , default_rebalance_setting
    , equities_with_fees_minimum_holding_size_dollar
    , equities_with_fees_minimum_holding_size_percent
    , equities_with_fees_minimum_trade_size_dollar
    , equities_with_fees_minimum_trade_size_percent
    , maximum_gain_amount
    , minimum_trade_size_tolerance_dollar
    , minimum_trade_size_tolerance_percent
    , non_fee_securities_minimum_holding_size_dollar
    , non_fee_securities_minimum_holding_size_percent
    , non_fee_securities_minimum_trade_size_dollar
    , non_fee_securities_minimum_trade_size_percent
    , only_buy_existing_holdings
    , only_warn_for_st_gain_violations
    , restrict_all_securities
    , sell_based_on_tax_optimization
    , short_term_gain_restriction_boundary
    , short_term_maximum_gain_amount_dollar
    , short_term_maximum_gain_amount_percent
    , transaction_fee_fund_minimum_holding_size_dollar
    , transaction_fee_fund_minimum_holding_size_percent
    , transaction_fee_fund_minimum_trade_size_dollar
    , transaction_fee_fund_minimum_trade_size_percent
    , annual_capital_gains_tax_budget
    , annual_capital_gains_tax_budget_per_used
    , annual_capital_gains_tax_budget_value_type
    , closing_method
    , long_term_carryover_ytd
    , long_term_tax_rate
    , realized_long_term_gain_loss_ytd
    , realized_short_term_gain_loss_ytd
    , short_term_carryover_ytd
    , short_term_tax_rate
    , state_tax_rate
    , tax_loss_harvesting_minimum_dollar
    , tax_loss_harvesting_minimum_percent
    , turnover_ytd
    , wash_sale_group_id
    , account_long_term_realized_gain_loss
    , account_short_term_realized_gain_loss
    , account_total_realized_gain_loss
    , annual_turnover
    , annualized_gross_irr
    , annualized_gross_twr
    , annualized_net_irr
    , annualized_net_twr
    , average_daily_balance
    , commissions
    , cumulative_turnover
    , expenses_excluding_revenue
    , expenses_percent_of_account
    , gross_irr
    , gross_twr
    , inflows
    , interest__dividends
    , internal_commissions
    , management_fees
    , management_fees_and_commissions
    , margin_expense
    , net_flows
    , net_investment_gain
    , net_irr
    , net_twr
    , number_of_trades
    , outflows
    , portfolio_yield
    , previous_12_months_turnover
    , purchases
    , sales
    , traded_away_commissions
    , aum_household_name
    , aum_upload_household_id
    , custody
    , custody_type
    , investment_discretion
    , investment_manager
    , voting_authority
    , wrap_program
    , accounts_within_group
    , household
    , migration__account_status
    , migration__group_name_1
    , migration__group_name_2
    , migration__keywords
    , migration__rebalancing_group_id
    , not_billed
    , not_billed_effective_date
    , not_billed_previous_value
    , not_billed_previous_value_effective_date
    , system_investment_discretion
    , system_investment_manager
    , system_voting_authority
    , managed_account_value_as_of_7_22_2022
    , unmanaged_account_value_as_of_7_22_2022
    , total_account_value_as_of_7_22_2022
    , {{ col_is_head(reference=source('tamarac_emerson', 'assets')) }}
    , {{ col_is_current(date_col='effective_date') }}
    , record_datetime as _source_loaded_at
from {{ source('tamarac_emerson', 'assets') }}