select
    'tamarac' as pms
    , 'emerson' as pms_location
    , 'mwa' AS firm_source
    , effective_date
    , account__net_worth_category
    , account__ownership_type
    , account__primary_owner_email
    , account_current_value
    , account_long_term_realized_gain_loss
    , account_name
    , account_number
    , account_short_term_realized_gain_loss
    , account_total_realized_gain_loss
    , account_type
    , address1
    , address2
    , address3
    , address4
    , address5
    , address6
    , advisor
    , amortization_calculation_enabled
    , annual_turnover
    , annualized_gross_irr
    , annualized_gross_twr
    , annualized_net_irr
    , annualized_net_twr
    , average_daily_balance
    , benchmark
    , benchmark_start_date
    , beneficial_billing_rate_tier_treatment
    , billing_closed_date
    , billing_definitions
    , billing_groups
    , billing_inception_date
    , calculate_performance
    , city
    , closed_date
    , closing_value
    , commissions
    , compute_billing_closed_date
    , compute_billing_inception_date
    , compute_performance_inception_date
    , country
    , cumulative_turnover
    , current_cash
    , custodian
    , default_template
    , description
    , discretionary
    , display_accrued_interest
    , display_preference
    , dollar_variance
    , entity_type
    , exclude_all_securities_from_billing
    , exclude_all_securities_from_performance
    , expenses_excluding_revenue
    , expenses_percent_of_account
    , first_name
    , fiscal_year_end
    , fiscal_year_end_date_use_for_reporting
    , gross_irr
    , gross_twr
    , household_assignments
    , include_accrued_dividends
    , include_accrued_gains
    , inflows
    , initial_value
    , "INTEREST_&_DIVIDENDS" as interest_and_dividends
    , internal_commissions
    , last_name
    , last_reconciliation_date
    , last_sync_start_date
    , last_sync_time
    , managed_account_value_preveod
    , management_fees
    , management_fees_and_commissions
    , manual_performance_history_end_date
    , manual_performance_return_behavior
    , manual_performance_value_behavior
    , margin_expense
    , master_account
    , net_flows
    , net_investment_gain
    , net_irr
    , net_twr
    , next_sync_start_date
    , number_of_trades
    , objective
    , objective_start_date
    , out_of_tolerance
    , outflows
    , ownership_account_type
    , ownership_parent_account
    , percent_variance
    , performance_date
    , performance_inception_date
    , portfolio_yield
    , prev_eod_date
    , previous_12_months_turnover
    , primary_advisor
    , primary_household_id
    , primary_household_primary_advisor
    , primary_household_primary_advisor_id
    , purchases
    , reconciliation_status
    , sales
    , service_team_compliance
    , service_team_name
    , service_team_operations
    , service_team_primary_advisor
    , service_team_secondary_advisor
    , short_name
    , sma
    , sma_description1
    , sma_description2
    , sma_description3
    , sma_sector
    , sma_subsector
    , source_of_record_for_realized_gain_loss_is_custodian
    , state
    , state_of_primary_residence
    , target_allocation
    , taxable
    , total_account_value_preveod
    , traded_away_commissions
    , unmanaged_account_value_preveod
    , upload_account_id
    , use_primary_household_address
    , year_to_date_net_return
    , zip
    , date_created
    , composite_reporting_group
    , intragroup_flow_auto_matching_enabled
    , service_team_csa
    , service_team_trade_approver
    , service_team_trader
    , sma_asset_class
    , account_level
    , allow_rebalancing
    , initial_model_deviation
    , last_order_date
    , last_trade_reconciliation_date
    , post_rebalance_model_deviation
    , reason_for_trade
    , rebalance_approved_by
    , rebalance_status
    , rebalanced_by
    , rebalancing_account_value
    , rebalancing_group_account_number
    , rebalancing_group_name
    , rebalancing_model_name
    , total_account_value
    , total_assets_excluding_cash
    , total_cash_reserve_actual_dollar
    , total_cash_reserves
    , total_initial_security_value
    , total_post_rebalance_security_value
    , allocation_preference
    , allow_buying_and_selling_of_same_slm
    , rebalancing_group_annual_capital_gains_tax_budget
    , "REBALANCING_GROUP_ANNUAL_CAPITAL_GAINS_TAX_BUDGET_%_USED" as rebalancing_group_annual_capital_gains_tax_budget_percent_used
    , rebalancing_group_annual_capital_gains_tax_budget_value_type
    , cash_to_raise
    , initial_cash_dollar
    , initial_cash_percent
    , margin_account
    , post_rebalance_cash_dollar
    , post_rebalance_cash_percent
    , sweep_cash
    , "T+1_CASH" as t_plus_one_cash
    , total_cash_dollar
    , total_cash_percent
    , total_cash_reserve_actual_percent
    , total_cash_reserve_goal_dollar
    , total_cash_reserve_goal_percent
    , tradeable_cash
    , uploaded_cash
    , account_status
    , commission_maximum_number_of_shares
    , custodian_fee_schedule
    , days_to_hold_buys
    , dvp_number
    , equity_dividend_reinvestment
    , equity_round_lot_size
    , equity_trade_file_format
    , hold_duplicate_trades
    , mutual_fund_buy_type
    , mutual_fund_capital_gains_reinvestment
    , mutual_fund_dividend_reinvestment
    , mutual_fund_round_lot_size
    , mutual_fund_sell_type
    , mutual_fund_trade_file_format
    , per_share_commission
    , per_trade_commission
    , prospect_account
    , rebalancing_funding_account_number
    , rebalancing_sma
    , trading_id
    , allow_redemption_fees
    , allow_short_term_gains
    , allow_violation_of_wash_sale_rule
    , asset_location_preference
    , default_rebalance_setting
    , equities_with_fees_minimum_holding_size_dollar
    , equities_with_fees_minimum_holding_size_percent
    , equities_with_fees_minimum_trade_size_dollar
    , equities_with_fees_minimum_trade_size_percent
    , maximum_gain_amount
    , minimum_trade_size_tolerance_dollar
    , minimum_trade_size_tolerance_percent
    , non_fee_securities_minimum_holding_size_dollar
    , non_fee_securities_minimum_holding_size_percent
    , non_fee_securities_minimum_trade_size_dollar
    , non_fee_securities_minimum_trade_size_percent
    , only_buy_existing_holdings
    , only_warn_for_st_gain_violations
    , restrict_all_securities
    , sell_based_on_tax_optimization
    , short_term_gain_restriction_boundary
    , short_term_maximum_gain_amount_dollar
    , short_term_maximum_gain_amount_percent
    , transaction_fee_fund_minimum_holding_size_dollar
    , transaction_fee_fund_minimum_holding_size_percent
    , transaction_fee_fund_minimum_trade_size_dollar
    , transaction_fee_fund_minimum_trade_size_percent
    , annual_capital_gains_tax_budget
    , "ANNUAL_CAPITAL_GAINS_TAX_BUDGET_%_USED" as annual_capital_gains_tax_budget_percent_used
    , annual_capital_gains_tax_budget_value_type
    , closing_method
    , long_term_carryover_ytd
    , long_term_tax_rate
    , realized_long_term_gain_loss_ytd
    , realized_short_term_gain_loss_ytd
    , short_term_carryover_ytd
    , short_term_tax_rate
    , state_tax_rate
    , tax_loss_harvesting_minimum_dollar
    , tax_loss_harvesting_minimum_percent
    , turnover_ytd
    , wash_sale_group_id
    , aum_household_name
    , aum_upload_household_id
    , custody
    , custody_type
    , investment_discretion
    , investment_manager
    , voting_authority
    , wrap_program
    , accounts_within_group
    , household
    , migration__account_status
    , migration__group_name_1
    , migration__group_name_2
    , migration__keywords
    , migration__rebalancing_group_id
    , not_billed
    , not_billed_effective_date
    , not_billed_previous_value
    , not_billed_previous_value_effective_date
    , system_investment_discretion
    , system_investment_manager
    , system_voting_authority
    , erisa
    , {{ col_is_head(reference=source('tamarac_emerson', 'accounts')) }}
    , {{ col_is_current(date_col='effective_date') }}
    , record_datetime as _source_loaded_at
from {{ source('tamarac_emerson', 'accounts') }}