{{ config(
  enabled=false
) }}

select
    employee_id                               as employee_id
  , is_active                                 as active
  , employment_status                         as employment_status
  , employee_num                              as payroll_file_number
  , associate_legal_name_first                as legal_name_first
  , associate_legal_name_middle               as legal_name_middle
  , associate_legal_name_last                 as legal_name_last
  , associate_legal_name_suffix               as legal_name_suffix
  , associate_legal_name_full                 as legal_name_full
  , associate_preferred_name                  as preferred_name
  , associate_birth_date                      as birth_date
  , associate_gender_code                     as gender_code
  , associate_gender_name                     as gender_name
  , associate_personal_email                  as personal_email
  , associate_personal_phone                  as personal_phone
  , associate_personal_cell_phone             as personal_cell_phone
  , associate_legal_address_line1             as legal_address_line1
  , associate_legal_address_line2             as legal_address_line2
  , associate_legal_address_city              as legal_address_city
  , associate_legal_address_state_abb         as legal_address_state_abb
  , associate_legal_address_state             as legal_address_state_name
  , associate_legal_address_zip_code          as legal_address_zip_code
  , associate_legal_address_country           as legal_address_country
  , associate_other_address_line1             as other_address_line1
  , associate_other_address_line2             as other_address_line2
  , associate_other_address_city              as other_address_city
  , associate_other_address_state_abb         as other_address_state_abb
  , associate_other_address_state             as other_address_state
  , associate_other_address_zip_code          as other_address_zip_code
  , associate_other_address_country           as other_address_country
  , associate_eeo_identification_method       as eeo_identification_method
  , associate_eeo_ethnicity                   as eeo_ethnicity
  , associate_education                       as education
  , associate_work_email                      as work_email
  , associate_work_phone                      as work_phone
  , associate_work_cell_phone                 as work_cell_phone
  , position_seniority_hire_date              as seniority_hire_date
  , associate_original_hire_date              as original_hire_date
  , associate_rehire_date                     as rehire_date
  , associate_final_termination_date          as final_termination_date
  , position_company_code                     as position_company_code
  , position_id                               as position_id
  , position_status_code                      as position_status_code
  , position_status                           as position_status
  , position_seniority_hire_date              as position_seniority_hire_date
  , position_start_date                       as position_start_date
  , position_termination_date                 as position_termination_date
  , position_change_reason                    as position_change_reason
  , position_region_code                      as position_region_code
  , position_region_name                      as position_region_name
  , position_region_description               as position_region_description
  , home_organizational_units_market_code     as position_market_code
  , position_market_name                      as position_market_name
  , home_organizational_units_department_code as position_department_code
  , position_department_name                  as position_department_name
  , position_manager_position_id              as position_manager_position_id
  , position_manager_name                     as position_manager_name
  , position_primary_job_indicator            as position_primary_job_indicator
  , position_title_code                       as position_title_code
  , position_title                            as position_title
  , job_function_code                         as job_function_code
  , position_worker_type                      as position_worker_type
  , position_benefits_group_code              as position_benefits_group_code
  , position_benefits_group_class             as position_benefits_group_class
  , occupational_classifications_eeo_code     as position_eeo_code
  , position_eeo_class                        as position_eeo_class
  , position_flsa                             as position_flsa
  , occupational_classifications_class_code   as position_class_code
  , position_eeo_class                        as position_class
  , position_full_time_equivalent             as position_full_time_equivalent
  , position_scheduled_hours                  as position_scheduled_hours
  , position_standard_hours                   as position_standard_hours
  , cost_num                                  as position_cost_number
  , position_cost_num_legal_code              as legal_code
  , position_region_code                      as region_region_code
  , position_cost_num_market_code             as market_code
  , location_code                             as location_code
  , position_cost_num_team_code               as team_code
  , position_cost_num_natural_account         as natural_account
  , position_cost_num_category                as category
  , position_work_site_location_code          as work_site_location_code
  , position_work_site_location_name          as work_site_location_name
  , position_work_site_address_line1          as work_site_address_line1
  , position_work_site_address_line2          as position_work_site_address_line2
  , position_work_site_address_line3          as position_work_site_address_line3
  , position_work_site_address_city           as position_work_site_address_city
  , position_work_site_address_state_abb      as position_work_site_address_state_abb
  , position_work_site_address_state          as position_work_site_address_state
  , position_work_site_address_zip_code       as position_work_site_address_zip_code
  , position_work_site_address_country        as position_work_site_address_country
  , null                                      as employee_record_adp_updated_date
  , data_last_refreshed_date                  as data_last_refreshed_date
  , hire_details                              as hire_details
  , change_reason_code                        as status_change_code
  , change_reason_description                 as status_change_reason
  , vol_invol                                 as vol_invol
  , reporting_office                          as reporting_office
  , source                                    as source
from {{ ref('int_adp_employees_all') }}
where true
    and is_head = 1