select
    id
  , owner_id
  , is_deleted
  , name
  , created_date
  , created_by_id
  , last_modified_date
  , last_modified_by_id
  , system_modstamp
  , last_activity_date
  , last_viewed_date
  , last_referenced_date
  , import_name_c
  , action_c
  , adjustment_type_c
  , advisor_consent_c
  , amount_c
  , approved_on_c
  , approved_by_ic_unapproved_purchase_c
  , approver_c
  , call_put_c
  , cash_raised_follow_up_c
  , category_c
  , client_directed_attachment_notes_c
  , client_directed_type_c
  , client_directed_c
  , client_c
  , comments_ic_c
  , comments_c
  , completed_by_c
  , cover_uncover_c
  , created_by_name_c
  , date_of_contact_c
  , date_of_trade_c
  , exported_c
  , import_id_c
  , journal_date_c
  , last_modified_by_name_c
  , limit_amount_c
  , limit_stop_amount_c
  , maturity_date_begin_c
  , maturity_date_end_c
  , maximum_dollar_price_c
  , minimum_credit_rating_c
  , model_c
  , month_c
  , moxy_order_id_c
  , non_discretionary_account_at_trade_time_c
  , notes_fixed_income_trader_c
  , order_type_c
  , override_trade_block_model_c
  , owner_name_c
  , price_c
  , priority_level_c
  , product_status_as_of_trade_c
  , quantity_c
  , recommender_name_c
  , recommender_c
  , recurrences_c
  , remaining_recurrences_c
  , requestor_name_c
  , requestor_c
  , security_name_c
  , security_type_c
  , security_c
  , sell_all_c
  , sell_entire_position_c
  , send_notification_transaction_completed_c
  , share_quantity_c
  , state_flexibility_c
  , state_c
  , strike_c
  , ticker_symbol_c
  , trade_frequency_c
  , trade_status_c
  , trade_type_c
  , trading_notes_c
  , transaction_block_c
  , worked_by_c
  , year_c
  , estate_item_c
  , previously_approved_by_ic_c
  , _fivetran_synced
  , account_name_c
  , custodial_firm_c
  , client_owner_c
  , account_cash_balance_c
  , account_c
  , courtesy_account_form_c
  , trading_system_c
  , bostale_date_c
  , current_model_on_account_c
  , account_id_c
  , current_cash_percentage_c
  , prime_broker_enabled_c
  , margin_on_account_c
  , recommender_name_2_c
  , ima_c
  , risk_objective_c
  , requester_name_2_del_c
  , non_discretionary_account_c
  , account_closed_date_c
  , current_account_value_c
  , block_on_account_c
  , valid_paperwork_c
  , branch_c
  , custodian_restriction_notes_c
  , risk_tolerance_c
  , location_c
  , as_of_date_c
  , sys_complete_notification_cc_c
from {{ source('salesforce_compass', 'trade_instruction_c') }}