select
    id
  , owner_id
  , is_deleted
  , name
  , record_type_id
  , created_date
  , created_by_id
  , last_modified_date
  , last_modified_by_id
  , system_modstamp
  , last_activity_date
  , last_viewed_date
  , last_referenced_date
  , aum_classification_confirmed_by_c
  , aum_classification_notes_c
  , aum_classification_c
  , account_description_c
  , account_idorion_c
  , account_operational_tags_c
  , account_type_c
  , baa_type_c
  , cash_balance_c
  , comments_c
  , committed_amount_c
  , current_value_c
  , identifier_c
  , ins_additional_coverage_c
  , ins_annual_premium_c
  , ins_coverage_amount_c
  , mariner_id_c
  , various_tags_c
  , subadvisor_date_opened_c
  , model_on_account_c
  , date_reviewed_c
  , date_revised_c
  , ins_expiration_date_c
  , investment_fee_percent_c
  , liability_interest_rate_c
  , quick_comment_c
  , subadvisor_date_closed_c
  , registration_type_c
  , status_c
  , trade_restriction_c
  , closing_date_c
  , opening_date_c
  , payment_mode_c
  , perf_10_yr_c
  , perf_1_d_c
  , perf_1_yr_c
  , perf_3_yr_c
  , perf_5_yr_c
  , perf_as_of_date_c
  , perf_inception_c
  , perf_mtd_c
  , perf_qtd_c
  , perf_ytd_c
  , policy_type_c
  , estate_item_type_c
  , net_cash_value_c
  , net_cash_value_date_c
  , data_source_override_c
  , current_historical_record_c
  , custodian_c
  , debt_balance_c
  , opportunity_c
  , only_in_salesforce_c
  , booperational_tags_c
  , bostale_date_c
  , custodian_as_of_date_c
  , as_of_date_c
  , custodian_restriction_notes_c
  , closing_check_ytdnet_c_w_c
  , subadvisor_id_c
  , paperwork_type_on_file_c
  , stale_date_client_c
  , stale_account_notes_c
  , stale_data_type_c
  , admin_fee_c
  , bill_calculated_in_salesforce_c
  , billable_market_value_c
  , billing_account_number_c
  , fidelity_purge_account_c
  , billing_exception_category_c
  , billing_exception_details_c
  , billing_method_c
  , billing_style_c
  , discount_rate_c
  , aggregated_in_tier_c
  , mh_billing_calculation_c
  , billing_account_outstanding_fees_c
  , block_on_account_c
  , capital_gains_reinvested_c
  , compensation_account_c
  , delink_from_custodian_c
  , fixed_income_holdings_c
  , margin_c
  , non_discretionary_account_c
  , orion_restriction_check_c
  , prime_broker_enabled_c
  , sma_c
  , sma_asset_name_c
  , tamarac_rebal_account_c
  , recon_notes_c
  , operations_notes_c
  , restriction_notes_c
  , restriction_notes_2_c
  , compliance_review_notes_c
  , i_rebal_household_c
  , is_managed_c
  , financing_company_c
  , linked_individual_fixed_income_c
  , recon_date_c
  , maturity_restriction_c
  , investment_status_notes_c
  , rating_restriction_c
  , other_restriction_c
  , distribution_type_c
  , distribution_amount_c
  , distribution_frequency_c
  , duration_c
  , swap_c
  , swap_cusips_c
  , swap_notes_c
  , position_size_c
  , replenish_minimum_cash_c
  , tax_status_c
  , minimum_cash_c
  , billing_exception_c
  , state_1_c
  , state_2_c
  , am_restrictions_c
  , subadvisor_c
  , fund_family_c
  , data_source_c
  , reconciliation_frequency_c
  , recon_assignment_c
  , erisa_c
  , erisa_confirmation_c
  , erisa_affiliated_investments_c
  , year_to_date_contributions_c
  , year_to_date_distributions_c
  , qtd_net_contributions_billable_c
  , subadvisor_rate_override_c
  , email_to_c
  , advisor_approved_status_c
  , billing_account_c
  , household_c
  , fee_schedule_c
  , eclipse_enabled_c
  , acknowledgment_letter_on_file_c
  , download_source_c
  , account_idmsec_c
  , msec_commissions_life_to_date_c
  , inorganic_funds_c
  , inorganic_revenue_cur_qtr_c
  , inorganic_revenue_prev_qtr_c
  , inorganic_value_c
  , option_multi_margin_c
  , options_investment_guidelines_c
  , options_level_c
  , options_rider_c
  , calculation_system_c
  , share_with_c
  , fixed_income_cash_available_c
  , sys_migration_source_c
  , sys_migration_id_c
  , equity_c
  , equity_goal_c
  , fixed_income_c
  , ytd_realized_gain_loss_c
  , trading_id_c
  , fixed_alts_c
  , pref_c
  , large_cap_c
  , smid_c
  , intl_equity_c
  , mlp_reits_c
  , firm_trading_c
  , other_c
  , trading_system_c
  , broker_dealer_account_c
  , elimination_period_c
  , monthly_maximum_c
  , _fivetran_synced
  , moxy_intra_day_import_c
  , billing_calculation_system_c
  , stale_date_aging_c
  , recon_date_calc_c
  , partner_firm_c
  , year_to_date_net_contributions_c
  , current_cash_pct_c
  , reconciliation_count_c
  , non_disc_mix_c
  , included_for_afis_c
  , current_commited_value_c
  , estate_item_id_18_c
  , reconciliation_valuation_date_rollup_c
  , reconciliation_date_rollup_c
  , current_historical_status_c
  , b_d_mix_c
  , sys_is_msecaccount_c
  , valid_paperwork_c
  , cash_percent_c
  , current_historical_valuation_date_c
  , stale_date_client_aging_c
  , location_c
  , msecopt_in_c
  , estate_item_name_data_table_edit_c
  , new_update_c
  , new_update_formula_c
  , rollover_effective_date_c
  , rollover_paperwork_c
  , rollover_involvement_c
  , rollover_type_c
  , rollover_c
  , annuity_maturity_date_c
from {{ source('salesforce_compass', 'estate_item_c') }}