select
    id
  , is_deleted
  , name
  , record_type_id
  , created_date
  , created_by_id
  , last_modified_date
  , last_modified_by_id
  , system_modstamp
  , last_activity_date
  , last_viewed_date
  , last_referenced_date
  , apx_reconciliation_c
  , adjustment_credit_remaining_c
  , adjustments_fee_c
  , admin_fee_total_c
  , advisor_approved_date_c
  , advisor_comments_c
  , approved_by_advisor_c
  , view_type_hh_plus_client_c
  , bc_adjustments_fee_c
  , bc_adjustments_stored_c
  , bc_billable_value_stored_c
  , bc_billing_style_stored_c
  , bc_fee_schedule_stored_c
  , date_finalized_c
  , bc_gross_fee_stored_c
  , billable_value_c
  , team_member_assigned_c
  , billing_calculation_status_c
  , billing_error_timestamp_c
  , billing_exception_completed_c
  , billing_method_old_c
  , billing_reject_notes_c
  , date_to_pull_fee_c
  , billing_style_c
  , branch_2_c
  , billing_account_outstanding_fees_new_c
  , calculation_as_of_date_c
  , calculation_finalized_timestamp_c
  , collection_date_c
  , collection_notes_c
  , collection_sheet_name_c
  , company_family_c
  , who_worked_reject_c
  , fee_estimate_c
  , fee_excluded_assets_c
  , fee_rebates_c
  , fee_schedule_c
  , fee_type_c
  , finalized_fee_status_c
  , first_level_approval_date_c
  , first_level_approver_c
  , gross_fee_c
  , insufficient_funds_workflow_count_c
  , plan_c
  , date_reject_resolved_c
  , fee_frequency_c
  , valuation_method_c
  , billing_account_number_audit_tracking_c
  , ready_for_collections_audit_tracking_c
  , non_was_referral_fee_c
  , service_rendered_c
  , source_invoice_identifier_c
  , calculation_system_c
  , invoice_date_c
  , invoice_link_c
  , management_style_c
  , manual_review_date_c
  , manual_reviewer_c
  , miscellaneous_adjustment_reason_c
  , miscellaneous_adjustment_c
  , ntf_1_c
  , ntf_2_c
  , ntf_3_c
  , ntf_fee_c
  , net_contributions_fee_c
  , operations_approval_date_c
  , operations_comments_c
  , orion_bill_id_c
  , overide_billing_custodian_c
  , payout_status_c
  , payout_timestamp_c
  , qpr_linking_c
  , quarterback_2_c
  , reject_category_c
  , rejected_count_c
  , rejected_date_c
  , status_c
  , third_party_calculation_c
  , total_account_value_c
  , was_fee_c
  , write_off_fee_c
  , x_40_act_fee_c
  , billing_account_c
  , account_generating_fee_c
  , old_name_c
  , estate_item_c
  , ar_ap_item_c
  , date_last_invoice_sent_c
  , _fivetran_synced
  , financial_account_household_id_del_c
  , fee_rate_c
  , revenue_as_of_date_c
  , client_previous_qtr_fee_c
  , registration_summary_c
  , invoice_hyperlink_c
  , ready_for_collections_c
  , days_since_rejected_c
  , client_unique_identifier_c
  , advisor_approved_status_c
  , cash_deficit_amount_c
  , concatenate_2_c
  , billing_account_number_c
  , was_percentage_c
  , orion_account_id_c
  , bc_billing_style_c
  , billing_method_c
  , account_close_date_c
  , client_name_c
  , account_type_c
  , cash_deficit_c
  , client_agreement_version_c
  , client_current_qtr_fee_c
  , invoice_on_qpr_c
  , billing_account_household_id_del_c
  , discount_amount_c
  , aggregated_in_tier_c
  , subadvisor_payout_amount_c
  , referral_fee_paid_c
  , client_fee_change_amt_c
  , recon_date_c
  , adjustments_cross_check_c
  , run_rate_revenue_c
  , final_fee_change_perc_c
  , net_fee_c
  , quarterback_c
  , orion_house_id_c
  , fee_account_c
  , client_fee_change_perc_c
  , status_summary_c
  , billing_account_formatted_c
  , days_outstanding_c
  , billing_account_tax_status_c
  , account_current_qtr_fee_c
  , billing_error_timestamp_elapsed_c
  , referral_fee_c
  , was_category_c
  , qpr_status_c
  , referral_fee_estimate_c
  , subadvisor_c
  , days_in_qtr_prior_to_invoice_c
  , is_qualified_c
  , bc_gross_fee_c
  , billing_exception_details_c
  , concatenate_3_c
  , admin_fee_c
  , gross_revenue_no_adjustments_c
  , first_level_summary_c
  , avg_annual_gross_fee_rate_c
  , account_number_c
  , registration_name_c
  , previous_qtr_fee_c
  , quarter_end_client_recon_c
  , model_on_account_c
  , billing_exception_c
  , billing_account_outstanding_fees_c
  , billing_account_type_c
  , fee_type_summary_c
  , custodian_c
  , billing_exception_category_c
  , billing_account_cash_c
  , discount_rate_c
  , billing_custodian_c
  , subadvisor_payout_rate_c
  , collection_month_c
  , start_date_c
  , short_name_c
  , revenue_quarter_c
  , final_fee_change_amt_c
  , aum_classification_c
  , gross_revenue_c
  , invoice_quarter_c
  , msec_commissions_last_12_months_c
  , household_type_c
  , tax_status_c
  , bc_billable_value_c
  , collection_week_c
  , branch_c
  , maximum_level_allowed_c
  , avg_annual_net_fee_rate_c
  , email_to_c
  , file_as_c
  , billing_account_approved_household_id_del_c
  , collection_quarter_c
  , days_in_invoice_qtr_c
  , payment_method_fee_c
from {{ source('salesforce_compass', 'invoice_review_c') }}