select
    id
  , is_deleted
  , master_record_id
  , account_id
  , last_name
  , first_name
  , salutation
  , middle_name
  , suffix
  , name
  , record_type_id
  , other_street
  , other_city
  , other_state
  , other_postal_code
  , other_country
  , other_latitude
  , other_longitude
  , other_geocode_accuracy
  , mailing_street
  , mailing_city
  , mailing_state
  , mailing_postal_code
  , mailing_country
  , mailing_latitude
  , mailing_longitude
  , mailing_geocode_accuracy
  , phone
  , fax
  , mobile_phone
  , home_phone
  , other_phone
  , assistant_phone
  , title
  , department
  , assistant_name
  , birthdate
  , description
  , owner_id
  , do_not_call
  , created_date
  , created_by_id
  , last_modified_date
  , last_modified_by_id
  , system_modstamp
  , last_activity_date
  , last_curequest_date
  , last_cuupdate_date
  , last_viewed_date
  , last_referenced_date
  , email_bounced_reason
  , email_bounced_date
  , is_email_bounced
  , photo_url
  , jigsaw_contact_id
  , assistant_email_c
  , business_email_c
  , business_name_c
  , business_phone_c
  , college_c
  , referral_source_c
  , date_of_death_c
  , favorite_alcoholic_beverage_c
  , favorite_light_beverage_c
  , favorite_snack_c
  , file_as_c
  , gender_c
  , hobbies_c
  , investment_interests_c
  , investment_objectives_c
  , investment_vehicles_used_c
  , legal_address_city_c
  , legal_address_label_c
  , legal_address_postal_code_c
  , legal_address_state_c
  , legal_street_address_c
  , marital_status_c
  , mobile_personal_c
  , nickname_c
  , occupation_c
  , personal_email_c
  , preferred_contact_method_c
  , preferred_contact_time_c
  , preferred_wealth_email_c
  , business_address_city_c
  , business_address_label_c
  , business_address_postal_code_c
  , business_address_state_c
  , business_address_c
  , college_graduation_c
  , digital_marketing_campaigns_wealth_c
  , digital_marketing_opt_out_wealth_c
  , digital_marketing_options_wealth_c
  , tags_c
  , wedding_anniversary_c
  , user_c
  , wealth_contact_lifecycle_c
  , retirement_contact_lifecycle_c
  , lead_source_wealth_c
  , asset_management_contact_lifecycle_c
  , lead_amount_wealth_c
  , marketing_owner_c
  , contact_type_c
  , individual_insurance_death_benefit_c
  , marketing_owner_wealth_c
  , marketing_owner_retirement_c
  , marketing_owner_asset_mgt_c
  , role_c
  , mh_quarterly_report_version_c
  , mh_rbg_color_assignment_c
  , mailing_label_c
  , mh_team_file_location_c
  , short_note_c
  , country_of_citizenship_c
  , advisor_termination_date_c
  , first_date_of_ofac_check_c
  , most_recent_date_of_ofac_check_c
  , unique_id_c
  , ddl_firm_id_c
  , ddl_rep_id_c
  , sys_topic_1_c
  , sys_topic_2_c
  , sys_topic_3_c
  , country_of_residence_c
  , sys_migration_source_c
  , sys_migration_id_c
  , mfit_exclusion_override_c
  , notification_id_c
  , mh_photo_c
  , _fivetran_synced
  , contact_id_18_c
  , client_age_c
  , occupation_code_c
  , retired_c
  , original_oppty_stage_c
from {{ source('salesforce_compass', 'contact') }}