select
    id
  , owner_id
  , is_deleted
  , name
  , record_type_id
  , created_date
  , created_by_id
  , last_modified_date
  , last_modified_by_id
  , system_modstamp
  , last_activity_date
  , last_viewed_date
  , last_referenced_date
  , allocations_c
  , as_of_date_estimated_performance_c
  , cash_tolerance_band_c
  , company_c
  , created_by_name_c
  , do_not_trade_mariner_trading_c
  , high_cash_invest_frequency_c
  , initial_transaction_fee_cost_fidelity_c
  , initial_transaction_fee_cost_schwab_c
  , last_modified_by_name_c
  , length_of_maturity_c
  , lock_down_final_warning_c
  , lock_down_reminder_c
  , mh_trading_model_notes_c
  , mtd_performance_estimated_c
  , management_style_c
  , maturity_date_c
  , minimum_investment_type_c
  , minimum_investment_c
  , model_cash_target_c
  , model_type_c
  , orion_model_id_c
  , owner_name_c
  , previous_model_name_c
  , qtd_performance_estimated_c
  , require_committed_amount_c
  , sma_asset_name_c
  , series_c
  , subadvisor_2_rate_c
  , subadvisor_rate_c
  , subadvisor_was_fee_c
  , ticker_c
  , total_value_c
  , total_value_of_holdings_c
  , vehicle_c
  , weighted_model_id_c
  , ytd_performance_estimated_c
  , sma_asset_category_c
  , sma_asset_class_c
  , sma_approval_status_c
  , sys_addendum_key_c
  , _fivetran_synced
  , send_reminder_c
  , reminder_date_c
  , final_warning_date_c
from {{ source('salesforce_compass', 'model_c') }}