select
    id::varchar(18)                              as id
    , is_deleted::boolean                        as is_deleted
    , master_record_id::varchar(18)              as master_record_id
    , case_number::varchar(90)                   as case_number
    , contact_id::varchar(18)                    as contact_id
    , account_id::varchar(18)                    as account_id
    , parent_id::varchar(18)                     as parent_id
    , supplied_name::varchar(240)                as supplied_name
    , supplied_phone::varchar(120)               as supplied_phone
    , supplied_company::varchar(240)             as supplied_company
    , type::varchar(765)                         as type
    , status::varchar(765)                       as status
    , reason::varchar(765)                       as reason
    , origin::varchar(765)                       as origin
    , language::varchar(120)                     as language
    , subject::varchar(765)                      as subject
    , priority::varchar(765)                     as priority
    , description::varchar(96000)                as description
    , is_closed::boolean                         as is_closed
    , closed_date::timestamp_tz(9)               as closed_date
    , is_escalated::boolean                      as is_escalated
    , owner_id::varchar(18)                      as owner_id
    , created_date::timestamp_tz(9)              as created_date
    , created_by_id::varchar(18)                 as created_by_id
    , last_modified_date::timestamp_tz(9)        as last_modified_date
    , last_modified_by_id::varchar(18)           as last_modified_by_id
    , system_modstamp::timestamp_tz(9)           as system_modstamp
    , contact_phone::varchar(120)                as contact_phone
    , contact_mobile::varchar(120)               as contact_mobile
    , contact_email::varchar(240)                as contact_email
    , contact_fax::varchar(120)                  as contact_fax
    , comments::varchar(4000)                    as comments
    , last_viewed_date::timestamp_tz(9)          as last_viewed_date
    , last_referenced_date::timestamp_tz(9)      as last_referenced_date
    , case_age_c::float                          as case_age_c
    , co_owner_c::varchar(18)                    as co_owner_c
    , due_date_c::date                           as due_date_c
    , offending_system_c::varchar(4099)          as offending_system_c
    , case_resolution_c::varchar(15000)          as case_resolution_c
    , ranking_c::float                           as ranking_c
    , location_c::varchar(3900)                  as location_c
    , division_c::varchar(3900)                  as division_c
    , investment_team_comments_c::varchar(98304) as investment_team_comments_c
    , import_id_c::varchar(150)                  as import_id_c
    , estate_item_c::varchar(18)                 as estate_item_c
    , personal_email_c::varchar(3900)            as personal_email_c
    , internal_comments_c::varchar(765)          as internal_comments_c
    , case_level_c::float                        as case_level_c
    , orion_case_number_c::varchar(36)           as orion_case_number_c
    , orion_project_number_c::varchar(36)        as orion_project_number_c
    , orion_card_number_c::varchar(36)           as orion_card_number_c
    , mwa_orion_integrated_case_c::boolean       as mwa_orion_integrated_case_c
    , mh_service_c::varchar(18)                  as mh_service_c
    , _fivetran_deleted::boolean                 as _fivetran_deleted
    , _fivetran_synced::timestamp_tz(9)          as _fivetran_synced
from {{ source('salesforce_compass_fivetran', 'case') }}
