select
    id
  , owner_id
  , is_deleted
  , name
  , record_type_id
  , created_date
  , created_by_id
  , last_modified_date
  , last_modified_by_id
  , system_modstamp
  , last_activity_date
  , last_viewed_date
  , last_referenced_date
  , account_execuitive_c
  , account_c
  , active_participants_c
  , administrator_benchmarking_review_c
  , adoption_agreement_received_c
  , advisory_or_brokerage_c
  , allocation_frequency_c
  , amendment_effective_date_c
  , amendments_received_c
  , analyst_c
  , annual_participant_retirement_report_c
  , assigned_tier_c
  , auto_enrollment_pct_c
  , auto_enrollment_c
  , bor_date_c
  , bor_c
  , behaviorial_finance_review_c
  , client_type_c
  , company_match_type_c
  , company_match_c
  , company_non_elective_c
  , composite_plan_return_c
  , confirmed_assets_c
  , consultant_c
  , contact_c
  , contract_number_c
  , copy_of_investment_policy_statement_c
  , created_by_name_c
  , date_client_profile_obtained_c
  , date_fiduciary_doc_pack_provided_c
  , date_iaa_submitted_c
  , date_ima_obtained_c
  , date_ips_revised_c
  , date_last_sp_checklist_contract_review_c
  , date_new_account_paperwork_issued_c
  , date_new_account_setup_c
  , date_new_acct_paperwork_obtained_c
  , date_scanned_in_c
  , date_signed_paperwork_faxed_c
  , date_toa_completed_c
  , date_toa_intiated_c
  , date_toa_obtained_c
  , date_of_last_admin_benchmarking_review_c
  , date_of_last_fee_review_c
  , date_of_last_fiduciary_training_c
  , date_of_last_goals_and_objectives_c
  , date_of_last_industry_reports_c
  , date_of_last_legislative_update_c
  , date_of_last_model_changes_c
  , date_of_last_participant_education_c
  , date_of_last_rfp_rfi_search_c
  , date_of_last_rk_plan_review_c
  , date_of_last_rk_review_c
  , date_of_last_review_c
  , date_of_verbal_intent_c
  , document_1_link_c
  , document_2_link_c
  , document_3_link_c
  , document_4_link_c
  , document_5_link_c
  , document_effective_date_c
  , education_specialist_c
  , eligibility_provisions_service_c
  , eligibility_provisions_c
  , employee_wellness_survey_c
  , entry_dates_c
  , fee_analysis_schedule_c
  , fee_analysis_c
  , fee_schedule_c
  , fiduciary_document_pack_c
  , fiduciary_relationship_c
  , fiduciary_training_schedule_c
  , financial_hardship_c
  , firm_plan_id_c
  , firm_plan_status_c
  , firm_refresh_date_time_c
  , first_payroll_submission_completed_c
  , goals_and_objectives_c
  , household_c
  , how_many_accounts_of_each_type_c
  , iaa_version_c
  , ima_fee_c
  , import_id_c
  , in_service_withdraw_c
  , industry_name_c
  , industry_reports_c
  , investment_menu_c
  , last_modified_by_name_c
  , lead_originator_c
  , legislative_update_c
  , loans_c
  , mra_investment_review_schedule_c
  , match_provisions_c
  , matching_formula_c
  , model_portfolio_c
  , models_per_account_c
  , non_elective_formula_c
  , number_of_funds_c
  , number_of_outstanding_loans_c
  , opportunity_c
  , other_eligibility_age_c
  , other_eligibility_service_c
  , other_vesting_schedule_c
  , outstanding_loan_amount_c
  , owner_name_c
  , participant_education_plan_c
  , participants_actual_c
  , participants_eligible_c
  , participants_with_three_plus_funds_c
  , participations_termed_c
  , plan_assets_as_of_date_c
  , plan_assets_c
  , plan_deferral_rate_c
  , plan_entry_dates_c
  , plan_implementation_completed_c
  , plan_participation_rate_c
  , plan_tax_id_c
  , plan_type_c
  , plan_year_end_c
  , platform_c
  , primary_contact_c
  , product_type_c
  , provider_name_c
  , provider_product_name_c
  , qdia_fund_c
  , quarterback_name_c
  , quarterback_c
  , rfp_rfi_search_c
  , ria_firm_name_c
  , rk_plan_review_c
  , rk_review_schedule_c
  , reason_for_delay_c
  , record_keeper_plan_number_c
  , recordkeeper_product_name_c
  , recordkeeper_c
  , report_email_address_c
  , report_schedule_c
  , review_frequency_c
  , roth_401_k_c
  , sfdc_project_end_date_c
  , sfdc_project_manager_c
  , sfdc_project_stage_c
  , sfdc_project_start_date_c
  , sfdc_project_status_c
  , sfdc_status_description_c
  , spd_effective_date_c
  , spd_received_c
  , sp_checklist_contract_review_c
  , safe_harbor_indicator_c
  , source_of_funds_c
  , tpa_obtained_c
  , tpa_c
  , temporary_account_number_c
  , tier_c
  , total_contribution_amount_c
  , total_distribution_amount_c
  , total_market_value_c
  , total_plan_net_amount_c
  , transfer_frequency_c
  , transfer_of_assets_completed_c
  , types_of_accounts_c
  , uninvested_cash_c
  , vendor_review_schedule_c
  , vesting_schedule_c
  , x_401_k_size_c
  , e_money_c
  , or_dollar_amount_c
  , account_idorion_c
  , billing_method_c
  , billing_frequency_c
  , date_fee_forms_submitted_to_recordkeeper_c
  , current_fee_at_recordkeeper_c
  , operations_notes_c
  , date_of_last_fee_review_confirmed_c
  , custodian_c
  , accounting_tracking_number_c
  , start_date_c
  , close_date_c
  , _fivetran_synced
  , aum_classification_c
  , actuary_c
  , third_party_administrator_tpa_c
  , auditor_c
  , review_schedule_c
  , hsa_provider_c
  , in_plan_roth_conversion_c
  , rk_rfp_rfi_c
  , financial_wellness_c
  , mariner_managed_accounts_c
  , education_meeting_frequency_c
  , education_meeting_type_c
  , education_rps_personnel_c
  , auto_increase_pct_c
  , advisor_rfp_rfi_search_c
  , hsa_c
  , date_of_last_rk_rfp_rfi_c
  , student_loan_repayment_c
  , auto_increase_c
  , after_tax_c
  , tdf_series_c
  , date_of_last_advisor_rfp_rfi_search_c
  , partner_firm_c
  , account_tier_c
  , days_since_fee_updated_at_recordkeeper_c
  , sfdc_project_duration_c
  , plan_id_18_c
  , rate_based_on_most_recent_assets_c
  , days_until_ips_expires_c
  , sfdc_days_remaining_c
  , days_until_new_ips_due_c
  , x_5_th_tier_dollars_threshold_c
  , flat_fee_type_c
  , flat_percent_fee_c
  , x_3_rd_tier_percent_c
  , fee_type_c
  , flat_annual_fee_c
  , advisory_fee_schedule_c
  , x_4_th_tier_dollars_threshold_c
  , x_1_st_tier_percent_c
  , x_2_nd_tier_dollars_threshold_c
  , x_1_st_tier_dollars_threshold_c
  , x_4_th_tier_percent_c
  , x_5_th_tier_percent_c
  , number_of_fee_tiers_c
  , x_3_rd_tier_dollars_threshold_c
  , x_2_nd_tier_percent_c
  , mh_location_c
  , x_3_rd_mariner_managed_tier_threshold_c
  , msec_registration_c
  , venrollment_video_c
  , x_1_st_mariner_managed_tier_c
  , x_4_th_mariner_managed_tier_c
  , bill_on_balance_c
  , x_4_th_mariner_managed_tier_threshold_c
  , ama_balance_c
  , x_6_th_tier_percent_c
  , mariner_managed_number_of_fee_tiers_c
  , trust_company_c
  , service_model_c
  , x_6_th_tier_dollars_threshold_c
  , x_1_st_mariner_managed_tier_threshold_c
  , x_2_nd_mariner_managed_tier_c
  , approximate_annual_contribution_c
  , x_2_nd_mariner_managed_tier_threshold_c
  , fixed_icr_c
  , interest_crediting_rate_strategy_c
  , x_3_rd_mariner_managed_tier_c
  , transferred_balance_c
from {{ source('salesforce_compass', 'plan_c') }}