select
    id
  , is_deleted
  , account_id
  , record_type_id
  , is_private
  , name
  , description
  , stage_name
  , amount
  , probability
  , expected_revenue
  , total_opportunity_quantity
  , close_date
  , type
  , next_step
  , lead_source
  , is_closed
  , is_won
  , forecast_category
  , forecast_category_name
  , campaign_id
  , has_opportunity_line_item
  , is_split
  , pricebook_2_id
  , owner_id
  , created_date
  , created_by_id
  , last_modified_date
  , last_modified_by_id
  , system_modstamp
  , last_activity_date
  , fiscal_quarter
  , fiscal_year
  , fiscal
  , contact_id
  , last_viewed_date
  , last_referenced_date
  , synced_quote_id
  , contract_id
  , has_open_activity
  , has_overdue_task
  , last_amount_changed_history_id
  , last_close_date_changed_history_id
  , actual_close_date_c
  , actual_aum_c
  , referral_source_c
  , expected_mwa_revenue_c
  , expected_montage_revenue_c
  , product_line_c
  , short_note_c
  , closed_lost_reason_c
  , closed_date_stamp_c
  , primary_contact_c
  , expected_revenue_c
  , sys_migration_source_c
  , sys_migration_id_c
  , _fivetran_synced
  , referral_firm_c
  , push_count
  , last_stage_change_date
  , total_expected_revenue_c
  , opportunity_age_c
from {{ source('salesforce_compass', 'opportunity') }}