select
    system_name
    , system_instance
    , system_key
    , firm_source
    , location_code
    , office_name
    , client_location_code
    , client_office_name
    , invoice_date
    , revenue_period_end_date
    , revenue_quarter_end_date
    , invoice_number_source
    , invoice_status
    , registrant_name
    , insurance_coordinator
    , insurance_carrier
    , insurance_revenue_source
    , insurance_policy_number
    , insurance_policy_added_date
    , lead_consultant
    , advisor_source
    , advisor
    , associate_id
    , client_fee_gross
    , client_fee_net
    , billing_style
    , billing_frequency
    , account_class
    , recurring_revenue
    , impacted_by_financial_markets
    , coa_account_number
    , coa_segment_1_legal_entity_id
    , coa_segment_2_product_id
    , coa_segment_3_accounting_id
    , coa_segment_4_team_id
    , coa_segment_5_natural_account_id
    , coa_segment_6_initiative_id
    , coa_segment_7_intercompany_id
    , coa_segment_8_future_id
    , revenue_category
    , revenue_type
    , system_name_crm
    , system_instance_crm
    , system_key_crm
    , account_id_crm
    , client_id_crm
    , client_id_original_crm
    , client_id_unique_compass
    , client_name
    , client_name_original_crm
    , client_lead_source
    , client_key_tags_crm
    , transaction_type
    , transaction_line_type
    , transaction_line_quantity
    , currency_code
    , currency_conversion_type
    , unit_selling_price
    , is_excluded
    , excluded_reasons
    , _invoice_key
    , _source_loaded_at
    , _source_file
    , _box_file_id
    , _extra_fields
    , _created_at
    , is_legacy
from {{ ref('nml_bills_insurance_mir') }}
