select
    id
    , _fivetran_deleted
    , _fivetran_synced
    , property_hs_all_contact_vids
    , property_first_deal_created_date
    , property_hs_calculated_mobile_number
    , property_hs_date_entered_customer
    , property_hs_count_is_worked
    , property_days_to_close
    , property_hs_count_is_unworked
    , property_gdc
    , property_assets_under_managment
    , property_hs_calculated_phone_number_country_code
    , property_hs_calculated_phone_number
    , property_hs_calculated_merged_vids
    , property_hs_avatar_filemanager_key
    , property_hs_calculated_form_submissions
    , property_first_conversion_date
    , property_first_conversion_event_name
    , property_call_disposition
    , property_home_city
    , property_home_zipcode
    , property_date_of_birth
    , property_home_state
    , property_home_address_1
    , property_hs_additional_emails
    , property_gender
    , property_hs_created_by_user_id
    , property_home_address_2
    , property_hs_content_membership_status
    , property_hs_date_entered_opportunity
    , property_hs_is_unworked
    , property_hs_date_entered_lead
    , property_hs_date_exited_lead
    , property_hs_is_contact
    , property_hs_email_domain
    , property_hs_last_sales_activity_timestamp
    , property_hs_last_sales_activity_date
    , property_hs_date_exited_opportunity
    , property_hs_first_engagement_object_id
    , property_hs_date_entered_subscriber
    , property_hs_date_exited_subscriber
    , property_hs_email_sends_since_last_engagement
    , property_hs_last_sales_activity_type
    , property_hs_ip_timezone
    , property_hs_email_hard_bounce_reason_enum
    , property_hs_latest_sequence_enrolled_date
    , property_hs_latest_sequence_enrolled
    , property_hs_pipeline
    , property_hs_marketable_until_renewal
    , property_hs_latest_source_timestamp
    , property_hs_object_id
    , property_hs_time_in_opportunity
    , property_hs_marketable_status
    , property_hs_time_in_lead
    , property_hs_time_between_contact_creation_and_deal_close
    , property_hs_time_to_move_from_lead_to_customer
    , property_hs_searchable_calculated_mobile_number
    , property_hs_time_to_move_from_opportunity_to_customer
    , property_hs_sales_email_last_opened
    , property_hs_time_in_customer
    , property_hs_lead_status
    , property_hs_sa_first_engagement_object_type
    , property_hs_sa_first_engagement_date
    , property_hs_time_between_contact_creation_and_deal_creation
    , property_hs_sa_first_engagement_descr
    , property_hs_time_to_first_engagement
    , property_hs_searchable_calculated_phone_number
    , property_hs_sales_email_last_clicked
    , property_hs_time_in_subscriber
    , property_hs_timezone
    , property_hs_legal_basis
    , property_hs_time_to_move_from_subscriber_to_customer
    , property_hs_sequences_actively_enrolled_count
    , property_hs_pinned_engagement_id
    , property_hs_sequences_is_enrolled
    , property_hs_sequences_enrolled_count
    , property_recent_deal_close_date
    , property_hs_email_optout_7368234
    , property_num_conversion_events
    , property_firstname
    , property_num_unique_conversion_events
    , property_num_associated_deals
    , property_lastmodifieddate
    , property_recent_deal_amount
    , property_total_revenue
    , property_twitterhandle
    , property_referal_partner
    , property_hs_user_ids_of_all_owners
    , property_hubspot_owner_assigneddate
    , property_recruiter_custodian_sales_team
    , property_hs_email_optout_7484018
    , property_social_media
    , property_spouse_name
    , property_hs_updated_by_user_id
    , property_hs_email_delivered
    , property_ip_state_code
    , property_ip_city
    , property_recent_conversion_event_name
    , property_ip_country
    , property_ip_state
    , property_recent_conversion_date
    , property_ip_country_code
    , property_street_address_2
    , property_work_email
    , property_hs_user_ids_of_all_notification_unfollowers
    , property_hs_user_ids_of_all_notification_followers
    , property_outbound_advisor_retirement
    , property_repcrd
    , property_riafirmcrd
    , property_riafirmname
    , property_city
    , property_lastname
    , property_hs_analytics_num_page_views
    , property_hubspot_team_id
    , property_hs_analytics_num_event_completions
    , property_hs_email_optout
    , property_hs_analytics_first_timestamp
    , property_twitterprofilephoto
    , property_hs_analytics_num_visits
    , property_email
    , property_hs_social_facebook_clicks
    , property_hs_analytics_first_visit_timestamp
    , property_hs_analytics_last_timestamp
    , property_hs_social_google_plus_clicks
    , property_hs_all_owner_ids
    , property_hs_social_twitter_clicks
    , property_hs_social_linkedin_clicks
    , property_num_notes
    , property_engagements_last_meeting_booked
    , property_notes_last_updated
    , property_mobilephone
    , property_notes_next_activity_date
    , property_notes_last_contacted
    , property_address
    , property_hs_sales_email_last_replied
    , property_num_contacted_notes
    , property_hubspot_owner_id
    , property_phone
    , property_fax
    , property_hs_email_last_email_name
    , property_hs_email_last_send_date
    , property_hs_latest_meeting_activity
    , property_hs_analytics_last_url
    , property_hs_email_open
    , property_hs_email_last_open_date
    , property_hs_email_bounce
    , property_hs_analytics_source_data_2
    , property_hs_analytics_source_data_1
    , property_hs_latest_source
    , property_hs_analytics_revenue
    , property_hs_analytics_average_page_views
    , property_hs_all_accessible_team_ids
    , property_associatedcompanyid
    , property_website
    , property_hs_social_num_broadcast_clicks
    , property_state
    , property_lifecyclestage
    , property_hs_analytics_last_visit_timestamp
    , property_hs_lifecyclestage_lead_date
    , property_hs_analytics_source
    , property_createdate
    , property_hs_all_team_ids
    , property_hs_lifecyclestage_opportunity_date
    , property_hs_latest_source_data_1
    , property_hs_latest_source_data_2
    , property_company
    , property_jobtitle
    , property_hs_lifecyclestage_customer_date
    , property_closedate
    , property_country
    , property_annualrevenue
    , property_hs_lifecyclestage_subscriber_date
    , property_zip
    , property_hs_email_first_send_date
    , property_hs_email_first_open_date
from {{ source('hubspot_network', 'contact') }}