select
    deal_id
    , portal_id
    , is_deleted
    , _fivetran_synced
    , property_hs_analytics_source_data_2
    , property_hs_analytics_source_data_1
    , property_hs_closed_amount_in_home_currency
    , property_hs_analytics_latest_source_timestamp_contact
    , property_hs_date_entered_decisionmakerboughtin
    , property_hs_date_entered_6734705
    , property_hs_date_entered_2494962
    , property_hs_date_entered_962615
    , property_amount_in_home_currency
    , property_days_to_close
    , property_hs_date_entered_41524885
    , property_hs_date_entered_appointmentscheduled
    , property_hs_analytics_source
    , property_hs_date_entered_1016290
    , property_hs_closed_amount
    , property_hs_analytics_latest_source_data_2_contact
    , property_hs_date_entered_closedwon
    , property_hs_date_entered_presentationscheduled
    , property_hs_analytics_latest_source
    , property_hs_analytics_latest_source_data_2
    , property_hs_analytics_latest_source_data_1
    , property_hs_analytics_latest_source_timestamp
    , property_hs_analytics_latest_source_contact
    , property_hs_analytics_latest_source_data_1_contact
    , property_hs_date_entered_closedlost
    , property_hs_analytics_latest_source_data_1_company
    , property_hs_analytics_latest_source_data_2_company
    , property_hs_analytics_latest_source_company
    , property_hs_created_by_user_id
    , property_hs_date_entered_1037199
    , property_hs_date_entered_2216211
    , property_hs_date_entered_2216212
    , property_hs_date_entered_1037201
    , property_hs_date_entered_1037200
    , property_hs_date_entered_2216213
    , property_hs_date_entered_43126578
    , property_hs_date_entered_37104998
    , property_hs_date_entered_37105004
    , property_hs_forecast_amount
    , property_hs_date_exited_decisionmakerboughtin
    , property_hs_date_exited_6734705
    , property_hs_date_exited_2494962
    , property_hs_date_exited_962615
    , property_hs_is_closed
    , property_hs_date_exited_presentationscheduled
    , property_hs_date_exited_41524885
    , property_hs_deal_stage_probability_shadow
    , property_hs_date_exited_appointmentscheduled
    , property_hs_deal_stage_probability
    , property_hs_lastmodifieddate
    , property_hs_is_closed_won
    , property_hs_is_deal_split
    , property_hs_date_exited_1016290
    , property_hs_num_target_accounts
    , property_hs_date_exited_2216211
    , property_hs_date_exited_1037200
    , property_hs_date_exited_1037201
    , property_hs_date_exited_1037199
    , property_hs_num_associated_deal_splits
    , property_hs_num_associated_active_deal_registrations
    , property_hs_num_associated_deal_registrations
    , property_hs_date_exited_43126578
    , property_hs_merged_object_ids
    , property_hs_time_in_1016290
    , property_hs_time_in_decisionmakerboughtin
    , property_hs_time_in_2494962
    , property_hs_time_in_appointmentscheduled
    , property_hs_projected_amount_in_home_currency
    , property_hs_time_in_962615
    , property_hs_updated_by_user_id
    , property_hs_time_in_6734705
    , deal_pipeline_id
    , property_hubspot_owner_assigneddate
    , property_hs_projected_amount
    , property_dealname
    , property_closedate
    , property_createdate
    , property_hs_sales_email_last_replied
    , property_hs_time_in_presentationscheduled
    , deal_pipeline_stage_id
    , property_amount
    , property_hs_object_id
    , property_hs_time_in_41524885
    , property_hs_time_in_closedwon
    , property_hs_user_ids_of_all_owners
    , property_hs_time_in_closedlost
    , property_hs_priority
    , property_hs_time_in_1037201
    , property_hs_time_in_1037200
    , property_hs_time_in_1037199
    , property_hs_time_in_2216212
    , property_hs_time_in_2216211
    , property_hs_time_in_2216213
    , property_hs_time_in_43126578
    , property_hs_time_in_37104998
    , property_hs_time_in_37105004
    , property_num_notes
    , property_hubspot_team_id
    , owner_id
    , property_closed_won_reason
    , property_notes_last_contacted
    , property_hs_all_accessible_team_ids
    , property_num_associated_contacts
    , property_notes_last_updated
    , property_num_contacted_notes
    , property_hs_all_team_ids
    , property_notes_next_activity_date
    , property_hs_createdate
    , property_hs_all_owner_ids
    , property_closed_lost_reason
    , property_dealtype
    , _fivetran_deleted
from {{ source('hubspot_network', 'deal') }}