select
    id
    , portal_id
    , is_deleted
    , _fivetran_synced
    , property_hs_analytics_source_data_2
    , property_hs_analytics_num_page_views
    , property_hs_analytics_source_data_1
    , property_hs_analytics_first_timestamp
    , property_hs_analytics_num_visits
    , property_hs_analytics_source
    , property_hs_date_entered_opportunity
    , property_founded_year
    , property_first_deal_created_date
    , property_hs_analytics_latest_source
    , property_hs_analytics_latest_source_data_2
    , property_hs_analytics_latest_source_data_1
    , property_hs_analytics_latest_source_timestamp
    , property_hs_date_entered_customer
    , property_hs_date_entered_lead
    , property_hs_lastmodifieddate
    , property_hs_num_decision_makers
    , property_hs_num_open_deals
    , property_num_associated_deals
    , property_hs_total_deal_value
    , property_hs_target_account_probability
    , property_num_associated_contacts
    , property_hs_object_id
    , property_hs_time_in_opportunity
    , property_is_public
    , property_hs_num_blockers
    , property_hs_num_contacts_with_buying_roles
    , property_hs_last_logged_call_date
    , property_hs_time_in_customer
    , property_hs_date_exited_opportunity
    , property_hs_last_sales_activity_date
    , property_hs_last_sales_activity_timestamp
    , property_hs_last_open_task_date
    , property_hs_pipeline
    , property_hs_last_sales_activity_type
    , property_hubspot_owner_assigneddate
    , property_hs_user_ids_of_all_owners
    , property_hs_time_in_lead
    , property_total_money_raised
    , property_city
    , property_domain
    , property_industry
    , property_zip
    , property_website
    , property_facebook_company_page
    , property_state
    , property_lifecyclestage
    , property_name
    , property_linkedinbio
    , property_address
    , property_linkedin_company_page
    , property_country
    , property_timezone
    , property_twitterhandle
    , property_annualrevenue
    , property_numberofemployees
    , property_phone
    , property_num_notes
    , property_num_conversion_events
    , property_notes_last_contacted
    , property_notes_last_updated
    , property_num_contacted_notes
    , property_address_2
    , property_recent_deal_amount
    , property_total_revenue
    , property_recent_deal_close_date
    , property_notes_next_activity_date
    , property_hs_sales_email_last_replied
    , property_hubspot_team_id
    , property_hs_all_accessible_team_ids
    , property_hs_all_team_ids
    , property_hubspot_owner_id
    , property_hs_all_owner_ids
    , property_description
    , property_createdate
    , property_first_contact_createdate
    , property_web_technologies
    , property_closedate
    , property_days_to_close
    , property_hs_num_child_companies
    , _fivetran_deleted
from {{ source('hubspot_network', 'company') }}