select
     employee_id
    ,position_id
    ,associate_id
    ,data_last_refreshed_date
    ,accounting_id
    ,employment_status
    ,job_function_code
    ,change_reason_code
    ,change_reason_description
    ,vol_invol
    ,reporting_office
    ,hire_details
    ,source
    ,title_change_reason
    ,associate_legal_name_first
    ,associate_legal_name_middle
    ,associate_legal_name_last
    ,associate_legal_name_full
    ,associate_preferred_name
    ,associate_legal_name_suffix
    ,associate_birth_date
    ,associate_gender_code
    ,associate_gender_name
    ,associate_personal_email
    ,associate_personal_phone
    ,associate_personal_cell_phone
    ,associate_legal_address_line1
    ,associate_legal_address_line2
    ,associate_legal_address_city
    ,associate_legal_address_state_abb
    ,associate_legal_address_state
    ,associate_legal_address_zip_code
    ,associate_legal_address_country
    ,associate_other_address_line1
    ,associate_other_address_line2
    ,associate_other_address_city
    ,associate_other_address_state_abb
    ,associate_other_address_state
    ,associate_other_address_zip_code
    ,associate_other_address_country
    ,associate_eeo_ethnicity
    ,associate_eeo_identification_method
    ,associate_education
    ,associate_work_email
    ,associate_work_phone
    ,associate_work_cell_phone
    ,associate_original_hire_date
    ,associate_rehire_date
    ,associate_final_termination_date
    ,position_company_code
    ,position_status_code
    ,position_status
    ,position_seniority_hire_date
    ,position_start_date
    ,position_termination_date
    ,position_change_reason
    ,position_manager_position_id
    ,position_manager_name
    ,position_primary_job_indicator
    ,position_title_code
    ,position_title
    ,position_worker_type
    ,position_benefits_group_code
    ,position_benefits_group_class
    ,position_flsa
    ,position_full_time_equivalent
    ,position_scheduled_hours
    ,position_standard_hours
    ,position_work_site_location_code
    ,position_work_site_location_name
    ,position_work_site_address_line1
    ,position_work_site_address_line2
    ,position_work_site_address_line3
    ,position_work_site_address_city
    ,position_work_site_address_state_abb
    ,position_work_site_address_state
    ,position_work_site_address_zip_code
    ,position_work_site_address_country
    ,position_eeo_class
    ,position_department_name
    ,position_location_name
    ,position_region_code
    ,position_region_description
    ,position_region_name
from {{ ref('int_adp_employees_all') }}
where is_head = 1 and nvl(is_deleted,0) = 0