select
    'salesforce'::text(200)                                               as system_name
  , 'adviceperiod'::text(200)                                             as system_instance
  , concat(system_name, '__', system_instance)::text(200)                 as system_key
  , 'mps'::text(200)                                                      as firm_source
  , a.json:ID:: varchar(18)                                               as id
  , a.json:IS_DELETED:: boolean                                           as is_deleted
  , a.json:MASTER_RECORD_ID:: varchar(18)                                 as master_record_id
  , a.json:NAME:: varchar(765)                                            as name
  , a.json:TYPE:: varchar(765)                                            as type
  , a.json:RECORD_TYPE_ID:: varchar(18)                                   as record_type_id
  , a.json:PARENT_ID:: varchar(18)                                        as parent_id
  , a.json:BILLING_STREET:: varchar(765)                                  as billing_street
  , a.json:BILLING_CITY:: varchar(120)                                    as billing_city
  , a.json:BILLING_STATE:: varchar(240)                                   as billing_state
  , a.json:BILLING_POSTAL_CODE:: varchar(60)                              as billing_postal_code
  , a.json:BILLING_COUNTRY:: varchar(240)                                 as billing_country
  , a.json:BILLING_STATE_CODE:: varchar(30)                               as billing_state_code
  , a.json:BILLING_COUNTRY_CODE:: varchar(30)                             as billing_country_code
  , a.json:BILLING_LATITUDE:: float                                       as billing_latitude
  , a.json:BILLING_LONGITUDE:: float                                      as billing_longitude
  , a.json:BILLING_GEOCODE_ACCURACY:: varchar(120)                        as billing_geocode_accuracy
  , a.json:SHIPPING_STREET:: varchar(765)                                 as shipping_street
  , a.json:SHIPPING_CITY:: varchar(120)                                   as shipping_city
  , a.json:SHIPPING_STATE:: varchar(240)                                  as shipping_state
  , a.json:SHIPPING_POSTAL_CODE:: varchar(60)                             as shipping_postal_code
  , a.json:SHIPPING_COUNTRY:: varchar(240)                                as shipping_country
  , a.json:SHIPPING_STATE_CODE:: varchar(30)                              as shipping_state_code
  , a.json:SHIPPING_COUNTRY_CODE:: varchar(30)                            as shipping_country_code
  , a.json:SHIPPING_LATITUDE:: float                                      as shipping_latitude
  , a.json:SHIPPING_LONGITUDE:: float                                     as shipping_longitude
  , a.json:SHIPPING_GEOCODE_ACCURACY:: varchar(120)                       as shipping_geocode_accuracy
  , a.json:PHONE:: varchar(120)                                           as phone
  , a.json:FAX:: varchar(120)                                             as fax
  , a.json:ACCOUNT_NUMBER:: varchar(120)                                  as account_number
  , a.json:WEBSITE:: varchar(765)                                         as website
  , a.json:PHOTO_URL:: varchar(765)                                       as photo_url
  , a.json:INDUSTRY:: varchar(765)                                        as industry
  , a.json:ANNUAL_REVENUE:: number                                        as annual_revenue
  , a.json:NUMBER_OF_EMPLOYEES:: number                                   as number_of_employees
  , a.json:OWNERSHIP:: varchar(765)                                       as ownership
  , a.json:DESCRIPTION:: varchar(96000)                                   as description
  , a.json:RATING:: varchar(765)                                          as rating
  , a.json:OWNER_ID:: varchar(18)                                         as owner_id
  , a.json:CREATED_DATE:: timestamp_tz(9)                                 as created_date
  , a.json:CREATED_BY_ID:: varchar(18)                                    as created_by_id
  , a.json:LAST_MODIFIED_DATE:: timestamp_tz(9)                           as last_modified_date
  , a.json:LAST_MODIFIED_BY_ID:: varchar(18)                              as last_modified_by_id
  , a.json:SYSTEM_MODSTAMP:: timestamp_tz(9)                              as system_modstamp
  , a.json:LAST_ACTIVITY_DATE:: date                                      as last_activity_date
  , a.json:LAST_VIEWED_DATE:: timestamp_tz(9)                             as last_viewed_date
  , a.json:LAST_REFERENCED_DATE:: timestamp_tz(9)                         as last_referenced_date
  , a.json:JIGSAW:: varchar(60)                                           as jigsaw
  , a.json:JIGSAW_COMPANY_ID:: varchar(60)                                as jigsaw_company_id
  , a.json:ACCOUNT_SOURCE:: varchar(765)                                  as account_source
  , a.json:SIC_DESC:: varchar(240)                                        as sic_desc
  , a.json:SALENTICA_LMNTS_ACTIVE_C:: varchar(765)                        as salentica_lmnts_active_c
  , a.json:SALENTICA_LMNTS_BILLING_FREQUENCY_C:: varchar(765)             as salentica_lmnts_billing_frequency_c
  , a.json:SALENTICA_LMNTS_BILLING_GROUP_C:: varchar(150)                 as salentica_lmnts_billing_group_c
  , a.json:SALENTICA_LMNTS_CLIENT_SINCE_C:: date                          as salentica_lmnts_client_since_c
  , a.json:SALENTICA_LMNTS_DAYS_SINCE_LAST_ADV_C:: float                  as salentica_lmnts_days_since_last_adv_c
  , a.json:SALENTICA_LMNTS_DAYS_SINCE_LAST_ADV_CALC_C:: float             as salentica_lmnts_days_since_last_adv_calc_c
  , a.json:SALENTICA_LMNTS_DAYS_SINCE_LAST_REVIEW_C:: float               as salentica_lmnts_days_since_last_review_c
  , a.json:SALENTICA_LMNTS_DAYS_UNTIL_NEXT_REVIEW_C:: float               as salentica_lmnts_days_until_next_review_c
  , a.json:SALENTICA_LMNTS_DAYS_UNTIL_NEXT_REVIEW_CALC_C:: float          as salentica_lmnts_days_until_next_review_calc_c
  , a.json:SALENTICA_LMNTS_ESTIMATED_ASSETS_C:: number                    as salentica_lmnts_estimated_assets_c
  , a.json:SALENTICA_LMNTS_ESTIMATED_REVENUE_C:: number                   as salentica_lmnts_estimated_revenue_c
  , a.json:SALENTICA_LMNTS_EXTERNAL_ID_C:: varchar(150)                   as salentica_lmnts_external_id_c
  , a.json:SALENTICA_LMNTS_LAST_ADV_DATE_C:: date                         as salentica_lmnts_last_adv_date_c
  , a.json:SALENTICA_LMNTS_LAST_CONTACT_ACTIVITY_C:: varchar(300)         as salentica_lmnts_last_contact_activity_c
  , a.json:SALENTICA_LMNTS_LAST_CONTACTED_BY_C:: varchar(18)              as salentica_lmnts_last_contacted_by_c
  , a.json:SALENTICA_LMNTS_LAST_CONTACTED_ON_C:: date                     as salentica_lmnts_last_contacted_on_c
  , a.json:SALENTICA_LMNTS_LAST_REVIEW_DATE_C:: date                      as salentica_lmnts_last_review_date_c
  , a.json:SALENTICA_LMNTS_MASTER_PORTFOLIO_C:: varchar(18)               as salentica_lmnts_master_portfolio_c
  , a.json:SALENTICA_LMNTS_NEXT_REVIEW_DATE_C:: date                      as salentica_lmnts_next_review_date_c
  , a.json:SALENTICA_LMNTS_NUMBEROF_LOCATIONS_C:: float                   as salentica_lmnts_numberof_locations_c
  , a.json:SALENTICA_LMNTS_PRIMARY_CONTACT_C:: varchar(18)                as salentica_lmnts_primary_contact_c
  , a.json:SALENTICA_LMNTS_PROSPECT_STAGE_C:: varchar(765)                as salentica_lmnts_prospect_stage_c
  , a.json:SALENTICA_LMNTS_REVIEW_FREQUENCY_C:: varchar(765)              as salentica_lmnts_review_frequency_c
  , a.json:SALENTICA_LMNTS_SLAEXPIRATION_DATE_C:: date                    as salentica_lmnts_slaexpiration_date_c
  , a.json:SALENTICA_LMNTS_SLASERIAL_NUMBER_C:: varchar(30)               as salentica_lmnts_slaserial_number_c
  , a.json:SALENTICA_LMNTS_SLA_C:: varchar(765)                           as salentica_lmnts_sla_c
  , a.json:SALENTICA_LMNTS_SALENTICA_DATA_BROKER_ID_C:: varchar(300)      as salentica_lmnts_salentica_data_broker_id_c
  , a.json:SALENTICA_LMNTS_SECONDARY_CONTACT_C:: varchar(18)              as salentica_lmnts_secondary_contact_c
  , a.json:SALENTICA_LMNTS_SEGMENTATION_C:: varchar(765)                  as salentica_lmnts_segmentation_c
  , a.json:SALENTICA_LMNTS_TOTAL_MARKET_VALUE_C:: number                  as salentica_lmnts_total_market_value_c
  , a.json:SALENTICA_LMNTS_TOTAL_SUPERVISED_C:: number                    as salentica_lmnts_total_supervised_c
  , a.json:SALENTICA_LMNTS_TOTAL_UNSUPERVISED_C:: number                  as salentica_lmnts_total_unsupervised_c
  , a.json:SALENTICA_LMNTS_UPSELL_OPPORTUNITY_C:: varchar(765)            as salentica_lmnts_upsell_opportunity_c
  , a.json:SALENTICA_LMNTS_VALUATION_DATE_C:: date                        as salentica_lmnts_valuation_date_c
  , a.json:SALENTICA_LMNTS_COI_PRIMARY_CONTACT_C:: varchar(18)            as salentica_lmnts_coi_primary_contact_c
  , a.json:BILLING_TYPE_C:: varchar(765)                                  as billing_type_c
  , a.json:DEBITED_ACCOUNT_C:: varchar(18)                                as debited_account_c
  , a.json:ULTRA_HIGH_NET_WORTH_C:: boolean                               as ultra_high_net_worth_c
  , a.json:LAST_IPS_REVIEW_DATE_C:: date                                  as last_ips_review_date_c
  , a.json:WIN_LOSS_REASON_C:: varchar(765)                               as win_loss_reason_c
  , a.json:AUM_FEE_C:: float                                              as aum_fee_c
  , a.json:FEE_VALUATION_C:: varchar(765)                                 as fee_valuation_c
  , a.json:SEC_FILING_STATUS_C:: varchar(765)                             as sec_filing_status_c
  , a.json:FEE_INFLATOR_DATE_C:: date                                     as fee_inflator_date_c
  , a.json:FEE_INFLATOR_PCT_C:: float                                     as fee_inflator_pct_c
  , a.json:HOT_PROSPECT_C:: boolean                                       as hot_prospect_c
  , a.json:STAGE_C:: varchar(765)                                         as stage_c
  , a.json:CLOSE_DATE_C:: date                                            as close_date_c
  , a.json:SOURCE_C:: varchar(765)                                        as source_c
  , a.json:LOSS_REASON_C:: varchar(765)                                   as loss_reason_c
  , a.json:CURRENT_AUM_C:: number                                         as current_aum_c
  , a.json:EXPECTED_AUM_C:: number                                        as expected_aum_c
  , a.json:CURRENT_NUMBER_OF_CLIENTS_C:: float                            as current_number_of_clients_c
  , a.json:EXPECTED_NUMBER_OF_CLIENTS_C:: float                           as expected_number_of_clients_c
  , a.json:CURRENT_REVENUE_C:: number                                     as current_revenue_c
  , a.json:EXPECTED_REVENUE_C:: number                                    as expected_revenue_c
  , a.json:PROSPECT_VALUE_C:: number                                      as prospect_value_c
  , a.json:INVESTMENT_PHILOSPHPY_C:: varchar(765)                         as investment_philosphpy_c
  , a.json:CUSTODIAN_C:: varchar(765)                                     as custodian_c
  , a.json:OTHER_CUSTODIAN_IF_APPLICABLE_C:: varchar(90)                  as other_custodian_if_applicable_c
  , a.json:OTHER_LOSS_REASON_IF_APPLICABLE_C:: varchar(90)                as other_loss_reason_if_applicable_c
  , a.json:PRIMARY_EMAIL_C:: varchar(765)                                 as primary_email_c
  , a.json:REFERRED_BY_C:: varchar(18)                                    as referred_by_c
  , a.json:PROSPECT_DETAILS_C:: varchar(98304)                            as prospect_details_c
  , a.json:COMPANY_C:: varchar(3900)                                      as company_c
  , a.json:EXIT_TYPE_C:: varchar(765)                                     as exit_type_c
  , a.json:STATE_C:: varchar(765)                                         as state_c
  , a.json:QUOVO_LINK_SENT_C:: boolean                                    as quovo_link_sent_c
  , a.json:QUOVO_LINK_SENT_TIME_C:: timestamp_tz(9)                       as quovo_link_sent_time_c
  , a.json:OUTSIDE_ACCOUNTS_LINKED_C:: boolean                            as outside_accounts_linked_c
  , a.json:OUTSIDE_ACCOUNTS_LINKED_DATE_C:: timestamp_tz(9)               as outside_accounts_linked_date_c
  , a.json:OUTSIDE_ACCOUNTS_REVIEW_C:: boolean                            as outside_accounts_review_c
  , a.json:OUTSIDE_ACCOUNTS_REVIEW_DATE_C:: timestamp_tz(9)               as outside_accounts_review_date_c
  , a.json:FEE_APPROVED_C:: boolean                                       as fee_approved_c
  , a.json:FEE_APPROVED_DATE_C:: timestamp_tz(9)                          as fee_approved_date_c
  , a.json:CONTRACT_DRAFTED_C:: boolean                                   as contract_drafted_c
  , a.json:CONTRACT_DRAFT_DATE_C:: timestamp_tz(9)                        as contract_draft_date_c
  , a.json:IPS_DRAFTED_C:: boolean                                        as ips_drafted_c
  , a.json:IPS_DRAFT_DATE_C:: timestamp_tz(9)                             as ips_draft_date_c
  , a.json:CONTRACT_COMPLIANCE_APPROVED_C:: boolean                       as contract_compliance_approved_c
  , a.json:CONTRACT_COMPLIANCE_APPROVED_DATE_C:: timestamp_tz(9)          as contract_compliance_approved_date_c
  , a.json:IPS_COMPLIANCE_APPROVED_C:: boolean                            as ips_compliance_approved_c
  , a.json:IPS_COMPLIANCE_APPROVED_DATE_C:: timestamp_tz(9)               as ips_compliance_approved_date_c
  , a.json:CONTRACT_SENT_C:: boolean                                      as contract_sent_c
  , a.json:CONTRACT_SENT_DATE_C:: timestamp_tz(9)                         as contract_sent_date_c
  , a.json:IPS_SENT_C:: boolean                                           as ips_sent_c
  , a.json:IPS_SENT_DATE_C:: timestamp_tz(9)                              as ips_sent_date_c
  , a.json:CONTRACT_SIGNED_C:: boolean                                    as contract_signed_c
  , a.json:CONTRACT_SIGNED_DATE_C:: timestamp_tz(9)                       as contract_signed_date_c
  , a.json:IPS_SIGNED_DATE_C:: timestamp_tz(9)                            as ips_signed_date_c
  , a.json:IPS_SIGNED_C:: boolean                                         as ips_signed_c
  , a.json:TRIGGER_TIME_C:: timestamp_tz(9)                               as trigger_time_c
  , a.json:IS_TRANSITION_C:: boolean                                      as is_transition_c
  , a.json:ACCT_OPENING_TRANSFER_FORMS_DRAFTED_C:: boolean                as acct_opening_transfer_forms_drafted_c
  , a.json:ACCT_OPENING_TRANSFER_FORMS_DRAFTED_T_C:: timestamp_tz(9)      as acct_opening_transfer_forms_drafted_t_c
  , a.json:ACCT_OPENING_TRANSFER_FORMS_REVIEWED_C:: boolean               as acct_opening_transfer_forms_reviewed_c
  , a.json:ACCT_OPENING_TRANSFER_FORMS_REVIEWED_T_C:: timestamp_tz(9)     as acct_opening_transfer_forms_reviewed_t_c
  , a.json:ACCT_OPENING_TRANSFER_FORMS_SENT_C:: boolean                   as acct_opening_transfer_forms_sent_c
  , a.json:ACCT_OPENING_TRANSFER_FORMS_SENT_T_C:: timestamp_tz(9)         as acct_opening_transfer_forms_sent_t_c
  , a.json:ACCT_OPENING_TRANSFER_FORMS_SIGNED_C:: boolean                 as acct_opening_transfer_forms_signed_c
  , a.json:ACCT_OPENING_TRANSFER_FORMS_SIGNED_T_C:: timestamp_tz(9)       as acct_opening_transfer_forms_signed_t_c
  , a.json:ACCTS_OPEN_AND_FUNDED_C:: boolean                              as accts_open_and_funded_c
  , a.json:ACCTS_OPEN_AND_FUNDED_DATE_C:: timestamp_tz(9)                 as accts_open_and_funded_date_c
  , a.json:COST_BASIS_RECEIVED_C:: boolean                                as cost_basis_received_c
  , a.json:COST_BASIS_RECEIVED_DATE_C:: timestamp_tz(9)                   as cost_basis_received_date_c
  , a.json:MONEY_MOVEMENT_REVIEWED_C:: boolean                            as money_movement_reviewed_c
  , a.json:MONEY_MOVEMENT_REVIEWED_DATE_C:: timestamp_tz(9)               as money_movement_reviewed_date_c
  , a.json:MONEY_MOVEMENT_FORMS_SENT_C:: boolean                          as money_movement_forms_sent_c
  , a.json:MONEY_MOVEMENT_FORMS_SENT_DATE_C:: timestamp_tz(9)             as money_movement_forms_sent_date_c
  , a.json:MONEY_MOVEMENT_SIGNED_C:: boolean                              as money_movement_signed_c
  , a.json:MONEY_MOVEMENT_SIGNED_DATE_C:: timestamp_tz(9)                 as money_movement_signed_date_c
  , a.json:PARTNER_AND_REPORTING_SUBLINK_REVIEWED_C:: boolean             as partner_and_reporting_sublink_reviewed_c
  , a.json:PARTNER_AND_REPORTING_SUBLINK_REVIEWED_D_C:: timestamp_tz(9)   as partner_and_reporting_sublink_reviewed_d_c
  , a.json:BLACK_DIAMOND_PORTFOLIO_CREATED_C:: boolean                    as black_diamond_portfolio_created_c
  , a.json:BLACK_DIAMOND_PORTFOLIO_CREATED_DATE_C:: timestamp_tz(9)       as black_diamond_portfolio_created_date_c
  , a.json:BLACK_DIAMOND_PORTFOLIO_REVIEWED_C:: boolean                   as black_diamond_portfolio_reviewed_c
  , a.json:BLACK_DIAMOND_PORTFOLIO_REVIEWED_DATE_C:: timestamp_tz(9)      as black_diamond_portfolio_reviewed_date_c
  , a.json:BLACK_DIAMOND_INVITE_SENT_C:: boolean                          as black_diamond_invite_sent_c
  , a.json:BLACK_DIAMOND_INVITE_SENT_DATE_C:: timestamp_tz(9)             as black_diamond_invite_sent_date_c
  , a.json:TRADE_AND_JOURNAL_PROPOSAL_C:: boolean                         as trade_and_journal_proposal_c
  , a.json:TRADE_AND_JOURNAL_PROPOSAL_DATE_C:: timestamp_tz(9)            as trade_and_journal_proposal_date_c
  , a.json:TRADE_AND_JOURNAL_PROPOSAL_APPROVED_C:: boolean                as trade_and_journal_proposal_approved_c
  , a.json:TRADE_AND_JOURNAL_PROPOSAL_APPROVED_DATE_C:: timestamp_tz(9)   as trade_and_journal_proposal_approved_date_c
  , a.json:TRADE_AND_JOURNALS_EXECUTED_C:: boolean                        as trade_and_journals_executed_c
  , a.json:TRADE_AND_JOURNALS_EXECUTED_DATE_C:: timestamp_tz(9)           as trade_and_journals_executed_date_c
  , a.json:TRADE_AND_JOURNALS_SETTLED_C:: boolean                         as trade_and_journals_settled_c
  , a.json:TRADE_AND_JOURNALS_SETTLED_DATE_C:: timestamp_tz(9)            as trade_and_journals_settled_date_c
  , a.json:ADVIZR_CLIENT_SET_UP_C:: boolean                               as advizr_client_set_up_c
  , a.json:ADVIZR_CLIENT_SET_UP_DATE_C:: timestamp_tz(9)                  as advizr_client_set_up_date_c
  , a.json:ADVIZR_CLIENT_REVIEWED_C:: boolean                             as advizr_client_reviewed_c
  , a.json:ADVIZR_CLIENT_REVIEWED_DATE_C:: timestamp_tz(9)                as advizr_client_reviewed_date_c
  , a.json:ADVIZR_INVITE_SENT_C:: boolean                                 as advizr_invite_sent_c
  , a.json:ADVIZR_INVITE_SENT_DATE_C:: timestamp_tz(9)                    as advizr_invite_sent_date_c
  , a.json:INSTITUTIONALIZED_C:: boolean                                  as institutionalized_c
  , a.json:INSTITUTIONALIZED_DATE_C:: timestamp_tz(9)                     as institutionalized_date_c
  , a.json:DAYS_TO_INSTITUTIONALIZE_C:: float                             as days_to_institutionalize_c
  , a.json:FLAT_MINIMUM_FEE_C:: number                                    as flat_minimum_fee_c
  , a.json:COMPAY_C:: varchar(3900)                                       as compay_c
  , a.json:DUPLICATES_C:: float                                           as duplicates_c
  , a.json:RELATIONSHIP_CLASSIFICATION_C:: varchar(3900)                  as relationship_classification_c
  , a.json:DUPCHECK_DC_3_DISABLE_DUPLICATE_CHECK_C:: boolean              as dupcheck_dc_3_disable_duplicate_check_c
  , a.json:DUPCHECK_DC_3_INDEX_C:: varchar(98304)                         as dupcheck_dc_3_index_c
  , a.json:CURRENT_FEE_STRUCTURE_C:: varchar(4099)                        as current_fee_structure_c
  , a.json:RELATIONSHIP_TEAM_C:: varchar(3900)                            as relationship_team_c
  , a.json:SALENTICA_LMNTS_REFERRAL_SOURCE_C:: varchar(18)                as salentica_lmnts_referral_source_c
  , a.json:SERVICES_CURRENTLY_OFFERED_C:: varchar(4099)                   as services_currently_offered_c
  , a.json:OTHER_SOURCE_C:: varchar(765)                                  as other_source_c
  , a.json:CITY_C:: varchar(765)                                          as city_c
  , a.json:CIRRUSADV_CREATED_BY_CIRRUS_INSIGHT_C:: boolean                as cirrusadv_created_by_cirrus_insight_c
  , a.json:LAST_ACTIVITY_DATE_C:: date                                    as last_activity_date_c
  , a.json:DAYS_SINCE_LAST_ACTIVITY_C:: float                             as days_since_last_activity_c
  , a.json:PRIMARY_CONTACT_EMAIL_C:: varchar(3900)                        as primary_contact_email_c
  , a.json:PROSPECT_CREATION_METHOD_C:: varchar(765)                      as prospect_creation_method_c
  , a.json:SCHWAB_MASTER_C:: varchar(765)                                 as schwab_master_c
  , a.json:FIDELITY_G_NUMBER_C:: varchar(765)                             as fidelity_g_number_c
  , a.json:START_DATE_C:: date                                            as start_date_c
  , a.json:BUILDING_ACCESS_C:: boolean                                    as building_access_c
  , a.json:PARKING_C:: boolean                                            as parking_c
  , a.json:BUSINESS_ADDRESS_C:: varchar(98304)                            as business_address_c
  , a.json:SET_UP_ON_PAYCHEX_FLEX_C:: boolean                             as set_up_on_paychex_flex_c
  , a.json:FED_EX_C:: boolean                                             as fed_ex_c
  , a.json:PAYCHEX_C:: boolean                                            as paychex_c
  , a.json:X_401_K_C:: boolean                                            as x_401_k_c
  , a.json:W_2_C:: boolean                                                as w_2_c
  , a.json:I_9_C:: boolean                                                as i_9_c
  , a.json:AMEX_C:: boolean                                               as amex_c
  , a.json:PREDICTIVE_INDEX_C:: varchar(765)                              as predictive_index_c
  , a.json:SEND_FINAL_EMPLOYMENT_AGREEMENT_C:: boolean                    as send_final_employment_agreement_c
  , a.json:SERIES_65_C:: boolean                                          as series_65_c
  , a.json:COMPLIANCE_MANUAL_C:: boolean                                  as compliance_manual_c
  , a.json:CODE_OF_ETHICS_C:: boolean                                     as code_of_ethics_c
  , a.json:EMPLOYEE_MANUAL_C:: boolean                                    as employee_manual_c
  , a.json:PERSONAL_STATEMENTS_C:: boolean                                as personal_statements_c
  , a.json:ACCOUNTING_SETUP_C:: boolean                                   as accounting_setup_c
  , a.json:UPDATED_PHONE_LIST_C:: boolean                                 as updated_phone_list_c
  , a.json:SEND_SWAG_C:: boolean                                          as send_swag_c
  , a.json:TEMPORARY_HEADSHOT_FOR_WEBSITE_C:: varchar(765)                as temporary_headshot_for_website_c
  , a.json:BIO_FOR_WEBSITE_C:: varchar(765)                               as bio_for_website_c
  , a.json:ADDED_TO_WEBSITE_C:: boolean                                   as added_to_website_c
  , a.json:LINKED_IN_BLOG_POST_C:: varchar(765)                           as linked_in_blog_post_c
  , a.json:EMAIL_TO_AP_4_DISTRIBUTION_LIST_C:: boolean                    as email_to_ap_4_distribution_list_c
  , a.json:BUSINESS_CARDS_C:: boolean                                     as business_cards_c
  , a.json:PRESS_RELEASE_C:: varchar(765)                                 as press_release_c
  , a.json:X_3_RD_PARTY_SPLIT_C:: float                                   as x_3_rd_party_split_c
  , a.json:AGE_OF_RECORD_C:: float                                        as age_of_record_c
  , a.json:COMPUTER_ORDERED_C:: boolean                                   as computer_ordered_c
  , a.json:EMAIL_SET_UP_C:: boolean                                       as email_set_up_c
  , a.json:FNF_ALIAS_C:: boolean                                          as fnf_alias_c
  , a.json:EMAIL_SIGNATURE_SET_UP_C:: boolean                             as email_signature_set_up_c
  , a.json:BOX_ACCESS_C:: boolean                                         as box_access_c
  , a.json:BOX_EDIT_C:: boolean                                           as box_edit_c
  , a.json:BOX_SUBMISSION_PORTAL_C:: boolean                              as box_submission_portal_c
  , a.json:BOX_FOLDERS_PROSPECT_CLIENT_RC_C:: boolean                     as box_folders_prospect_client_rc_c
  , a.json:OFFICE_365_C:: boolean                                         as office_365_c
  , a.json:ADOBE_ACCESS_C:: boolean                                       as adobe_access_c
  , a.json:RING_CENTRAL_C:: boolean                                       as ring_central_c
  , a.json:ELEMENTS_C:: boolean                                           as elements_c
  , a.json:SLACK_ACCESS_C:: boolean                                       as slack_access_c
  , a.json:SLACK_CHANNELS_C:: boolean                                     as slack_channels_c
  , a.json:TODOIST_C:: boolean                                            as todoist_c
  , a.json:HMA_C:: boolean                                                as hma_c
  , a.json:FIDELITY_G_NUMBER_LOGIN_C:: boolean                            as fidelity_g_number_login_c
  , a.json:SCHWAB_MASTER_LOGIN_C:: boolean                                as schwab_master_login_c
  , a.json:BETTERMENT_LOGIN_AND_FNF_LOGIN_C:: boolean                     as betterment_login_and_fnf_login_c
  , a.json:RIGHT_CAPITAL_ACCESS_C:: boolean                               as right_capital_access_c
  , a.json:BLACK_DIAMOND_ACCESS_C:: boolean                               as black_diamond_access_c
  , a.json:LOGIN_DOCUMENT_C:: varchar(765)                                as login_document_c
  , a.json:CAIS_ACCESS_C:: boolean                                        as cais_access_c
  , a.json:EMAIL_SIGNATURE_ON_CELL_C:: boolean                            as email_signature_on_cell_c
  , a.json:DEPARTURE_PREP_GOOD_LEAVER_MEETING_C:: boolean                 as departure_prep_good_leaver_meeting_c
  , a.json:OBTAIN_PROPOSED_OFFICE_SOLUTION_C:: boolean                    as obtain_proposed_office_solution_c
  , a.json:GENERIC_PARTNER_DECK_PROVIDED_C:: boolean                      as generic_partner_deck_provided_c
  , a.json:TALKING_POINTS_PROVIDED_C:: boolean                            as talking_points_provided_c
  , a.json:CLIENT_INVENTORY_SHEET_PROVIDED_C:: boolean                    as client_inventory_sheet_provided_c
  , a.json:DAY_ONE_GAME_PLAN_DRAFTED_C:: boolean                          as day_one_game_plan_drafted_c
  , a.json:SUPPLIES_LIST_PROVIDED_C:: boolean                             as supplies_list_provided_c
  , a.json:CALL_SCRIPT_PROVIDED_C:: boolean                               as call_script_provided_c
  , a.json:SAMPLE_PARTNER_AGREEMENT_PROVIDED_C:: boolean                  as sample_partner_agreement_provided_c
  , a.json:SAMPLE_PARTNER_EMPLOYEE_AGREEMENT_C:: boolean                  as sample_partner_employee_agreement_c
  , a.json:FOLLOWUP_EMAIL_TEMPLATE_PROVIDED_C:: boolean                   as followup_email_template_provided_c
  , a.json:SCHEDULE_PREP_PHONE_CALLS_MEETINGS_C:: boolean                 as schedule_prep_phone_calls_meetings_c
  , a.json:BLOCK_TIME_ON_JACK_S_CALENDAR_C:: boolean                      as block_time_on_jack_s_calendar_c
  , a.json:COMPUTER_AND_SYSTEMS_CHECKED_C:: boolean                       as computer_and_systems_checked_c
  , a.json:UPDATE_SHARED_SERVICES_ON_DAY_1_C:: boolean                    as update_shared_services_on_day_1_c
  , a.json:SET_UP_EQUIPMENT_C:: boolean                                   as set_up_equipment_c
  , a.json:CONFIRM_PARTNER_AGREEMENT_SIGNED_C:: boolean                   as confirm_partner_agreement_signed_c
  , a.json:SHARE_GAME_PLAN_WITH_PARTNER_C:: boolean                       as share_game_plan_with_partner_c
  , a.json:PARTNER_LIVE_ON_WEBSITE_C:: boolean                            as partner_live_on_website_c
  , a.json:PRESS_RELEASE_OUT_C:: boolean                                  as press_release_out_c
  , a.json:LINKED_IN_POST_OUT_C:: boolean                                 as linked_in_post_out_c
  , a.json:DAILY_LINKED_IN_POSTS_SHARED_WITH_PARTNER_C:: boolean          as daily_linked_in_posts_shared_with_partner_c
  , a.json:GAMEPLAN_FOR_BILLABLE_ASSETS_C:: boolean                       as gameplan_for_billable_assets_c
  , a.json:GAME_PLAN_FOR_LINKING_OUTSIDE_ACCOUNTS_C:: boolean             as game_plan_for_linking_outside_accounts_c
  , a.json:REVIEW_OF_ALL_DOCS_THAT_NEED_SIGNATURE_C:: boolean             as review_of_all_docs_that_need_signature_c
  , a.json:ASK_FOR_FEEDBACK_C:: boolean                                   as ask_for_feedback_c
  , a.json:WELCOME_TO_AP_C:: boolean                                      as welcome_to_ap_c
  , a.json:COMMUNICATIONS_C:: boolean                                     as communications_c
  , a.json:WELCOME_TO_AP_COMPLETE_DATE_C:: date                           as welcome_to_ap_complete_date_c
  , a.json:COMMUNICATIONS_COMPLETE_DATE_C:: date                          as communications_complete_date_c
  , a.json:SYSTEMS_OVERVIEW_COMPLETE_DATE_C:: date                        as systems_overview_complete_date_c
  , a.json:WORKING_WITH_SHARED_SERVICES_COMPLETE_DA_C:: date              as working_with_shared_services_complete_da_c
  , a.json:ELEMENTS_TRAINING_DATE_C:: date                                as elements_training_date_c
  , a.json:COMPANY_HYGIENE_COMPLETE_DATE_C:: date                         as company_hygiene_complete_date_c
  , a.json:INVESTMENTS_COMPLETE_DATE_C:: date                             as investments_complete_date_c
  , a.json:RESOURCES_DATE_COMPLETE_C:: boolean                            as resources_date_complete_c
  , a.json:COMPLIANCE_COMPLETE_DATE_C:: date                              as compliance_complete_date_c
  , a.json:BLACK_DIAMOND_COMPLETE_DATE_C:: date                           as black_diamond_complete_date_c
  , a.json:REBALANCING_COMPLETE_DATE_C:: date                             as rebalancing_complete_date_c
  , a.json:RIGHT_CAPITAL_COMPLETE_DATE_C:: date                           as right_capital_complete_date_c
  , a.json:PARTNER_BUSINESS_COMPLETE_DATE_C:: date                        as partner_business_complete_date_c
  , a.json:WHO_TO_GO_TO_FOR_WHAT_COMPLETE_DATE_C:: date                   as who_to_go_to_for_what_complete_date_c
  , a.json:LAST_P_L_REVIEW_C:: date                                       as last_p_l_review_c
  , a.json:LAST_P_L_DRAFT_C:: date                                        as last_p_l_draft_c
  , a.json:NEXT_P_L_REVIEW_C:: date                                       as next_p_l_review_c
  , a.json:CURRENT_NUMBER_OF_PROSPECTS_C:: float                          as current_number_of_prospects_c
  , a.json:STAGE_HIDDEN_C:: varchar(765)                                  as stage_hidden_c
  , a.json:AP_SPLIT_C:: float                                             as ap_split_c
  , a.json:INDIVIDUAL_RELATIONSHIP_C:: boolean                            as individual_relationship_c
  , a.json:PENSION_PSP_C:: boolean                                        as pension_psp_c
  , a.json:CHARITY_C:: boolean                                            as charity_c
  , a.json:CORP_OTHER_BUSINESS_C:: boolean                                as corp_other_business_c
  , a.json:ONE_TIME_PLANNING_C:: boolean                                  as one_time_planning_c
  , a.json:AP_SHARE_C:: number                                            as ap_share_c
  , a.json:X_3_RD_PARTY_SHARE_C:: number                                  as x_3_rd_party_share_c
  , a.json:NET_TO_PARTNER_C:: number                                      as net_to_partner_c
  , a.json:BILLING_INCEPTION_C:: date                                     as billing_inception_c
  , a.json:RELATIONSHIP_STATE_C:: varchar(765)                            as relationship_state_c
  , a.json:BILL_PAY_C:: boolean                                           as bill_pay_c
  , a.json:INVESTMENT_DISCRETION_C:: varchar(765)                         as investment_discretion_c
  , a.json:EUSTACE_BOX_BOX_FOLDER_ID_C:: varchar(150)                     as eustace_box_box_folder_id_c
  , a.json:REFERRAL_NETWORK_C:: varchar(765)                              as referral_network_c
  , a.json:REFERRAL_NUMBER_ID_C:: varchar(765)                            as referral_number_id_c
  , a.json:FIRST_RESPONSE_DATE_C:: date                                   as first_response_date_c
  , a.json:NUMBER_OF_CONTACT_ATTEMPTS_C:: float                           as number_of_contact_attempts_c
  , a.json:DA_SCOOP_COMPOSER_ACCOUNT_TAGS_C:: varchar(4099)               as da_scoop_composer_account_tags_c
  , a.json:DA_SCOOP_COMPOSER_ALIAS_1_C:: varchar(765)                     as da_scoop_composer_alias_1_c
  , a.json:DA_SCOOP_COMPOSER_ALIAS_2_C:: varchar(765)                     as da_scoop_composer_alias_2_c
  , a.json:DA_SCOOP_COMPOSER_CHURNED_CUSTOMER_C:: boolean                 as da_scoop_composer_churned_customer_c
  , a.json:DA_SCOOP_COMPOSER_DOMAIN_1_C:: varchar(765)                    as da_scoop_composer_domain_1_c
  , a.json:DA_SCOOP_COMPOSER_DOMAIN_2_C:: varchar(765)                    as da_scoop_composer_domain_2_c
  , a.json:DA_SCOOP_COMPOSER_DONT_MATCH_LEADS_TO_THIS_ACCOUNT_C:: boolean as da_scoop_composer_dont_match_leads_to_this_account_c
  , a.json:DA_SCOOP_COMPOSER_ENGAGEMENT_STATUS_C:: varchar(765)           as da_scoop_composer_engagement_status_c
  , a.json:DA_SCOOP_COMPOSER_GROOVE_NOTES_C:: varchar(98304)              as da_scoop_composer_groove_notes_c
  , a.json:DA_SCOOP_COMPOSER_HASH_1_C:: varchar(765)                      as da_scoop_composer_hash_1_c
  , a.json:DA_SCOOP_COMPOSER_HASH_2_C:: varchar(765)                      as da_scoop_composer_hash_2_c
  , a.json:DA_SCOOP_COMPOSER_HASH_3_C:: varchar(765)                      as da_scoop_composer_hash_3_c
  , a.json:DA_SCOOP_COMPOSER_INFERRED_STATUS_C:: varchar(3900)            as da_scoop_composer_inferred_status_c
  , a.json:PREFERRED_BD_3_EMAIL_ADDRESS_C:: varchar(240)                  as preferred_bd_3_email_address_c
  , a.json:UNQUALIFIED_START_C:: date                                     as unqualified_start_c
  , a.json:UNQUALIFIED_END_C:: date                                       as unqualified_end_c
  , a.json:SUSPECT_START_C:: date                                         as suspect_start_c
  , a.json:SUSPECT_END_C:: date                                           as suspect_end_c
  , a.json:PROSPECT_START_C:: date                                        as prospect_start_c
  , a.json:PROSPECT_END_C:: date                                          as prospect_end_c
  , a.json:ASSESSMENT_START_C:: date                                      as assessment_start_c
  , a.json:ASSESSMENT_END_C:: date                                        as assessment_end_c
  , a.json:VERBAL_COMMIT_START_C:: date                                   as verbal_commit_start_c
  , a.json:VERBAL_COMMIT_END_C:: date                                     as verbal_commit_end_c
  , a.json:PROSPECT_WON_DATE_C:: date                                     as prospect_won_date_c
  , a.json:PROSPECT_LOSS_DATE_C:: date                                    as prospect_loss_date_c
  , a.json:DAYS_IN_UNQUALIFIED_C:: float                                  as days_in_unqualified_c
  , a.json:DAYS_IN_SUSPECT_C:: float                                      as days_in_suspect_c
  , a.json:DAYS_IN_PROSPECT_C:: float                                     as days_in_prospect_c
  , a.json:DAYS_IN_ASSESSMENT_C:: float                                   as days_in_assessment_c
  , a.json:DAYS_IN_VERBAL_COMMIT_C:: float                                as days_in_verbal_commit_c
  , a.json:BEST_CONTACT_C:: varchar(393216)                               as best_contact_c
  , a.json:CLIENT_TYPE_C:: varchar(765)                                   as client_type_c
  , a.json:ANNUAL_SALES_TARGET_C:: number                                 as annual_sales_target_c
  , a.json:TOTAL_REQUESTS_C:: float                                       as total_requests_c
  , a.json:MEETING_DELIVERABLE_C:: varchar(765)                           as meeting_deliverable_c
  , a.json:PARTNER_TEAM_C:: varchar(18)                                   as partner_team_c
  , a.json:STARTING_YEAR_REVENUE_C:: number                               as starting_year_revenue_c
  , a.json:STARTING_WEEK_REVENUE_C:: number                               as starting_week_revenue_c
  , a.json:STARTING_MONTH_REVENUE_C:: number                              as starting_month_revenue_c
  , a.json:STARTING_QUARTER_REVENUE_C:: number                            as starting_quarter_revenue_c
  , a.json:WTD_GROWTH_C:: float                                           as wtd_growth_c
  , a.json:MTD_C:: number                                                 as mtd_c
  , a.json:QTD_C:: number                                                 as qtd_c
  , a.json:YTD_C:: number                                                 as ytd_c
  , a.json:WTD_C:: number                                                 as wtd_c
  , a.json:MTD_GROWTH_C:: float                                           as mtd_growth_c
  , a.json:QTD_GROWTH_C:: float                                           as qtd_growth_c
  , a.json:YTD_GROWTH_C:: float                                           as ytd_growth_c
  , a.json:YTD_SALES_TARGET_C:: number                                    as ytd_sales_target_c
  , a.json:PARTNER_COHORT_C:: varchar(3900)                               as partner_cohort_c
  , a.json:NEXT_ACTION_NOTE_C:: varchar(765)                              as next_action_note_c
  , a.json:CLIENT_AUM_C:: number                                          as client_aum_c
  , a.json:PARTNER_TOTAL_ASSETS_C:: number                                as partner_total_assets_c
  , a.json:PERCENT_MANAGED_C:: float                                      as percent_managed_c
  , a.json:REVENUE_PER_CLIENT_C:: number                                  as revenue_per_client_c
  , a.json:AUM_PER_CLIENT_C:: number                                      as aum_per_client_c
  , a.json:ACTION_DUE_DATE_C:: date                                       as action_due_date_c
  , a.json:ACTION_OWNER_C:: varchar(18)                                   as action_owner_c
  , a.json:ASSOCIATE_C:: varchar(18)                                      as associate_c
  , a.json:ADVISOR_C:: varchar(18)                                        as advisor_c
  , a.json:STARTING_YEAR_AUM_C:: number                                   as starting_year_aum_c
  , a.json:STARTING_QUARTER_AUM_C:: number                                as starting_quarter_aum_c
  , a.json:STARTING_MONTH_AUM_C:: number                                  as starting_month_aum_c
  , a.json:STARTING_WEEK_AUM_C:: number                                   as starting_week_aum_c
  , a.json:STARTING_YEAR_CLIENTS_C:: float                                as starting_year_clients_c
  , a.json:STARTING_QUARTER_CLIENTS_C:: float                             as starting_quarter_clients_c
  , a.json:STARTING_MONTH_CLIENTS_C:: float                               as starting_month_clients_c
  , a.json:STARTING_WEEK_CLIENTS_C:: float                                as starting_week_clients_c
  , a.json:YTD_AUM_GROWTH_C:: float                                       as ytd_aum_growth_c
  , a.json:QTD_AUM_GROWTH_C:: float                                       as qtd_aum_growth_c
  , a.json:MTD_AUM_GROWTH_C:: float                                       as mtd_aum_growth_c
  , a.json:WTD_AUM_GROWTH_C:: float                                       as wtd_aum_growth_c
  , a.json:YTD_AUM_PER_CLIENT_GROWTH_C:: float                            as ytd_aum_per_client_growth_c
  , a.json:QTD_AUM_PER_CLIENT_GROWTH_C:: float                            as qtd_aum_per_client_growth_c
  , a.json:MTD_AUM_PER_CLIENT_GROWTH_C:: float                            as mtd_aum_per_client_growth_c
  , a.json:WTD_AUM_PER_CLIENT_GROWTH_C:: float                            as wtd_aum_per_client_growth_c
  , a.json:YTD_PER_CLIENT_C:: number                                      as ytd_per_client_c
  , a.json:QTD_PER_CLIENT_C:: number                                      as qtd_per_client_c
  , a.json:MTD_PER_CLIENT_C:: number                                      as mtd_per_client_c
  , a.json:WTD_PER_CLIENT_C:: number                                      as wtd_per_client_c
  , a.json:YTD_PER_CLIENT_GROWTH_C:: float                                as ytd_per_client_growth_c
  , a.json:QTD_PER_CLIENT_GROWTH_C:: float                                as qtd_per_client_growth_c
  , a.json:MTD_PER_CLIENT_GROWTH_C:: float                                as mtd_per_client_growth_c
  , a.json:WTD_PER_CLIENT_GROWTH_C:: float                                as wtd_per_client_growth_c
  , a.json:PARTNER_REQUESTS_C:: float                                     as partner_requests_c
  , a.json:LAB_HOT_PROSPECT_C:: boolean                                   as lab_hot_prospect_c
  , a.json:LARRY_MILES_CONTACT_C:: boolean                                as larry_miles_contact_c
  , a.json:FLAT_FEE_CLIENTS_C:: float                                     as flat_fee_clients_c
  , a.json:AUM_FEE_CLIENTS_C:: float                                      as aum_fee_clients_c
  , a.json:PERCENT_FLAT_FEES_C:: float                                    as percent_flat_fees_c
  , a.json:PERCENT_BPS_FEES_C:: float                                     as percent_bps_fees_c
  , a.json:EFFECTIVE_FEE_TYPE_C:: varchar(3900)                           as effective_fee_type_c
  , a.json:UNMANAGED_BILLING_OPPORTUNITY_C:: number                       as unmanaged_billing_opportunity_c
  , a.json:PARTNER_UNMANAGED_BILLING_OPPORTUNITY_C:: number               as partner_unmanaged_billing_opportunity_c
  , a.json:PERCENT_TARGET_C:: float                                       as percent_target_c
  , a.json:YTD_PERCENT_TARGET_C:: float                                   as ytd_percent_target_c
  , a.json:PIPELINE_VALUE_C:: number                                      as pipeline_value_c
  , a.json:X_2020_TOTAL_FLOWS_C:: number                                  as x_2020_total_flows_c
  , a.json:ANALYST_C:: varchar(18)                                        as analyst_c
  , a.json:CLIENT_RANK_C:: float                                          as client_rank_c
  , a.json:PERCENT_TOTAL_REVENUE_C:: float                                as percent_total_revenue_c
  , a.json:CLIENT_SCORE_C:: float                                         as client_score_c
  , a.json:RELATED_TO_REFERRED_BY_C:: varchar(18)                         as related_to_referred_by_c
  , a.json:REFERRALS_C:: float                                            as referrals_c
  , a.json:MAX_REFERRALS_C:: float                                        as max_referrals_c
  , a.json:REFERRAL_POTENTIAL_C:: varchar(765)                            as referral_potential_c
  , a.json:AVERAGE_CLIENT_COST_C:: number                                 as average_client_cost_c
  , a.json:SENIOR_ANALYST_C:: varchar(18)                                 as senior_analyst_c
  , a.json:X_2019_TOTAL_FLOWS_C:: number                                  as x_2019_total_flows_c
  , a.json:X_2018_TOTAL_FLOWS_C:: number                                  as x_2018_total_flows_c
  , a.json:NEW_CLIENTS_LAST_YEAR_C:: float                                as new_clients_last_year_c
  , a.json:NEW_PROSPECTS_LAST_YEAR_C:: float                              as new_prospects_last_year_c
  , a.json:PARTNER_CLIENTS_LOST_LAST_YEAR_C:: float                       as partner_clients_lost_last_year_c
  , a.json:PARTNER_PROSPECT_CONVERSIONS_C:: float                         as partner_prospect_conversions_c
  , a.json:NEW_PROSPECT_C:: date                                          as new_prospect_c
  , a.json:NEW_CLIENT_C:: date                                            as new_client_c
  , a.json:X_2017_TOTAL_FLOWS_C:: number                                  as x_2017_total_flows_c
  , a.json:CONVERTED_C:: varchar(300)                                     as converted_c
  , a.json:LOST_C:: varchar(300)                                          as lost_c
  , a.json:PARTNER_CLOSE_RATE_C:: float                                   as partner_close_rate_c
  , a.json:PARTNER_TURNOVER_RATE_C:: float                                as partner_turnover_rate_c
  , a.json:FEE_CALCULATOR_C:: number                                      as fee_calculator_c
  , a.json:SERVICE_LEVEL_C:: varchar(4099)                                as service_level_c
  , a.json:CLIENT_DRIVEN_COMPLEXITY_C:: boolean                           as client_driven_complexity_c
  , a.json:X_100_ROBO_PLATFORM_C:: boolean                                as x_100_robo_platform_c
  , a.json:ADDITIONAL_NUCLEAR_FAMILIES_C:: float                          as additional_nuclear_families_c
  , a.json:TOTAL_NET_WORTH_C:: number                                     as total_net_worth_c
  , a.json:INVESTABLE_PORTFOLIO_AUM_C:: number                            as investable_portfolio_aum_c
  , a.json:PERCENT_AUM_C:: float                                          as percent_aum_c
  , a.json:PERCENT_AUA_C:: float                                          as percent_aua_c
  , a.json:FEE_TYPE_C:: varchar(3900)                                     as fee_type_c
  , a.json:PRIMARY_ADVISOR_C:: varchar(18)                                as primary_advisor_c
  , a.json:SECONDARY_ADVISOR_C:: varchar(18)                              as secondary_advisor_c
  , a.json:DESIGNEE_1_C:: varchar(18)                                     as designee_1_c
  , a.json:DESIGNEE_2_C:: varchar(18)                                     as designee_2_c
  , a.json:AVERAGE_CLIENT_AGE_C:: float                                   as average_client_age_c
  , a.json:TARGETED_BRANCH_C:: boolean                                    as targeted_branch_c
  , a.json:REGION_C:: varchar(765)                                        as region_c
  , a.json:BRANCH_MANAGER_C:: varchar(18)                                 as branch_manager_c
  , a.json:RECORD_TYPE_TEXT_C:: varchar(3900)                             as record_type_text_c
  , a.json:LID_LINKED_IN_COMPANY_ID_C:: varchar(240)                      as lid_linked_in_company_id_c
  , a.json:MULTIPLE_SELECT_SOURCE_C:: varchar(4099)                       as multiple_select_source_c
  , a.json:PRODUCT_SOLUTION_C:: varchar(765)                              as product_solution_c
  , a.json:VANILLA_PROSPECT_TYPE_C:: varchar(765)                         as vanilla_prospect_type_c
  , a.json:VANILLA_STAGE_C:: varchar(765)                                 as vanilla_stage_c
  , a.json:LAST_BOX_REVIEW_C:: date                                       as last_box_review_c
  , a.json:UPCOMING_MEETING_C:: date                                      as upcoming_meeting_c
  , a.json:CFS_CHECK_C:: boolean                                          as cfs_check_c
  , a.json:WEALTH_STRATEGIST_1_C:: varchar(18)                            as wealth_strategist_1_c
  , a.json:WEALTH_STRATEGIST_2_C:: varchar(18)                            as wealth_strategist_2_c
  , a.json:CFO_STAGE_C:: varchar(765)                                     as cfo_stage_c
  , a.json:FIDELITY_BRANCH_C:: varchar(18)                                as fidelity_branch_c
  , a.json:FIDELITY_REP_C:: varchar(18)                                   as fidelity_rep_c
  , a.json:ACCOUNT_LIST_SENT_C:: varchar(765)                             as account_list_sent_c
  , a.json:CLIENT_QUESTIONNAIRE_C:: varchar(765)                          as client_questionnaire_c
  , a.json:FOLLOW_UP_QUESTIONNAIRE_C:: varchar(765)                       as follow_up_questionnaire_c
  , a.json:WAS_REGION_C:: varchar(3900)                                   as was_region_c
  , a.json:WAS_STAGE_C:: varchar(765)                                     as was_stage_c
  , a.json:INSTITUTION_STATUS_C:: varchar(3900)                           as institution_status_c
  , a.json:PROSPECT_SUITABILITY_C:: varchar(765)                          as prospect_suitability_c
  , a.json:LIQUID_NET_WORTH_C:: number                                    as liquid_net_worth_c
  , a.json:RISK_COMFORT_LEVEL_C:: varchar(765)                            as risk_comfort_level_c
  , a.json:RISK_TIME_HORIZON_C:: varchar(765)                             as risk_time_horizon_c
  , a.json:RISK_TIME_HORIZON_OTHER_C:: varchar(765)                       as risk_time_horizon_other_c
  , a.json:COMPLETED_FINANCIAL_PLAN_C:: varchar(765)                      as completed_financial_plan_c
  , a.json:LAST_UPDATE_TO_FINANCIAL_PLAN_C:: date                         as last_update_to_financial_plan_c
  , a.json:HAVE_YOU_SET_UP_A_REVOCABLE_TRUST_C:: varchar(765)             as have_you_set_up_a_revocable_trust_c
  , a.json:HAVE_YOU_SET_UP_A_POUR_OVER_WILL_C:: varchar(765)              as have_you_set_up_a_pour_over_will_c
  , a.json:HAVE_YOU_SET_UP_A_POWER_OF_ATTORNEY_C:: varchar(765)           as have_you_set_up_a_power_of_attorney_c
  , a.json:HAVE_YOU_SET_UP_A_HEALTH_CARE_DIRECTIVE_C:: varchar(765)       as have_you_set_up_a_health_care_directive_c
  , a.json:LAST_TIME_ESTATE_PLAN_WAS_REVIEWED_C:: date                    as last_time_estate_plan_was_reviewed_c
  , a.json:NUMBER_OF_CLIENTS_AT_ADVICE_PERIOD_C:: float                   as number_of_clients_at_advice_period_c
  , a.json:ANNUAL_REVENUE_AT_ADVICE_PERIOD_C:: number                     as annual_revenue_at_advice_period_c
  , a.json:ANNUAL_REVENUE_GOAL_AT_ADVICE_PERIOD_C:: number                as annual_revenue_goal_at_advice_period_c
  , a.json:SIGNED_REVENUE_YTD_AT_ADVICE_PERIOD_C:: number                 as signed_revenue_ytd_at_advice_period_c
  , a.json:YTD_REVENUE_VS_GOAL_C:: number                                 as ytd_revenue_vs_goal_c
  , a.json:LIFE_INSURANCE_C:: varchar(765)                                as life_insurance_c
  , a.json:DISABILITY_INSURANCE_C:: varchar(765)                          as disability_insurance_c
  , a.json:LTC_INSURANCE_C:: varchar(765)                                 as ltc_insurance_c
  , a.json:UMBRELLA_INSURANCE_C:: varchar(4099)                           as umbrella_insurance_c
  , a.json:PROPERTY_CASUALTY_INSURANCE_C:: varchar(765)                   as property_casualty_insurance_c
  , a.json:CLIENT_SCHEDULE_C:: varchar(765)                               as client_schedule_c
  , a.json:TERMINATED_C:: boolean                                         as terminated_c
  , a.json:APX_CLIENT_C:: boolean                                         as apx_client_c
  , a.json:AT_RISK_CLIENT_C:: boolean                                     as at_risk_client_c
  , a.json:REFERRED_BY_INTERNAL_C:: varchar(18)                           as referred_by_internal_c
  , a.json:STEVE_S_PROSPECT_NOTES_C:: varchar(765)                        as steve_s_prospect_notes_c
  , a.json:FIDELITY_BRANCH_NAME_C:: varchar(3900)                         as fidelity_branch_name_c
  , a.json:FIDELITY_REP_NAME_C:: varchar(3900)                            as fidelity_rep_name_c
  , a.json:CFO_CONTRACT_DRAFTED_C:: boolean                               as cfo_contract_drafted_c
  , a.json:SUITABLE_FOR_VANILLA_C:: boolean                               as suitable_for_vanilla_c
  , a.json:PROPOSAL_STAGE_C:: varchar(765)                                as proposal_stage_c
  , a.json:CFO_RELATIONSHIP_C:: boolean                                   as cfo_relationship_c
  , a.json:LAB_ONBOARDING_STAGE_C:: varchar(765)                          as lab_onboarding_stage_c
  , a.json:ASSET_FLAVOR_C:: varchar(765)                                  as asset_flavor_c
  , a.json:CASH_BUFFER_C:: varchar(765)                                   as cash_buffer_c
  , a.json:IPS_PORTFOLIO_ASSET_ALLOCATION_C:: varchar(765)                as ips_portfolio_asset_allocation_c
  , a.json:REQUEST_SCORE_CLIENT_C:: float                                 as request_score_client_c
  , a.json:NORMALIZED_REQUEST_SCORE_CLIENTS_C:: float                     as normalized_request_score_clients_c
  , a.json:STEVE_INVOLVED_C:: boolean                                     as steve_involved_c
  , a.json:CASH_BUFFER_AMOUNT_C:: number                                  as cash_buffer_amount_c
  , a.json:ANNUAL_GAIN_BUDGET_C:: varchar(765)                            as annual_gain_budget_c
  , a.json:ANNUAL_GAIN_BUDGET_AMOUNT_C:: number                           as annual_gain_budget_amount_c
  , a.json:PORTFOLIO_MANAGEMENT_GROUP_C:: varchar(765)                    as portfolio_management_group_c
  , a.json:ASSISTANT_EMAIL_C:: varchar(240)                               as assistant_email_c
  , a.json:RECURRING_DISTRIBUTION_C:: varchar(765)                        as recurring_distribution_c
  , a.json:RECURRING_DISTRIBUTION_MONTHLY_AMOUNT_C:: number               as recurring_distribution_monthly_amount_c
  , a.json:SENIOR_ADVISOR_C:: varchar(18)                                 as senior_advisor_c
  , a.json:NOTES_PM_C:: varchar(98304)                                    as notes_pm_c
  , a.json:SERVICE_SEGMENTATION_C:: varchar(3900)                         as service_segmentation_c
  , a.json:CLIENT_SIGNATURE_PREFERENCE_C:: varchar(765)                   as client_signature_preference_c
  , a.json:LAST_PROSPECT_REVIEW_C:: date                                  as last_prospect_review_c
  , a.json:NEXT_ACTION_SHORT_NOTE_C:: varchar(765)                        as next_action_short_note_c
  , a.json:SELF_BRANDED_C:: varchar(3900)                                 as self_branded_c
  , a.json:WEALTH_MANAGER_C:: varchar(18)                                 as wealth_manager_c
  , a.json:BACKUP_CSA_C:: varchar(18)                                     as backup_csa_c
  , a.json:RTQ_SCORE_C:: float                                            as rtq_score_c
  , a.json:RTQ_LINK_IN_BOX_C:: varchar(765)                               as rtq_link_in_box_c
  , a.json:_FIVETRAN_SYNCED:: timestamp_tz(9)                             as _fivetran_synced
  , a.json:_FIVETRAN_DELETED:: boolean                                    as _fivetran_deleted
  , a.json:CFO_SR_STAFF_ACCOUNTANT_C:: varchar(18)                        as cfo_sr_staff_accountant_c
  , a.json:CFO_STAFF_ACCOUNTANT_C:: varchar(18)                           as cfo_staff_accountant_c
  , a.json:CFO_CRM_C:: varchar(18)                                        as cfo_crm_c
  , a.json:PARALEGAL_C:: varchar(18)                                      as paralegal_c

  , a.effective_at::timestamp                                             as effective_at
  , a._created_at::timestamp                                              as _created_at
  , {{ col_is_head(reference=source('salesforce_adviceperiod', 'account'), source_date_col='a.effective_at', reference_date_col='effective_at') }}
  , case when b.rn = 1 then 1 else 0 end                                  as is_latest
from {{ source('salesforce_adviceperiod', 'account') }} a
left join (
    select
        effective_at::date                                                            as effective_at
      , _created_at
      , row_number() over (partition by effective_at::date order by _created_at desc) as rn
    from {{ source('salesforce_adviceperiod', 'account') }}
    group by 1, 2
)                                                       b
on a.effective_at::date = b.effective_at::date
    and a._created_at = b._created_at