select
    'salesforce'::text(200)                                                 as system_name
  , 'adviceperiod'::text(200)                                               as system_instance
  , concat(system_name, '__', system_instance)::text(200)                   as system_key
  , 'mps'::text(200)                                                        as firm_source
  , a.json:ID:: varchar(18)                                                 as id
  , a.json:IS_DELETED:: boolean                                             as is_deleted
  , a.json:MASTER_RECORD_ID:: varchar(18)                                   as master_record_id
  , a.json:ACCOUNT_ID:: varchar(18)                                         as account_id
  , a.json:LAST_NAME:: varchar(240)                                         as last_name
  , a.json:FIRST_NAME:: varchar(120)                                        as first_name
  , a.json:SALUTATION:: varchar(120)                                        as salutation
  , a.json:MIDDLE_NAME:: varchar(120)                                       as middle_name
  , a.json:SUFFIX:: varchar(120)                                            as suffix
  , a.json:NAME:: varchar(363)                                              as name
  , a.json:RECORD_TYPE_ID:: varchar(18)                                     as record_type_id
  , a.json:OTHER_STREET:: varchar(765)                                      as other_street
  , a.json:OTHER_CITY:: varchar(120)                                        as other_city
  , a.json:OTHER_STATE:: varchar(240)                                       as other_state
  , a.json:OTHER_POSTAL_CODE:: varchar(60)                                  as other_postal_code
  , a.json:OTHER_COUNTRY:: varchar(240)                                     as other_country
  , a.json:OTHER_STATE_CODE:: varchar(30)                                   as other_state_code
  , a.json:OTHER_COUNTRY_CODE:: varchar(30)                                 as other_country_code
  , a.json:OTHER_LATITUDE:: float                                           as other_latitude
  , a.json:OTHER_LONGITUDE:: float                                          as other_longitude
  , a.json:OTHER_GEOCODE_ACCURACY:: varchar(120)                            as other_geocode_accuracy
  , a.json:MAILING_STREET:: varchar(765)                                    as mailing_street
  , a.json:MAILING_CITY:: varchar(120)                                      as mailing_city
  , a.json:MAILING_STATE:: varchar(240)                                     as mailing_state
  , a.json:MAILING_POSTAL_CODE:: varchar(60)                                as mailing_postal_code
  , a.json:MAILING_COUNTRY:: varchar(240)                                   as mailing_country
  , a.json:MAILING_STATE_CODE:: varchar(30)                                 as mailing_state_code
  , a.json:MAILING_COUNTRY_CODE:: varchar(30)                               as mailing_country_code
  , a.json:MAILING_LATITUDE:: float                                         as mailing_latitude
  , a.json:MAILING_LONGITUDE:: float                                        as mailing_longitude
  , a.json:MAILING_GEOCODE_ACCURACY:: varchar(120)                          as mailing_geocode_accuracy
  , a.json:PHONE:: varchar(120)                                             as phone
  , a.json:FAX:: varchar(120)                                               as fax
  , a.json:MOBILE_PHONE:: varchar(120)                                      as mobile_phone
  , a.json:HOME_PHONE:: varchar(120)                                        as home_phone
  , a.json:OTHER_PHONE:: varchar(120)                                       as other_phone
  , a.json:ASSISTANT_PHONE:: varchar(120)                                   as assistant_phone
  , a.json:REPORTS_TO_ID:: varchar(18)                                      as reports_to_id
  , a.json:EMAIL:: varchar(240)                                             as email
  , a.json:TITLE:: varchar(384)                                             as title
  , a.json:DEPARTMENT:: varchar(240)                                        as department
  , a.json:ASSISTANT_NAME:: varchar(120)                                    as assistant_name
  , a.json:LEAD_SOURCE:: varchar(765)                                       as lead_source
  , a.json:BIRTHDATE:: date                                                 as birthdate
  , a.json:DESCRIPTION:: varchar(96000)                                     as description
  , a.json:OWNER_ID:: varchar(18)                                           as owner_id
  , a.json:HAS_OPTED_OUT_OF_EMAIL:: boolean                                 as has_opted_out_of_email
  , a.json:DO_NOT_CALL:: boolean                                            as do_not_call
  , a.json:CREATED_DATE:: timestamp_tz(9)                                   as created_date
  , a.json:CREATED_BY_ID:: varchar(18)                                      as created_by_id
  , a.json:LAST_MODIFIED_DATE:: timestamp_tz(9)                             as last_modified_date
  , a.json:LAST_MODIFIED_BY_ID:: varchar(18)                                as last_modified_by_id
  , a.json:SYSTEM_MODSTAMP:: timestamp_tz(9)                                as system_modstamp
  , a.json:LAST_ACTIVITY_DATE:: date                                        as last_activity_date
  , a.json:LAST_CUREQUEST_DATE:: timestamp_tz(9)                            as last_curequest_date
  , a.json:LAST_CUUPDATE_DATE:: timestamp_tz(9)                             as last_cuupdate_date
  , a.json:LAST_VIEWED_DATE:: timestamp_tz(9)                               as last_viewed_date
  , a.json:LAST_REFERENCED_DATE:: timestamp_tz(9)                           as last_referenced_date
  , a.json:EMAIL_BOUNCED_REASON:: varchar(765)                              as email_bounced_reason
  , a.json:EMAIL_BOUNCED_DATE:: timestamp_tz(9)                             as email_bounced_date
  , a.json:IS_EMAIL_BOUNCED:: boolean                                       as is_email_bounced
  , a.json:PHOTO_URL:: varchar(765)                                         as photo_url
  , a.json:JIGSAW:: varchar(60)                                             as jigsaw
  , a.json:JIGSAW_CONTACT_ID:: varchar(60)                                  as jigsaw_contact_id
  , a.json:INDIVIDUAL_ID:: varchar(18)                                      as individual_id
  , a.json:SALENTICA_LMNTS_AGE_EOY_C:: float                                as salentica_lmnts_age_eoy_c
  , a.json:SALENTICA_LMNTS_AGE_EOY_CALC_C:: float                           as salentica_lmnts_age_eoy_calc_c
  , a.json:SALENTICA_LMNTS_AGE_CURRENT_C:: float                            as salentica_lmnts_age_current_c
  , a.json:SALENTICA_LMNTS_AGE_CURRENT_CALC_C:: float                       as salentica_lmnts_age_current_calc_c
  , a.json:SALENTICA_LMNTS_ALTERNATE_EMAIL_C:: varchar(240)                 as salentica_lmnts_alternate_email_c
  , a.json:SALENTICA_LMNTS_ANNIVERSARY_C:: date                             as salentica_lmnts_anniversary_c
  , a.json:SALENTICA_LMNTS_ANNUAL_INCOME_C:: number                         as salentica_lmnts_annual_income_c
  , a.json:SALENTICA_LMNTS_CITIZENSHIP_C:: varchar(765)                     as salentica_lmnts_citizenship_c
  , a.json:SALENTICA_LMNTS_CONTACT_SUBTYPE_C:: varchar(765)                 as salentica_lmnts_contact_subtype_c
  , a.json:SALENTICA_LMNTS_CONTACT_TYPE_C:: varchar(765)                    as salentica_lmnts_contact_type_c
  , a.json:SALENTICA_LMNTS_CURRENT_EMPLOYER_C:: varchar(18)                 as salentica_lmnts_current_employer_c
  , a.json:SALENTICA_LMNTS_DOB_DAY_C:: float                                as salentica_lmnts_dob_day_c
  , a.json:SALENTICA_LMNTS_DOB_MONTH_C:: float                              as salentica_lmnts_dob_month_c
  , a.json:SALENTICA_LMNTS_DOB_YEAR_C:: float                               as salentica_lmnts_dob_year_c
  , a.json:SALENTICA_LMNTS_DATE_OF_DEATH_C:: date                           as salentica_lmnts_date_of_death_c
  , a.json:SALENTICA_LMNTS_DAYS_UNTIL_NEXT_BIRTHDAY_C:: float               as salentica_lmnts_days_until_next_birthday_c
  , a.json:SALENTICA_LMNTS_DAYS_UNTIL_NEXT_BIRTHDAY_CALC_C:: float          as salentica_lmnts_days_until_next_birthday_calc_c
  , a.json:SALENTICA_LMNTS_EXTERNAL_ID_C:: varchar(150)                     as salentica_lmnts_external_id_c
  , a.json:SALENTICA_LMNTS_GENDER_C:: varchar(765)                          as salentica_lmnts_gender_c
  , a.json:SALENTICA_LMNTS_INHERIT_RELATIONSHIP_BILLING_ADDRESS_C:: boolean as salentica_lmnts_inherit_relationship_billing_address_c
  , a.json:SALENTICA_LMNTS_INHERIT_RELATIONSHIP_MAILING_ADDRESS_C:: boolean as salentica_lmnts_inherit_relationship_mailing_address_c
  , a.json:SALENTICA_LMNTS_MARITAL_STATUS_C:: varchar(765)                  as salentica_lmnts_marital_status_c
  , a.json:SALENTICA_LMNTS_NEXT_BIRTHDAY_C:: date                           as salentica_lmnts_next_birthday_c
  , a.json:SALENTICA_LMNTS_NEXT_BIRTHDAY_CALC_C:: date                      as salentica_lmnts_next_birthday_calc_c
  , a.json:SALENTICA_LMNTS_OCCUPATION_C:: varchar(300)                      as salentica_lmnts_occupation_c
  , a.json:SALENTICA_LMNTS_SSN_SIN_C:: varchar(60)                          as salentica_lmnts_ssn_sin_c
  , a.json:SALENTICA_LMNTS_SALENTICA_DATA_BROKER_ID_C:: varchar(300)        as salentica_lmnts_salentica_data_broker_id_c
  , a.json:SALENTICA_LMNTS_SPOUSE_PARTNER_C:: varchar(18)                   as salentica_lmnts_spouse_partner_c
  , a.json:FSTR_DAYS_UNTIL_NEXT_BIRTHDAY_C:: float                          as fstr_days_until_next_birthday_c
  , a.json:FSTR_NEXT_BIRTHDAY_C:: date                                      as fstr_next_birthday_c
  , a.json:SALENTICA_LMNTS_NICKNAME_C:: varchar(150)                        as salentica_lmnts_nickname_c
  , a.json:NOTES_C:: varchar(98304)                                         as notes_c
  , a.json:LAWYER_C:: varchar(765)                                          as lawyer_c
  , a.json:CPA_C:: varchar(765)                                             as cpa_c
  , a.json:LINKED_IN_C:: varchar(765)                                       as linked_in_c
  , a.json:RECEIVE_E_STATEMENTS_C:: boolean                                 as receive_e_statements_c
  , a.json:STOCK_RESTRICTIONS_C:: boolean                                   as stock_restrictions_c
  , a.json:TOTAL_NET_WORTH_C:: number                                       as total_net_worth_c
  , a.json:FINRA_MEMBER_C:: boolean                                         as finra_member_c
  , a.json:TOTAL_INVESTABLE_ASSETS_C:: number                               as total_investable_assets_c
  , a.json:SOCIAL_SECURITY_NUMBER_C:: varchar(36)                           as social_security_number_c
  , a.json:TITLE_FUNCTION_C:: varchar(765)                                  as title_function_c
  , a.json:SUPERVISOR_C:: varchar(18)                                       as supervisor_c
  , a.json:EXTENSION_C:: varchar(15)                                        as extension_c
  , a.json:LID_LANGUAGES_C:: varchar(300)                                   as lid_languages_c
  , a.json:LID_LEVEL_C:: varchar(765)                                       as lid_level_c
  , a.json:DUPCHECK_DC_3_DISABLE_DUPLICATE_CHECK_C:: boolean                as dupcheck_dc_3_disable_duplicate_check_c
  , a.json:DESCRIPTION_C:: varchar(98304)                                   as description_c
  , a.json:LID_LINKED_IN_COMPANY_ID_C:: varchar(240)                        as lid_linked_in_company_id_c
  , a.json:LID_LINKED_IN_MEMBER_TOKEN_C:: varchar(240)                      as lid_linked_in_member_token_c
  , a.json:LID_NO_LONGER_AT_COMPANY_C:: varchar(765)                        as lid_no_longer_at_company_c
  , a.json:LID_SESSION_ID_C:: varchar(3900)                                 as lid_session_id_c
  , a.json:REBALANCE_C:: date                                               as rebalance_c
  , a.json:LAST_ACTIVITY_DATE_C:: date                                      as last_activity_date_c
  , a.json:DAYS_SINCE_LAST_ACTIVITY_C:: float                               as days_since_last_activity_c
  , a.json:LAST_GOAL_C:: varchar(765)                                       as last_goal_c
  , a.json:UPCOMING_LIFE_EVENT_C:: varchar(765)                             as upcoming_life_event_c
  , a.json:RELATIONSHIP_SEGMENT_C:: varchar(3900)                           as relationship_segment_c
  , a.json:LAST_YEAR_RETURN_C:: varchar(765)                                as last_year_return_c
  , a.json:THIS_YEAR_ROTH_CONVERSION_C:: varchar(765)                       as this_year_roth_conversion_c
  , a.json:THIS_YEAR_ROTH_CONVERSION_BACKDOOR_C:: varchar(765)              as this_year_roth_conversion_backdoor_c
  , a.json:THIS_YEAR_CHARITABLE_C:: varchar(765)                            as this_year_charitable_c
  , a.json:LAST_YEAR_ROTH_CONVERSION_C:: varchar(765)                       as last_year_roth_conversion_c
  , a.json:LAST_YEAR_ROTH_CONVERSION_BACKDOOR_C:: varchar(765)              as last_year_roth_conversion_backdoor_c
  , a.json:LAST_YEAR_CHARITABLE_C:: varchar(765)                            as last_year_charitable_c
  , a.json:DUPCHECK_DC_3_INDEX_C:: varchar(98304)                           as dupcheck_dc_3_index_c
  , a.json:DUPLICATES_C:: float                                             as duplicates_c
  , a.json:SALENTICA_LMNTS_INHERIT_B_A_DEL_C:: boolean                      as salentica_lmnts_inherit_b_a_del_c
  , a.json:SALENTICA_LMNTS_INHERIT_M_A_DEL_C:: boolean                      as salentica_lmnts_inherit_m_a_del_c
  , a.json:SALENTICA_LMNTS_LAST_CONTACT_ACTIVITY_C:: varchar(300)           as salentica_lmnts_last_contact_activity_c
  , a.json:SALENTICA_LMNTS_LAST_CONTACTED_BY_C:: varchar(18)                as salentica_lmnts_last_contacted_by_c
  , a.json:SALENTICA_LMNTS_LAST_CONTACTED_ON_C:: date                       as salentica_lmnts_last_contacted_on_c
  , a.json:DATA_NUMBER_C:: float                                            as data_number_c
  , a.json:FIDELITY_APPROVED_RECRUITER_C:: boolean                          as fidelity_approved_recruiter_c
  , a.json:CITY_C:: varchar(180)                                            as city_c
  , a.json:CIRRUSADV_CREATED_BY_CIRRUS_INSIGHT_C:: boolean                  as cirrusadv_created_by_cirrus_insight_c
  , a.json:DA_SCOOP_COMPOSER_BLACK_LIST_C:: varchar(18)                     as da_scoop_composer_black_list_c
  , a.json:DA_SCOOP_COMPOSER_EMAIL_2_C:: varchar(240)                       as da_scoop_composer_email_2_c
  , a.json:DA_SCOOP_COMPOSER_EMAIL_DOMAIN_C:: varchar(765)                  as da_scoop_composer_email_domain_c
  , a.json:DA_SCOOP_COMPOSER_GROOVE_CREATE_OPPORTUNITY_C:: varchar(3900)    as da_scoop_composer_groove_create_opportunity_c
  , a.json:FAVORITE_FOODS_C:: varchar(98304)                                as favorite_foods_c
  , a.json:HOBBIES_C:: varchar(98304)                                       as hobbies_c
  , a.json:CHARITABLE_INTERESTS_C:: varchar(765)                            as charitable_interests_c
  , a.json:FAVORITE_MUSIC_TV_SHOWS_C:: varchar(98304)                       as favorite_music_tv_shows_c
  , a.json:MISCELLANEOUS_NOTES_C:: varchar(98304)                           as miscellaneous_notes_c
  , a.json:EUSTACE_BOX_BOX_FOLDER_ID_C:: varchar(150)                       as eustace_box_box_folder_id_c
  , a.json:RH_2_CURRENCY_TEST_C:: number                                    as rh_2_currency_test_c
  , a.json:RH_2_DESCRIBE_C:: varchar(18)                                    as rh_2_describe_c
  , a.json:RH_2_FORMULA_TEST_C:: number                                     as rh_2_formula_test_c
  , a.json:RH_2_INTEGER_TEST_C:: float                                      as rh_2_integer_test_c
  , a.json:DA_SCOOP_COMPOSER_GROOVE_LOG_A_CALL_C:: varchar(3900)            as da_scoop_composer_groove_log_a_call_c
  , a.json:DA_SCOOP_COMPOSER_GROOVE_NOTES_C:: varchar(98304)                as da_scoop_composer_groove_notes_c
  , a.json:DA_SCOOP_COMPOSER_NORMALIZED_MOBILE_C:: varchar(45)              as da_scoop_composer_normalized_mobile_c
  , a.json:DA_SCOOP_COMPOSER_NORMALIZED_PHONE_C:: varchar(45)               as da_scoop_composer_normalized_phone_c
  , a.json:MEETING_PREFERENCES_C:: varchar(98304)                           as meeting_preferences_c
  , a.json:MEETING_DELIVERABLE_C:: varchar(765)                             as meeting_deliverable_c
  , a.json:NEXT_ACTION_NOTE_C:: varchar(765)                                as next_action_note_c
  , a.json:ACTION_DUE_DATE_C:: date                                         as action_due_date_c
  , a.json:PARTNER_TEAM_C:: varchar(18)                                     as partner_team_c
  , a.json:LAB_STANDUP_C:: boolean                                          as lab_standup_c
  , a.json:ACTION_OWNER_C:: varchar(18)                                     as action_owner_c
  , a.json:LAST_MEETING_C:: date                                            as last_meeting_c
  , a.json:UPCOMING_MEETING_C:: date                                        as upcoming_meeting_c
  , a.json:BEST_CONTACT_C:: varchar(98304)                                  as best_contact_c
  , a.json:CLIENT_CONTRACT_C:: varchar(18)                                  as client_contract_c
  , a.json:CLIENT_PROFILE_LINK_C:: varchar(3900)                            as client_profile_link_c
  , a.json:DAYS_UNTIL_MEETING_C:: float                                     as days_until_meeting_c
  , a.json:DAYS_UNTIL_ACTION_ITEM_C:: float                                 as days_until_action_item_c
  , a.json:CUSTODIAN_DATA_DUMP_C:: varchar(765)                             as custodian_data_dump_c
  , a.json:RELATIONSHIP_TEAM_C:: varchar(3900)                              as relationship_team_c
  , a.json:CONTACT_OWNER_C:: varchar(3900)                                  as contact_owner_c
  , a.json:EMAIL_OPT_OUT_TEXT_C:: varchar(3900)                             as email_opt_out_text_c
  , a.json:MC_4_SF_MC_SUBSCRIBER_C:: varchar(18)                            as mc_4_sf_mc_subscriber_c
  , a.json:FLOW_OPS_REQUESTS_C:: varchar(765)                               as flow_ops_requests_c
  , a.json:FLOW_REQUEST_CATEGORY_C:: varchar(765)                           as flow_request_category_c
  , a.json:FULL_NAME_FOR_DUPES_C:: varchar(3900)                            as full_name_for_dupes_c
  , a.json:CLIENT_SUBSCRIBER_C:: varchar(3900)                              as client_subscriber_c
  , a.json:ANNUAL_INCOME_SOURCE_C:: varchar(4099)                           as annual_income_source_c
  , a.json:OTHER_ANNUAL_INCOME_SOURCE_C:: varchar(765)                      as other_annual_income_source_c
  , a.json:EMPLOYMENT_STATUS_C:: varchar(765)                               as employment_status_c
  , a.json:DA_SCOOP_COMPOSER_IS_CREATED_BY_GROOVE_C:: boolean               as da_scoop_composer_is_created_by_groove_c
  , a.json:TOTAL_NUMBER_OF_DEPENDENT_C:: float                              as total_number_of_dependent_c
  , a.json:NUMBER_OF_CHILDREN_C:: float                                     as number_of_children_c
  , a.json:CHILDREN_S_NAME_AND_DOB_C:: varchar(98304)                       as children_s_name_and_dob_c
  , a.json:NUMBER_OF_GRANDCHILDREN_C:: float                                as number_of_grandchildren_c
  , a.json:LIQUID_NET_WORTH_C:: number                                      as liquid_net_worth_c
  , a.json:ACCOUNT_INFORMATION_C:: varchar(98304)                           as account_information_c
  , a.json:ARE_YOU_CURRENTLY_TAKING_WITHDRAWAL_C:: varchar(765)             as are_you_currently_taking_withdrawal_c
  , a.json:TAX_CONSIDERATIONS_C:: varchar(98304)                            as tax_considerations_c
  , a.json:MARGINAL_FEDERAL_RATE_C:: varchar(765)                           as marginal_federal_rate_c
  , a.json:LIFE_INSURANCE_C:: varchar(765)                                  as life_insurance_c
  , a.json:DISABILITY_INSURANCE_C:: varchar(765)                            as disability_insurance_c
  , a.json:LTC_INSURANCE_C:: varchar(765)                                   as ltc_insurance_c
  , a.json:UMBRELLA_INSURANCE_C:: varchar(765)                              as umbrella_insurance_c
  , a.json:PROPERTY_CASUALTY_INSURANCE_C:: varchar(765)                     as property_casualty_insurance_c
  , a.json:COMFORTABLE_WITH_CURRENT_LEVEL_OF_RISK_C:: varchar(765)          as comfortable_with_current_level_of_risk_c
  , a.json:RISK_LEVEL_C:: varchar(765)                                      as risk_level_c
  , a.json:INVESTMENT_RISK_SENTIMENT_C:: varchar(765)                       as investment_risk_sentiment_c
  , a.json:ACCOUNT_RESTRICTIONS_C:: varchar(98304)                          as account_restrictions_c
  , a.json:COMPLETED_FINANCIAL_PLANNING_C:: varchar(765)                    as completed_financial_planning_c
  , a.json:FINANCIAL_PLANNING_DATE_C:: date                                 as financial_planning_date_c
  , a.json:EMPLOYER_C:: varchar(765)                                        as employer_c
  , a.json:QUESTIONNAIRE_INFORMATIONS_C:: varchar(98304)                    as questionnaire_informations_c
  , a.json:_FIVETRAN_SYNCED:: timestamp_tz(9)                               as _fivetran_synced
  , a.json:_FIVETRAN_DELETED:: boolean                                      as _fivetran_deleted
  , a.json:DRIVERS_LICENSE_STATE_C:: varchar(765)                           as drivers_license_state_c
  , a.json:DRIVERS_LICENSE_NUMBER_C:: varchar(765)                          as drivers_license_number_c

  , a.effective_at::timestamp                                               as effective_at
  , a._created_at::timestamp                                                as _created_at
  , {{ col_is_head(reference=source('salesforce_adviceperiod', 'contact'), source_date_col='a.effective_at', reference_date_col='effective_at') }}
  , case when b.rn = 1 then 1 else 0 end                                    as is_latest
from {{ source('salesforce_adviceperiod', 'contact') }} a
left join (
    select
        effective_at::date                                                            as effective_at
      , _created_at
      , row_number() over (partition by effective_at::date order by _created_at desc) as rn
    from {{ source('salesforce_adviceperiod', 'contact') }}
    group by 1, 2
)                                                       b
on a.effective_at::date = b.effective_at::date
    and a._created_at = b._created_at