select
    'tamarac'                                      as system_name
    , 'nashville'                                  as system_instance
    , concat(system_name , '__' , system_instance) as system_key
    , 'mwa'                                        as firm_source
    , effective_date                               as effective_date
    , account__net_worth_category
    , account__ownership_type
    , account__primary_owner_email
    , account_current_value
    , account_level
    , account_long_term_realized_gain_loss
    , account_name
    , account_number                               as account_number_formatted
    , regexp_replace(replace(
        ltrim(upper(account_number) , '0')
        , '-' , ''
    ) , '\\s{2,}'
    , ' ')                                         as account_number
    , account_short_term_realized_gain_loss
    , account_status
    , account_total_realized_gain_loss
    , account_type
    , address1
    , address2
    , address3
    , address4
    , address5
    , address6
    , advisor
    , age
    , allocation_preference
    , allow_buying_and_selling_of_same_slm
    , allow_rebalancing
    , allow_redemption_fees
    , allow_short_term_gains
    , allow_violation_of_wash_sale_rule
    , amortization_calculation_enabled
    , annual_turnover
    , annualized_gross_irr
    , annualized_gross_twr
    , annualized_net_irr
    , annualized_net_twr
    , asset_location_preference
    , average_daily_balance
    , benchmark
    , benchmark_start_date
    , beneficial_billing_rate_tier_treatment
    , billing_closed_date
    , billing_definitions
    , billing_groups
    , billing_inception_date
    , calculate_performance
    , cash_to_raise
    , city
    , closed_date
    , closing_method
    , closing_value
    , commission_maximum_number_of_shares
    , commissions
    , compute_billing_closed_date
    , compute_billing_inception_date
    , compute_performance_inception_date
    , country
    , cumulative_turnover
    , current_cash
    , custodian
    , custodian_fee_schedule
    , date_created
    , days_to_hold_buys
    , default_rebalance_setting
    , default_template
    , description
    , discretionary
    , display_accrued_interest
    , display_preference
    , dollar_variance
    , dvp_number
    , entity_type
    , equities_with_fees_minimum_holding_size_dollar
    , equities_with_fees_minimum_holding_size_percent
    , equities_with_fees_minimum_trade_size_dollar
    , equities_with_fees_minimum_trade_size_percent
    , equity_dividend_reinvestment
    , equity_round_lot_size
    , equity_trade_file_format
    , exclude_all_securities_from_billing
    , exclude_all_securities_from_performance
    , expenses_excluding_revenue
    , expenses_percent_of_account
    , first_name
    , fiscal_year_end
    , fiscal_year_end_date_use_for_reporting
    , gross_irr
    , gross_twr
    , hold_duplicate_trades
    , household
    , household_assignments
    , include_accrued_dividends
    , include_accrued_gains
    , inflows
    , initial_cash_dollar
    , initial_cash_percent
    , initial_model_deviation
    , initial_value
    , interest_dividends
    , internal_commissions
    , intragroup_flow_auto_matching_enabled
    , last_name
    , last_order_date
    , last_reconciliation_date
    , last_sync_start_date
    , last_sync_time
    , last_trade_reconciliation_date
    , long_term_carryover_ytd
    , long_term_tax_rate
    , managed_account_value_preveod
    , management_fees
    , management_fees_and_commissions
    , manual_performance_history_end_date
    , manual_performance_return_behavior
    , manual_performance_value_behavior
    , margin_account
    , margin_expense
    , master_account
    , maximum_gain_amount
    , migration__account_status
    , migration__group_name_1
    , migration__group_name_2
    , migration__keywords
    , migration__rebalancing_group_id
    , minimum_trade_size_tolerance_dollar
    , minimum_trade_size_tolerance_percent
    , model_2
    , mutual_fund_buy_type
    , mutual_fund_capital_gains_reinvestment
    , mutual_fund_dividend_reinvestment
    , mutual_fund_round_lot_size
    , mutual_fund_sell_type
    , mutual_fund_trade_file_format
    , net_flows
    , net_investment_gain
    , net_irr
    , net_twr
    , next_sync_start_date
    , non_fee_securities_minimum_holding_size_dollar
    , non_fee_securities_minimum_holding_size_percent
    , non_fee_securities_minimum_trade_size_dollar
    , non_fee_securities_minimum_trade_size_percent
    , number_of_trades
    , objective
    , objective_start_date
    , only_buy_existing_holdings
    , only_warn_for_st_gain_violations
    , out_of_tolerance
    , outflows
    , ownership_account_type
    , ownership_parent_account
    , per_share_commission
    , per_trade_commission
    , percent_variance
    , performance_date
    , performance_inception_date
    , portfolio_yield
    , post_rebalance_cash_dollar
    , post_rebalance_cash_percent
    , post_rebalance_model_deviation
    , prev_eod_date
    , previous_12_months_turnover
    , primary_advisor
    , primary_household_id
    , primary_household_primary_advisor
    , primary_household_primary_advisor_id
    , prospect_account
    , purchases
    , realized_long_term_gain_loss_ytd
    , realized_short_term_gain_loss_ytd
    , reason_for_trade
    , rebalance_approved_by
    , rebalance_status
    , rebalanced_by
    , rebalancing_account_value
    , rebalancing_funding_account_number
    , rebalancing_group_account_number
    , rebalancing_group_name
    , rebalancing_model_name
    , rebalancing_sma
    , reconciliation_status
    , restrict_all_securities
    , sales
    , sell_based_on_tax_optimization
    , service_team_compliance
    , service_team_csa
    , service_team_name
    , service_team_operations
    , service_team_primary_advisor
    , service_team_secondary_advisor
    , service_team_trade_approver
    , service_team_trader
    , short_name
    , short_term_carryover_ytd
    , short_term_gain_restriction_boundary
    , short_term_maximum_gain_amount_dollar
    , short_term_maximum_gain_amount_percent
    , short_term_tax_rate
    , sma
    , sma_asset_class
    , sma_av_position
    , sma_description1
    , sma_description2
    , sma_description3
    , sma_performance
    , sma_sector
    , sma_share_class
    , sma_subsector
    , sma_treasuries
    , source_of_record_for_realized_gain_loss_is_custodian
    , state
    , state_of_primary_residence
    , state_tax_rate
    , sweep_cash
    , t1cash
    , target_allocation
    , tax_loss_harvesting_minimum_dollar
    , tax_loss_harvesting_minimum_percent
    , taxable
    , total_account_value
    , total_account_value_preveod
    , total_assets_excluding_cash
    , total_cash_dollar
    , total_cash_percent
    , total_cash_reserve_actual_dollar
    , total_cash_reserve_actual_percent
    , total_cash_reserve_goal_dollar
    , total_cash_reserve_goal_percent
    , total_cash_reserves
    , total_initial_security_value
    , total_post_rebalance_security_value
    , tradeable_cash
    , traded_away_commissions
    , trading_id
    , trailing_3yr_net_return
    , trailing_5yr_net_return
    , transaction_fee_fund_minimum_holding_size_dollar
    , transaction_fee_fund_minimum_holding_size_percent
    , transaction_fee_fund_minimum_trade_size_dollar
    , transaction_fee_fund_minimum_trade_size_percent
    , turnover_ytd
    , unmanaged_account_value_preveod
    , upload_account_id
    , uploaded_cash
    , use_primary_household_address
    , wash_sale_group_id
    , year_to_date_net_return
    , yodlee_id
    , yodlee_matching_status
    , zip
    , {{ col_is_head(reference=source('tamarac_nashville', 'financial_accounts')) }}
    , {{ col_is_current(date_col='effective_date') }}
    , record_datetime                              as _source_loaded_at
from {{ source('tamarac_nashville', 'financial_accounts') }}
where entity_type = 'Single Account'
