select a.value:allocId::string																as allocation_allocId,
      a.value:userId::string																as userId,
      a.value:tradingSessionId::string	 													as allocation_tradingSessionId,
      a.value:clientOrderId::string															as allocation_clientOrderId,
      a.value:origClientOrderId::string	 													as origClientOrderId,
      a.value:allocTransType::string	 													as allocTransType,
      a.value:symbol::string	 															as allocation_symbol,
      a.value:shares::number(19, 6) 														as shares,
      a.value:avgPx::number(19, 6) 															as allocation_avgPx,
      a.value:noOrders::int 																as noOrders,
      a.value:noExecs::int 																	as noExecs,
      a.value:side::string 																	as allocation_side,
      a.value:securityId::string                        									as securityId,
      a.value:securityIdSrc::string                     									as securityIdSrc,
      try_to_date(a.value:tradeDate::varchar(100), 'YYYYMMDD') 								as allocation_tradeDate,
	  try_to_timestamp(a.value:transactTime::varchar(100), 'YYYYMMDD-HH24:MI:SS.FF3') 		as allocation_transactTime,
      a.value:netMoney::string 																as netMoney,
      a.value:totNoAllocs::int 																as totNoAllocs,
      a.value:noAllocs::int 																as noAllocs,
      a.value:currentAllocStatus::string 													as currentAllocStatus,
      a.value:orderQty::number(19, 6) 														as allocation_orderQty,
      a.value:accruedInterestRate::number(19, 6) 											as accruedInterestRate,
      a.value:custId::string 																as allocation_custId,
      a.value:userName::string 																as userName,
      a.value:allocationMethod::string 														as allocationMethod,
	  a.value:beginString::string 															as allocation_beginString,
      a.value:onBehalfOfCompID::string 														as allocation_onBehalfOfCompID,
      a.value:onBehalfOfSubID::string 														as onBehalifOfSubID,
      a.value:targetCompId::string															as allocation_targetCompId,
      a.value:senderCompId::string 															as allocation_senderCompId,
	  m.value:allocId::string 																as member_allocId,
	  m.value:indivAllocId::string 															as indivAllocId,
	  m.value:tradingSessionId::string														as member_tradingSessionId,
	  m.value:userId::string 																as member_userId,
	  m.value:creatorId::string 															as member_creatorId,
	  m.value:creatorName::string 															as member_creatorName,
	  m.value:allocPrice::number(19, 6) 													as allocPrice,
	  m.value:allocQty::number(19, 6) 														as allocQty,
	  m.value:allocAvgPx::number(19, 6) 													as allocAvgPx,
	  m.value:allocNetMoney::number(19, 6) 													as allocnetMoney,
	  m.value:allocAmount::number(19, 6) 													as allocAmount,
	  m.value:allocAccount::string 															as allocAccount,
	  m.value:originalOrderQty::number(19, 6) 												as originalOrderQty,
	  m.value:originalClientOrderId::string 												as originalClientOrderId,
	  m.value:secFee::number(19, 6) 														as secFee,
	  m.value:otherFee::number(19, 6) 														as otherFee,
	  m.value:settlementType::string														as settlementType,
	  m.value:accruedInterestAmount::number(19, 6)											as maccruedInterestAmount,
	  m.value:purchasePrice::number(19, 6) 													as purchasePrice,
	  m.value:principal::number(19, 6) 														as principal,
	  m.value:comm::number(19, 6) 															as comm,
	  m.value:commType::string 																as commType,
	  m.value:allocAccountName::string 														as allocAccountName,
	  m.value:lotId::string 																as lotId,
      a.value:messageType::string 															as allocation_messageType,
      a.value:messageSequenceNo::string 													as messageSequenceNo,
	  a.value:order.blockId::string 														as blockId,
	  a.value:order.aggregatedClientOrderId::string 										as aggregatedClientOrderId,
	  a.value:order.sleeveId::string 														as sleeveId,
	  a.value:order.creatorId::string 														as order_creatorId,
	  a.value:order.creatorName::string 													as order_creatorName,
	  a.value:order.indivCount::number(19, 6) 												as indivCount,
	  a.value:order.autoSliceStatus::string 												as autoSliceStatus,
	  a.value:order.clientOrderId::string 													as order_clientOrderId,
	  a.value:order.userId::string 															as order_userId,
	  a.value:order.tradingSessionId::string 												as order_tradingSessionId,
	  a.value:order.custId::string 															as order_custId,
	  a.value:order.userName::string 														as order_userName,
	  a.value:order.traderId::string 														as traderId,
	  a.value:order.traderName::string 														as traderName,
	  a.value:order.custodialAccount::string 												as custodialAccount,
	  a.value:order.symbol::string 															as order_symbol,
	  a.value:order.side::string 															as order_side,
	  try_to_date(a.value:order.tradeDate::varchar(100), 'YYYYMMDD') 						as order_tradeDate,
	  a.value:order.timeInForce::string 													as timeInForce,
	  a.value:order.execInst::string 														as execInst,
	  a.value:order.orderType::string 														as orderType,
	  a.value:order.price::number(19, 6) 													as price,
	  a.value:order.orderQty::number(19, 6) 												as order_orderQty,
	  try_to_timestamp(a.value:order.transactTime::varchar(100), 'YYYYMMDD-HH24:MI:SS.FF3') as order_transactTime,
	  a.value:order.account::string 														as account,
	  a.value:order.stopPx::number(19, 6) 													as stopPx,
	  a.value:order.handlInst::string 														as handlInst,
	  a.value:order.expireTime::string    													as expireTime,
	  a.value:order.commission::number(19, 6) 												as commission,
	  a.value:order.maxFloor::number(19, 6) 												as maxFloor,
	  a.value:order.ratioQty::number(19, 6) 												as ratioQty,
	  a.value:order.noLegs::string															as noLegs,
	  a.value:order.avgPx::number(19, 6) 													as order_avgPx,
	  a.value:order.fillQty::number(19, 6) 													as fillQty,
	  a.value:order.beginString::string 													as order_beginString,
	  a.value:order.targetCompId::string 													as order_targetCompId,
	  a.value:order.senderCompId::string 													as order_senderCompId,
	  a.value:order.messageType::string 													as order_messageType,
	  a.value:order.onBehalfOfCompID::string 												as order_onBehalfOfCompID,
	  a.value:order.onBehalfOfSubID::string 												as onBehalfOfSubID,
	  a.value:order.validSymbol::boolean 													as validSymbol,
	  a.value:order.assetClass::string 														as assetClass,
      a.value:order.restageFlag::boolean                									as restageFlag,
      a.value:order.currentOrderStatus::string          									as currentOrderStatus,
      a.value:order.submittedBy::string                 									as submittedBy,
      a.value:order.option.clientOrdId::string          									as option_clientOrdId,
      a.value:order.option.tradingSessionId::string     									as option_tradingSessionId,
      a.value:order.option.userId::string               									as option_userId,
      try_to_date(a.value:order.option.maturityDate::varchar(100), 'YYYYMMDD') 				as option_maturityDate,
      a.value:order.option.strikePrice::number(19, 6)   									as option_strikePrice,
      a.value:order.option.putOrCall::string            									as option_putOrCall,
      a.value:order.option.positionEffect::string       									as option_positionEffect,
      a.value:order.option.customerOrFirm::string       									as option_customerOrFirm,
      a.value:order.mutualFund.clientOrdId::string      									as mutualfund_clientOrdId,
      a.value:order.mutualFund.tradingSessionId::string 									as mutualfund_tradingSessionId,
      a.value:order.mutualFund.userId::string           									as mutualfund_userId,
      a.value:order.mutualFund.state::string            									as mutualfund_state,
      a.value:order.mutualFund.amount::number(19,6)     									as mutualfund_amount,
      a.value:order.mutualFund.round::string            									as mutualfund_round,
      a.value:order.mutualFund.dividend::string         									as mutualfund_dividend,
      a.value:order.mutualFund.longTermGain::string     									as mutualfund_longTermGain,
      a.value:order.mutualFund.shortTermGain::string    									as mutualfund_shortTermGain,
      a.value:order.mutualFund.initialOrFull::boolean   									as mutualfund_initialOrFull,
      a.value:order.mutualFund.feeIndicator::boolean    									as mutualfund_feeIndicator,
      a.value:order.mutualFund.linkQtyPercent::number(19,6) 								as mutualfund_linkQtyPercent,
      a.value:order.mutualFund.linkAmount::number(19, 6) 									as mutualfund_linkAmount,
      a.value:order.fixedIncome.clientOrderId::string   									as fixedincome_clientOrderId,
      a.value:order.fixedIncome.tradingSessionId::string  									as fixedincome_tradingSessionId,
      a.value:order.fixedIncome.userId::string          									as fixedincome_userId,
      a.value:order.fixedIncome.couponRate::number(19, 6) 									as fixedincome_couponRate,
      a.value:order.fixedIncome.securityDesc::string    									as fixedincome_securityDesc,
      a.value:order.fixedIncome.priceType::string       									as fixedincome_priceType,
      a.value:order.fixedIncome.accruedInterestAmt::number(19, 6)  							as fixedincome_accruedInterestAmt,
      a.value:order.fixedIncome.factor::number(19, 6)   									as fixedincome_factor,
      a.value:order.fixedIncome.product::number(19, 6)  									as fixedincome_product,
      a.value:order.fixedIncome.yield::number(19, 6)    									as fixedincome_yield,
      a.value:order.fixedIncome.originalFace::number(19, 6) 								as fixedincome_originalFace,
      a.value:order.fixedIncome.principal::number(19, 6) 									as fixedincome_principal,
      oa.RECORD_DATE,
      oa.RECORD_DATETIME
from {{ source('copilot', 'copilot_orders_allocations') }} oa,
lateral flatten(input => oa.VARIANT_DATA, path => 'allocations', outer => true, mode => 'array') a,
lateral flatten(input => a.VALUE, path => 'memberList', outer => true, mode => 'array') m