select 	pos.value:accountId::string 					    as account_id,
			pos.value:accountPercent::number(19, 6) 		as accountPercent,
    		pos.value:amount::number(19, 6)					as amount,
    		pos.value:averagePrice::number(19, 6)			as average_price,
    		pos.value:currentFxRate::number(19, 6)			as current_fx_rate,
    		pos.value:currentPrice::number(19, 6)			as current_price,
    		pos.value:custId:: string						as cust_id,
    		pos.value:custodian::string						as custodian,
    		pos.value:dayPnL::number(19, 6)					as day_pnl,
    		pos.value:groupId::string 						as group_id,
    		pos.value:industry::string 						as industry,
    		pos.value:issue::string							as issue,
    	    to_timestamp(pos.value:lastModified::varchar(100), 'YYYY-MM-DD"T"HH24:MI:SS.FF3TZHTZM') as last_modified,
    		pos.value:marketValue::number(19, 6)			as market_value,
    		pos.value:parentGroupId::string					as parent_group_id,
    		pos.value:positionId::string					as position_id,
    		pos.value:previousClose::number(19, 6)			as previous_close,
    		pos.value:price::number(19, 6)					as price,
    		pos.value:product::string 						as product,
    		pos.value:quantity::number(19, 6)				as quantity,
    		pos.value:realizedPnL::number(19, 6)			as realized_pnl,
    		pos.value:secIdSrc::string						as sec_id_src,
    		pos.value:sector::string						as sector,
    		pos.value:securityId::string 					as security_id,
    		pos.value:sleeveId::string 						as sleeve_id,
    		pos.value:sleevePercent::number(19, 6) 			as sleeve_percent,
    		pos.value:sleeveType::string 					as sleeve_type,
    		pos.value:totalPnL::number(19, 6) 				as total_pnl,
    		pos.value:unrealizedPnL::number(19, 6) 			as unrealized_pnl,
    		pos.value:unsupervised::boolean					as unsupervised,
            c.record_date,
            c.record_datetime
from {{ source('copilot', 'copilot_positions') }} c,
    lateral flatten(input => c.VARIANT_DATA, path => 'all_positions') p,
    lateral flatten(input => p.VALUE, path => 'positions') pos