select
    clientid
  , advisorid
  , clientname
  , firstname
  , lastname
  , gender
  , maritalstatus
  , citizenship
  , companyname
  , spousefirstname
  , spouselastname
  , address1
  , address2
  , city
  , stateorprovince
  , postalcode
  , homephone
  , businessphone
  , cellphone
  , spousecellphone
  , spousebusinessphone
  , fax
  , email
  , spouseemail
  , empname
  , empaddress1
  , empaddress2
  , empcity
  , empstate
  , emppostalcode
  , empbusinessfax
  , empemailaddress
  , empjobtitle
  , empyearsemployed
  , empprevempname
  , empprevjobtitle
  , empprevempyearsemployed
  , spouseempname
  , spouseempaddress1
  , spouseempaddress2
  , spouseempcity
  , spouseempstate
  , spouseemppostalcode
  , spouseempbusinessfax
  , spouseempemailaddress
  , spouseempjobtitle
  , spouseempyearsemployed
  , spouseempprevempname
  , spouseempprevjobtitle
  , spouseempprevempyearsemployed
  , userrole
  , userroleint
  , entitlements
  , createtimestamp
  , deletetimestamp
  , filename
  , accountid
  , effective_date
  , record_datetime
  , record_date
  , {{ col_is_head(reference=source('emoney_mwa', 'emoney_mwa_clients'), reference_date_col='record_datetime', source_date_col='record_datetime') }}
from {{ source('emoney_mwa', 'emoney_mwa_clients') }}