select
    json:ID :: text                                                                          as id
  , json:USERNAME :: text                                                                    as username
  , json:LAST_NAME :: text                                                                   as last_name
  , json:FIRST_NAME :: text                                                                  as first_name
  , json:NAME :: text                                                                        as name
  , json:COMPANY_NAME :: text                                                                as company_name
  , json:DIVISION :: text                                                                    as division
  , json:DEPARTMENT :: text                                                                  as department
  , json:TITLE :: text                                                                       as title
  , json:STREET :: text                                                                      as street
  , json:CITY :: text                                                                        as city
  , json:STATE :: text                                                                       as state
  , json:POSTAL_CODE :: text                                                                 as postal_code
  , json:COUNTRY :: text                                                                     as country
  , json:STATE_CODE :: text                                                                  as state_code
  , json:COUNTRY_CODE :: text                                                                as country_code
  , json:LATITUDE :: float                                                                   as latitude
  , json:LONGITUDE :: float                                                                  as longitude
  , json:GEOCODE_ACCURACY :: text                                                            as geocode_accuracy
  , json:EMAIL :: text                                                                       as email
  , json:EMAIL_PREFERENCES_AUTO_BCC :: boolean                                               as email_preferences_auto_bcc
  , json:EMAIL_PREFERENCES_AUTO_BCC_STAY_IN_TOUCH :: boolean                                 as email_preferences_auto_bcc_stay_in_touch
  , json:EMAIL_PREFERENCES_STAY_IN_TOUCH_REMINDER :: boolean                                 as email_preferences_stay_in_touch_reminder
  , json:SENDER_EMAIL :: text                                                                as sender_email
  , json:SENDER_NAME :: text                                                                 as sender_name
  , json:SIGNATURE :: text                                                                   as signature
  , json:STAY_IN_TOUCH_SUBJECT :: text                                                       as stay_in_touch_subject
  , json:STAY_IN_TOUCH_SIGNATURE :: text                                                     as stay_in_touch_signature
  , json:STAY_IN_TOUCH_NOTE :: text                                                          as stay_in_touch_note
  , json:PHONE :: text                                                                       as phone
  , json:FAX :: text                                                                         as fax
  , json:MOBILE_PHONE :: text                                                                as mobile_phone
  , json:ALIAS :: text                                                                       as alias
  , json:COMMUNITY_NICKNAME :: text                                                          as community_nickname
  , json:BADGE_TEXT :: text                                                                  as badge_text
  , json:IS_ACTIVE :: boolean                                                                as is_active
  , json:TIME_ZONE_SID_KEY :: text                                                           as time_zone_sid_key
  , json:LOCALE_SID_KEY :: text                                                              as locale_sid_key
  , json:RECEIVES_INFO_EMAILS :: boolean                                                     as receives_info_emails
  , json:RECEIVES_ADMIN_INFO_EMAILS :: boolean                                               as receives_admin_info_emails
  , json:EMAIL_ENCODING_KEY :: text                                                          as email_encoding_key
  , json:USER_TYPE :: text                                                                   as user_type
  , json:LANGUAGE_LOCALE_KEY :: text                                                         as language_locale_key
  , json:EMPLOYEE_NUMBER :: text                                                             as employee_number
  , json:DELEGATED_APPROVER_ID :: text                                                       as delegated_approver_id
  , json:MANAGER_ID :: text                                                                  as manager_id
  , json:LAST_LOGIN_DATE :: timestamp_tz                                                     as last_login_date
  , json:CREATED_DATE :: timestamp_tz                                                        as created_date
  , json:CREATED_BY_ID :: text                                                               as created_by_id
  , json:LAST_MODIFIED_DATE :: timestamp_tz                                                  as last_modified_date
  , json:LAST_MODIFIED_BY_ID :: text                                                         as last_modified_by_id
  , json:SYSTEM_MODSTAMP :: timestamp_tz                                                     as system_modstamp
  , json:OFFLINE_TRIAL_EXPIRATION_DATE :: timestamp_tz                                       as offline_trial_expiration_date
  , json:OFFLINE_PDA_TRIAL_EXPIRATION_DATE :: timestamp_tz                                   as offline_pda_trial_expiration_date
  , json:USER_PERMISSIONS_MARKETING_USER :: boolean                                          as user_permissions_marketing_user
  , json:USER_PERMISSIONS_OFFLINE_USER :: boolean                                            as user_permissions_offline_user
  , json:USER_PERMISSIONS_AVANTGO_USER :: boolean                                            as user_permissions_avantgo_user
  , json:USER_PERMISSIONS_CALL_CENTER_AUTO_LOGIN :: boolean                                  as user_permissions_call_center_auto_login
  , json:USER_PERMISSIONS_SFCONTENT_USER :: boolean                                          as user_permissions_sfcontent_user
  , json:USER_PERMISSIONS_INTERACTION_USER :: boolean                                        as user_permissions_interaction_user
  , json:USER_PERMISSIONS_SUPPORT_USER :: boolean                                            as user_permissions_support_user
  , json:FORECAST_ENABLED :: boolean                                                         as forecast_enabled
  , json:USER_PREFERENCES_ACTIVITY_REMINDERS_POPUP :: boolean                                as user_preferences_activity_reminders_popup
  , json:USER_PREFERENCES_EVENT_REMINDERS_CHECKBOX_DEFAULT :: boolean                        as user_preferences_event_reminders_checkbox_default
  , json:USER_PREFERENCES_TASK_REMINDERS_CHECKBOX_DEFAULT :: boolean                         as user_preferences_task_reminders_checkbox_default
  , json:USER_PREFERENCES_REMINDER_SOUND_OFF :: boolean                                      as user_preferences_reminder_sound_off
  , json:USER_PREFERENCES_DISABLE_ALL_FEEDS_EMAIL :: boolean                                 as user_preferences_disable_all_feeds_email
  , json:USER_PREFERENCES_DISABLE_FOLLOWERS_EMAIL :: boolean                                 as user_preferences_disable_followers_email
  , json:USER_PREFERENCES_DISABLE_PROFILE_POST_EMAIL :: boolean                              as user_preferences_disable_profile_post_email
  , json:USER_PREFERENCES_DISABLE_CHANGE_COMMENT_EMAIL :: boolean                            as user_preferences_disable_change_comment_email
  , json:USER_PREFERENCES_DISABLE_LATER_COMMENT_EMAIL :: boolean                             as user_preferences_disable_later_comment_email
  , json:USER_PREFERENCES_DIS_PROF_POST_COMMENT_EMAIL :: boolean                             as user_preferences_dis_prof_post_comment_email
  , json:USER_PREFERENCES_HIDE_CSNGET_CHATTER_MOBILE_TASK :: boolean                         as user_preferences_hide_csnget_chatter_mobile_task
  , json:USER_PREFERENCES_DISABLE_MENTIONS_POST_EMAIL :: boolean                             as user_preferences_disable_mentions_post_email
  , json:USER_PREFERENCES_DIS_MENTIONS_COMMENT_EMAIL :: boolean                              as user_preferences_dis_mentions_comment_email
  , json:USER_PREFERENCES_HIDE_CSNDESKTOP_TASK :: boolean                                    as user_preferences_hide_csndesktop_task
  , json:USER_PREFERENCES_HIDE_CHATTER_ONBOARDING_SPLASH :: boolean                          as user_preferences_hide_chatter_onboarding_splash
  , json:USER_PREFERENCES_HIDE_SECOND_CHATTER_ONBOARDING_SPLASH :: boolean                   as user_preferences_hide_second_chatter_onboarding_splash
  , json:USER_PREFERENCES_DIS_COMMENT_AFTER_LIKE_EMAIL :: boolean                            as user_preferences_dis_comment_after_like_email
  , json:USER_PREFERENCES_DISABLE_LIKE_EMAIL :: boolean                                      as user_preferences_disable_like_email
  , json:USER_PREFERENCES_SORT_FEED_BY_COMMENT :: boolean                                    as user_preferences_sort_feed_by_comment
  , json:USER_PREFERENCES_DISABLE_MESSAGE_EMAIL :: boolean                                   as user_preferences_disable_message_email
  , json:USER_PREFERENCES_DISABLE_BOOKMARK_EMAIL :: boolean                                  as user_preferences_disable_bookmark_email
  , json:USER_PREFERENCES_DISABLE_SHARE_POST_EMAIL :: boolean                                as user_preferences_disable_share_post_email
  , json:USER_PREFERENCES_ENABLE_AUTO_SUB_FOR_FEEDS :: boolean                               as user_preferences_enable_auto_sub_for_feeds
  , json:USER_PREFERENCES_DISABLE_FILE_SHARE_NOTIFICATIONS_FOR_API :: boolean                as user_preferences_disable_file_share_notifications_for_api
  , json:USER_PREFERENCES_SHOW_TITLE_TO_EXTERNAL_USERS :: boolean                            as user_preferences_show_title_to_external_users
  , json:USER_PREFERENCES_SHOW_MANAGER_TO_EXTERNAL_USERS :: boolean                          as user_preferences_show_manager_to_external_users
  , json:USER_PREFERENCES_SHOW_EMAIL_TO_EXTERNAL_USERS :: boolean                            as user_preferences_show_email_to_external_users
  , json:USER_PREFERENCES_SHOW_WORK_PHONE_TO_EXTERNAL_USERS :: boolean                       as user_preferences_show_work_phone_to_external_users
  , json:USER_PREFERENCES_SHOW_MOBILE_PHONE_TO_EXTERNAL_USERS :: boolean                     as user_preferences_show_mobile_phone_to_external_users
  , json:USER_PREFERENCES_SHOW_FAX_TO_EXTERNAL_USERS :: boolean                              as user_preferences_show_fax_to_external_users
  , json:USER_PREFERENCES_SHOW_STREET_ADDRESS_TO_EXTERNAL_USERS :: boolean                   as user_preferences_show_street_address_to_external_users
  , json:USER_PREFERENCES_SHOW_CITY_TO_EXTERNAL_USERS :: boolean                             as user_preferences_show_city_to_external_users
  , json:USER_PREFERENCES_SHOW_STATE_TO_EXTERNAL_USERS :: boolean                            as user_preferences_show_state_to_external_users
  , json:USER_PREFERENCES_SHOW_POSTAL_CODE_TO_EXTERNAL_USERS :: boolean                      as user_preferences_show_postal_code_to_external_users
  , json:USER_PREFERENCES_SHOW_COUNTRY_TO_EXTERNAL_USERS :: boolean                          as user_preferences_show_country_to_external_users
  , json:USER_PREFERENCES_SHOW_PROFILE_PIC_TO_GUEST_USERS :: boolean                         as user_preferences_show_profile_pic_to_guest_users
  , json:USER_PREFERENCES_SHOW_TITLE_TO_GUEST_USERS :: boolean                               as user_preferences_show_title_to_guest_users
  , json:USER_PREFERENCES_SHOW_CITY_TO_GUEST_USERS :: boolean                                as user_preferences_show_city_to_guest_users
  , json:USER_PREFERENCES_SHOW_STATE_TO_GUEST_USERS :: boolean                               as user_preferences_show_state_to_guest_users
  , json:USER_PREFERENCES_SHOW_POSTAL_CODE_TO_GUEST_USERS :: boolean                         as user_preferences_show_postal_code_to_guest_users
  , json:USER_PREFERENCES_SHOW_COUNTRY_TO_GUEST_USERS :: boolean                             as user_preferences_show_country_to_guest_users
  , json:USER_PREFERENCES_SHOW_FORECASTING_CHANGE_SIGNALS :: boolean                         as user_preferences_show_forecasting_change_signals
  , json:USER_PREFERENCES_LIVE_AGENT_MIAW_SETUP_DEFLECTION :: boolean                        as user_preferences_live_agent_miaw_setup_deflection
  , json:USER_PREFERENCES_HIDE_S_1_BROWSER_UI :: boolean                                     as user_preferences_hide_s_1_browser_ui
  , json:USER_PREFERENCES_DISABLE_ENDORSEMENT_EMAIL :: boolean                               as user_preferences_disable_endorsement_email
  , json:USER_PREFERENCES_PATH_ASSISTANT_COLLAPSED :: boolean                                as user_preferences_path_assistant_collapsed
  , json:USER_PREFERENCES_CACHE_DIAGNOSTICS :: boolean                                       as user_preferences_cache_diagnostics
  , json:USER_PREFERENCES_SHOW_EMAIL_TO_GUEST_USERS :: boolean                               as user_preferences_show_email_to_guest_users
  , json:USER_PREFERENCES_SHOW_MANAGER_TO_GUEST_USERS :: boolean                             as user_preferences_show_manager_to_guest_users
  , json:USER_PREFERENCES_SHOW_WORK_PHONE_TO_GUEST_USERS :: boolean                          as user_preferences_show_work_phone_to_guest_users
  , json:USER_PREFERENCES_SHOW_MOBILE_PHONE_TO_GUEST_USERS :: boolean                        as user_preferences_show_mobile_phone_to_guest_users
  , json:USER_PREFERENCES_SHOW_FAX_TO_GUEST_USERS :: boolean                                 as user_preferences_show_fax_to_guest_users
  , json:USER_PREFERENCES_SHOW_STREET_ADDRESS_TO_GUEST_USERS :: boolean                      as user_preferences_show_street_address_to_guest_users
  , json:USER_PREFERENCES_LIGHTNING_EXPERIENCE_PREFERRED :: boolean                          as user_preferences_lightning_experience_preferred
  , json:USER_PREFERENCES_HIDE_END_USER_ONBOARDING_ASSISTANT_MODAL :: boolean                as user_preferences_hide_end_user_onboarding_assistant_modal
  , json:USER_PREFERENCES_HIDE_LIGHTNING_MIGRATION_MODAL :: boolean                          as user_preferences_hide_lightning_migration_modal
  , json:USER_PREFERENCES_HIDE_SFX_WELCOME_MAT :: boolean                                    as user_preferences_hide_sfx_welcome_mat
  , json:USER_PREFERENCES_HIDE_BIGGER_PHOTO_CALLOUT :: boolean                               as user_preferences_hide_bigger_photo_callout
  , json:USER_PREFERENCES_GLOBAL_NAV_BAR_WTSHOWN :: boolean                                  as user_preferences_global_nav_bar_wtshown
  , json:USER_PREFERENCES_GLOBAL_NAV_GRID_MENU_WTSHOWN :: boolean                            as user_preferences_global_nav_grid_menu_wtshown
  , json:USER_PREFERENCES_CREATE_LEXAPPS_WTSHOWN :: boolean                                  as user_preferences_create_lexapps_wtshown
  , json:USER_PREFERENCES_FAVORITES_WTSHOWN :: boolean                                       as user_preferences_favorites_wtshown
  , json:USER_PREFERENCES_RECORD_HOME_SECTION_COLLAPSE_WTSHOWN :: boolean                    as user_preferences_record_home_section_collapse_wtshown
  , json:USER_PREFERENCES_RECORD_HOME_RESERVED_WTSHOWN :: boolean                            as user_preferences_record_home_reserved_wtshown
  , json:USER_PREFERENCES_FAVORITES_SHOW_TOP_FAVORITES :: boolean                            as user_preferences_favorites_show_top_favorites
  , json:USER_PREFERENCES_EXCLUDE_MAIL_APP_ATTACHMENTS :: boolean                            as user_preferences_exclude_mail_app_attachments
  , json:USER_PREFERENCES_SUPPRESS_TASK_SFXREMINDERS :: boolean                              as user_preferences_suppress_task_sfxreminders
  , json:USER_PREFERENCES_SUPPRESS_EVENT_SFXREMINDERS :: boolean                             as user_preferences_suppress_event_sfxreminders
  , json:USER_PREFERENCES_PREVIEW_CUSTOM_THEME :: boolean                                    as user_preferences_preview_custom_theme
  , json:USER_PREFERENCES_HAS_CELEBRATION_BADGE :: boolean                                   as user_preferences_has_celebration_badge
  , json:USER_PREFERENCES_USER_DEBUG_MODE_PREF :: boolean                                    as user_preferences_user_debug_mode_pref
  , json:USER_PREFERENCES_SRHOVERRIDE_ACTIVITIES :: boolean                                  as user_preferences_srhoverride_activities
  , json:USER_PREFERENCES_HAS_SENT_WARNING_EMAIL :: boolean                                  as user_preferences_has_sent_warning_email
  , json:USER_PREFERENCES_HAS_SENT_WARNING_EMAIL_238 :: boolean                              as user_preferences_has_sent_warning_email_238
  , json:USER_PREFERENCES_HAS_SENT_WARNING_EMAIL_240 :: boolean                              as user_preferences_has_sent_warning_email_240
  , json:USER_PREFERENCES_HIDE_BROWSE_PRODUCT_REDIRECT_CONFIRMATION :: boolean               as user_preferences_hide_browse_product_redirect_confirmation
  , json:USER_PREFERENCES_HIDE_ONLINE_SALES_APP_TAB_VISIBILITY_REQUIREMENTS_MODAL :: boolean as user_preferences_hide_online_sales_app_tab_visibility_requirements_modal
  , json:USER_PREFERENCES_HIDE_ONLINE_SALES_APP_WELCOME_MAT :: boolean                       as user_preferences_hide_online_sales_app_welcome_mat
  , json:USER_PREFERENCES_SHOW_FORECASTING_ROUNDED_AMOUNTS :: boolean                        as user_preferences_show_forecasting_rounded_amounts
  , json:CALL_CENTER_ID :: text                                                              as call_center_id
  , json:EXTENSION :: text                                                                   as extension
  , json:FEDERATION_IDENTIFIER :: text                                                       as federation_identifier
  , json:ABOUT_ME :: text                                                                    as about_me
  , json:FULL_PHOTO_URL :: text                                                              as full_photo_url
  , json:SMALL_PHOTO_URL :: text                                                             as small_photo_url
  , json:IS_EXT_INDICATOR_VISIBLE :: boolean                                                 as is_ext_indicator_visible
  , json:OUT_OF_OFFICE_MESSAGE :: text                                                       as out_of_office_message
  , json:MEDIUM_PHOTO_URL :: text                                                            as medium_photo_url
  , json:DIGEST_FREQUENCY :: text                                                            as digest_frequency
  , json:DEFAULT_GROUP_NOTIFICATION_FREQUENCY :: text                                        as default_group_notification_frequency
  , json:LAST_VIEWED_DATE :: timestamp_tz                                                    as last_viewed_date
  , json:LAST_REFERENCED_DATE :: timestamp_tz                                                as last_referenced_date
  , json:BANNER_PHOTO_URL :: text                                                            as banner_photo_url
  , json:SMALL_BANNER_PHOTO_URL :: text                                                      as small_banner_photo_url
  , json:MEDIUM_BANNER_PHOTO_URL :: text                                                     as medium_banner_photo_url
  , json:IS_PROFILE_PHOTO_ACTIVE :: boolean                                                  as is_profile_photo_active
  , json:_FIVETRAN_DELETED :: boolean                                                        as _fivetran_deleted
  , json:_FIVETRAN_SYNCED :: timestamp_tz                                                    as _fivetran_synced
  , json:CONTACT_ID :: text                                                                  as contact_id
  , json:PRACTIFI_MGP_CLIENT_ID_C :: text                                                    as practifi_mgp_client_id_c
  , json:PRACTIFI_QUIK_FORM_FIELDS_DATA_JSON_C :: text                                       as practifi_quik_form_fields_data_json_c
  , json:PRACTIFI_ENVESTNET_USERNAME_C :: text                                               as practifi_envestnet_username_c
  , json:PRACTIFI_ENVESTNET_PROPOSAL_HANDLE_C :: text                                        as practifi_envestnet_proposal_handle_c
  , json:PRACTIFI_SEND_EMAILS_WHEN_ASSIGNED_WORKFLOW_TASKS_C :: boolean                      as practifi_send_emails_when_assigned_workflow_tasks_c
  , json:PRACTIFI_DIVISION_ID_C :: text                                                      as practifi_division_id_c
  , json:PRACTIFI_ACCEPTED_TERMS_AND_CONDITIONS_VERSION_C :: text                            as practifi_accepted_terms_and_conditions_version_c
  , json:PRACTIFI_DISABLE_LOOKUP_FILTERS_C :: boolean                                        as practifi_disable_lookup_filters_c
  , json:USER_PREFERENCES_APEX_PAGES_DEVELOPER_MODE :: boolean                               as user_preferences_apex_pages_developer_mode
  , json:PRACTIFI_QUIK_CONTACT_ID_LIST_C :: text                                             as practifi_quik_contact_id_list_c
  , json:INDIVIDUAL_ID :: text                                                               as individual_id
  , json:USER_ROLE_ID :: text                                                                as user_role_id
  , json:ACCOUNT_ID :: text                                                                  as account_id
  , json:USER_PREFERENCES_RECEIVE_NOTIFICATIONS_AS_DELEGATED_APPROVER :: boolean             as user_preferences_receive_notifications_as_delegated_approver
  , json:PRACTIFI_EXTERNAL_ID_C :: text                                                      as practifi_external_id_c
  , json:PROFILE_ID :: text                                                                  as profile_id
  , json:USER_PREFERENCES_RECEIVE_NO_NOTIFICATIONS_AS_APPROVER :: boolean                    as user_preferences_receive_no_notifications_as_approver
  , json:PRACTIFI_PERSHING_RR_CODE_C :: text                                                 as practifi_pershing_rr_code_c
  , json:PRACTIFI_DIVISION_NAME_C :: text                                                    as practifi_division_name_c
  , json:USER_PREFERENCES_ASSISTIVE_ACTIONS_ENABLED_IN_ACTION_LAUNCHER :: boolean            as user_preferences_assistive_actions_enabled_in_action_launcher
  , json:USER_PREFERENCES_ACTION_LAUNCHER_EINSTEIN_GPT_CONSENT :: boolean                    as user_preferences_action_launcher_einstein_gpt_consent
  , 'salesforce'::text                                                                       as system_name
  , 'igo'::text                                                                              as system_instance
  , system_name || '__' || system_instance                                                   as system_key
  , effective_at                                                                             as effective_at
  , _created_at                                                                              as _created_at
  , {{ col_is_head(
      reference=source('salesforce_igo', 'user'),
      source_date_col='effective_at',
      reference_date_col='effective_at'
      ) }}
from {{ source('salesforce_igo', 'user') }}
