select   
    nullif(json:"_acl"::text , '')::variant                                                  as _acl
    , nullif(json:"_module"::text , '')::text                                                as _module
    , nullif(json:"ab_testing_subject_lines_c"::text , '')::text                             as ab_testing_subject_lines_c
    , nullif(json:"access_to_quickbooks"::text , '')::text                                   as access_to_quickbooks
    , nullif(json:"account_id_c"::text , '')::text                                           as account_id_c
    , nullif(json:"accounts_scrm_campaigns_c1"::text , '')::variant                          as accounts_scrm_campaigns_c1
    , nullif(json:"accounts_scrm_campaigns_c1_name"::text , '')::text                        as accounts_scrm_campaigns_c1_name
    , nullif(json:"accounts_scrm_campaigns_c1accounts_ida"::text , '')::text                 as accounts_scrm_campaigns_c1accounts_ida
    , nullif(json:"accounts_scrm_campaigns_c2"::text , '')::variant                          as accounts_scrm_campaigns_c2
    , nullif(json:"accounts_scrm_campaigns_c2_name"::text , '')::text                        as accounts_scrm_campaigns_c2_name
    , nullif(json:"accounts_scrm_campaigns_c2accounts_ida"::text , '')::text                 as accounts_scrm_campaigns_c2accounts_ida
    , nullif(json:"active_books_c"::text , '')::int                                          as active_books_c
    , nullif(json:"actual_closing_date"::text , '')::date                                    as actual_closing_date
    , nullif(json:"actual_fee"::text , '')::decimal(20 , 6)                                  as actual_fee
    , nullif(json:"actual_value"::text , '')::decimal(20 , 6)                                as actual_value
    , try_to_boolean(nullif(json:"adsites_c"::text , ''))::boolean                           as adsites_c
    , nullif(json:"analyst"::text , '')::text                                                as analyst
    , nullif(json:"anticipated_rmkt_date"::text , '')::text                                  as anticipated_rmkt_date
    , nullif(json:"any_special_indemnity_or_other_comments"::text , '')::text                as any_special_indemnity_or_other_comments
    , nullif(json:"assigned_user_id"::text , '')::text                                       as assigned_user_id
    , nullif(json:"assigned_user_link"::text , '')::variant                                  as assigned_user_link
    , nullif(json:"assigned_user_name"::text , '')::text                                     as assigned_user_name
    , nullif(json:"base_rate"::text , '')::decimal(20 , 6)                                   as base_rate
    , nullif(json:"benchmark_date_c"::text , '')::text                                       as benchmark_date_c
    , nullif(json:"bid_form"::text , '')::text                                               as bid_form
    , nullif(json:"bids_current_campaign_c"::text , '')::int                                 as bids_current_campaign_c
    , nullif(json:"bids_due_ext_pd"::text , '')::date                                        as bids_due_ext_pd
    , nullif(json:"bids_prior_campaigns_c"::text , '')::int                                  as bids_prior_campaigns_c
    , nullif(json:"book_bid_count_c"::text , '')::int                                        as book_bid_count_c
    , nullif(json:"book_buyer_count_c"::text , '')::int                                      as book_buyer_count_c
    , nullif(json:"book_closing_date"::text , '')::date                                      as book_closing_date
    , nullif(json:"book_count_c"::text , '')::int                                            as book_count_c
    , nullif(json:"book_draft_to_client"::text , '')::date                                   as book_draft_to_client
    , nullif(json:"book_loi_count_c"::text , '')::int                                        as book_loi_count_c
    , nullif(json:"book_loi_executed_count_c"::text , '')::int                               as book_loi_executed_count_c
    , nullif(json:"book_loi_nonex_exec_count_c"::text , '')::int                             as book_loi_nonex_exec_count_c
    , nullif(json:"book_mm_count_c"::text , '')::int                                         as book_mm_count_c
    , nullif(json:"book_pass_count_c"::text , '')::int                                       as book_pass_count_c
    , nullif(json:"book_priors_c"::text , '')::int                                           as book_priors_c
    , nullif(json:"book_status"::text , '')::text                                            as book_status
    , nullif(json:"book_unresponsive_count_c"::text , '')::int                               as book_unresponsive_count_c
    , nullif(json:"book_writer"::text , '')::text                                            as book_writer
    , nullif(json:"books_bids_pctg_c"::text , '')::int                                       as books_bids_pctg_c
    , nullif(json:"books_current_campaign_c"::text , '')::int                                as books_current_campaign_c
    , nullif(json:"books_prior_campaigns_c"::text , '')::int                                 as books_prior_campaigns_c
    , nullif(json:"books_with_bids"::text , '')::int                                         as books_with_bids
    , nullif(json:"business_writer_email_c"::text , '')::text                                as business_writer_email_c
    , nullif(json:"buyer_country"::text , '')::text                                          as buyer_country
    , try_to_boolean(nullif(json:"buyer_true_or_false_c"::text , ''))::boolean               as buyer_true_or_false_c
    , nullif(json:"bw_active_c"::text , '')::text                                            as bw_active_c
    , nullif(json:"bw_complete_c"::text , '')::int                                           as bw_complete_c
    , nullif(json:"bw_team_lead_c"::text , '')::text                                         as bw_team_lead_c
    , nullif(json:"campaign_create_date"::text , '')::date                                   as campaign_create_date
    , nullif(json:"campaign_ultimate_buyer"::text , '')::text                                as campaign_ultimate_buyer
    , nullif(json:"cash_at_close"::text , '')::decimal(20 , 6)                               as cash_at_close
    , nullif(json:"cash_at_close_percent"::text , '')::int                                   as cash_at_close_percent
    , try_to_boolean(nullif(json:"cim_1st_draft_client_feedback"::text , ''))::boolean       as cim_1st_draft_client_feedback
    , nullif(json:"cim_1st_draft_complete_c"::text , '')::int                                as cim_1st_draft_complete_c
    , try_to_boolean(nullif(json:"cim_1st_draft_internal_review"::text , ''))::boolean       as cim_1st_draft_internal_review
    , try_to_boolean(nullif(json:"cim_client_sign_off"::text , ''))::boolean                 as cim_client_sign_off
    , try_to_boolean(nullif(json:"cim_competitor_slide_sent"::text , ''))::boolean           as cim_competitor_slide_sent
    , try_to_boolean(nullif(json:"cim_final_draft_completed"::text , ''))::boolean           as cim_final_draft_completed
    , try_to_boolean(nullif(json:"cim_final_draft_internal_review"::text , ''))::boolean     as cim_final_draft_internal_review
    , try_to_boolean(nullif(json:"cim_first_draft_complete_c"::text , ''))::boolean          as cim_first_draft_complete_c
    , nullif(json:"cim_forecast_ebitda"::text , '')::decimal(20 , 6)                         as cim_forecast_ebitda
    , nullif(json:"cim_forecast_revenue"::text , '')::decimal(20 , 6)                        as cim_forecast_revenue
    , try_to_boolean(nullif(json:"cim_tables_approved"::text , ''))::boolean                 as cim_tables_approved
    , try_to_boolean(nullif(json:"cim_tables_complete_c"::text , ''))::boolean               as cim_tables_complete_c
    , try_to_boolean(nullif(json:"cim_tables_sent"::text , ''))::boolean                     as cim_tables_sent
    , nullif(json:"client_acct_record"::text , '')::text                                     as client_acct_record
    , nullif(json:"client_egnyte_link_c"::text , '')::text                                   as client_egnyte_link_c
    , nullif(json:"client_financials_due"::text , '')::date                                  as client_financials_due
    , nullif(json:"client_mkting_materials_due"::text , '')::date                            as client_mkting_materials_due
    , nullif(json:"client_review_only_c"::text , '')::text                                   as client_review_only_c
    , nullif(json:"client_sign_off"::text , '')::date                                        as client_sign_off
    , nullif(json:"client_sign_off_fin"::text , '')::date                                    as client_sign_off_fin
    , nullif(json:"client_type"::text , '')::text                                            as client_type
    , nullif(json:"close_date_certainty_c"::text , '')::text                                 as close_date_certainty_c
    , try_to_boolean(nullif(json:"closed_within_exclusivity"::text , ''))::boolean           as closed_within_exclusivity
    , nullif(json:"closer"::text , '')::text                                                 as closer
    , nullif(json:"closing_deadline"::text , '')::date                                       as closing_deadline
    , nullif(json:"closing_team_oversight_c"::text , '')::text                               as closing_team_oversight_c
    , nullif(json:"code_name"::text , '')::text                                              as code_name
    , nullif(json:"contacts_scrm_campaigns_c1"::text , '')::variant                          as contacts_scrm_campaigns_c1
    , nullif(json:"contacts_scrm_campaigns_c1_name"::text , '')::text                        as contacts_scrm_campaigns_c1_name
    , nullif(json:"contacts_scrm_campaigns_c1contacts_ida"::text , '')::text                 as contacts_scrm_campaigns_c1contacts_ida
    , nullif(json:"contacts_scrm_campaigns_c2"::text , '')::variant                          as contacts_scrm_campaigns_c2
    , nullif(json:"contacts_scrm_campaigns_c2_name"::text , '')::text                        as contacts_scrm_campaigns_c2_name
    , nullif(json:"contacts_scrm_campaigns_c2contacts_ida"::text , '')::text                 as contacts_scrm_campaigns_c2contacts_ida
    , nullif(json:"contacts_scrm_campaigns_c3"::text , '')::variant                          as contacts_scrm_campaigns_c3
    , nullif(json:"contacts_scrm_campaigns_c3_name"::text , '')::text                        as contacts_scrm_campaigns_c3_name
    , nullif(json:"contacts_scrm_campaigns_c3contacts_ida"::text , '')::text                 as contacts_scrm_campaigns_c3contacts_ida
    , nullif(json:"contract_terminated_date"::text , '')::date                               as contract_terminated_date
    , nullif(json:"create_rmkt_c"::text , '')::text                                          as create_rmkt_c
    , nullif(json:"created_by"::text , '')::text                                             as created_by
    , nullif(json:"created_by_link"::text , '')::variant                                     as created_by_link
    , nullif(json:"created_by_name"::text , '')::text                                        as created_by_name
    , nullif(json:"currency"::text , '')::text                                               as currency
    , nullif(json:"currency_id"::text , '')::text                                            as currency_id
    , nullif(json:"current_active_books_c"::text , '')::int                                  as current_active_books_c
    , nullif(json:"current_bids_c"::text , '')::int                                          as current_bids_c
    , nullif(json:"current_books_c"::text , '')::int                                         as current_books_c
    , nullif(json:"current_books_with_bids"::text , '')::int                                 as current_books_with_bids
    , try_to_boolean(nullif(json:"databook_approved"::text , ''))::boolean                   as databook_approved
    , nullif(json:"databook_status"::text , '')::text                                        as databook_status
    , nullif(json:"date_entered"::text , '')::timestamp                                      as date_entered
    , nullif(json:"date_exclusivity_ends"::text , '')::date                                  as date_exclusivity_ends
    , nullif(json:"date_modified"::text , '')::timestamp                                     as date_modified
    , nullif(json:"date_of_engagement"::text , '')::date                                     as date_of_engagement
    , try_to_boolean(nullif(json:"day_1_call"::text , ''))::boolean                          as day_1_call
    , nullif(json:"day_1_call_date"::text , '')::date                                        as day_1_call_date
    , try_to_boolean(nullif(json:"day_2_call"::text , ''))::boolean                          as day_2_call
    , nullif(json:"day_2_call_date"::text , '')::date                                        as day_2_call_date
    , nullif(json:"day_prior_month_s_financials_close_c"::text , '')::int                    as day_prior_month_s_financials_close_c
    , nullif(json:"days_fm_engagement_to_clos_c"::text , '')::int                            as days_fm_engagement_to_clos_c
    , nullif(json:"days_from_bid_due_to_loi_signed_c"::text , '')::int                       as days_from_bid_due_to_loi_signed_c
    , nullif(json:"days_from_launch_to_loi_signed_c"::text , '')::int                        as days_from_launch_to_loi_signed_c
    , nullif(json:"days_left_in_exclusivity_c"::text , '')::int                              as days_left_in_exclusivity_c
    , nullif(json:"days_since_bids_due_c"::text , '')::int                                   as days_since_bids_due_c
    , nullif(json:"days_since_on_hold_c"::text , '')::int                                    as days_since_on_hold_c
    , nullif(json:"days_to_close_c"::text , '')::int                                         as days_to_close_c
    , nullif(json:"days_to_remarket_launch_c"::text , '')::int                               as days_to_remarket_launch_c
    , nullif(json:"dba"::text , '')::text                                                    as dba
    , nullif(json:"deal_multiple"::text , '')::text                                          as deal_multiple
    , nullif(json:"deal_multiple1"::text , '')::text                                         as deal_multiple1
    , try_to_boolean(nullif(json:"dealroom_training"::text , ''))::boolean                   as dealroom_training
    , nullif(json:"dealroom_training_date"::text , '')::date                                 as dealroom_training_date
    , nullif(json:"debt"::text , '')::decimal(20 , 6)                                        as debt
    , try_to_boolean(nullif(json:"deleted"::text , ''))::boolean                             as deleted
    , nullif(json:"description"::text , '')::text                                            as description
    , nullif(json:"description_1"::text , '')::text                                          as description_1
    , nullif(json:"digital_marketing_launcher_c"::text , '')::text                           as digital_marketing_launcher_c
    , try_to_boolean(nullif(json:"discuss_on_weekly_call"::text , ''))::boolean              as discuss_on_weekly_call
    , nullif(json:"dm_additional_comments_c"::text , '')::text                               as dm_additional_comments_c
    , try_to_boolean(nullif(json:"ebitda_adj_approved"::text , ''))::boolean                 as ebitda_adj_approved
    , try_to_boolean(nullif(json:"ebitda_adj_sent"::text , ''))::boolean                     as ebitda_adj_sent
    , nullif(json:"ebitda_at_close"::text , '')::decimal(20 , 6)                             as ebitda_at_close
    , nullif(json:"ebitda_margin"::text , '')::int                                           as ebitda_margin
    , nullif(json:"ebitda_multiple"::text , '')::int                                         as ebitda_multiple
    , nullif(json:"engagement_days_since_launch2_c"::text , '')::int                         as engagement_days_since_launch2_c
    , nullif(json:"engagement_days_since_launch_c"::text , '')::int                          as engagement_days_since_launch_c
    , nullif(json:"engagement_days_so_far_c"::text , '')::int                                as engagement_days_so_far_c
    , nullif(json:"engagement_total_days_c"::text , '')::int                                 as engagement_total_days_c
    , nullif(json:"equity_roll"::text , '')::decimal(20 , 6)                                 as equity_roll
    , nullif(json:"equity_roll_dollar"::text , '')::decimal(20 , 6)                          as equity_roll_dollar
    , nullif(json:"est_closing_date_from_launch"::text , '')::date                           as est_closing_date_from_launch
    , nullif(json:"fa_team_lead_c"::text , '')::text                                         as fa_team_lead_c
    , nullif(json:"fee_type_c"::text , '')::text                                             as fee_type_c
    , nullif(json:"fin_analyst_email_c"::text , '')::text                                    as fin_analyst_email_c
    , nullif(json:"fin_analyst_lead_email_c"::text , '')::text                               as fin_analyst_lead_email_c
    , nullif(json:"fin_performance_notes"::text , '')::text                                  as fin_performance_notes
    , nullif(json:"fin_source"::text , '')::text                                             as fin_source
    , nullif(json:"fin_update_eta"::text , '')::date                                         as fin_update_eta
    , nullif(json:"fin_update_priority_c"::text , '')::int                                   as fin_update_priority_c
    , nullif(json:"final_cim"::text , '')::text                                              as final_cim
    , nullif(json:"financial_status_comments"::text , '')::text                              as financial_status_comments
    , try_to_boolean(nullif(json:"financial_write_up_complete"::text , ''))::boolean         as financial_write_up_complete
    , nullif(json:"financials_last_updated"::text , '')::date                                as financials_last_updated
    , try_to_boolean(nullif(json:"financials_received_from_client"::text , ''))::boolean     as financials_received_from_client
    , nullif(json:"financials_status"::text , '')::text                                      as financials_status
    , nullif(json:"fiscal_year_ends"::text , '')::text                                       as fiscal_year_ends
    , try_to_boolean(nullif(json:"follow_up_call"::text , ''))::boolean                      as follow_up_call
    , nullif(json:"follow_up_call_date"::text , '')::date                                    as follow_up_call_date
    , try_to_boolean(nullif(json:"following"::text , ''))::boolean                           as following_c
    , try_to_boolean(nullif(json:"forecast_approved"::text , ''))::boolean                   as forecast_approved
    , try_to_boolean(nullif(json:"forecast_built"::text , ''))::boolean                      as forecast_built
    , nullif(json:"forecast_call_date"::text , '')::date                                     as forecast_call_date
    , try_to_boolean(nullif(json:"future_story_call"::text , ''))::boolean                   as future_story_call
    , nullif(json:"future_story_call_date"::text , '')::date                                 as future_story_call_date
    , nullif(json:"fy_end_date"::text , '')::date                                            as fy_end_date
    , nullif(json:"general_indemnity_cap"::text , '')::decimal(20 , 6)                       as general_indemnity_cap
    , nullif(json:"general_indemnity_cap_percent"::text , '')::int                           as general_indemnity_cap_percent
    , nullif(json:"id"::text , '')::text                                                     as id
    , nullif(json:"income_statement_needed"::text , '')::text                                as income_statement_needed
    , nullif(json:"indemnity_escrow"::text , '')::decimal(20 , 6)                            as indemnity_escrow
    , nullif(json:"indemnity_escrow_percent"::text , '')::int                                as indemnity_escrow_percent
    , nullif(json:"initial_end_of_exclusivity"::text , '')::date                             as initial_end_of_exclusivity
    , nullif(json:"iois_due"::text , '')::date                                               as iois_due
    , try_to_boolean(nullif(json:"isactive"::text, ''))::boolean                              as is_active
    , try_to_boolean(nullif(json:"kick_off_complete"::text , ''))::boolean                   as kick_off_complete
    , nullif(json:"kick_off_meeting"::text , '')::date                                       as kick_off_meeting
    , nullif(json:"kickoff_date_to_start_date_c"::text , '')::int                            as kickoff_date_to_start_date_c
    , nullif(json:"last_year_s_t3m_ebitda"::text , '')::decimal(20 , 6)                      as last_year_s_t3m_ebitda
    , nullif(json:"lastactivitydate"::text , '')::date                                       as lastactivitydate
    , nullif(json:"lawyer"::text , '')::text                                                 as lawyer
    , nullif(json:"likelihood_of_loi_signing"::text , '')::text                              as likelihood_of_loi_signing
    , nullif(json:"link_to_teaser"::text , '')::text                                         as link_to_teaser
    , try_to_boolean(nullif(json:"list_criteria_completed"::text , ''))::boolean             as list_criteria_completed
    , try_to_boolean(nullif(json:"list_criteria_discussion"::text , ''))::boolean            as list_criteria_discussion
    , try_to_boolean(nullif(json:"list_segmentation_complete"::text , ''))::boolean          as list_segmentation_complete
    , try_to_boolean(nullif(json:"list_sent_for_appending"::text , ''))::boolean             as list_sent_for_appending
    , nullif(json:"locked_fields"::text , '')::variant                                       as locked_fields
    , nullif(json:"loi_days_left_c"::text , '')::int                                         as loi_days_left_c
    , nullif(json:"loi_days_so_far_c"::text , '')::int                                       as loi_days_so_far_c
    , nullif(json:"loi_signed"::text , '')::date                                             as loi_signed
    , nullif(json:"loi_total_days_c"::text , '')::int                                        as loi_total_days_c
    , nullif(json:"lois_current_campaign_c"::text , '')::int                                 as lois_current_campaign_c
    , nullif(json:"lois_due"::text , '')::date                                               as lois_due
    , nullif(json:"lois_prior_campaign_c"::text , '')::int                                   as lois_prior_campaign_c
    , nullif(json:"main_marcom_contact"::text , '')::text                                    as main_marcom_contact
    , nullif(json:"marked_closed_date_c"::text , '')::date                                   as marked_closed_date_c
    , nullif(json:"marketing_associate"::text , '')::text                                    as marketing_associate
    , nullif(json:"marketing_associate_email"::text , '')::text                              as marketing_associate_email
    , nullif(json:"marketing_status_comments"::text , '')::text                              as marketing_status_comments
    , nullif(json:"marketing_video"::text , '')::text                                        as marketing_video
    , try_to_boolean(nullif(json:"marni_client_call"::text , ''))::boolean                   as marni_client_call
    , nullif(json:"mca_c"::text , '')::text                                                  as mca_c
    , nullif(json:"member_vett_in_use_c"::text , '')::int                                    as member_vett_in_use_c
    , nullif(json:"mm_videos"::text , '')::text                                              as mm_videos
    , nullif(json:"mms_current_campaign_c"::text , '')::int                                  as mms_current_campaign_c
    , nullif(json:"mms_prior_campaigns_c"::text , '')::int                                   as mms_prior_campaigns_c
    , nullif(json:"mmt_1st_day"::text , '')::date                                            as mmt_1st_day
    , nullif(json:"mmt_2nd_day_c"::text , '')::date                                          as mmt_2nd_day_c
    , nullif(json:"mmt_deck_status"::text , '')::text                                        as mmt_deck_status
    , try_to_boolean(nullif(json:"mmt_industry_research"::text , ''))::boolean               as mmt_industry_research
    , nullif(json:"mmt_schedule_status"::text , '')::text                                    as mmt_schedule_status
    , nullif(json:"modified_by_name"::text , '')::text                                       as modified_by_name
    , nullif(json:"modified_user_id"::text , '')::text                                       as modified_user_id
    , nullif(json:"modified_user_link"::text , '')::variant                                  as modified_user_link
    , nullif(json:"month_of_close"::text , '')::text                                         as month_of_close
    , try_to_boolean(nullif(json:"monthly_call_set"::text , ''))::boolean                    as monthly_call_set
    , try_to_boolean(nullif(json:"my_favorite"::text , ''))::boolean                         as my_favorite
    , nullif(json:"name"::text , '')::text                                                   as name
    , nullif(json:"name_1"::text , '')::text                                                 as name_1
    , try_to_boolean(nullif(json:"nda_approved_by_client"::text , ''))::boolean              as nda_approved_by_client
    , try_to_boolean(nullif(json:"nda_edited_by_client"::text , ''))::boolean                as nda_edited_by_client
    , nullif(json:"nda_link"::text , '')::text                                               as nda_link
    , nullif(json:"ndabuyerchangesreviewedby"::text , '')::text                              as ndabuyerchangesreviewedby
    , nullif(json:"ndas_received_c"::text , '')::int                                         as ndas_received_c
    , nullif(json:"next_contact_oh"::text , '')::date                                        as next_contact_oh
    , nullif(json:"no_of_times_retraded_c"::text , '')::int                                  as no_of_times_retraded_c
    , nullif(json:"numberofcontacts"::text , '')::int                                        as numberofcontacts
    , nullif(json:"numberofresponses"::text , '')::int                                       as numberofresponses
    , nullif(json:"nwc_escrow"::text , '')::decimal(20 , 6)                                  as nwc_escrow
    , nullif(json:"nwc_escrow_percent"::text , '')::int                                      as nwc_escrow_percent
    , nullif(json:"on_hold_date"::text , '')::date                                           as on_hold_date
    , try_to_boolean(nullif(json:"on_hold_fin_updates_req_d"::text , ''))::boolean           as on_hold_fin_updates_req_d
    , nullif(json:"other_consideration"::text , '')::decimal(20 , 6)                         as other_consideration
    , nullif(json:"peg_bookscount_c"::text , '')::int                                        as peg_bookscount_c
    , try_to_boolean(nullif(json:"post_kick_off_research_email"::text , ''))::boolean        as post_kick_off_research_email
    , nullif(json:"potential_concerns"::text , '')::text                                     as potential_concerns
    , nullif(json:"pre_launch_closers"::text , '')::text                                     as pre_launch_closers
    , try_to_boolean(nullif(json:"pre_launch_research_marketing_email"::text , ''))::boolean as pre_launch_research_marketing_email
    , nullif(json:"r_w_insurance"::text , '')::text                                          as r_w_insurance
    , try_to_boolean(nullif(json:"raw_data_received"::text , ''))::boolean                   as raw_data_received
    , nullif(json:"reason_deal_broke"::text , '')::variant                                   as reason_deal_broke
    , nullif(json:"reason_for_ted_talk_reshoot_c"::text , '')::text                          as reason_for_ted_talk_reshoot_c
    , nullif(json:"received_clien_sensitiveveto_del"::text , '')::text                       as received_clien_sensitiveveto_del
    , nullif(json:"received_client_request"::text , '')::text                                as received_client_request
    , nullif(json:"region"::text , '')::text                                                 as region
    , nullif(json:"remarket_1_c"::text , '')::int                                            as remarket_1_c
    , try_to_boolean(nullif(json:"renewed_marketing_materials_c"::text , ''))::boolean       as renewed_marketing_materials_c
    , nullif(json:"report_close_date_c"::text , '')::date                                    as report_close_date_c
    , nullif(json:"report_start_date_c"::text , '')::date                                    as report_start_date_c
    , nullif(json:"research_comments_c"::text , '')::text                                    as research_comments_c
    , nullif(json:"research_list_comments"::text , '')::text                                 as research_list_comments
    , try_to_boolean(nullif(json:"research_list_completed"::text , ''))::boolean             as research_list_completed
    , nullif(json:"research_list_status"::text , '')::text                                   as research_list_status
    , nullif(json:"researcher"::text , '')::text                                             as researcher
    , nullif(json:"researcher_email_c"::text , '')::text                                     as researcher_email_c
    , nullif(json:"retrade_date_c"::text , '')::date                                         as retrade_date_c
    , nullif(json:"retrade_end_date_c"::text , '')::date                                     as retrade_end_date_c
    , nullif(json:"revenue_at_close"::text , '')::decimal(20 , 6)                            as revenue_at_close
    , nullif(json:"rmkt_1_c"::text , '')::int                                                as rmkt_1_c
    , nullif(json:"rmkt_days_to_launch_c"::text , '')::int                                   as rmkt_days_to_launch_c
    , nullif(json:"rmkt_primary_contact"::text , '')::text                                   as rmkt_primary_contact
    , nullif(json:"sa_closer_email_c"::text , '')::text                                      as sa_closer_email_c
    , nullif(json:"scrm_campaigns_contacts_1"::text , '')::variant                           as scrm_campaigns_contacts_1
    , nullif(json:"scrm_campaigns_contacts_1_name"::text , '')::text                         as scrm_campaigns_contacts_1_name
    , nullif(json:"scrm_campaigns_contacts_1contacts_idb"::text , '')::text                  as scrm_campaigns_contacts_1contacts_idb
    , nullif(json:"scrm_campaigns_opportunities_1"::text , '')::variant                      as scrm_campaigns_opportunities_1
    , nullif(json:"scrm_campaigns_opportunities_1_name"::text , '')::text                    as scrm_campaigns_opportunities_1_name
    , nullif(json:"scrm_campaigns_opportunities_1opportunities_idb"::text , '')::text        as scrm_campaigns_opportunities_1opportunities_idb
    , nullif(json:"sector"::text , '')::text                                                 as sector
    , nullif(json:"segmentation_industries_c"::text , '')::text                              as segmentation_industries_c
    , nullif(json:"sf_created_at_c"::text , '')::timestamp                                   as sf_created_at_c
    , nullif(json:"sf_created_by_c"::text , '')::text                                        as sf_created_by_c
    , nullif(json:"sf_last_modified_at_c"::text , '')::timestamp                             as sf_last_modified_at_c
    , nullif(json:"sf_last_modified_by_c"::text , '')::text                                  as sf_last_modified_by_c
    , nullif(json:"sf_object_type_c"::text , '')::text                                       as sf_object_type_c
    , nullif(json:"special_campaign_notes"::text , '')::text                                 as special_campaign_notes
    , nullif(json:"special_indemnity_escrow"::text , '')::decimal(20 , 6)                    as special_indemnity_escrow
    , nullif(json:"special_indemnity_escrow_percent"::text , '')::int                        as special_indemnity_escrow_percent
    , nullif(json:"start_to_close_c"::text , '')::int                                        as start_to_close_c
    , nullif(json:"startdate"::text , '')::date                                              as startdate
    , nullif(json:"status"::text , '')::text                                                 as status
    , nullif(json:"stop_date"::text , '')::date                                              as stop_date
    , nullif(json:"strategic_books_c"::text , '')::int                                       as strategic_books_c
    , nullif(json:"sync_key"::text , '')::text                                               as sync_key
    , nullif(json:"t3m_ebitda"::text , '')::decimal(20 , 6)                                  as t3m_ebitda
    , nullif(json:"tag"::text , '')::variant                                                 as tag
    , nullif(json:"team_count_link"::text , '')::variant                                     as team_count_link
    , nullif(json:"team_name"::text , '')::variant                                           as team_name
    , try_to_boolean(nullif(json:"teaser_client_sign_off"::text , ''))::boolean              as teaser_client_sign_off
    , try_to_boolean(nullif(json:"teaser_draft"::text , ''))::boolean                        as teaser_draft
    , try_to_boolean(nullif(json:"teaser_internal_review"::text , ''))::boolean              as teaser_internal_review
    , nullif(json:"teaser_video_to_client"::text , '')::date                                 as teaser_video_to_client
    , nullif(json:"ted_talk"::text , '')::text                                               as ted_talk
    , nullif(json:"ted_talk_reshoot"::text , '')::text                                       as ted_talk_reshoot
    , nullif(json:"ted_talk_status"::text , '')::text                                        as ted_talk_status
    , nullif(json:"test_book_pass_count_c"::text , '')::int                                  as test_book_pass_count_c
    , nullif(json:"test_book_prior_bids_c"::text , '')::int                                  as test_book_prior_bids_c
    , nullif(json:"testimonial"::text , '')::text                                            as testimonial
    , nullif(json:"third_closer_email_c"::text , '')::text                                   as third_closer_email_c
    , nullif(json:"times_closing_deadline_changed_c"::text , '')::int                        as times_closing_deadline_changed_c
    , nullif(json:"times_loi_signed_date_changed_c"::text , '')::int                         as times_loi_signed_date_changed_c
    , nullif(json:"total_bids_c"::text , '')::int                                            as total_bids_c
    , nullif(json:"total_books_c"::text , '')::int                                           as total_books_c
    , nullif(json:"total_earnout"::text , '')::decimal(20 , 6)                               as total_earnout
    , nullif(json:"total_earnout_percent"::text , '')::int                                   as total_earnout_percent
    , nullif(json:"total_ev"::text , '')::decimal(20 , 6)                                    as total_ev
    , nullif(json:"total_lois_c"::text , '')::int                                            as total_lois_c
    , nullif(json:"total_lois_executed_c"::text , '')::int                                   as total_lois_executed_c
    , nullif(json:"total_mgmt_mtgs_c"::text , '')::int                                       as total_mgmt_mtgs_c
    , nullif(json:"total_prior_bids_c"::text , '')::int                                      as total_prior_bids_c
    , nullif(json:"total_seller_note"::text , '')::decimal(20 , 6)                           as total_seller_note
    , nullif(json:"total_seller_note_percent"::text , '')::int                               as total_seller_note_percent
    , nullif(json:"total_time_in_market_c"::text , '')::int                                  as total_time_in_market_c
    , nullif(json:"tradeshows_received_c"::text , '')::text                                  as tradeshows_received_c
    , nullif(json:"tt_video_date"::text , '')::date                                          as tt_video_date
    , nullif(json:"ttm_check_c"::text , '')::text                                            as ttm_check_c
    , nullif(json:"ttm_check_closing_deadline_c"::text , '')::text                           as ttm_check_closing_deadline_c
    , nullif(json:"ttm_check_start_date_c"::text , '')::text                                 as ttm_check_start_date_c
    , nullif(json:"ttm_ebitda"::text , '')::decimal(20 , 6)                                  as ttm_ebitda
    , nullif(json:"type"::text , '')::text                                                   as type
    , nullif(json:"under_loi_date"::text , '')::date                                         as under_loi_date
    , nullif(json:"underwriter_lead"::text , '')::text                                       as underwriter_lead
    , nullif(json:"us_closer_email_c"::text , '')::text                                      as us_closer_email_c
    , nullif(json:"us_region_c"::text , '')::text                                            as us_region_c
    , nullif(json:"uw_active_c"::text , '')::text                                            as uw_active_c
    , nullif(json:"uw_bw_priority_c"::text , '')::int                                        as uw_bw_priority_c
    , nullif(json:"uw_complete_new_c"::text , '')::int                                       as uw_complete_new_c
    , nullif(json:"uw_secondary"::text , '')::text                                           as uw_secondary
    , nullif(json:"vid_shoot_date"::text , '')::date                                         as vid_shoot_date
    , try_to_boolean(nullif(json:"video_client_feedback"::text , ''))::boolean               as video_client_feedback
    , try_to_boolean(nullif(json:"video_client_sign_off"::text , ''))::boolean               as video_client_sign_off
    , try_to_boolean(nullif(json:"video_shoot"::text , ''))::boolean                          as video_shoot
    , nullif(json:"website_sub_sector"::text , '')::variant                                  as website_sub_sector
    , nullif(json:"x3rd_closer_c"::text , '')::text                                          as x3rd_closer_c
    , nullif(json:"ytd_ebitda"::text , '')::decimal(20 , 6)                                  as ytd_ebitda
    , _created_at::timestamp                                                                 as _created_at
    , {{ col_is_head(reference=source('sugarcrm_woodbridge', 'campaigns')     
        , reference_date_col='_created_at'     
        , source_date_col='_created_at') }}     
from {{ source('sugarcrm_woodbridge', 'campaigns') }}     