{% macro create_ff_text_format() %}
CREATE FILE FORMAT IF NOT EXISTS {{target.schema}}.TEXT_FORMAT 
TYPE = 'CSV' 
FIELD_DELIMITER = NONE
SKIP_BLANK_LINES = TRUE
ESCAPE_UNENCLOSED_FIELD = NONE
;

GRANT USAGE ON FILE FORMAT {{target.schema}}.TEXT_FORMAT TO ROLE ENGINEERING;
GRANT USAGE ON FILE FORMAT {{target.schema}}.TEXT_FORMAT TO ROLE INTEGRATION_DM;
{% endmacro %}