select
    recordtype                     as record_type
  , custodianid                    as custodian_id
  , mstracctnumber                 as master_account_number
  , masteraccountname              as master_account_name
  , businessdate                   as business_date
  , accountid                      as account_number
  , accounttitle1                  as account_title_line_1
  , accounttitle2                  as account_title_line_2
  , accounttitle3                  as account_title_line_3
  , accountregis                   as account_registration
  , accounttype                    as account_type
  , prodcode                       as product_code
  , prodcatgcode                   as product_category_code
  , taxcode                        as tax_code
  , lyst                           as legacy_security_type
  , tickersymbol                   as ticker_symbol
  , industrytickersymbol           as industry_ticker_symbol
  , cusip                          as cusip
  , schwabsecnbr                   as schwab_security_number
  , itemissueid                    as item_issue_id
  , rulstsufid                     as rule_set_suffix_id
  , isin                           as isin
  , sedol                          as sedol
  , optionsdisplaysymbol           as options_display_symbol
  , underlyingtickersymbol         as underlying_ticker_symbol
  , underlyingindustrytickersymbol as underlying_industry_ticker_symbol
  , underlyingcusip                as underlying_cusip
  , underlyingschwabnmbr           as underlying_schwab_security_number
  , underlyingitmissid             as underlying_item_issue_id
  , unrulsufid                     as underlying_rule_set_suffix_id
  , underlyingisn                  as underlying_isin
  , underlyingsedol                as underlying_sedol
  , mnymkcode                      as money_market_code
  , trcd                           as transaction_type_code
  , sbcd                           as transaction_subtype_code
  , transactioncategory            as transaction_category
  , transrccde                     as transaction_source_code
  , transactionsourcecodedesc      as transaction_source_code_description
  , transactiondetaildescription   as transaction_detail_description
  , tradetypecd                    as action_code
  , tc                             as transaction_cancel_code
  , tradedate                      as trade_date
  , settlementdate                 as settlement_date
  , traddate                       as transaction_date
  , eddivdnddate                   as ex_dividend_date
  , quantity                       as quantity
  , price                          as price
  , grossamount                    as gross_amount
  , debitcredit                    as debit_credit_indicator
  , netamount                      as net_amount
  , commission                     as commission
  , exchangeprocessingfee          as exchange_processing_fee
  , brokerservicefee               as broker_service_fee
  , primebrokerfee                 as prime_broker_fee
  , tradeawayfee                   as trade_away_fee
  , redemptionfee                  as redemption_fee
  , otherfee                       as other_fee
  , federaltefrawithholding        as federal_tefra_withholding
  , statetaxwithholding            as state_tax_withholding
  , sttx                           as state_receiving_tax
  , accruedinterest                as accrued_interest
  , accountingrulecode             as accounting_rule_code
  , ordersrcd                      as order_source_code
  , ordernumber                    as order_number
  , tradeorderentrytimestamp       as trade_order_entry_time_stamp
  , tradeorderexecutiontimestamp   as trade_order_execution_time_stamp
  , brokercode                     as broker_code
  , brokername                     as broker_name
  , swbfromaccount                 as schwab_from_account
  , swbtoaccount                   as schwab_to_account
  , s1check                        as schwab1_check_number
  , si                             as sweep_indicator
  , stockexchg                     as stock_exchange_code
  , ie                             as inter_class_exchange_code
  , distributionrate               as distribution_rate
  , cashinlieushareqty             as cash_in_lieu_share_quantity
  , divintshareqty                 as dividend_interest_share_quantity
  , cashinlieurate                 as cash_in_lieu_rate
  , assetbackedfactor              as asset_backed_factor
  , srsy                           as source_system
  , jntp                           as journal_type
  , dm                             as deposit_media
  , cashieringid                   as schwab_cashiering_unique_identifier
  , recipmakername1                as recipient_maker_name_1
  , recipmakername2                as recipient_maker_name_2
  , recipmakername3                as recipient_maker_name_3
  , frequency                      as frequency
  , disbursechecknum               as disbursed_check_number
  , federalbankrefnum              as fed_reference_number
  , recipmakeracctnum              as fed_reference_number
  , bankaccttype                   as bank_account_type
  , banknamepart1                  as bank_name_part_1
  , banknamepart2                  as bank_name_part_2
  , bankaba                        as bank_aba_number
  , intermedname                   as intermediary_name
  , checkmemo1                     as transaction_check_memo_1
  , checkmemo2                     as transaction_check_memo_2
  , retfedincometax                as retirement_federal_income_tax
  , retstateinctax                 as retirement_state_income_tax
  , rttx                           as retirement_income_tax_state
  , pubtimestamp                   as publication_time_stamp
  , versmrkr1                      as version_marker_1
  , tipsfactor                     as tips_factor
  , closingprice                   as closing_price
  , versmrkr2                      as version_marker_2
  , transmemo                      as transaction_memo
  , versmrkr3                      as version_marker_3
  , closingpriceunfactored         as closing_price_unfactored
  , factor                         as factor
  , factordate                     as factor_date
  , 'mps'                          as firm_source
  , effective_date::date           as effective_date
  , {{ col_is_head(reference=source('schwab_mps', 'tax_lots')) }}
  , {{ col_is_current(date_col='effective_date') }}
  , record_datetime::timestamp     as record_datetime
  , record_date::date              as record_date
  , record_datetime::timestamp     as _source_loaded_at
from {{ source('schwab_mps', 'transactions') }}