
select 
    custodianid                                 as custodian_id
    ,masteraccountnumber::varchar(25)           as master_account_number
    ,masteraccountname                          as master_account_name
    ,businessdate::date                         as business_date
    ,accountid                                  as account_id
    ,accounttitleline1                          as account_title_line_1
    ,accounttitleline2                          as account_title_line_2
    ,accounttitleline3                          as account_title_line_3
    ,accountstatus                              as account_status
    ,accountregistration                        as account_registration
    ,accounttype                                as account_type
    ,taxpayertitle                              as tax_payer_title
    ,taxpayerfirstname                          as tax_payer_first_name
    ,taxpayermiddlename                         as tax_payer_middle_name
    ,taxpayerlastname                           as tax_payer_last_name
    ,taxpayersuffix                             as tax_payer_suffix
    ,taxwithholdcode                            as tax_withold_code
    ,primarycontact                             as primary_contact
    ,aliasname                                  as alias_name
    ,mailingaddressline1                        as mailing_address_line_1
    ,mailingaddressline2                        as mailing_address_line_2
    ,mailingaddressline3                        as mailing_address_line_3
    ,accountmailingcity                         as account_mailing_city
    ,accountmailingstate                        as account_mailing_state
    ,accountmailingzip                          as account_mailing_zip
    ,accountmailingcountrycode                  as account_mailing_country_code
    ,emailaddress                               as email_address
    ,phone                                      as phone
    ,businessphone                              as business_phone
    ,dateopened::date                           as date_opened
    ,schwabbranchcode                           as schwab_branch_code
    ,sweepstatuscode                            as sweep_status_code
    ,accountcashinstructionscash                as account_cash_instructions_cash
    ,accountcashinstructionsmargin              as account_cash_instructions_margin
    ,marginaccountindicator                     as margin_account_indicator
    ,accountrestrictions                        as account_restrictions
    ,additionalmailings                         as additional_mailing
    ,numberofadditionalmailings                 as number_of_additional_mailings
    ,approvedoptionlevel::int                   as approved_option_level
    ,beneficiaryonfile                          as beneficiary_on_file
    ,numberofbeneficiaries::int                 as number_of_beneficiaries
    ,paymentfeatureschecks                      as payment_features_checks
    ,paymentfeaturedebitcard                    as payment_feature_debit_card
    ,paymentfeaturesbillpay                     as payment_features_bill_pay
    ,undeliverablemailflag                      as undeliverable_mail_flag
    ,fafeestatus                                as fa_fee_status
    ,interestbearingfeaturecode                 as interest_bearing_feature_code
    ,interestbearingfeaturemoneymarketcode      as interest_Beraing_feature_money_market_code
    ,interestbearingfeaturetickersymbol         as interest_bearing_feature_ticker_symbol
    ,interestbearingfeatureitemissueid          as interest_bearing_feature_item_issue_id
    ,interestbearingfeaturerulesetsuffix        as interest_bearing_feature_rule_set_suffix
    ,proxyvotingauthority                       as proxy_voting_authority
    ,proxymailing                               as proxy_mailing
    ,statementpreferences                       as statement_preferences
    ,accounttaxableindicator                    as account_taxable_indicator
    ,defaultlotselectionmethod                  as default_lot_selection_method
    ,costmethod                                 as cost_method
    ,costbasismethodformutualfunds              as cost_basis_method_for_mutual_funds
    ,costbasismethodnonmutualfunds              as cost_basis_method_non_mutual_funds
    ,costbasismethoddate::date                  as cost_basis_method_date
    ,versionmarkernumber                        as version_marker_number
    ,customertype                               as customer_type
    ,organizationprimaryname                    as organization_primary_name
    ,restrictionreasoncode1                     as restriction_reason_code_1
    ,restrictionreasoncode2                     as restriction_reason_code_2
    ,restrictionreasoncode3                     as restriction_reason_code_3
    ,restrictionreasoncode4                     as restriction_reason_code_4
    ,restrictionreasoncode5                     as restriction_reason_code_5
    ,versionmarkernumber2                       as version_marker_number_2
    ,schwabbankinvestorcheckingaccountnumber    as schcwab_bank_investor_checking_account_number
    ,versionmarkernumber3                       as version_marker_number_3
    ,ssn_tin                                    as ssn_tin
    ,versionmarkernumber4                       as version_marker_number_4
    ,primebrokerenabledindicator                as prime_broker_enabled_indicator
    ,managedaccountplatformcode                 as managed_account_platform_code
    ,managedaccountmoneymanager                 as managed_account_money_manager
    ,managedaccountinvestmentstrategy           as managed_account_investment_strategy
    ,versionmarkernumber5                       as version_marker_number_5
    ,banksweepdisplayname                       as bank_sweep_display_name
    ,{{ col_is_head(reference=source('schwab_mps', 'accounts')) }}
    ,{{ col_is_current(date_col='effective_date') }}
    ,'mps'                                      as firm_source
    ,effective_date::date                       as effective_date
    ,record_datetime::timestamp                 as record_datetime
    ,record_date::date                          as record_date
    ,record_datetime::timestamp                 as _source_loaded_at
from {{ source('schwab_mps', 'accounts') }}