-- depends_on: {{ ref('schwab__stg_transactions') }}

select
    a.custodian
  , cl.firm_source
  , cf.firm
  , a.record_type
  , a.custodian_id
  , a.master_account_number
  , a.master_account_name
  , a.business_date
  , a.account_number
  , a.account_title_line_1
  , a.account_title_line_2
  , a.account_title_line_3
  , a.account_registration
  , a.account_type
  , a.product_code
  , a.product_category_code
  , a.tax_code
  , a.legacy_security_type
  , a.ticker_symbol
  , a.industry_ticker_symbol
  , a.cusip
  , a.schwab_security_number
  , a.item_issue_id
  , a.rule_set_suffix_id
  , a.isin
  , a.sedol
  , a.options_display_symbol
  , a.underlying_ticker_symbol
  , a.underlying_industry_ticker_symbol
  , a.underlying_cusip
  , a.underlying_schwab_security_number
  , a.underlying_item_issue_id
  , a.underlying_rule_set_suffix_id
  , a.underlying_isin
  , a.underlying_sedol
  , a.money_market_code
  , a.transaction_type_code
  , a.transaction_sub_type_code
  , a.transaction_category
  , a.transaction_source_code
  , a.transaction_source_code_description
  , a.transaction_detail_description
  , a.action_code
  , a.transaction_cancel_code
  , a.trade_date
  , a.settlement_date
  , a.transaction_date
  , a.ex_dividend_date
  , a.quantity
  , a.price
  , a.gross_amount
  , a.debit_credit_indicator
  , a.net_amount
  , a.commission
  , a.exchange_processing_fee
  , a.broker_service_fee
  , a.prime_broker_fee
  , a.trade_away_fee
  , a.redemption_fee
  , a.other_fee
  , a.federal_tefra_withholding
  , a.state_tax_withholding
  , a.state_receiving_tax
  , a.accrued_interest
  , a.accounting_rule_code
  , a.order_source_code
  , a.order_number
  , a.trade_order_entry_time_stamp
  , a.trade_order_execution_time_stamp
  , a.broker_code
  , a.broker_name
  , a.schwab_from_account
  , a.schwab_to_account
  , a.schwab1_check_number
  , a.sweep_indicator
  , a.stock_exchange_code
  , a.inter_class_exchange_code
  , a.distribution_rate
  , a.cash_in_lieu_share_quantity
  , a.dividend_interest_share_quantity
  , a.cash_in_lieu_rate
  , a.asset_backed_factor
  , a.source_system
  , a.journal_type
  , a.deposit_media
  , a.schwab_cashiering_unique_identifier
  , a.recipient_maker_name_line_1
  , a.recipient_maker_name_line_2
  , a.recipient_maker_name_line_3
  , a.frequency
  , a.disbursed_check_number
  , a.fed_reference_number
  , a.recipient_maker_account_number
  , a.bank_account_type
  , a.bank_name_part_1
  , a.bank_name_part_2
  , a.bank_aba_number
  , a.intermediary_name
  , a.transaction_check_memo_1
  , a.transaction_check_memo_2
  , a.retirement_federal_income_tax
  , a.retirement_state_income_tax
  , a.retirement_income_tax_state
  , a.publication_time_stamp
  , a.version_marker_1
  , a.tips_factor
  , a.closing_price
  , a.version_marker_2
  , a.transaction_memo
  , a.version_marker_3
  , a.closing_price_unfactored
  , a.factor
  , a.factor_date
  , a.master_number
  , a.is_deceased
  , a.is_from_tda_migration
  , a.effective_date
  , a.rn
  , {{ col_is_head(reference=source('schwab', 'trn_transactions')) }}
  , {{ col_is_current(date_col='a.effective_date') }}
  , a._source_loaded_at
  , a._source_file
from {{ source('schwab', 'trn_transactions') }} a
left join {{ ref('aux__stg_custodian_links') }} cl
          on a.master_number = cl.link
              and cl.custodian = 'schwab'
left join {{ ref('custodian_firms') }}          cf
          on cl.firm_source = cf.firm_source
