{%- macro fidelity_raw_nabase_101_account(src) -%}
select
    trim(substring(content, 9, 3)) || trim(substring(content, 12, 6))                     as ACCOUNT_CUSTODIAL
  , trim(substring(content, 9, 3)) || '-' || trim(substring(content, 12, 6))              as ACCOUNT_CUSTODIAL_FORMATTED
  , nullif(trim(substring(content, 1, 1)), '')                                            as RECORD_TYPE
  , nullif(trim(substring(content, 2, 3)), '')                                            as RECORD_NUMBER
  , nullif(trim(substring(content, 5, 4)), '')                                            as FIRM
  , nullif(trim(substring(content, 9, 3)), '')                                            as BRANCH
  , nullif(trim(substring(content, 12, 6)), '')                                           as ACCOUNT_NUMBER
  , nullif(trim(substring(content, 18, 2)), '')                                           as NUMBER_OF_CONFIRMS
  , nullif(trim(substring(content, 20, 2)), '')                                           as NUMBER_OF_STATEMENTS
  , nullif(trim(substring(content, 22, 9)), '')                                           as IRS_NO
  , nullif(trim(substring(content, 31, 1)), '')                                           as IRS_CODE
  , nullif(trim(substring(content, 32, 5)), '')                                           as ZIP_CODE
  , nullif(trim(substring(content, 37, 3)), '')                                           as STATE_COUNTRY_CODE
  , nullif(trim(substring(content, 40, 1)), '')                                           as SEPARATE_ACCOUNT_MANAGER_INDICATOR
  , nullif(trim(substring(content, 41, 10)), '')                                          as SHORT_NAME
  , nullif(trim(substring(content, 51, 1)), '')                                           as TRANSFER_LEGEND_CODE
  , nullif(trim(substring(content, 52, 1)), '')                                           as MANAGED_ACCOUNT_CODE
  , nullif(trim(substring(content, 53, 1)), '')                                           as LAST_UPDATE_CODE
  , nullif(trim(substring(content, 54, 8)), '')                                           as LAST_UPDATE_DATE
  , nullif(trim(substring(content, 62, 3)), '')                                           as REGISTERED_REP_OWNING_REP_RR
  , nullif(trim(substring(content, 65, 1)), '')                                           as TRADING_AUTH_CODE_BNAM
  , nullif(trim(substring(content, 66, 1)), '')                                           as EMPLOYEE_CODE
  , nullif(trim(substring(content, 67, 1)), '')                                           as CITIZEN_CODE
  , nullif(trim(substring(content, 68, 3)), '')                                           as COUNTRY_OF_TAX_RESIDENCY
  , nullif(trim(substring(content, 71, 1)), '')                                           as DO_NOT_PURGE_CODE
  , nullif(trim(substring(content, 72, 2)), '')                                           as ACCOUNT_CLASSIFICATION
  , nullif(trim(substring(content, 74, 1)), '')                                           as PROCEEDS_INSTRUCTIONS
  , nullif(trim(substring(content, 75, 1)), '')                                           as SECURITIES_INSTRUCTIONS
  , nullif(trim(substring(content, 76, 1)), '')                                           as CASH_DIVIDEND_INSTRUCTIONS
  , nullif(trim(substring(content, 77, 1)), '')                                           as DIVIDEND_ROUNDOUT_INSTRUCTION_CODE
  , nullif(trim(substring(content, 78, 1)), '')                                           as NON_OBJECTING_BENEFICIAL_OWNER_CODE
  , nullif(trim(substring(content, 79, 1)), '')                                           as COMMISSION_CLASS
  , nullif(trim(substring(content, 80, 5)), '')                                           as COMMISSION_DISCOUNT_PERCENT
  , nullif(trim(substring(content, 85, 2)), '')                                           as COMMISSION_SCHEDULE
  , nullif(trim(substring(content, 87, 3)), '')                                           as PARENT_BRANCH
  , nullif(trim(substring(content, 90, 6)), '')                                           as PARENT_ACCOUNT
  , nullif(trim(substring(content, 96, 8)), '')                                           as AGENCY_CODE
  , nullif(trim(substring(content, 104, 3)), '')                                          as REGISTERED_REP_EXEC_REP_RR2
  , nullif(trim(substring(content, 107, 1)), '')                                          as NAP_RAP_INDICATOR
  , nullif(trim(substring(content, 108, 8)), '')                                          as NAP_RAP_DATE
  , nullif(trim(substring(content, 116, 1)), '')                                          as INSTITUTIONAL_DELIVERY_CODE
  , nullif(trim(substring(content, 117, 5)), '')                                          as INSTITUTIONAL_DELIVERY_NUMBER
  , nullif(trim(substring(content, 122, 5)), '')                                          as AGENT_BANK_NUMBER
  , nullif(trim(substring(content, 127, 8)), '')                                          as ESTABLISH_DATE
  , nullif(trim(substring(content, 135, 1)), '')                                          as RESTRICTION_CODE_PARTIAL
  , nullif(trim(substring(content, 136, 1)), '')                                          as BYPASS_MISC_FEE_INDICATOR
  , nullif(trim(substring(content, 137, 1)), '')                                          as INVESTMENT_CLUB_AGREEMENT
  , nullif(trim(substring(content, 138, 1)), '')                                          as JOINT_ACCOUNT_AGREEMENT
  , nullif(trim(substring(content, 139, 1)), '')                                          as TRUST_SERVICE_PROVIDER_TLA
  , nullif(trim(substring(content, 140, 1)), '')                                          as CORPORATE_AGREEMENT
  , nullif(trim(substring(content, 141, 1)), '')                                          as TRUST_ACCOUNTING
  , nullif(trim(substring(content, 142, 1)), '')                                          as PARTNER_AGREEMENT
  , nullif(trim(substring(content, 143, 1)), '')                                          as MARGIN_AGREEMENT
  , nullif(trim(substring(content, 144, 1)), '')                                          as OPTION_STATUS
  , nullif(trim(substring(content, 145, 1)), '')                                          as OPTION_AGREEMENT
  , nullif(trim(substring(content, 146, 1)), '')                                          as NON_PURPOSE_LOAN_AGREEMENT
  , nullif(trim(substring(content, 147, 1)), '')                                          as TRUST_AGREEMENT
  , nullif(trim(substring(content, 148, 1)), '')                                          as NEW_ACCOUNT_PAPERS
  , nullif(trim(substring(content, 149, 1)), '')                                          as SPECIAL_PRODUCT_PAPERS
  , nullif(trim(substring(content, 150, 2)), '')                                          as OMNIBUS_CODE
  , nullif(trim(substring(content, 152, 1)), '')                                          as SEGREGATION_CODE
  , nullif(trim(substring(content, 153, 5)), '')                                          as SPECIAL_MARGIN_RATE
  , nullif(trim(substring(content, 158, 1)), '')                                          as MONEY_MOVEMENT_AUTHORIZATION_LEVEL
  , nullif(trim(substring(content, 159, 1)), '')                                          as MASTER_SECURITY_LENDING_AGREEMENT_MSLA_INDICATOR
  , nullif(trim(substring(content, 160, 1)), '')                                          as CORPORATE_TAX_STATUS
  , nullif(trim(substring(content, 161, 4)), '')                                          as COST_BASIS_DISPOSAL_METHOD_CODE
  , nullif(trim(substring(content, 165, 1)), '')                                          as DVP_SUPPRESSION_INDICATOR
  , nullif(trim(substring(content, 166, 8)), '')                                          as ABANDONED_PROPERTY_DATE
  , nullif(trim(substring(content, 174, 3)), '')                                          as PREFERRED_CUSTOMER_CODE
  , nullif(trim(substring(content, 177, 9)), '')                                          as PREFERRED_ZIP_CODE
  , nullif(trim(substring(content, 186, 12)), '')                                         as OASYS_ACCESS_CODE
  , nullif(trim(substring(content, 198, 8)), '')                                          as OASYS_INSTITUTION
  , nullif(trim(substring(content, 206, 1)), '')                                          as NUMBER_OF_ADDRESS_LINES
  , nullif(trim(substring(content, 207, 32)), '')                                         as NAME_AND_ADDRESS_LINE_1
  , nullif(trim(substring(content, 239, 32)), '')                                         as NAME_AND_ADDRESS_LINE_2
  , nullif(trim(substring(content, 271, 32)), '')                                         as NAME_AND_ADDRESS_LINE_3
  , nullif(trim(substring(content, 303, 32)), '')                                         as NAME_AND_ADDRESS_LINE_4
  , nullif(trim(substring(content, 335, 32)), '')                                         as NAME_AND_ADDRESS_LINE_5
  , nullif(trim(substring(content, 367, 32)), '')                                         as NAME_AND_ADDRESS_LINE_6
  , nullif(trim(substring(content, 399, 4)), '')                                          as REGISTRATION_TYPE
  , nullif(trim(substring(content, 403, 8)), '')                                          as BIRTH_DATE
  , nullif(trim(substring(content, 411, 2)), '')                                          as PRODUCT_LEVEL
  , nullif(trim(substring(content, 413, 8)), '')                                          as BIRTH_DATE_SHADOW
  , nullif(trim(substring(content, 421, 1)), '')                                          as MULTI_CURRENCY_ACCOUNT
  , nullif(trim(substring(content, 422, 1)), '')                                          as PORTFOLIO_MARGIN_INDICATOR
  , nullif(trim(substring(content, 423, 1)), '')                                          as ADVISOR_REPORTING_INDICATOR
  , nullif(trim(substring(content, 424, 1)), '')                                          as LATE_TRADE_INDICATOR
  , nullif(trim(substring(content, 425, 1)), '')                                          as MARGIN_SWEEP_CODE
  , nullif(trim(substring(content, 426, 1)), '')                                          as SETUP_FEE_INDICATOR
  , nullif(trim(substring(content, 427, 1)), '')                                          as PRODUCT_LEVEL_SUBTYPE_CODE
  , nullif(trim(substring(content, 428, 1)), '')                                          as W_8_FORM_CODE
  , nullif(trim(substring(content, 429, 8)), '')                                          as W_8_CERTIFICATION_DATE
  , nullif(trim(substring(content, 438, 3)), '')                                          as ACCOUNT_SOURCE_CODE
  , nullif(trim(substring(content, 441, 9)), '')                                          as BDA_PARENT_ACCOUNT_NUMBER
  , nullif(trim(substring(content, 450, 1)), '')                                          as NET_ASSET_VALUE_INDICATOR
  , nullif(trim(substring(content, 451, 5)), '')                                          as PLAN_NAME_CODE
  , nullif(trim(substring(content, 456, 3)), '')                                          as TEAM_CODE
  , nullif(trim(substring(content, 459, 1)), '')                                          as FIAG_ACCOUNT_INDICATOR
  , nullif(trim(substring(content, 460, 1)), '')                                          as PROXY_VOTE_INDICATOR
  , nullif(trim(substring(content, 461, 1)), '')                                          as PRIME_BROKER_INDICATOR
  , nullif(trim(substring(content, 462, 3)), '')                                          as TRANSFER_AGENT_FEE_CODE
  , nullif(trim(substring(content, 465, 3)), '')                                          as TRANSFER_AGENT_MANAGEMENT_FEE_CODE
  , nullif(trim(substring(content, 468, 2)), '')                                          as ACCOUNT_REGULATORY_CODE
  , nullif(trim(substring(content, 470, 1)), '')                                          as EXCHANGE_INDICATOR
  , nullif(trim(substring(content, 471, 2)), '')                                          as CASH_MANAGEMENT_FEE_SCHEDULE_CODE
  , nullif(trim(substring(content, 473, 1)), '')                                          as MULTIPLE_MARGIN_INDICATOR
  , nullif(trim(substring(content, 474, 1)), '')                                          as ASSET_DISTRIBUTION_ACCOUNT_CODE
  , nullif(trim(substring(content, 475, 1)), '')                                          as CONFIRM_PRINT_CODE
  , nullif(trim(substring(content, 476, 1)), '')                                          as FAMILY_OFFICE_TYPE_CODE
  , nullif(trim(substring(content, 477, 1)), '')                                          as SHADOSUITE_DVP_CODE
  , nullif(trim(substring(content, 478, 2)), '')                                          as VENDOR_CODE
  , nullif(trim(substring(content, 480, 1)), '')                                          as CHARGEBACK_TYPE_CODE
  , nullif(trim(substring(content, 481, 1)), '')                                          as CASH_MOVEMENT_TYPE_CODE
  , nullif(trim(substring(content, 482, 1)), '')                                          as FUTURES_STATUS_CODE
  , nullif(trim(substring(content, 483, 1)), '')                                          as BROKER_DEALER_SOLD_CODE
  , nullif(trim(substring(content, 484, 1)), '')                                          as FEE_AUTHORIZATION_CODE
  , nullif(trim(substring(content, 485, 1)), '')                                          as MUTUAL_FUND_FEE_REBATE_CODE
  , nullif(trim(substring(content, 486, 5)), '')                                          as SPECIAL_ACCOUNT_USAGE_CODE
  , nullif(trim(substring(content, 491, 1)), '')                                          as TRADE_AWAY_ELIGIBLE_CODE
  , nullif(trim(substring(content, 492, 1)), '')                                          as COVERDELL_SPECIAL_NEEDS_INDICATOR
  , nullif(trim(substring(content, 493, 1)), '')                                          as MULTIPLE_MARGIN_MODEL_CODE
  , nullif(trim(substring(content, 494, 1)), '')                                          as MUTUAL_FUND_INVESTMENT_IRA_INDICATOR
  , nullif(trim(substring(content, 495, 1)), '')                                          as MONEY_MARKET_ACCOUNT_DESIGNATION
  , nullif(trim(substring(content, 496, 8)), '')                                          as PRODUCT_CLASS
  , nullif(trim(substring(content, 504, 8)), '')                                          as PLATFORM_SOURCE
  , nullif(trim(substring(content, 512, 2)), '')                                          as FIDUCIARY_APPROACH_CODE
  , nullif(trim(substring(content, 514, 8)), '')                                          as FIDUCIARY_APPROACH_LAST_UPDATE_DATE
  , {{ col_is_head(reference=src) }}
  , {{ col_is_current(date_col='effective_date') }}
  , effective_date
  , record_datetime                                                                         as _source_loaded_at
  , source_file                                                                             as _source_file
from {{ src }}
where left(content, 4) = 'D101'
{%- endmacro -%}