{%- macro fidelity_raw_acctbald_account_balance(src) -%}
select
    trim(substring(content, 2, 3)) || trim(substring(content, 5, 6))                        as ACCOUNT_CUSTODIAL
  , trim(substring(content, 2, 3)) || '-' ||
    trim(substring(content, 5, 6))                                                          as ACCOUNT_CUSTODIAL_FORMATTED
  , nullif(trim(substring(content, 1, 1)), '')                                              as RECORD_NUMBER
  , nullif(trim(substring(content, 2, 3)), '')                                              as BRANCH
  , nullif(trim(substring(content, 5, 6)), '')                                              as ACCOUNT_NUMBER
  , nullif(trim(substring(content, 11, 6)), '')                                             as LAST_UPDATE_DATE
  , nullif(trim(substring(content, 17, 1)), '')                                             as BALANCE_FIELD_SIGN_1
  , nullif(trim(substring(content, 18, 17)), '')                                            as NETWORTH
  , nullif(trim(substring(content, 35, 1)), '')                                             as BALANCE_FIELD_SIGN_2
  , nullif(trim(substring(content, 36, 17)), '')                                            as CASH_COLLECTED_BALANCE
  , nullif(trim(substring(content, 53, 1)), '')                                             as BALANCE_FIELD_SIGN_3
  , nullif(trim(substring(content, 54, 17)), '')                                            as COLLECTED_BALANCE
  , nullif(trim(substring(content, 71, 1)), '')                                             as BALANCE_FIELD_SIGN_4
  , nullif(trim(substring(content, 72, 17)), '')                                            as NET_TRADE_DATE_BALANCE
  , nullif(trim(substring(content, 89, 1)), '')                                             as BALANCE_FIELD_SIGN_5
  , nullif(trim(substring(content, 90, 17)), '')                                            as NETWORTH_MARKET_VALUE
  , nullif(trim(substring(content, 107, 1)), '')                                            as BALANCE_FIELD_SIGN_6
  , nullif(trim(substring(content, 108, 17)), '')                                           as CASH_MONEY_MARKETS
  , nullif(trim(substring(content, 125, 1)), '')                                            as BALANCE_FIELD_SIGN_7
  , nullif(trim(substring(content, 126, 17)), '')                                           as OPTION_MARKET_VALUE
  , nullif(trim(substring(content, 143, 1)), '')                                            as BALANCE_FIELD_SIGN_8
  , nullif(trim(substring(content, 144, 17)), '')                                           as OPTION_IN_MONEY_AMT
  , nullif(trim(substring(content, 161, 1)), '')                                            as BALANCE_FIELD_SIGN_9
  , nullif(trim(substring(content, 162, 17)), '')                                           as MEMO_ADJUSTMENTS
  , nullif(trim(substring(content, 179, 1)), '')                                            as BALANCE_FIELD_SIGN_10
  , nullif(trim(substring(content, 180, 17)), '')                                           as AVAILABLE_TO_PURCHASE_MARGIN
  , nullif(trim(substring(content, 197, 1)), '')                                            as BALANCE_FIELD_SIGN_11
  , nullif(trim(substring(content, 198, 17)), '')                                           as BUYING_POWER_CORP_BONDS
  , nullif(trim(substring(content, 215, 1)), '')                                            as BALANCE_FIELD_SIGN_12
  , nullif(trim(substring(content, 216, 17)), '')                                           as BUYING_POWER_MUNI_BONDS
  , nullif(trim(substring(content, 233, 1)), '')                                            as BALANCE_FIELD_SIGN_13
  , nullif(trim(substring(content, 234, 17)), '')                                           as BUYING_POWER_GOVT_BONDS
  , nullif(trim(substring(content, 251, 1)), '')                                            as BALANCE_FIELD_SIGN_14
  , nullif(trim(substring(content, 252, 17)), '')                                           as HOUSE_SURPLUS_CALL
  , nullif(trim(substring(content, 269, 1)), '')                                            as BALANCE_FIELD_SIGN_15
  , nullif(trim(substring(content, 270, 17)), '')                                           as NYSE_SURPLUS_CALL
  , nullif(trim(substring(content, 287, 1)), '')                                            as BALANCE_FIELD_SIGN_16
  , nullif(trim(substring(content, 288, 17)), '')                                           as SMA_FED_CALL
  , nullif(trim(substring(content, 305, 1)), '')                                            as BALANCE_FIELD_SIGN_17
  , nullif(trim(substring(content, 306, 17)), '')                                           as MINIMUM_EQUITY_CALL
  , nullif(trim(substring(content, 323, 1)), '')                                            as BALANCE_FIELD_SIGN_18
  , nullif(trim(substring(content, 324, 17)), '')                                           as TOTAL_CORE_MONEY_MARKETS
  , nullif(trim(substring(content, 341, 1)), '')                                            as BALANCE_FIELD_SIGN_19
  , nullif(trim(substring(content, 342, 17)), '')                                           as MARGIN_EQUITY
  , nullif(trim(substring(content, 359, 1)), '')                                            as BALANCE_FIELD_SIGN_20
  , nullif(trim(substring(content, 360, 17)), '')                                           as MARGIN_LIQUIDATING_EQUITY
  , nullif(trim(substring(content, 377, 5)), '')                                            as MARGIN_EQUITY_PERCENTAGE
  , nullif(trim(substring(content, 382, 1)), '')                                            as BALANCE_FIELD_SIGN_21
  , nullif(trim(substring(content, 383, 17)), '')                                           as FED_CALL_REDUCTION
  , nullif(trim(substring(content, 400, 1)), '')                                            as BALANCE_FIELD_SIGN_22
  , nullif(trim(substring(content, 401, 17)), '')                                           as HOUSE_CALL_REDUCTION
  , nullif(trim(substring(content, 418, 1)), '')                                            as BALANCE_FIELD_SIGN_23
  , nullif(trim(substring(content, 419, 17)), '')                                           as NYSE_CALL_REDUCTION
  , nullif(trim(substring(content, 436, 1)), '')                                            as BALANCE_FIELD_SIGN_24
  , nullif(trim(substring(content, 437, 17)), '')                                           as UNCOLLECTED_BALANCE
  , nullif(trim(substring(content, 454, 1)), '')                                            as BALANCE_FIELD_SIGN_25
  , nullif(trim(substring(content, 455, 17)), '')                                           as MINIMUM_EQUITY_CALL_REDUCTION
  , nullif(trim(substring(content, 472, 1)), '')                                            as TRANSFER_LEGEND_CODE
  , nullif(trim(substring(content, 473, 1)), '')                                            as MARGIN_PAPERS_SWITCH
  , nullif(trim(substring(content, 474, 1)), '')                                            as POSITION_SWITCH
  , nullif(trim(substring(content, 475, 1)), '')                                            as UNPRICED_POSITIONS_SWITCH
  , nullif(trim(substring(content, 476, 1)), '')                                            as EMPLOYEE_ACCOUNT_SWITCH
  , nullif(trim(substring(content, 477, 1)), '')                                            as TYPE_OF_ACCOUNT_SWITCH
  , nullif(trim(substring(content, 478, 1)), '')                                            as SHORT_POSITION_SWITCH
  , nullif(trim(substring(content, 479, 1)), '')                                            as LONG_POSITION_SWITCH
  , nullif(trim(substring(content, 480, 1)), '')                                            as MEMO_ENTRIES_SWITCH
  , nullif(trim(substring(content, 481, 1)), '')                                            as DAY_TRADES_SWITCH
  , nullif(trim(substring(content, 482, 1)), '')                                            as POSSIBLE_LIQUIDATIONS_SWITCH
  , nullif(trim(substring(content, 483, 1)), '')                                            as MINIMUM_FEDCALL_TRANS_SWITCH
  , nullif(trim(substring(content, 484, 3)), '')                                            as ACCOUNT_TYPE_RECORD_COUNT
  , nullif(trim(substring(content, 487, 3)), '')                                            as SUPER_BRANCH
  , nullif(trim(substring(content, 490, 1)), '')                                            as BALANCE_FIELD_SIGN_26
  , nullif(trim(substring(content, 491, 17)), '')                                           as AVAILABLE_TO_PURCHASE_CASH
  , nullif(trim(substring(content, 508, 1)), '')                                            as BALANCE_FIELD_SIGN_27
  , nullif(trim(substring(content, 509, 17)), '')                                           as AVAILABLE_TO
  , nullif(trim(substring(content, 526, 1)), '')                                            as BALANCE_FIELD_SIGN_28
  , nullif(trim(substring(content, 527, 17)), '')                                           as AVAILABLE_TO_PURCHASE_NON_MGN
  , nullif(trim(substring(content, 544, 1)), '')                                            as BALANCE_FIELD_SIGN_29
  , nullif(trim(substring(content, 545, 17)), '')                                           as CUSTOMER_FACING_NETWORTH
  , nullif(trim(substring(content, 562, 1)), '')                                            as ACCOUNT_TYPE_1
  , nullif(trim(substring(content, 563, 1)), '')                                            as BALANCE_FIELD_SIGN_30
  , nullif(trim(substring(content, 564, 17)), '')                                           as MARKET_VALUE_1
  , nullif(trim(substring(content, 581, 1)), '')                                            as BALANCE_FIELD_SIGN_31
  , nullif(trim(substring(content, 582, 17)), '')                                           as TRADE_DATE_BALANCE_1
  , nullif(trim(substring(content, 599, 1)), '')                                            as BALANCE_FIELD_SIGN_32
  , nullif(trim(substring(content, 600, 17)), '')                                           as SETTLEMENT_DATE_BALANCE_1
  , nullif(trim(substring(content, 617, 1)), '')                                            as ACCOUNT_TYPE_2
  , nullif(trim(substring(content, 618, 1)), '')                                            as BALANCE_FIELD_SIGN_33
  , nullif(trim(substring(content, 619, 17)), '')                                           as MARKET_VALUE_2
  , nullif(trim(substring(content, 636, 1)), '')                                            as BALANCE_FIELD_SIGN_34
  , nullif(trim(substring(content, 637, 17)), '')                                           as TRADE_DATE_BALANCE_2
  , nullif(trim(substring(content, 654, 1)), '')                                            as BALANCE_FIELD_SIGN_35
  , nullif(trim(substring(content, 655, 17)), '')                                           as SETTLEMENT_DATE_BALANCE_2
  , nullif(trim(substring(content, 672, 1)), '')                                            as ACCOUNT_TYPE_3
  , nullif(trim(substring(content, 673, 1)), '')                                            as BALANCE_FIELD_SIGN_36
  , nullif(trim(substring(content, 674, 17)), '')                                           as MARKET_VALUE_3
  , nullif(trim(substring(content, 691, 1)), '')                                            as BALANCE_FIELD_SIGN_37
  , nullif(trim(substring(content, 692, 17)), '')                                           as TRADE_DATE_BALANCE_3
  , nullif(trim(substring(content, 709, 1)), '')                                            as BALANCE_FIELD_SIGN_38
  , nullif(trim(substring(content, 710, 17)), '')                                           as SETTLEMENT_DATE_BALANCE_3
  , nullif(trim(substring(content, 727, 1)), '')                                            as ACCOUNT_TYPE_4
  , nullif(trim(substring(content, 728, 1)), '')                                            as BALANCE_FIELD_SIGN_39
  , nullif(trim(substring(content, 729, 17)), '')                                           as MARKET_VALUE_4
  , nullif(trim(substring(content, 746, 1)), '')                                            as BALANCE_FIELD_SIGN_40
  , nullif(trim(substring(content, 747, 17)), '')                                           as TRADE_DATE_BALANCE_4
  , nullif(trim(substring(content, 764, 1)), '')                                            as BALANCE_FIELD_SIGN_41
  , nullif(trim(substring(content, 765, 17)), '')                                           as SETTLEMENT_DATE_BALANCE_4
  , nullif(trim(substring(content, 782, 1)), '')                                            as ACCOUNT_TYPE_5
  , nullif(trim(substring(content, 783, 1)), '')                                            as BALANCE_FIELD_SIGN_42
  , nullif(trim(substring(content, 784, 17)), '')                                           as MARKET_VALUE_5
  , nullif(trim(substring(content, 801, 1)), '')                                            as BALANCE_FIELD_SIGN_43
  , nullif(trim(substring(content, 802, 17)), '')                                           as TRADE_DATE_BALANCE_5
  , nullif(trim(substring(content, 819, 1)), '')                                            as BALANCE_FIELD_SIGN_44
  , nullif(trim(substring(content, 820, 17)), '')                                           as SETTLEMENT_DATE_BALANCE_5
  , nullif(trim(substring(content, 837, 1)), '')                                            as ACCOUNT_TYPE_6
  , nullif(trim(substring(content, 838, 1)), '')                                            as BALANCE_FIELD_SIGN_45
  , nullif(trim(substring(content, 839, 17)), '')                                           as MARKET_VALUE_6
  , nullif(trim(substring(content, 856, 1)), '')                                            as BALANCE_FIELD_SIGN_46
  , nullif(trim(substring(content, 857, 17)), '')                                           as TRADE_DATE_BALANCE_6
  , nullif(trim(substring(content, 874, 1)), '')                                            as BALANCE_FIELD_SIGN_47
  , nullif(trim(substring(content, 875, 17)), '')                                           as SETTLEMENT_DATE_BALANCE_6
  , nullif(trim(substring(content, 892, 1)), '')                                            as ACCOUNT_TYPE_7
  , nullif(trim(substring(content, 893, 1)), '')                                            as BALANCE_FIELD_SIGN_48
  , nullif(trim(substring(content, 894, 17)), '')                                           as MARKET_VALUE_7
  , nullif(trim(substring(content, 911, 1)), '')                                            as BALANCE_FIELD_SIGN_49
  , nullif(trim(substring(content, 912, 17)), '')                                           as TRADE_DATE_BALANCE_7
  , nullif(trim(substring(content, 929, 1)), '')                                            as BALANCE_FIELD_SIGN_50
  , nullif(trim(substring(content, 930, 17)), '')                                           as SETTLEMENT_DATE
  , nullif(trim(substring(content, 947, 1)), '')                                            as ACCOUNT_TYPE_8
  , nullif(trim(substring(content, 948, 1)), '')                                            as BALANCE_FIELD_SIGN_51
  , nullif(trim(substring(content, 949, 17)), '')                                           as MARKET_VALUE_8
  , nullif(trim(substring(content, 966, 1)), '')                                            as BALANCE_FIELD_SIGN_52
  , nullif(trim(substring(content, 967, 17)), '')                                           as TRADE_DATE_BALANCE_8
  , nullif(trim(substring(content, 984, 1)), '')                                            as BALANCE_FIELD_SIGN_53
  , nullif(trim(substring(content, 985, 17)), '')                                           as SETTLEMENT_DATE_BALANCE_7
  , nullif(trim(substring(content, 1002, 1)), '')                                           as ACCOUNT_TYPE_9
  , nullif(trim(substring(content, 1003, 1)), '')                                           as BALANCE_FIELD_SIGN_54
  , nullif(trim(substring(content, 1004, 17)), '')                                          as MARKET_VALUE_9
  , nullif(trim(substring(content, 1021, 1)), '')                                           as BALANCE_FIELD_SIGN_55
  , nullif(trim(substring(content, 1022, 17)), '')                                          as TRADE_DATE_BALANCE_9
  , nullif(trim(substring(content, 1039, 1)), '')                                           as BALANCE_FIELD_SIGN_56
  , nullif(trim(substring(content, 1040, 17)), '')                                          as SETTLEMENT_DATE_BALANCE_8
  , nullif(trim(substring(content, 1057, 1)), '')                                           as ACCOUNT_TYPE_10
  , nullif(trim(substring(content, 1058, 1)), '')                                           as BALANCE_FIELD_SIGN_57
  , nullif(trim(substring(content, 1059, 17)), '')                                          as MARKET_VALUE_10
  , nullif(trim(substring(content, 1076, 1)), '')                                           as BALANCE_FIELD_SIGN_58
  , nullif(trim(substring(content, 1077, 17)), '')                                          as TRADE_DATE_BALANCE_10
  , nullif(trim(substring(content, 1094, 1)), '')                                           as BALANCE_FIELD_SIGN_59
  , nullif(trim(substring(content, 1095, 17)), '')                                          as SETTLEMENT_DATE_BALANCE_9
  , nullif(trim(substring(content, 1112, 1)), '')                                           as PORTFOLIO_MARGIN_INDICATOR
  , nullif(trim(substring(content, 1113, 1)), '')                                           as MASTER_SECURITY_LENDING_AGREEMENT_MSLA_INDICATOR
  , nullif(trim(substring(content, 1114, 1)), '')                                           as RELATIONSHIP_TYPE_CODE
  , nullif(trim(substring(content, 1115, 1)), '')                                           as MULTI_CURRENCY_ACCOUNT_INDICATOR
  , nullif(trim(substring(content, 1116, 1)), '')                                           as TRUST_ACCOUNTING
  , nullif(trim(substring(content, 1117, 1)), '')                                           as NON_PURPOSE_LOAN_INDICATOR
  , nullif(trim(substring(content, 1118, 1)), '')                                           as NET_CASH_SETTLEMENT_INDICATOR
  , nullif(trim(substring(content, 1119, 1)), '')                                           as WHEN_ISSUED_INDICATOR
  , nullif(trim(substring(content, 1120, 1)), '')                                           as ACCOUNT_TYPE_5_INDICATOR
  , nullif(trim(substring(content, 1121, 1)), '')                                           as BALANCE_FIELD_SIGN_60
  , nullif(trim(substring(content, 1122, 17)), '')                                          as AVAILABLE_TO_BORROW
  , nullif(trim(substring(content, 1139, 1)), '')                                           as BALANCE_FIELD_SIGN_61
  , nullif(trim(substring(content, 1140, 17)), '')                                          as CASH_AVAILABLE_TO_WITHDRAW
  , nullif(trim(substring(content, 1157, 1)), '')                                           as BALANCE_FIELD_SIGN_62
  , nullif(trim(substring(content, 1158, 17)), '')                                          as SETTLED_CASH
  , nullif(trim(substring(content, 1175, 1)), '')                                           as BALANCE_FIELD_SIGN_63
  , nullif(trim(substring(content, 1176, 17)), '')                                          as UNSETTLED_CASH_CREDIT
  , nullif(trim(substring(content, 1193, 1)), '')                                           as BALANCE_FIELD_SIGN_64
  , nullif(trim(substring(content, 1194, 17)), '')                                          as UNSETTLED_CASH_DEBIT
  , nullif(trim(substring(content, 1211, 1)), '')                                           as BALANCE_FIELD_SIGN_65
  , nullif(trim(substring(content, 1212, 17)), '')                                          as AVAILABLE_TO_PAY
  , nullif(trim(substring(content, 1229, 1)), '')                                           as BALANCE_FIELD_SIGN_66
  , nullif(trim(substring(content, 1230, 17)), '')                                          as CORE_SWEEP_FUND
  , nullif(trim(substring(content, 1247, 1)), '')                                           as BALANCE_FIELD_SIGN_67
  , nullif(trim(substring(content, 1248, 17)), '')                                          as NON_CORE_MONEY_MARKET_AMOUNT
  , {{ col_is_head(reference=src) }}
  , {{ col_is_current(date_col='effective_date') }}
  , effective_date, record_datetime::date as record_date, record_datetime::timestamp as record_datetime, source_file as source_file
  , record_datetime                                                                         as _source_loaded_at
  , source_file                                                                             as _source_file
from {{ src }}
where 1 = 1
  and left(content, 1) = 'D'
{%- endmacro -%}