{%- macro fidelity_raw_secmast_1_security(src) -%}
select
    nullif(trim(substring(content, 1, 1)), '')                                             as RECORD_TYPE
  , nullif(trim(substring(content, 2, 1)), '')                                             as RECORD_NUMBER
  , nullif(trim(substring(content, 3, 1)), '')                                             as RECORD_STATUS_CODE
  , nullif(trim(substring(content, 4, 9)), '')                                             as CUSIP
  , nullif(trim(substring(content, 13, 20)), '')                                           as SYMBOL
  , nullif(trim(substring(content, 33, 20)), '')                                           as FLOOR_TRADING_SYMBOL
  , nullif(trim(substring(content, 53, 1)), '')                                            as SECURITY_TYPE
  , nullif(trim(substring(content, 54, 1)), '')                                            as SECURITY_TYPE_MODIFIER
  , nullif(trim(substring(content, 55, 1)), '')                                            as SECURITY_TYPE_CALCULATION
  , nullif(trim(substring(content, 56, 20)), '')                                           as SECURITY_DESCRIPTION_LINE_1
  , nullif(trim(substring(content, 76, 20)), '')                                           as SECURITY_DESCRIPTION_LINE_2
  , nullif(trim(substring(content, 96, 20)), '')                                           as SECURITY_DESCRIPTION_LINE_3
  , nullif(trim(substring(content, 116, 20)), '')                                          as SECURITY_DESCRIPTION_LINE_4
  , nullif(trim(substring(content, 136, 20)), '')                                          as SECURITY_DESCRIPTION_LINE_5
  , nullif(trim(substring(content, 156, 20)), '')                                          as SECURITY_DESCRIPTION_LINE_6
  , nullif(trim(substring(content, 176, 8)), '')                                           as ISSUE_DATE
  , nullif(trim(substring(content, 184, 3)), '')                                           as ISSUER_COUNTRY
  , nullif(trim(substring(content, 187, 1)), '')                                           as PRIMARY_EXCHANGE_1
  , nullif(trim(substring(content, 188, 1)), '')                                           as DTC_ELIGIBILITY_CODE
  , nullif(trim(substring(content, 189, 8)), '')                                           as OPTION_RIGHTS_WTS_EXPIRE_DATE
  , nullif(trim(substring(content, 197, 1)), '')                                           as DISTRIBUTION_FREQUENCY_CODE
  , nullif(trim(substring(content, 198, 10)), '')                                          as SECURITY_SHORT_NAME
  , nullif(trim(substring(content, 208, 6)), '')                                           as DATED_DATE
  , nullif(trim(substring(content, 214, 15)), '')                                          as ISIN
  , nullif(trim(substring(content, 229, 15)), '')                                          as SEDOL
  , nullif(trim(substring(content, 244, 3)), '')                                           as CURRENCY_CODE
  , nullif(trim(substring(content, 247, 3)), '')                                           as COUNTRY_CODE
  , nullif(trim(substring(content, 250, 1)), '')                                           as FOREIGN
  , nullif(trim(substring(content, 251, 2)), '')                                           as ISSUER_STATE_CODE
  , nullif(trim(substring(content, 253, 12)), '')                                          as PRODUCT_CODE
  , nullif(trim(substring(content, 265, 1)), '')                                           as UNDERLYING_CUSIP_CODE
  , nullif(trim(substring(content, 266, 9)), '')                                           as UNDERLYING_CUSIP
  , nullif(trim(substring(content, 275, 1)), '')                                           as USER_CUSIP_INDICATOR
  , nullif(trim(substring(content, 276, 1)), '')                                           as PIP_ELIGIBLE
  , nullif(trim(substring(content, 277, 1)), '')                                           as SWP_ELIGIBLE
  , nullif(trim(substring(content, 278, 4)), '')                                           as BASE_INTEREST_DATE
  , nullif(trim(substring(content, 282, 1)), '')                                           as INTEREST_DAYS
  , nullif(trim(substring(content, 283, 6)), '')                                           as FIRST_COUPON_DATE
  , nullif(trim(substring(content, 289, 1)), '')                                           as DEBT_INTEREST_RATE_SIGN
  , nullif(trim(substring(content, 290, 7)), '')                                           as DEBT_INTEREST_RATE
  , nullif(trim(substring(content, 297, 6)), '')                                           as DEBT_MATURITY_DATE_1
  , nullif(trim(substring(content, 303, 1)), '')                                           as BOND_CLASS_CODE
  , nullif(trim(substring(content, 304, 3)), '')                                           as EXCHANGE_GROUP_NUMBER
  , nullif(trim(substring(content, 307, 5)), '')                                           as FUND_FAMILY_NUMBER
  , nullif(trim(substring(content, 312, 20)), '')                                          as FUND_FAMILY_DESCRIPTION
  , nullif(trim(substring(content, 332, 1)), '')                                           as FUND_LOAD_TYPE
  , nullif(trim(substring(content, 333, 1)), '')                                           as FUND_CLASS_OF_SHARES
  , nullif(trim(substring(content, 334, 1)), '')                                           as TYPE_OF_FUND
  , nullif(trim(substring(content, 335, 1)), '')                                           as REORGANIZATION_PENDING_CODE
  , nullif(trim(substring(content, 337, 9)), '')                                           as INITIAL_MINIMUM
  , nullif(trim(substring(content, 346, 9)), '')                                           as SUBSEQUENT_MINIMUM
  , nullif(trim(substring(content, 355, 9)), '')                                           as REDEMPTION_MINIMUM
  , nullif(trim(substring(content, 364, 9)), '')                                           as REDEMPTION_MAXIMUM
  , nullif(trim(substring(content, 373, 1)), '')                                           as RATING_AGENT_CODE_1
  , nullif(trim(substring(content, 374, 5)), '')                                           as RATING_1
  , nullif(trim(substring(content, 379, 1)), '')                                           as RATING_AGENT_CODE_2
  , nullif(trim(substring(content, 380, 5)), '')                                           as RATING_2
  , nullif(trim(substring(content, 385, 1)), '')                                           as RATING_AGENT_CODE_3
  , nullif(trim(substring(content, 386, 5)), '')                                           as RATING_3
  , nullif(trim(substring(content, 391, 10)), '')                                          as CURRENT_FACTOR_AMOUNT
  , nullif(trim(substring(content, 401, 8)), '')                                           as CURRENT_FACTOR_DATE
  , nullif(trim(substring(content, 409, 1)), '')                                           as ZERO_COUPON_INDICATOR
  , nullif(trim(substring(content, 410, 6)), '')                                           as LAST_COUPON_DATE
  , nullif(trim(substring(content, 416, 6)), '')                                           as OPTION_ACTIVITY_BEGIN_DATE
  , nullif(trim(substring(content, 422, 6)), '')                                           as OPTION_ACTIVITY_END_DATE
  , nullif(trim(substring(content, 428, 1)), '')                                           as CBL_COVERED_SECURITY_INDICATOR
  , nullif(trim(substring(content, 429, 8)), '')                                           as CBL_COVERED_SECURITY_EFFECTIVE_DATE
  , nullif(trim(substring(content, 437, 18)), '')                                          as BID_PRICE
  , nullif(trim(substring(content, 455, 18)), '')                                          as ASK_PRICE
  , nullif(trim(substring(content, 473, 18)), '')                                          as CLOSING_MARKET_PRICE
  , nullif(trim(substring(content, 491, 8)), '')                                           as PRICE_DATE
  , nullif(trim(substring(content, 499, 1)), '')                                           as UNFACTORED_PRICE_SIGN
  , nullif(trim(substring(content, 500, 18)), '')                                          as UNFACTORED_PRICE
  , nullif(trim(substring(content, 518, 1)), '')                                           as FACTORED_PRICE_SIGN
  , nullif(trim(substring(content, 519, 18)), '')                                          as FACTORED_PRICE
  , nullif(trim(substring(content, 537, 10)), '')                                          as PREVIOUS_FACTOR_AMOUNT
  , nullif(trim(substring(content, 547, 8)), '')                                           as PREVIOUS_FACTOR_DATE
  , nullif(trim(substring(content, 555, 10)), '')                                          as SECOND_PREVIOUS_FACTOR_AMOUNT
  , nullif(trim(substring(content, 565, 8)), '')                                           as SECOND_PREVIOUS_FACTOR_DATE
  , nullif(trim(substring(content, 573, 3)), '')                                           as DAY_DELAY
  , nullif(trim(substring(content, 576, 1)), '')                                           as CPI_RATIO_SIGN
  , nullif(trim(substring(content, 577, 10)), '')                                          as CPI_RATIO
  , nullif(trim(substring(content, 587, 8)), '')                                           as CPI_RATIO_DATE
  , nullif(trim(substring(content, 595, 1)), '')                                           as DATED_DATE_CPI_SIGN
  , nullif(trim(substring(content, 596, 8)), '')                                           as DATED_DATE_CPI
  , nullif(trim(substring(content, 604, 8)), '')                                           as CURRENT_COUPON_EFFECTIVE_DATE
  , nullif(trim(substring(content, 612, 1)), '')                                           as NEXT_STEPPED_COUPON_RATE_SIGN
  , nullif(trim(substring(content, 613, 7)), '')                                           as NEXT_STEPPED_COUPON_RATE
  , nullif(trim(substring(content, 620, 8)), '')                                           as NEXT_COUPON_RESET_DATE
  , nullif(trim(substring(content, 628, 2)), '')                                           as COUPON_RESET_FREQUENCY
  , nullif(trim(substring(content, 630, 1)), '')                                           as COUPON_RATE_MINIMUM_SIGN
  , nullif(trim(substring(content, 631, 5)), '')                                           as COUPON_RATE_MINIMUM
  , nullif(trim(substring(content, 636, 1)), '')                                           as COUPON_RATE_MAXIMUM_SIGN
  , nullif(trim(substring(content, 637, 5)), '')                                           as COUPON_RATE_MAXIMUM
  , nullif(trim(substring(content, 642, 3)), '')                                           as COUPON_TYPE_CODE
  , nullif(trim(substring(content, 645, 40)), '')                                          as COUPON_FORMULA_TEXT
  , nullif(trim(substring(content, 685, 8)), '')                                           as COUPON_FORMULA_EFFECTIVE_DATE
  , nullif(trim(substring(content, 693, 4)), '')                                           as COUPON_FORMULA_BENCHMARK_SEQUENCE_NUMBER_1
  , nullif(trim(substring(content, 697, 8)), '')                                           as COUPON_FORMULA_BENCHMARK_1
  , nullif(trim(substring(content, 705, 4)), '')                                           as COUPON_FORMULA_BENCHMARK_SEQUENCE_NUMBER_2
  , nullif(trim(substring(content, 709, 8)), '')                                           as COUPON_FORMULA_BENCHMARK_2
  , nullif(trim(substring(content, 717, 4)), '')                                           as COUPON_FORMULA_BENCHMARK_SEQUENCE_NUMBER_3
  , nullif(trim(substring(content, 721, 8)), '')                                           as COUPON_FORMULA_BENCHMARK_3
  , nullif(trim(substring(content, 729, 1)), '')                                           as DEFAULT_TYPE_CODE
  , nullif(trim(substring(content, 730, 8)), '')                                           as DEFAULT_DATE
  , nullif(trim(substring(content, 738, 2)), '')                                           as CALL_FREQUENCY_CODE
  , nullif(trim(substring(content, 740, 1)), '')                                           as MAKE_WHOLE_INDICATOR
  , nullif(trim(substring(content, 741, 1)), '')                                           as EXTRAORDINARY_CALL_INDICATOR
  , nullif(trim(substring(content, 742, 1)), '')                                           as MUNICIPAL_REDEMPTION_TYPE_CODE
  , nullif(trim(substring(content, 743, 30)), '')                                          as MUNICIPAL_REDEMPTION_TYPE_LONG_DESCRIPTION
  , nullif(trim(substring(content, 773, 8)), '')                                           as MANDATORY_PUT_DATE
  , nullif(trim(substring(content, 781, 1)), '')                                           as MANDATORY_PUT_PRICE_SIGN
  , nullif(trim(substring(content, 782, 8)), '')                                           as MANDATORY_PUT_PRICE
  , nullif(trim(substring(content, 790, 8)), '')                                           as NEXT_CALL_DATE
  , nullif(trim(substring(content, 798, 1)), '')                                           as NEXT_CALL_PRICE_SIGN
  , nullif(trim(substring(content, 799, 10)), '')                                          as NEXT_CALL_PRICE
  , nullif(trim(substring(content, 809, 8)), '')                                           as FIRST_PAR_CALL_DATE
  , nullif(trim(substring(content, 817, 1)), '')                                           as FIRST_PAR_CALL_PRICE_SIGN
  , nullif(trim(substring(content, 818, 10)), '')                                          as FIRST_PAR_CALL_PRICE
  , nullif(trim(substring(content, 828, 1)), '')                                           as NEXT_PUT_PRICE_SIGN
  , nullif(trim(substring(content, 829, 10)), '')                                          as NEXT_PUT_PRICE
  , nullif(trim(substring(content, 839, 8)), '')                                           as NEXT_PUT_DATE
  , nullif(trim(substring(content, 847, 3)), '')                                           as CALL_NOTIFICATION_MINIMUM
  , nullif(trim(substring(content, 850, 8)), '')                                           as CONTINUOUSLY_CALLABLE_EFFECTIVE_DATE
  , nullif(trim(substring(content, 858, 8)), '')                                           as NEXT_SINK_DATE
  , nullif(trim(substring(content, 866, 1)), '')                                           as NEXT_SINK_TYPE
  , nullif(trim(substring(content, 867, 1)), '')                                           as NEXT_SINK_PRICE_SIGN
  , nullif(trim(substring(content, 868, 10)), '')                                          as NEXT_SINK_PRICE
  , nullif(trim(substring(content, 878, 1)), '')                                           as NEXT_SINK_AMOUNT_SIGN
  , nullif(trim(substring(content, 879, 8)), '')                                           as NEXT_SINK_AMOUNT
  , nullif(trim(substring(content, 887, 1)), '')                                           as AUCTION_RATE_PREFERRED_INDICATOR
  , nullif(trim(substring(content, 888, 1)), '')                                           as VARIABLE_RATE_INDICATOR
  , nullif(trim(substring(content, 889, 4)), '')                                           as UIT_FUND_FAMILY_CODE
  , nullif(trim(substring(content, 893, 6)), '')                                           as UIT_FUND_FAMILY_SPONSOR
  , nullif(trim(substring(content, 899, 4)), '')                                           as UIT_FUND_FAMILY_NUMBER
  , nullif(trim(substring(content, 903, 1)), '')                                           as REDEMPTION_CALL_INDICATOR
  , nullif(trim(substring(content, 904, 1)), '')                                           as REDEMPTION_PUT_INDICATOR
  , nullif(trim(substring(content, 905, 6)), '')                                           as OPTION_CONTRACT_ID
  , nullif(trim(substring(content, 911, 30)), '')                                          as OPTION_SYMBOL_ID
  , nullif(trim(substring(content, 941, 1)), '')                                           as OPTION_CALL_PUT_INDICATOR
  , nullif(trim(substring(content, 942, 1)), '')                                           as CONVERSION_RATIO_SIGN
  , nullif(trim(substring(content, 943, 6)), '')                                           as CONVERSION_RATIO
  , nullif(trim(substring(content, 949, 2)), '')                                           as PRIMARY_EXCHANGE_2
  , nullif(trim(substring(content, 951, 1)), '')                                           as TRADABLE_FLAG
  , nullif(trim(substring(content, 952, 1)), '')                                           as CALL_DEFEASED_INDICATOR
  , nullif(trim(substring(content, 953, 1)), '')                                           as SINK_DEFEASED_INDICATOR
  , nullif(trim(substring(content, 954, 1)), '')                                           as BANK_QUALIFIED_INDICATOR
  , nullif(trim(substring(content, 955, 1)), '')                                           as ALTERNATIVE_INVESTMENT_INDICATOR
  , nullif(trim(substring(content, 956, 8)), '')                                           as CALLABLE_DATE
  , nullif(trim(substring(content, 964, 1)), '')                                           as MARGIN_CODE
  , nullif(trim(substring(content, 965, 6)), '')                                           as MARGIN_PRICE_EFFECTIVE_DATE
  , nullif(trim(substring(content, 971, 6)), '')                                           as MARGIN_PRICE_EXPIRE_DATE
  , nullif(trim(substring(content, 977, 11)), '')                                          as STRIKE_PRICE
  , nullif(trim(substring(content, 988, 1)), '')                                           as WORTHLESS_SECURITY_INDICATOR
  , nullif(trim(substring(content, 989, 1)), '')                                           as INTEREST_POSTING_CODE
  , nullif(trim(substring(content, 990, 8)), '')                                           as DEBT_MATURITY_DATE_2
  , nullif(trim(substring(content, 998, 6)), '')                                           as LAST_CHANGED_DATE
  , nullif(trim(substring(content, 1004, 1)), '')                                          as MONEY_MARKET_FUND_DESIGNATION
  , {{ col_is_head(reference=src) }}
  , {{ col_is_current(date_col='effective_date') }}
  ,  case when  effective_date = max(effective_date) over (partition by cusip) then 1 else 0 end::int             as IS_CUSIP_HEAD
  , effective_date
  , record_datetime::date as record_date
  , record_datetime::timestamp as record_datetime
  , source_file as source_file
  , record_datetime                                                                         as _source_loaded_at
  , source_file                                                                             as _source_file
from {{ src }}
where 1 = 1
  and left(content, 2) = 'D1'
{%- endmacro -%}