{%- macro fidelity_raw_trdrev_td(src) -%}
select
    trim(substring(content, 28, 3)) || trim(substring(content, 31, 6))                       as ACCOUNT_CUSTODIAL
  , trim(substring(content, 28, 3)) || '-' ||
      trim(substring(content, 31, 6))                                                        as ACCOUNT_CUSTODIAL_FORMATTED
  , nullif(trim(substring(content, 1, 1)), '')                                               as RECORD_NUMBER
  , nullif(trim(substring(content, 2, 4)), '')                                               as FIRM
  , nullif(trim(substring(content, 6, 1)), '')                                               as BUY_SELL_CODE
  , nullif(trim(substring(content, 7, 8)), '')                                               as TRADE_DATE
  , nullif(trim(substring(content, 15, 8)), '')                                              as SETTLEMENT_DATE
  , nullif(trim(substring(content, 23, 1)), '')                                              as MARKET_CODE
  , nullif(trim(substring(content, 24, 1)), '')                                              as BLOTTER_CODE
  , nullif(trim(substring(content, 25, 1)), '')                                              as CANCEL_CODE
  , nullif(trim(substring(content, 27, 1)), '')                                              as CORRECTION_CODE
  , nullif(trim(substring(content, 28, 3)), '')                                              as BRANCH
  , nullif(trim(substring(content, 31, 6)), '')                                              as ACCOUNT_NUMBER
  , nullif(trim(substring(content, 37, 1)), '')                                              as ACCOUNT_TYPE
  , nullif(trim(substring(content, 38, 9)), '')                                              as CUSIP
  , nullif(trim(substring(content, 47, 1)), '')                                              as BASIS_PRICE_CODE
  , nullif(trim(substring(content, 48, 8)), '')                                              as RUN_DATE
  , nullif(trim(substring(content, 56, 11)), '')                                             as TRADE_REFERENCE_NUMBER
  , nullif(trim(substring(content, 67, 11)), '')                                             as USER_REFERENCE_NUMBER
  , nullif(trim(substring(content, 78, 11)), '')                                             as CANCELED_COMBINED_REFERENCE
  , nullif(trim(substring(content, 89, 5)), '')                                              as BATCH
  , nullif(trim(substring(content, 94, 6)), '')                                              as COUNT
  , nullif(trim(substring(content, 100, 16)), '')                                            as SYMBOL
  , nullif(trim(substring(content, 116, 1)), '')                                             as SECURITY_TYPE
  , nullif(trim(substring(content, 117, 1)), '')                                             as SECURITY_TYPE_MODIFIER
  , nullif(trim(substring(content, 118, 1)), '')                                             as SECURITY_TYPE_CALCULATION
  , nullif(trim(substring(content, 119, 1)), '')                                             as CNS_CODE
  , nullif(trim(substring(content, 120, 2)), '')                                             as PRIMARY_EXCHANGE
  , nullif(trim(substring(content, 122, 1)), '')                                             as DTC_ELIGIBILITY_CODE
  , nullif(trim(substring(content, 123, 1)), '')                                             as FOREIGN_CODE
  , nullif(trim(substring(content, 124, 3)), '')                                             as REGISTERED_REP_ENTER_REP
  , nullif(trim(substring(content, 127, 3)), '')                                             as STATE_COUNTRY_CODE
  , nullif(trim(substring(content, 130, 1)), '')                                             as SECURITIES_INSTRUCTIONS
  , nullif(trim(substring(content, 131, 9)), '')                                             as PARENT_ACCOUNT
  , nullif(trim(substring(content, 140, 8)), '')                                             as AGENCY_CODE
  , nullif(trim(substring(content, 148, 1)), '')                                             as PROCEEDS_INSTRUCTIONS
  , nullif(trim(substring(content, 149, 1)), '')                                             as CASH_DIVIDEND_INSTRUCTIONS
  , nullif(trim(substring(content, 150, 1)), '')                                             as TRADE_UNIT
  , nullif(trim(substring(content, 151, 10)), '')                                            as SHORT_NAME
  , nullif(trim(substring(content, 161, 2)), '')                                             as ACCOUNT_CLASSIFICATION
  , nullif(trim(substring(content, 163, 1)), '')                                             as CITIZEN_CODE
  , nullif(trim(substring(content, 164, 3)), '')                                             as COUNTRY_OF_TAX_RESIDENCY
  , nullif(trim(substring(content, 167, 1)), '')                                             as TRANSFER_LEGEND_CODE
  , nullif(trim(substring(content, 168, 1)), '')                                             as MARKET_MAKER_CODE
  , nullif(trim(substring(content, 169, 4)), '')                                             as MINOR_EXECUTING_BROKER
  , nullif(trim(substring(content, 173, 4)), '')                                             as MINOR_CLEARING_BROKER
  , nullif(trim(substring(content, 177, 10)), '')                                            as OFFSET_ACCOUNT
  , nullif(trim(substring(content, 187, 10)), '')                                            as OFFSET_SHORTNAME
  , nullif(trim(substring(content, 197, 3)), '')                                             as OFFSET_RR
  , nullif(trim(substring(content, 200, 10)), '')                                            as OFFSET_COMMISSION
  , nullif(trim(substring(content, 210, 1)), '')                                             as SOURCE
  , nullif(trim(substring(content, 211, 1)), '')                                             as TYPE_OF_ORDER
  , nullif(trim(substring(content, 212, 1)), '')                                             as CONFIRMATION_PRINT
  , nullif(trim(substring(content, 213, 1)), '')                                             as COMMISSION_ACCUMULATION
  , nullif(trim(substring(content, 214, 2)), '')                                             as COMMISSION_SCHEDULE
  , nullif(trim(substring(content, 216, 1)), '')                                             as BLOTTER_OVERRIDE_CODE
  , nullif(trim(substring(content, 217, 1)), '')                                             as NSCC_CODE
  , nullif(trim(substring(content, 218, 1)), '')                                             as COMMISSION_CONCESSION_CODE_1
  , nullif(trim(substring(content, 219, 17)), '')                                            as QUANTITY
  , nullif(trim(substring(content, 236, 18)), '')                                            as PRICE
  , nullif(trim(substring(content, 254, 9)), '')                                             as ALPHAPRICE_DOLLAR
  , nullif(trim(substring(content, 263, 1)), '')                                             as ALPHAPRICE_SPACE
  , nullif(trim(substring(content, 264, 9)), '')                                             as ALPHAPRICE_FRACTION
  , nullif(trim(substring(content, 273, 18)), '')                                            as PLUS_MINUS
  , nullif(trim(substring(content, 291, 15)), '')                                            as PRINCIPAL
  , nullif(trim(substring(content, 306, 13)), '')                                            as ACCRUED_INTEREST
  , nullif(trim(substring(content, 319, 10)), '')                                            as TRADE_COMMISSION
  , nullif(trim(substring(content, 329, 8)), '')                                             as STATE_TAX
  , nullif(trim(substring(content, 337, 8)), '')                                             as SEC_FEE
  , nullif(trim(substring(content, 345, 8)), '')                                             as OPTIONS_REGULATORY_FEE
  , nullif(trim(substring(content, 353, 10)), '')                                            as SERVICE_CHARGE_MISC_FEE
  , nullif(trim(substring(content, 363, 15)), '')                                            as NET
  , nullif(trim(substring(content, 378, 10)), '')                                            as TRADE_CONCESSION
  , nullif(trim(substring(content, 388, 10)), '')                                            as STANDARD_COMMISSION
  , nullif(trim(substring(content, 398, 1)), '')                                             as NUMBER_OF_SECURITY_DESCRIPTION_LINES
  , nullif(trim(substring(content, 399, 20)), '')                                            as SECURITY_DESCRIPTION_LINE_1
  , nullif(trim(substring(content, 419, 20)), '')                                            as SECURITY_DESCRIPTION_LINE_2
  , nullif(trim(substring(content, 439, 20)), '')                                            as SECURITY_DESCRIPTION_LINE_3
  , nullif(trim(substring(content, 459, 20)), '')                                            as SECURITY_DESCRIPTION_LINE_4
  , nullif(trim(substring(content, 479, 20)), '')                                            as SECURITY_DESCRIPTION_LINE_5
  , nullif(trim(substring(content, 499, 20)), '')                                            as SECURITY_DESCRIPTION_LINE_6
  , nullif(trim(substring(content, 519, 20)), '')                                            as SECURITY_DESCRIPTION_LINE_7
  , nullif(trim(substring(content, 539, 20)), '')                                            as SECURITY_DESCRIPTION_LINE_8
  , nullif(trim(substring(content, 559, 20)), '')                                            as SECURITY_DESCRIPTION_LINE_9
  , nullif(trim(substring(content, 579, 2)), '')                                             as CONFIRM_LEGEND_CODE_1
  , nullif(trim(substring(content, 581, 2)), '')                                             as CONFIRM_LEGEND_CODE_2
  , nullif(trim(substring(content, 583, 3)), '')                                             as REGISTERED_REP_EXEC_REP_RR2
  , nullif(trim(substring(content, 586, 10)), '')                                            as COMMISSION_DISCOUNT_PERCENT
  , nullif(trim(substring(content, 596, 9)), '')                                             as STRIKE_PRICE
  , nullif(trim(substring(content, 605, 1)), '')                                             as COMMISSION_CONCESSION_CODE_2
  , nullif(trim(substring(content, 606, 4)), '')                                             as FUND_LOAD_OVERRIDE
  , nullif(trim(substring(content, 610, 1)), '')                                             as QUANTITY_TYPE
  , nullif(trim(substring(content, 611, 1)), '')                                             as CONFIRM_LINE_NUMBER
  , nullif(trim(substring(content, 612, 1)), '')                                             as EXCHANGE_LINE_NUMBER
  , nullif(trim(substring(content, 613, 5)), '')                                             as YIELD
  , nullif(trim(substring(content, 618, 1)), '')                                             as YIELD_TYPE
  , nullif(trim(substring(content, 621, 6)), '')                                             as YIELD_DATE
  , nullif(trim(substring(content, 627, 6)), '')                                             as YIELD_PRICE
  , nullif(trim(substring(content, 633, 1)), '')                                             as TRADING_AWAY_CODE
  , nullif(trim(substring(content, 634, 4)), '')                                             as MAJOR_CLEARING_BROKER
  , nullif(trim(substring(content, 638, 4)), '')                                             as MAJOR_EXECUTING_BROKER
  , nullif(trim(substring(content, 642, 4)), '')                                             as EXECUTION_TIME_1
  , nullif(trim(substring(content, 646, 3)), '')                                             as BRANCH_2
  , nullif(trim(substring(content, 649, 1)), '')                                             as COMPLEX_ORDER_INDICATOR
  , nullif(trim(substring(content, 650, 5)), '')                                             as MARKET_PLACE
  , nullif(trim(substring(content, 655, 6)), '')                                             as MARKET_SEQUENCE
  , nullif(trim(substring(content, 661, 1)), '')                                             as TIME_IN_FORCE_CODE
  , nullif(trim(substring(content, 662, 1)), '')                                             as AUTO_EXEC_CODE
  , nullif(trim(substring(content, 663, 6)), '')                                             as ISSUER
  , nullif(trim(substring(content, 669, 2)), '')                                             as ISSUER_TYPE
  , nullif(trim(substring(content, 671, 4)), '')                                             as BOND_TRADER
  , nullif(trim(substring(content, 675, 1)), '')                                             as BOND_CLASS_CODE
  , nullif(trim(substring(content, 676, 10)), '')                                            as ADDITIONAL_MARKUP
  , nullif(trim(substring(content, 686, 4)), '')                                             as TERMINAL_ID
  , nullif(trim(substring(content, 695, 3)), '')                                             as REGISTERED_REP_SIGNON_REP
  , nullif(trim(substring(content, 698, 3)), '')                                             as REGISTERED_REP_OWNING_REP_RR
  , nullif(trim(substring(content, 701, 4)), '')                                             as FUND_LOAD_PERCENT
  , nullif(trim(substring(content, 705, 12)), '')                                            as PRODUCT_CODE
  , nullif(trim(substring(content, 717, 1)), '')                                             as TRADING_FLAT_CODE
  , nullif(trim(substring(content, 718, 1)), '')                                             as "12B1_CODE"
  , nullif(trim(substring(content, 719, 2)), '')                                             as ADDITIONAL_FEE_CODE_1
  , nullif(trim(substring(content, 721, 12)), '')                                            as ADDITIONAL_FEE_AMOUNT_1
  , nullif(trim(substring(content, 733, 2)), '')                                             as ADDITIONAL_FEE_CODE_2
  , nullif(trim(substring(content, 735, 12)), '')                                            as ADDITIONAL_FEE_AMOUNT_2
  , nullif(trim(substring(content, 747, 2)), '')                                             as ADDITIONAL_FEE_CODE_3
  , nullif(trim(substring(content, 749, 12)), '')                                            as ADDITIONAL_FEE_AMOUNT_3
  , nullif(trim(substring(content, 761, 2)), '')                                             as ADDITIONAL_FEE_CODE_4
  , nullif(trim(substring(content, 763, 12)), '')                                            as ADDITIONAL_FEE_AMOUNT_4
  , nullif(trim(substring(content, 775, 2)), '')                                             as ADDITIONAL_FEE_CODE_5
  , nullif(trim(substring(content, 777, 12)), '')                                            as ADDITIONAL_FEE_AMOUNT_5
  , nullif(trim(substring(content, 789, 2)), '')                                             as ADDITIONAL_FEE_CODE_6
  , nullif(trim(substring(content, 791, 12)), '')                                            as ADDITIONAL_FEE_AMOUNT_6
  , nullif(trim(substring(content, 803, 4)), '')                                             as INSTITUTIONAL_THIRD_PARTY
  , nullif(trim(substring(content, 807, 1)), '')                                             as BORD_TORD_CODE
  , nullif(trim(substring(content, 808, 4)), '')                                             as MUTUAL_FUND_DTC_NUMBER
  , nullif(trim(substring(content, 812, 6)), '')                                             as TRADE_ENTRY
  , nullif(trim(substring(content, 818, 5)), '')                                             as ENTRY_SEQUENCE_NUMBER
  , nullif(trim(substring(content, 823, 1)), '')                                             as SOLICITED_CODE
  , nullif(trim(substring(content, 824, 3)), '')                                             as ELECTRONIC_TRADE_ID
  , nullif(trim(substring(content, 827, 3)), '')                                             as ROLLUP_COUNT
  , nullif(trim(substring(content, 830, 2)), '')                                             as CONFIRM_LEGEND_CODE_3
  , nullif(trim(substring(content, 832, 2)), '')                                             as CONFIRM_LEGEND_CODE_4
  , nullif(trim(substring(content, 834, 12)), '')                                            as RELATIONSHIP_ID
  , nullif(trim(substring(content, 846, 1)), '')                                             as CAPACITY_CODE
  , nullif(trim(substring(content, 847, 2)), '')                                             as CONFIRM_LEGEND_CODE_5
  , nullif(trim(substring(content, 849, 2)), '')                                             as CONFIRM_LEGEND_CODE_6
  , nullif(trim(substring(content, 851, 1)), '')                                             as ALTERNATIVE_INVESTMENT_CODE
  , nullif(trim(substring(content, 852, 9)), '')                                             as EXPANDED_YIELD
  , nullif(trim(substring(content, 861, 1)), '')                                             as EXPANDED_YIELD_SIGN
  , nullif(trim(substring(content, 862, 6)), '')                                             as OPTION_CONTRACT_ID
  , nullif(trim(substring(content, 868, 6)), '')                                             as OPTION_EXPIRATION_DATE
  , nullif(trim(substring(content, 874, 1)), '')                                             as OPTION_CALL_PUT_INDICATOR
  , nullif(trim(substring(content, 875, 8)), '')                                             as OPTION_STRIKE_PRICE
  , nullif(trim(substring(content, 883, 30)), '')                                            as OPTION_SYMBOL_ID
  , nullif(trim(substring(content, 913, 4)), '')                                             as COST_BASIS_DISPOSAL_METHOD_CODE
  , nullif(trim(substring(content, 917, 1)), '')                                             as REVENUE_CLEARING_CHARGE_SIGN
  , nullif(trim(substring(content, 918, 7)), '')                                             as REVENUE_CLEARING_CHARGE_AMOUNT
  , nullif(trim(substring(content, 925, 1)), '')                                             as REVENUE_MISCELLANEOUS_FEE_SIGN
  , nullif(trim(substring(content, 926, 7)), '')                                             as REVENUE_MISCELLANEOUS_FEE_AMOUNT
  , nullif(trim(substring(content, 933, 2)), '')                                             as PRODUCT_LEVEL
  , nullif(trim(substring(content, 935, 1)), '')                                             as CONCESSION_CODE
  , nullif(trim(substring(content, 936, 2)), '')                                             as PURCHASE_TYPE_CODE
  , nullif(trim(substring(content, 938, 1)), '')                                             as TRADE_DEFINITION_TYPE
  , nullif(trim(substring(content, 939, 9)), '')                                             as TRADE_DEFINITION_TRADE_ID
  , nullif(trim(substring(content, 948, 1)), '')                                             as REVENUE_COMMISSION_SIGN
  , nullif(trim(substring(content, 949, 10)), '')                                            as REVENUE_COMMISSION_AMOUNT
  , nullif(trim(substring(content, 959, 1)), '')                                             as REVENUE_CONCESSION_SIGN
  , nullif(trim(substring(content, 960, 10)), '')                                            as REVENUE_CONCESSION_AMOUNT
  , nullif(trim(substring(content, 970, 1)), '')                                             as REVENUE_LOAD_SIGN
  , nullif(trim(substring(content, 971, 10)), '')                                            as REVENUE_LOAD_AMOUNT
  , nullif(trim(substring(content, 981, 11)), '')                                            as ORDER_REFERENCE_NUMBER
  , nullif(trim(substring(content, 992, 1)), '')                                             as INPUT_COMMISSION_SIGN
  , nullif(trim(substring(content, 993, 10)), '')                                            as INPUT_COMMISSION_AMOUNT
  , nullif(trim(substring(content, 1003, 2)), '')                                            as CONFIRM_LEGEND_CODE_7
  , nullif(trim(substring(content, 1005, 2)), '')                                            as CONFIRM_LEGEND_CODE_8
  , nullif(trim(substring(content, 1007, 20)), '')                                           as ORIGINAL_DESCRIPTION_1
  , nullif(trim(substring(content, 1027, 20)), '')                                           as ORIGINAL_DESCRIPTION_2
  , nullif(trim(substring(content, 1047, 6)), '')                                            as EXECUTION_TIME_2
  , nullif(trim(substring(content, 1053, 3)), '')                                            as REGISTERED_REP_PAY_TO_REP
  , nullif(trim(substring(content, 1056, 1)), '')                                            as CLEARING_CHARGE_SIGN
  , nullif(trim(substring(content, 1057, 7)), '')                                            as CLEARING_CHARGE
  , nullif(trim(substring(content, 1064, 1)), '')                                            as EXECUTION_FEE_SIGN
  , nullif(trim(substring(content, 1065, 7)), '')                                            as EXECUTION_FEE
  , nullif(trim(substring(content, 1072, 1)), '')                                            as FOREIGN_SURCHARGE_SIGN
  , nullif(trim(substring(content, 1073, 6)), '')                                            as FOREIGN_SURCHARGE
  , nullif(trim(substring(content, 1079, 4)), '')                                            as SPAWNING_SYSTEM_CODE
  , nullif(trim(substring(content, 1083, 12)), '')                                           as CLEARING_PRODUCT_CODE
  , nullif(trim(substring(content, 1095, 2)), '')                                            as CLEARING_PRODUCT_TYPE
  , nullif(trim(substring(content, 1097, 1)), '')                                            as MANAGED_ACCOUNT_SOLUTIONS_MAS_CUSTODY_INDICATOR
  , nullif(trim(substring(content, 1247, 15)), '')                                           as ISIN
  , nullif(trim(substring(content, 1262, 15)), '')                                           as SEDOL
  , nullif(trim(substring(content, 1277, 3)), '')                                            as CURRENCY_CODE_1
  , nullif(trim(substring(content, 1280, 3)), '')                                            as CURRENCY_CODE_2
  , nullif(trim(substring(content, 1283, 1)), '')                                            as LOCAL_CURRENCY_FEES_SIGN
  , nullif(trim(substring(content, 1284, 18)), '')                                           as LOCAL_CURRENCY_FEES
  , nullif(trim(substring(content, 1302, 1)), '')                                            as LOCAL_CURRENCY_COMMISSION_SIGN
  , nullif(trim(substring(content, 1303, 18)), '')                                           as LOCAL_CURRENCY_COMMISSION
  , nullif(trim(substring(content, 1321, 16)), '')                                           as LOCAL_CURRENCY_PRICE
  , nullif(trim(substring(content, 1337, 1)), '')                                            as LOCAL_CURRENCY_PRINCIPAL_SIGN
  , nullif(trim(substring(content, 1338, 18)), '')                                           as LOCAL_CURRENCY_PRINCIPAL
  , nullif(trim(substring(content, 1356, 1)), '')                                            as LOCAL_CURRENCY_INTEREST_SIGN
  , nullif(trim(substring(content, 1357, 18)), '')                                           as LOCAL_CURRENCY_INTEREST
  , nullif(trim(substring(content, 1375, 1)), '')                                            as LOCAL_CURRENCY_CAPITALIZED_INTEREST_SIGN
  , nullif(trim(substring(content, 1376, 18)), '')                                           as LOCAL_CURRENCY_CAPITALIZED_INTEREST
  , nullif(trim(substring(content, 1394, 16)), '')                                           as REPORTING_CURRENCY_CONVERSION_PRICE
  , nullif(trim(substring(content, 1410, 1)), '')                                            as FX_TRADE_INDICATOR
  , nullif(trim(substring(content, 1411, 30)), '')                                           as FX_TRADE_LINK
  , nullif(trim(substring(content, 1441, 4)), '')                                            as SHADO_COUNTRY_CODE
  , nullif(trim(substring(content, 1445, 1)), '')                                            as LOCAL_CURRENCY_CONCESSION_SIGN
  , nullif(trim(substring(content, 1446, 18)), '')                                           as LOCAL_CURRENCY_CONCESSION
  , nullif(trim(substring(content, 1464, 16)), '')                                           as REPORTING_CURRENCY_CONVERSION_RATE
  , {{ col_is_head(reference=src) }}
  , {{ col_is_current(date_col='effective_date') }}
  , effective_date, record_datetime::date as record_date, record_datetime::timestamp as record_datetime, source_file as source_file
  , record_datetime                                                                         as _source_loaded_at
  , source_file                                                                             as _source_file
from {{ src }}
where 1 = 1
  and left(content, 1) = 'D'
{%- endmacro -%}