{% macro fidelity_raw_actvyd_activity(src) -%}
select
    trim(substring(content, 2, 3)) || trim(substring(content, 5, 6))                      as ACCOUNT_CUSTODIAL
  , trim(substring(content, 2, 3)) || '-' || trim(substring(content, 5, 6))               as ACCOUNT_CUSTODIAL_FORMATTED
  , nullif(trim(substring(content, 1, 1)), '')                                            as RECORD_NUMBER
  , nullif(trim(substring(content, 2, 3)), '')                                            as BRANCH
  , nullif(trim(substring(content, 5, 6)), '')                                            as ACCOUNT_NUMBER
  , nullif(trim(substring(content, 11, 1)), '')                                           as ACCOUNT_TYPE
  , nullif(trim(substring(content, 12, 9)), '')                                           as CUSIP
  , nullif(trim(substring(content, 21, 2)), '')                                           as KEY_CODE
  , nullif(trim(substring(content, 23, 3)), '')                                           as TRANSACTION_TYPE_MNEMONIC
  , nullif(trim(substring(content, 26, 6)), '')                                           as BKPG_REFERENCE_NUMBER
  , nullif(trim(substring(content, 32, 8)), '')                                           as RUN_DATE
  , nullif(trim(substring(content, 40, 8)), '')                                           as ENTRY_DATE
  , nullif(trim(substring(content, 48, 1)), '')                                           as OFFSET_ACCT_TYPE
  , nullif(trim(substring(content, 49, 13)), '')                                          as BOOKKEEPING_QUANTITY
  , nullif(trim(substring(content, 62, 1)), '')                                           as BOOKKEEPING_QUANTITY_SIGN
  , nullif(trim(substring(content, 63, 11)), '')                                          as BOOKKEEPING_AMOUNT
  , nullif(trim(substring(content, 74, 1)), '')                                           as BOOKKEEPING_AMOUNT_SIGN
  , nullif(trim(substring(content, 75, 11)), '')                                          as BOOKKEEPING_MARKET_VALUE
  , nullif(trim(substring(content, 86, 1)), '')                                           as BOOKKEEPING_MARKET_VALUE_SIGN
  , nullif(trim(substring(content, 87, 1)), '')                                           as NUMBER_OF_SECURITY_DESCRIPTION_LINES
  , nullif(trim(substring(content, 88, 20)), '')                                          as BKPG_DESCRIPTION_LINE_1
  , nullif(trim(substring(content, 108, 20)), '')                                         as BKPG_DESCRIPTION_LINE_2
  , nullif(trim(substring(content, 128, 20)), '')                                         as BKPG_DESCRIPTION_LINE_3
  , nullif(trim(substring(content, 148, 20)), '')                                         as BKPG_DESCRIPTION_LINE_4
  , nullif(trim(substring(content, 168, 20)), '')                                         as BKPG_DESCRIPTION_LINE_5
  , nullif(trim(substring(content, 188, 20)), '')                                         as BKPG_DESCRIPTION_LINE_6
  , nullif(trim(substring(content, 208, 20)), '')                                         as BKPG_DESCRIPTION_LINE_7
  , nullif(trim(substring(content, 228, 20)), '')                                         as BKPG_DESCRIPTION_LINE_8
  , nullif(trim(substring(content, 248, 20)), '')                                         as BKPG_DESCRIPTION_LINE_9
  , nullif(trim(substring(content, 268, 8)), '')                                          as TRADE_DATE
  , nullif(trim(substring(content, 276, 1)), '')                                          as SECURITIES_INSTRUCTIONS
  , nullif(trim(substring(content, 277, 1)), '')                                          as TRANSFER_LEGEND_CODE
  , nullif(trim(substring(content, 278, 9)), '')                                          as ALPHAPRICE_DOLLAR
  , nullif(trim(substring(content, 287, 1)), '')                                          as ALPHAPRICE_SPACE
  , nullif(trim(substring(content, 288, 9)), '')                                          as ALPHAPRICE_FRACTION
  , nullif(trim(substring(content, 297, 9)), '')                                          as ACCRUED_INTEREST
  , nullif(trim(substring(content, 306, 1)), '')                                          as BOOKKEEPING_ACCRUED_INTEREST_SIGN
  , nullif(trim(substring(content, 307, 7)), '')                                          as COMMISSION
  , nullif(trim(substring(content, 314, 1)), '')                                          as COMMISSION_SIGN
  , nullif(trim(substring(content, 315, 10)), '')                                         as CONCESSION
  , nullif(trim(substring(content, 325, 1)), '')                                          as CONCESSION_SIGN
  , nullif(trim(substring(content, 326, 1)), '')                                          as BUY_SELL_CODE
  , nullif(trim(substring(content, 327, 1)), '')                                          as MARKET_CODE
  , nullif(trim(substring(content, 328, 1)), '')                                          as BLOTTER_CODE
  , nullif(trim(substring(content, 329, 1)), '')                                          as TRADE_TYPE
  , nullif(trim(substring(content, 330, 1)), '')                                          as CANCEL_CODE
  , nullif(trim(substring(content, 331, 1)), '')                                          as BKPG_CORRECTION_CODE
  , nullif(trim(substring(content, 332, 5)), '')                                          as BATCH
  , nullif(trim(substring(content, 337, 3)), '')                                          as REGISTERED_REP_ENTER_REP
  , nullif(trim(substring(content, 340, 1)), '')                                          as SECURITY_TYPE
  , nullif(trim(substring(content, 341, 1)), '')                                          as SECURITY_TYPE_MODIFIER
  , nullif(trim(substring(content, 342, 1)), '')                                          as SECURITY_TYPE_CALCULATION
  , nullif(trim(substring(content, 343, 1)), '')                                          as ORDER_TYPE
  , nullif(trim(substring(content, 344, 8)), '')                                          as AGENCY_CODE
  , nullif(trim(substring(content, 352, 3)), '')                                          as REGISTERED_REP_OWNING_REP_RR
  , nullif(trim(substring(content, 355, 3)), '')                                          as REGISTERED_REP_EXEC_REP_RR2
  , nullif(trim(substring(content, 358, 1)), '')                                          as MULTI_CURRENCY_INDICATOR
  , nullif(trim(substring(content, 359, 8)), '')                                          as CONSOLIDATED_PRIME_BROKER_FEES
  , nullif(trim(substring(content, 367, 30)), '')                                         as OPTION_SYMBOL_ID
  , nullif(trim(substring(content, 397, 6)), '')                                          as OPTION_CONTRACT_ID
  , nullif(trim(substring(content, 403, 6)), '')                                          as OPTION_EXPIRATION_DATE
  , nullif(trim(substring(content, 409, 1)), '')                                          as OPTION_CALL_PUT_INDICATOR
  , nullif(trim(substring(content, 410, 8)), '')                                          as OPTION_STRIKE_PRICE
  , nullif(trim(substring(content, 418, 15)), '')                                         as PRINCIPAL
  , nullif(trim(substring(content, 433, 1)), '')                                          as PRINCIPAL_SIGN
  , nullif(trim(substring(content, 434, 18)), '')                                         as PRICE
  , nullif(trim(substring(content, 452, 1)), '')                                          as PRICE_SIGN
  , nullif(trim(substring(content, 453, 10)), '')                                         as PRORATED_COMMISSION
  , nullif(trim(substring(content, 463, 1)), '')                                          as PRORATED_COMMISSION_SIGN
  , nullif(trim(substring(content, 464, 8)), '')                                          as STATE_TAX
  , nullif(trim(substring(content, 472, 1)), '')                                          as STATE_TAX_SIGN
  , nullif(trim(substring(content, 473, 8)), '')                                          as TICKET_CHARGE
  , nullif(trim(substring(content, 481, 1)), '')                                          as TICKET_CHARGE_SIGN
  , nullif(trim(substring(content, 482, 8)), '')                                          as OPTIONS_REGULATORY_FEE
  , nullif(trim(substring(content, 490, 1)), '')                                          as OPTIONS_REGULATORY_FEE_SIGN
  , nullif(trim(substring(content, 491, 4)), '')                                          as FUND_LOAD_PERCENT
  , nullif(trim(substring(content, 495, 4)), '')                                          as FUND_LOAD_OVERRIDE
  , nullif(trim(substring(content, 499, 8)), '')                                          as SEC_FEE
  , nullif(trim(substring(content, 507, 1)), '')                                          as SEC_FEE_SIGN
  , nullif(trim(substring(content, 508, 10)), '')                                         as SERVICE_CHARGE_MISC_FEE
  , nullif(trim(substring(content, 518, 1)), '')                                          as SERVICE_CHARGE_MISC_FEE_SIGN
  , nullif(trim(substring(content, 519, 2)), '')                                          as ADDITIONAL_FEE_CODE_1
  , nullif(trim(substring(content, 521, 12)), '')                                         as ADDITIONAL_FEE_AMOUNT_1
  , nullif(trim(substring(content, 533, 1)), '')                                          as ADDITIONAL_FEE_AMOUNT_SIGN_1
  , nullif(trim(substring(content, 534, 2)), '')                                          as ADDITIONAL_FEE_CODE_2
  , nullif(trim(substring(content, 536, 12)), '')                                         as ADDITIONAL_FEE_AMOUNT_2
  , nullif(trim(substring(content, 548, 1)), '')                                          as ADDITIONAL_FEE_AMOUNT_SIGN_2
  , nullif(trim(substring(content, 549, 2)), '')                                          as ADDITIONAL_FEE_CODE_3
  , nullif(trim(substring(content, 551, 12)), '')                                         as ADDITIONAL_FEE_AMOUNT_3
  , nullif(trim(substring(content, 563, 1)), '')                                          as ADDITIONAL_FEE_AMOUNT_SIGN_3
  , nullif(trim(substring(content, 564, 2)), '')                                          as ADDITIONAL_FEE_CODE_4
  , nullif(trim(substring(content, 566, 12)), '')                                         as ADDITIONAL_FEE_AMOUNT_4
  , nullif(trim(substring(content, 578, 1)), '')                                          as ADDITIONAL_FEE_AMOUNT_SIGN_4
  , nullif(trim(substring(content, 579, 2)), '')                                          as ADDITIONAL_FEE_CODE_5
  , nullif(trim(substring(content, 581, 12)), '')                                         as ADDITIONAL_FEE_AMOUNT_5
  , nullif(trim(substring(content, 593, 1)), '')                                          as ADDITIONAL_FEE_AMOUNT_SIGN_5
  , nullif(trim(substring(content, 594, 2)), '')                                          as ADDITIONAL_FEE_CODE_6
  , nullif(trim(substring(content, 596, 12)), '')                                         as ADDITIONAL_FEE_AMOUNT_6
  , nullif(trim(substring(content, 608, 1)), '')                                          as ADDITIONAL_FEE_AMOUNT_SIGN_6
  , nullif(trim(substring(content, 609, 4)), '')                                          as MINOR_EXECUTING_BROKER
  , nullif(trim(substring(content, 613, 4)), '')                                          as MINOR_CLEARING_BROKER
  , nullif(trim(substring(content, 617, 4)), '')                                          as MAJOR_EXECUTING_BROKER
  , nullif(trim(substring(content, 621, 4)), '')                                          as MAJOR_CLEARING_BROKER
  , nullif(trim(substring(content, 625, 10)), '')                                         as CHECK_NUMBER
  , nullif(trim(substring(content, 635, 3)), '')                                          as TRUST_ACCOUNT_TAX_CODE
  , nullif(trim(substring(content, 638, 50)), '')                                         as TRUST_ACCOUNT_TRANSACTION_CATEGORY
  , nullif(trim(substring(content, 688, 30)), '')                                         as TRUST_ACCOUNT_ADDITIONAL_DESCRIPTION
  , nullif(trim(substring(content, 718, 17)), '')                                         as BOOKKEEPING_QUANTITY_EXPANDED
  , nullif(trim(substring(content, 735, 1)), '')                                          as BOOKKEEPING_QUANTITY_SIGN_EXPANDED
  , nullif(trim(substring(content, 736, 15)), '')                                         as BOOKKEEPING_AMOUNT_EXPANDED
  , nullif(trim(substring(content, 751, 1)), '')                                          as BOOKKEEPING_AMOUNT_SIGN_EXPANDED
  , nullif(trim(substring(content, 752, 15)), '')                                         as BOOKKEEPING_MARKET_VALUE_EXPANDED
  , nullif(trim(substring(content, 767, 1)), '')                                          as BOOKKEEPING_MARKET_VALUE_SIGN_EXPANDED
  , nullif(trim(substring(content, 768, 13)), '')                                         as ACCRUED_INTEREST_EXPANDED
  , nullif(trim(substring(content, 781, 1)), '')                                          as BOOKKEEPING_ACCRUED_INTEREST_SIGN_EXPANDED
  , nullif(trim(substring(content, 782, 10)), '')                                         as COMMISSION_EXPANDED
  , nullif(trim(substring(content, 792, 1)), '')                                          as COMMISSION_SIGN_EXPANDED
  , nullif(trim(substring(content, 868, 15)), '')                                         as ISIN
  , nullif(trim(substring(content, 883, 15)), '')                                         as SEDOL
  , nullif(trim(substring(content, 898, 3)), '')                                          as CURRENCY_CODE_1
  , nullif(trim(substring(content, 901, 3)), '')                                          as CURRENCY_CODE_2
  , nullif(trim(substring(content, 904, 16)), '')                                         as LOCAL_CURRENCY_PRICE
  , nullif(trim(substring(content, 920, 18)), '')                                         as LOCAL_CURRENCY_FEES
  , nullif(trim(substring(content, 938, 1)), '')                                          as LOCAL_CURRENCY_FEES_SIGN
  , nullif(trim(substring(content, 939, 16)), '')                                         as REPORTING_CURRENCY_CONVERSION_RATE
  , nullif(trim(substring(content, 955, 10)), '')                                         as SHADO_PARENT_NUMBER
  , nullif(trim(substring(content, 965, 2)), '')                                          as SHADO_CHILD_NUMBER
  , nullif(trim(substring(content, 967, 16)), '')                                         as REPORTING_CURRENCY_CONVERSION_PRICE
  , nullif(trim(substring(content, 983, 1)), '')                                          as FX_TRADE_INDICATOR
  , nullif(trim(substring(content, 984, 30)), '')                                         as FX_TRADE_LINK
  , nullif(trim(substring(content, 1014, 4)), '')                                         as SHADO_COUNTRY_CODE
  , nullif(trim(substring(content, 1018, 18)), '')                                        as LOCAL_CURRENCY_PRINCIPAL
  , nullif(trim(substring(content, 1036, 1)), '')                                         as LOCAL_CURRENCY_PRINCIPAL_SIGN
  , nullif(trim(substring(content, 1037, 18)), '')                                        as LOCAL_CURRENCY_COMMISSION
  , nullif(trim(substring(content, 1055, 1)), '')                                         as LOCAL_CURRENCY_COMMISSION_SIGN
  , nullif(trim(substring(content, 1056, 18)), '')                                        as LOCAL_CURRENCY_INTEREST
  , nullif(trim(substring(content, 1074, 1)), '')                                         as LOCAL_CURRENCY_INTEREST_SIGN
  , {{ col_is_head(reference=src) }}
  , {{ col_is_current(date_col='effective_date') }}
  , effective_date
  , record_datetime                                                                         as _source_loaded_at
  , source_file                                                                             as _source_file
from {{ src }}
where 1 = 1
  and left(content, 1) = 'D'
{%- endmacro %}