version: 2

sources:
  - name: lifi
    description: ""
    database: "{{ var('db_devops_src', env_var('DBT_DB_DEVOPS_SRC', 'devops')) }}"
    tables:
      - name: estate_item_temp_lifi
        description: ""
