select
    'orion' as pms
    , 'hayes' as pms_location
    , 'mwa' AS firm_source
    , effective_date
    , client_id
    , registration_id
    , account_id
    , first_name
    , last_name
    , client_name
    , reg_name
    , reg_l_name
    , reg_f_name
    , reg_dob
    , rep_account_manager
    , rep_name
    , rep_number
    , address1
    , address2
    , address3
    , city
    , state
    , zip
    , email
    , phone_home
    , phone_business
    , statement_transmit_method
    , reg_description
    , fund_name
    , account_number
    , mgmt_style
    , fee_schedule
    , fee_type
    , master_payout_schedule
    , pay_method_instruction
    , bill_frequency
    , bill_style
    , custodian
    , outside_id
    , subadvisorname
    , is_performance_billed
    , last_performance_bill_date
    , createddate
    , createdby
    , editeddate
    , investmentobjective
    , planname
    , plansponsor
    , planadministratorname
    , account_start_date
    , bill_start_date
    , fkplan
    , current_value
    , pkacct_that_does_paying
    , percent_paid_by_account
    , acct_value_that_does_paying
    , acct_no_that_does_paying
    , time_horizon
    , return_objective
    , stock_percentage
    , risk_tolerance
    , risk_budget
    , model_name
    , bd_name
    , valuation_method
    , credit_remaining
    , salutation
    , net_worth
    , cycle_month
    , isqual
    , is_trading_blocked
    , trade_instruction
    , business_line
    , custodian_code
    , plan_number
    , mgmt_style_code
    , sub_advisor_code
    , additional_charge_credit_amount
    , additional_charge_credit_type
    , model_group_num
    , minimum_inception_date
    , true_account_start_date
    , reponsible_party
    , account_status
    , include_in_qpe
    , include_in_twr
    , billingnonmgdacctno
    , billingnonmgdacctname
    , billingnonmgdclient
    , ssn
    , isaccountactive
    , isclientactive
    , branchid
    , clientcreateddate
    , lasttrxdate
    , lastinvoicecreationdate
    , fkaccounthistory
    , firstinvestdate
    , as_of_date
    , download_source
    , acctstartvalue
    , sleeve_account
    , isdiscretionary
    , adv_reportable
    , is13f_reportable
    , {{ col_is_head(reference=source('orion_hayes', 'audit_all_accounts_19206_history')) }}
    , {{ col_is_current(date_col='effective_date') }}
    , record_datetime as _source_loaded_at
from {{ source('orion_hayes', 'audit_all_accounts_19206_history') }}