select
    id                             as id
  , dn                             as dn
  , rdn                            as rdn
  , basedn                         as basedn
  , instancetype                   as instancetype
  , ntsecuritydescriptor           as ntsecuritydescriptor
  , objectcategory                 as objectcategory
  , objectclass                    as objectclass
  , samaccountname                 as samaccountname
  , accountexpires                 as accountexpires
  , accountnamehistory             as accountnamehistory
  , acspolicyname                  as acspolicyname
  , streetaddress                  as streetaddress
  , homepostaladdress              as homepostaladdress
  , admincount                     as admincount
  , admindescription               as admindescription
  , admindisplayname               as admindisplayname
  , allowedattributes              as allowedattributes
  , allowedattributeseffective     as allowedattributeseffective
  , allowedchildclasses            as allowedchildclasses
  , allowedchildclasseseffective   as allowedchildclasseseffective
  , altsecurityidentities          as altsecurityidentities
  , assistant                      as assistant
  , badpasswordtime                as badpasswordtime
  , badpwdcount                    as badpwdcount
  , bridgeheadserverlistbl         as bridgeheadserverlistbl
  , canonicalname                  as canonicalname
  , codepage                       as codepage
  , info                           as info
  , cn                             as cn
  , company                        as company
  , controlaccessrights            as controlaccessrights
  , countrycode                    as countrycode
  , c                              as c
  , createtimestamp                as createtimestamp
  , dbcspwd                        as dbcspwd
  , defaultclassstore              as defaultclassstore
  , department                     as department
  , description                    as description
  , desktopprofile                 as desktopprofile
  , destinationindicator           as destinationindicator
  , displayname                    as displayname
  , displaynameprintable           as displaynameprintable
  , division                       as division
  , dsasignature                   as dsasignature
  , dscorepropagationdata          as dscorepropagationdata
  , dynamicldapserver              as dynamicldapserver
  , mail                           as mail
  , employeeid                     as employeeid
  , employeenumber                 as employeenumber
  , employeetype                   as employeetype
  , extensionname                  as extensionname
  , facsimiletelephonenumber       as facsimiletelephonenumber
  , flags                          as flags
  , fromentry                      as fromentry
  , frscomputerreferencebl         as frscomputerreferencebl
  , frsmemberreferencebl           as frsmemberreferencebl
  , fsmoroleowner                  as fsmoroleowner
  , garbagecollperiod              as garbagecollperiod
  , generationqualifier            as generationqualifier
  , givenname                      as givenname
  , groupmembershipsam             as groupmembershipsam
  , grouppriority                  as grouppriority
  , groupstoignore                 as groupstoignore
  , homedirectory                  as homedirectory
  , homedrive                      as homedrive
  , initials                       as initials
  , internationalisdnnumber        as internationalisdnnumber
  , iscriticalsystemobject         as iscriticalsystemobject
  , isdeleted                      as isdeleted
  , isprivilegeholder              as isprivilegeholder
  , lastknownparent                as lastknownparent
  , lastlogoff                     as lastlogoff
  , lastlogon                      as lastlogon
  , lmpwdhistory                   as lmpwdhistory
  , localeid                       as localeid
  , l                              as l
  , lockouttime                    as lockouttime
  , thumbnaillogo                  as thumbnaillogo
  , logoncount                     as logoncount
  , logonhours                     as logonhours
  , logonworkstation               as logonworkstation
  , managedobjects                 as managedobjects
  , manager                        as manager
  , masteredby                     as masteredby
  , maxstorage                     as maxstorage
  , mhsoraddress                   as mhsoraddress
  , modifytimestamp                as modifytimestamp
  , "MS-DS-CONSISTENCYCHILDCOUNT"  as "MS-DS-CONSISTENCYCHILDCOUNT"
  , "MS-DS-CONSISTENCYGUID"        as "MS-DS-CONSISTENCYGUID"
  , "MS-DS-CREATORSID"             as "MS-DS-CREATORSID"
  , msmqdigests                    as msmqdigests
  , msmqdigestsmig                 as msmqdigestsmig
  , msmqsigncertificates           as msmqsigncertificates
  , msmqsigncertificatesmig        as msmqsigncertificatesmig
  , msnpallowdialin                as msnpallowdialin
  , msnpcallingstationid           as msnpcallingstationid
  , msnpsavedcallingstationid      as msnpsavedcallingstationid
  , msradiuscallbacknumber         as msradiuscallbacknumber
  , msradiusframedipaddress        as msradiusframedipaddress
  , msradiusframedroute            as msradiusframedroute
  , msradiusservicetype            as msradiusservicetype
  , msrassavedcallbacknumber       as msrassavedcallbacknumber
  , msrassavedframedipaddress      as msrassavedframedipaddress
  , msrassavedframedroute          as msrassavedframedroute
  , netbootscpbl                   as netbootscpbl
  , networkaddress                 as networkaddress
  , nonsecuritymemberbl            as nonsecuritymemberbl
  , ntpwdhistory                   as ntpwdhistory
  , distinguishedname              as distinguishedname
  , objectguid                     as objectguid
  , objectsid                      as objectsid
  , objectversion                  as objectversion
  , operatorcount                  as operatorcount
  , ou                             as ou
  , o                              as o
  , otherloginworkstations         as otherloginworkstations
  , othermailbox                   as othermailbox
  , middlename                     as middlename
  , otherwellknownobjects          as otherwellknownobjects
  , partialattributedeletionlist   as partialattributedeletionlist
  , partialattributeset            as partialattributeset
  , personaltitle                  as personaltitle
  , otherfacsimiletelephonenumber  as otherfacsimiletelephonenumber
  , otherhomephone                 as otherhomephone
  , homephone                      as homephone
  , otheripphone                   as otheripphone
  , ipphone                        as ipphone
  , primaryinternationalisdnnumber as primaryinternationalisdnnumber
  , othermobile                    as othermobile
  , mobile                         as mobile
  , othertelephone                 as othertelephone
  , otherpager                     as otherpager
  , pager                          as pager
  , physicaldeliveryofficename     as physicaldeliveryofficename
  , thumbnailphoto                 as thumbnailphoto
  , possibleinferiors              as possibleinferiors
  , postaladdress                  as postaladdress
  , postalcode                     as postalcode
  , postofficebox                  as postofficebox
  , preferreddeliverymethod        as preferreddeliverymethod
  , preferredou                    as preferredou
  , primarygroupid                 as primarygroupid
  , profilepath                    as profilepath
  , proxiedobjectname              as proxiedobjectname
  , proxyaddresses                 as proxyaddresses
  , pwdlastset                     as pwdlastset
  , querypolicybl                  as querypolicybl
  , name                           as name
  , registeredaddress              as registeredaddress
  , repluptodatevector             as repluptodatevector
  , directreports                  as directreports
  , repsfrom                       as repsfrom
  , repsto                         as repsto
  , revision                       as revision
  , rid                            as rid
  , samaccounttype                 as samaccounttype
  , scriptpath                     as scriptpath
  , sdrightseffective              as sdrightseffective
  , securityidentifier             as securityidentifier
  , seealso                        as seealso
  , serverreferencebl              as serverreferencebl
  , serviceprincipalname           as serviceprincipalname
  , showinaddressbook              as showinaddressbook
  , showinadvancedviewonly         as showinadvancedviewonly
  , sidhistory                     as sidhistory
  , siteobjectbl                   as siteobjectbl
  , st                             as st
  , street                         as street
  , subrefs                        as subrefs
  , subschemasubentry              as subschemasubentry
  , supplementalcredentials        as supplementalcredentials
  , sn                             as sn
  , systemflags                    as systemflags
  , telephonenumber                as telephonenumber
  , teletexterminalidentifier      as teletexterminalidentifier
  , telexnumber                    as telexnumber
  , primarytelexnumber             as primarytelexnumber
  , terminalserver                 as terminalserver
  , co                             as co
  , textencodedoraddress           as textencodedoraddress
  , title                          as title
  , unicodepwd                     as unicodepwd
  , useraccountcontrol             as useraccountcontrol
  , usercert                       as usercert
  , comment                        as comment
  , userparameters                 as userparameters
  , userpassword                   as userpassword
  , userprincipalname              as userprincipalname
  , usersharedfolder               as usersharedfolder
  , usersharedfolderother          as usersharedfolderother
  , usersmimecertificate           as usersmimecertificate
  , userworkstations               as userworkstations
  , usnchanged                     as usnchanged
  , usncreated                     as usncreated
  , usndsalastobjremoved           as usndsalastobjremoved
  , usnintersite                   as usnintersite
  , usnlastobjrem                  as usnlastobjrem
  , usnsource                      as usnsource
  , wbempath                       as wbempath
  , wellknownobjects               as wellknownobjects
  , whenchanged                    as whenchanged
  , whencreated                    as whencreated
  , wwwhomepage                    as wwwhomepage
  , url                            as url
  , x121address                    as x121address
  , usercertificate                as usercertificate
  , record_datetime                as record_datetime
  , record_date                    as record_date
from {{ source('active_directory_mwa', 'user_history') }}
where record_datetime in (
                             select max(record_datetime)
                             from {{ source('active_directory_mwa', 'user_history') }}
                         )