version: 2

sources:
  - name: copilot
    description: ""
    database: "{{ var('db_devops_src', env_var('DBT_DB_DEVOPS_SRC', 'devops')) }}"
    schema: fixflyer_options
    tables:
      - name: allocations
        description: ""
      - name: positions
        description: ""
      - name: groups
        description: "Raw groups data from copilot"
      - name: models
        description: "Raw models data from copilot"
      - name: restrictions
        description: "Raw security restrictions data from copilot"
      - name: accounts
        description: ""
      - name: sod_salesforce_accounts
        description: "Salesforce estate item table."