version: 2
models:
  - name: fixflyer_options__stg_groups
    columns:
      - name: GROUP_NAME
        description: ''
        data_type: VARCHAR
      - name: GROUP_DESCRIPTION
        description: ''
        data_type: VARCHAR
      - name: GROUP_ID
        description: ''
        data_type: VARCHAR
      - name: GROUP_TYPE
        description: ''
        data_type: VARCHAR
      - name: GROUPS
        description: ''
        data_type: VARCHAR
      - name: GROUP_CUST_ID
        description: ''
        data_type: VARCHAR
      - name: PARENT_GROUP_ID
        description: ''
        data_type: VARCHAR
      - name: USER_ID
        description: ''
        data_type: NUMBER
      - name: ACCOUNT_DETAIL
        description: ''
        data_type: VARCHAR
      - name: ACCOUNT_ID
        description: ''
        data_type: NUMBER
      - name: ACCOUNT_NUMBER
        description: ''
        data_type: VARCHAR
      - name: ACCOUNT_NAME
        description: ''
        data_type: VARCHAR
      - name: IS_CASH_ACCOUNT
        description: ''
        data_type: NUMBER
      - name: CASH_RESERVE
        description: ''
        data_type: FLOAT
      - name: CASH_RESERVE_EXPIRATION_DATE
        description: ''
        data_type: DATE
      - name: CASH_RESERVE_EXPIRATION
        description: ''
        data_type: VARCHAR
      - name: COMPLIANCE_RULES
        description: ''
        data_type: VARCHAR
      - name: ACCOUNT_CUST_ID
        description: ''
        data_type: VARCHAR
      - name: CUSTODIAN
        description: ''
        data_type: VARCHAR
      - name: IS_DISABLE_SLEEVES
        description: ''
        data_type: NUMBER
      - name: END_DATE
        description: ''
        data_type: DATE
      - name: IS_EXPLICIT_SLEEVE
        description: ''
        data_type: NUMBER
      - name: ACCOUNT_GROUP_ID
        description: ''
        data_type: NUMBER
      - name: HOUSEHOLD_ID
        description: ''
        data_type: NUMBER
      - name: IMPORT_DATE
        description: ''
        data_type: DATE
      - name: LONG_NAME
        description: ''
        data_type: VARCHAR
      - name: LONG_TERM_TAX_RATE
        description: ''
        data_type: FLOAT
      - name: MODEL_ID
        description: ''
        data_type: NUMBER
      - name: MODEL_NAME
        description: ''
        data_type: VARCHAR
      - name: ACCOUNT_NAME_2
        description: ''
        data_type: VARCHAR
      - name: NOTES
        description: ''
        data_type: VARCHAR
      - name: PERCENT_OR_VALUE
        description: ''
        data_type: FLOAT
      - name: SHORT_TERM_TAX_RATE
        description: ''
        data_type: FLOAT
      - name: START_DATE
        description: ''
        data_type: DATE
      - name: TAX_LOT_RELIEF_METHOD
        description: ''
        data_type: VARCHAR
      - name: IS_TAXABLE
        description: ''
        data_type: NUMBER
      - name: IS_HEAD
        description: ''
        data_type: NUMBER
      - name: IS_LATEST
        description: ''
        data_type: NUMBER
      - name: _CREATED_AT
        description: ''
        data_type: TIMESTAMP_NTZ
      - name: _SOURCE_FILE
        description: ''
        data_type: VARCHAR
      - name: _URI
        description: ''
        data_type: VARCHAR
