version: 2
models:
  - name: fixflyer_options__stg_models
    columns:
      - name: MODEL_ID
        description: ''
        data_type: NUMBER
      - name: CUST_ID
        description: ''
        data_type: NUMBER
      - name: MODEL_NAME
        description: ''
        data_type: VARCHAR
      - name: IS_MASTER_MODEL
        description: ''
        data_type: NUMBER
      - name: PERCENT_OR_SHARES
        description: ''
        data_type: FLOAT
      - name: PERCENT
        description: ''
        data_type: FLOAT
      - name: ASSET_TYPE
        description: ''
        data_type: VARCHAR
      - name: CONTENTS_MODEL_ID
        description: ''
        data_type: NUMBER
      - name: SECURITY_ID
        description: ''
        data_type: VARCHAR
      - name: CONTENTS_PERCENT
        description: ''
        data_type: FLOAT
      - name: SHARE_PERCENT
        description: ''
        data_type: FLOAT
      - name: QUANTITY
        description: ''
        data_type: FLOAT
      - name: PRICE
        description: ''
        data_type: FLOAT
      - name: VALUE
        description: ''
        data_type: FLOAT
      - name: PRODUCT
        description: ''
        data_type: NUMBER
      - name: CUSIP
        description: ''
        data_type: VARCHAR
      - name: IS_UPDATED
        description: ''
        data_type: NUMBER
      - name: LAST_MODIFIED_AT
        description: ''
        data_type: TIMESTAMP_NTZ
      - name: IS_HEAD
        description: ''
        data_type: NUMBER
      - name: IS_LATEST
        description: ''
        data_type: NUMBER
      - name: _CREATED_AT
        description: ''
        data_type: TIMESTAMP_NTZ
      - name: _SOURCE_FILE
        description: ''
        data_type: VARCHAR
      - name: _URI
        description: ''
        data_type: VARCHAR
