select
    id
    , dn
    , rdn
    , basedn
    , grouptype
    , instancetype
    , ntsecuritydescriptor
    , objectcategory
    , objectclass
    , samaccountname
    , accountnamehistory
    , admincount
    , admindescription
    , admindisplayname
    , allowedattributes
    , allowedattributeseffective
    , allowedchildclasses
    , allowedchildclasseseffective
    , altsecurityidentities
    , bridgeheadserverlistbl
    , canonicalname
    , info
    , cn
    , controlaccessrights
    , createtimestamp
    , description
    , desktopprofile
    , displayname
    , displaynameprintable
    , dsasignature
    , dscorepropagationdata
    , mail
    , extensionname
    , flags
    , fromentry
    , frscomputerreferencebl
    , frsmemberreferencebl
    , fsmoroleowner
    , garbagecollperiod
    , groupattributes
    , groupmembershipsam
    , iscriticalsystemobject
    , isdeleted
    , isprivilegeholder
    , lastknownparent
    , legacyexchangedn
    , managedby
    , managedobjects
    , masteredby
    , member
    , modifytimestamp
    , "MS-DS-CONSISTENCYCHILDCOUNT"--noqa: RF05
    , "MS-DS-CONSISTENCYGUID"--noqa: RF05
    , netbootscpbl
    , nonsecuritymember
    , nonsecuritymemberbl
    , ntgroupmembers
    , distinguishedname
    , objectguid
    , objectsid
    , objectversion
    , operatorcount
    , otherwellknownobjects
    , partialattributedeletionlist
    , partialattributeset
    , possibleinferiors
    , primarygrouptoken
    , proxiedobjectname
    , proxyaddresses
    , querypolicybl
    , name
    , repluptodatevector
    , directreports
    , repsfrom
    , repsto
    , revision
    , rid
    , samaccounttype
    , sdrightseffective
    , securityidentifier
    , serverreferencebl
    , showinaddressbook
    , showinadvancedviewonly
    , sidhistory
    , siteobjectbl
    , subrefs
    , subschemasubentry
    , supplementalcredentials
    , systemflags
    , telephonenumber
    , textencodedoraddress
    , usercert
    , usersmimecertificate
    , usnchanged
    , usncreated
    , usndsalastobjremoved
    , usnintersite
    , usnlastobjrem
    , usnsource
    , wbempath
    , wellknownobjects
    , whenchanged
    , whencreated
    , wwwhomepage
    , url
    , usercertificate
    , record_datetime
    , record_date
from {{ source('active_directory_mwa', 'groups_history') }}
where record_datetime in (
        select max(t.record_datetime)
        from {{ source('active_directory_mwa', 'groups_history') }} as t
    )
