select
    ci.clientname                               as clientname
  , content:fkalclient::integer                 as fkalclient
  , content:pkfundfamily::integer               as pkfundfamily
  , content:fkpersonal::integer                 as fkpersonal
  , content:fundname::varchar(255)              as fundname
  , content:isannuity::boolean::int             as isannuity
  , content:iscanbedownload::boolean::int       as iscanbedownload
  , content:oldgroup::varchar(10)               as oldgroup
  , content:oldff_id::integer                   as oldff_id
  , content:fkperscontact::integer              as fkperscontact
  , content:fkpersovernt::integer               as fkpersovernt
  , content:speeddial::varchar(20)              as speeddial
  , content:tradeinstr::varchar(300)            as tradeinstr
  , content:isactive::boolean::int              as isactive
  , content:ffcreateddate::date                 as ffcreateddate
  , content:ffcreatedby::varchar(30)            as ffcreatedby
  , content:editeddate::date                    as editeddate
  , content:editedby::varchar(30)               as editedby
  , content:timestampfundfamily::varchar(200)   as timestampfundfamily
  , content:vendor::varchar(60)                 as vendor
  , content:status::varchar(60)                 as status
  , content:restrictionnotes::varchar(600)      as restrictionnotes
  , content:reregistrationnotes::varchar(600)   as reregistrationnotes
  , content:cstoperationhours::varchar(30)      as cstoperationhours
  , content:isphonetrade::boolean::int          as isphonetrade
  , content:isfaxtrade::boolean::int            as isfaxtrade
  , content:isuploadtrade::boolean::int         as isuploadtrade
  , content:isconfirmphone::boolean::int        as isconfirmphone
  , content:isconfirminternet::boolean::int     as isconfirminternet
  , content:isconfirmfundserv::boolean::int     as isconfirmfundserv
  , content:isconfirmaps::boolean::int          as isconfirmaps
  , content:isconfirmother::boolean::int        as isconfirmother
  , content:confirmnotes::varchar(600)          as confirmnotes
  , content:downloadmethod::varchar(20)         as downloadmethod
  , content:downloadnotes::varchar(600)         as downloadnotes
  , content:custfundserve::varchar(30)          as custfundserve
  , content:directfundserve::varchar(30)        as directfundserve
  , content:trader::varchar(30)                 as trader
  , content:unitbalancescale::integer           as unitbalancescale
  , content:pricescale::integer                 as pricescale
  , content:isacctnumunique::boolean::int       as isacctnumunique
  , content:isnetworkingeligible::boolean::int  as isnetworkingeligible
  , content:isshareclasssensitive::boolean::int as isshareclasssensitive
  , content:sungardbrokerid::integer            as sungardbrokerid
  , content:isdefault::boolean::int             as isdefault
  , content:iscreatedistribution::boolean::int  as iscreatedistribution
  , content:fkblobsignature::integer            as fkblobsignature
  , content:createddate::timestamp              as createddate
  , a.effective_at::date                        as effective_date
  , a._pk::varchar(200)                         as _pk
  , a._client::int                              as _client
  , a._extracted_at                             as _extracted_at
  , {{ col_is_head(reference=source('orion', 'vw_fundfamily'), source_date_col='a.effective_at', reference_date_col='effective_at') }}
  , {{ col_is_current(date_col='a.effective_at::date') }}
  , a._is_full::int                             as _is_full
  , a._created_at                               as _created_at
  , a._source_file                              as _source_file
  , a._checksum                                 as _checksum
from {{ source('orion', 'vw_fundfamily') }} a
join {{ ref('orion__base_vw_clientinfo') }}     ci
     on a._client::int = ci.pkalclient
