select
    ci.clientname                              as clientname
  , content:fkalclient::integer                as fkalclient
  , content:pkbillaccountitem::integer         as pkbillaccountitem
  , content:fkbillaccount::integer             as fkbillaccount
  , content:fkbillstatus::integer              as fkbillstatus
  , content:fkbilltype::integer                as fkbilltype
  , content:fkbillinstance::integer            as fkbillinstance
  , content:fkpayforaccount::integer           as fkpayforaccount
  , content:fkhighasset::integer               as fkhighasset
  , content:cinitialamt::double                as cinitialamt
  , content:cbalancedue::double                as cbalancedue
  , content:dtcalcdate::date                   as dtcalcdate
  , content:isvalid::boolean::int              as isvalid
  , content:ctotalmktvalue::double             as ctotalmktvalue
  , content:dailyaccrualperc::double           as dailyaccrualperc
  , content:dtstartdate::date                  as dtstartdate
  , content:dtenddate::date                    as dtenddate
  , content:idaysincycle::integer              as idaysincycle
  , content:oldreceivableid::integer           as oldreceivableid
  , content:asofdate::date                     as asofdate
  , content:basis::integer                     as basis
  , content:aggregateval::double               as aggregateval
  , content:feeperc::double                    as feeperc
  , content:error::varchar(250)                as error
  , content:feeschedule::varchar(60)           as feeschedule
  , content:buildcomplete::boolean::int        as buildcomplete
  , content:payforperc::double                 as payforperc
  , content:fktempaccountitem::integer         as fktempaccountitem
  , content:appliedadj::double                 as appliedadj
  , content:daysinyear::integer                as daysinyear
  , content:billfrequency::integer             as billfrequency
  , content:paymethod::varchar(30)             as paymethod
  , content:fkaccountstamp::integer            as fkaccountstamp
  , content:flatfee::double                    as flatfee
  , content:howbilled::integer                 as howbilled
  , content:lastcollectattempt::date           as lastcollectattempt
  , content:payoutaggval::double               as payoutaggval
  , content:payoutbasis::integer               as payoutbasis
  , content:transfermktvalue::double           as transfermktvalue
  , content:indirectlink::integer              as indirectlink
  , content:receivableguid::varchar(50)        as receivableguid
  , content:note::varchar(300)                 as note
  , content:fkbilladjtype::integer             as fkbilladjtype
  , content:fkbillentity::integer              as fkbillentity
  , content:fkbillpayment::integer             as fkbillpayment
  , content:cprevbalance::double               as cprevbalance
  , content:ccurrbalance::double               as ccurrbalance
  , content:cchangeamt::double                 as cchangeamt
  , content:dtdateoccured::date                as dtdateoccured
  , content:fkpaidforbyaccount::integer        as fkpaidforbyaccount
  , content:fkgeneralaccountdetailsrc::integer as fkgeneralaccountdetailsrc
  , content:fkgeneralaccountdetailadj::integer as fkgeneralaccountdetailadj
  , content:addlannualamt::double              as addlannualamt
  , content:addlannualamttype::integer         as addlannualamttype
  , content:fktraderequest::integer            as fktraderequest
  , content:fktransaction::integer             as fktransaction
  , content:billaiediteddate::date             as billaiediteddate
  , content:billaieditedby::varchar(200)       as billaieditedby
  , content:billaicreateddate::date            as billaicreateddate
  , content:billaicreatedby::varchar(200)      as billaicreatedby
  , content:islocked::boolean::int             as islocked
  , content:createddate::timestamp             as createddate
  , a.effective_at::date                       as effective_date
  , a._pk::varchar(200)                        as _pk
  , a._client::int                             as _client
  , a._extracted_at                            as _extracted_at
  , {{ col_is_head(reference=source('orion', 'stg_vw_billaccountitem'), source_date_col='a.effective_at', reference_date_col='effective_at') }}
  , {{ col_is_current(date_col='a.effective_at::date') }}
  , a._is_full::int                            as _is_full
  , a._created_at                              as _created_at
  , a._source_file                             as _source_file
  , a._checksum                                as _checksum
from {{ source('orion', 'stg_vw_billaccountitem') }} a
join {{ ref('orion__base_vw_clientinfo') }}          ci
     on a._client::int = ci.pkalclient
