select
    ci.clientname                                as clientname
  , content:fkalclient::integer                  as fkalclient
  , content:pkbillaccount::integer               as pkbillaccount
  , content:fkbillregistration::integer          as fkbillregistration
  , content:fkbillpaymethod::integer             as fkbillpaymethod
  , content:fkbillfeeschedule::integer           as fkbillfeeschedule
  , content:fkaccount::integer                   as fkaccount
  , content:fkbillpayoutschedule::integer        as fkbillpayoutschedule
  , content:editeddate::date                     as editeddate
  , content:editedby::varchar(150)               as editedby
  , content:billacctcreateddate::date            as billacctcreateddate
  , content:billacctcreatedby::varchar(150)      as billacctcreatedby
  , content:scustodialacctnum::varchar(60)       as scustodialacctnum
  , content:sabanumber::varchar(30)              as sabanumber
  , content:sbankacctnum::varchar(30)            as sbankacctnum
  , content:sbankname::varchar(60)               as sbankname
  , content:snameonacct::varchar(60)             as snameonacct
  , content:screditcardnumber::varchar(300)      as screditcardnumber
  , content:icyclemonth::integer                 as icyclemonth
  , content:ibillfrequency::integer              as ibillfrequency
  , content:sexpdate::varchar(20)                as sexpdate
  , content:snameoncard::varchar(60)             as snameoncard
  , content:scardtype::varchar(30)               as scardtype
  , content:snmacctnum::varchar(60)              as snmacctnum
  , content:snmacctname::varchar(60)             as snmacctname
  , content:snmclientname::varchar(60)           as snmclientname
  , content:isactive::boolean::int               as isactive
  , content:ibillingstyle::integer               as ibillingstyle
  , content:fkbillmasterpayoutschedule::integer  as fkbillmasterpayoutschedule
  , content:acceptslist::boolean::int            as acceptslist
  , content:feeformcount::integer                as feeformcount
  , content:lastperfbilldate::date               as lastperfbilldate
  , content:isperformancebilled::boolean::int    as isperformancebilled
  , content:fkperffeeschedule::integer           as fkperffeeschedule
  , content:fkperfmasterpayoutschedule::integer  as fkperfmasterpayoutschedule
  , content:billstartdate::date                  as billstartdate
  , content:useminfee::boolean::int              as useminfee
  , content:valuemethod::integer                 as valuemethod
  , content:addlannualamt::double                as addlannualamt
  , content:addlannualamttype::integer           as addlannualamttype
  , content:fkbilladjtype::integer               as fkbilladjtype
  , content:fkbillentity::integer                as fkbillentity
  , content:creditcardnoencryption::varchar(300) as creditcardnoencryption
  , content:addr1::varchar(300)                  as addr1
  , content:addr2::varchar(300)                  as addr2
  , content:addr3::varchar(300)                  as addr3
  , content:city::varchar(50)                    as city
  , content:state::varchar(3)                    as state
  , content:zip::varchar(20)                     as zip
  , content:includeinaggregate::boolean::int     as includeinaggregate
  , content:fkbillaccountstatus::integer         as fkbillaccountstatus
  , content:tieredfeepriority::integer           as tieredfeepriority
  , content:usefeehierarchy::boolean::int        as usefeehierarchy
  , content:createddate::timestamp               as createddate
  , a.effective_at::date                         as effective_date
  , a._pk::varchar(200)                          as _pk
  , a._client::int                               as _client
  , a._extracted_at                              as _extracted_at
  , {{ col_is_head(reference=source('orion', 'stg_vw_billaccount'), source_date_col='a.effective_at', reference_date_col='effective_at') }}
  , {{ col_is_current(date_col='a.effective_at::date') }}
  , a._is_full::int                              as _is_full
  , a._created_at                                as _created_at
  , a._source_file                               as _source_file
  , a._checksum                                  as _checksum
from {{ source('orion', 'stg_vw_billaccount') }} a
join {{ ref('orion__base_vw_clientinfo') }}      ci
     on a._client::int = ci.pkalclient
