select
    ci.clientname                                 as clientname
  , content:fkalclient::integer                   as fkalclient
  , content:pkpersonal::integer                   as pkpersonal
  , content:fname::varchar(30)                    as fname
  , content:lname::varchar(255)                   as lname
  , content:entityname::varchar(255)              as entityname
  , content:addr1::varchar(255)                   as addr1
  , content:addr2::varchar(255)                   as addr2
  , content:addr3::varchar(255)                   as addr3
  , content:city::varchar(30)                     as city
  , content:state::char(2)                        as state
  , content:zip::varchar(10)                      as zip
  , content:phhome::varchar(15)                   as phhome
  , content:phhomeext::varchar(10)                as phhomeext
  , content:phbus::varchar(15)                    as phbus
  , content:phbusext::varchar(10)                 as phbusext
  , content:phmobile::varchar(15)                 as phmobile
  , content:phfax::varchar(15)                    as phfax
  , content:phfaxext::varchar(10)                 as phfaxext
  , content:phother::varchar(15)                  as phother
  , content:photherext::varchar(10)               as photherext
  , content:phpager::varchar(15)                  as phpager
  , content:phpagerext::varchar(10)               as phpagerext
  , content:email::varchar(200)                   as email
  , content:webaddress::varchar(255)              as webaddress
  , content:salutation::varchar(50)               as salutation
  , content:ssn_taxid::varchar(15)                as ssn_taxid
  , content:dob::varchar(20)                      as dob
  , content:issmoker::boolean::int                as issmoker
  , content:sex::char(1)                          as sex
  , content:marital::varchar(50)                  as marital
  , content:prefix::varchar(50)                   as prefix
  , content:suffix::varchar(50)                   as suffix
  , content:entitytype::integer                   as entitytype
  , content:personalcreateddate::date             as personalcreateddate
  , content:personalcreatedby::varchar(40)        as personalcreatedby
  , content:editeddate::date                      as editeddate
  , content:editedby::varchar(40)                 as editedby
  , content:fkparent::integer                     as fkparent
  , content:personaldesc::varchar(50)             as personaldesc
  , content:isactive::boolean::int                as isactive
  , content:jobtitle::varchar(200)                as jobtitle
  , content:isblockedpersonoverride::boolean::int as isblockedpersonoverride
  , content:isuscitizen::boolean::int             as isuscitizen
  , content:company::varchar(255)                 as company
  , content:twitterusername::varchar(50)          as twitterusername
  , content:facebookurl::varchar(8000)            as facebookurl
  , content:fkblobphoto::integer                  as fkblobphoto
  , content:reportname::varchar(255)              as reportname
  , content:isusresident::boolean::int            as isusresident
  , content:country::varchar(150)                 as country
  , content:ismobileverified::boolean::int        as ismobileverified
  , content:fkpersonalglobal::integer             as fkpersonalglobal
  , content:jsonpayload::varbinary                as jsonpayload
  , content:hashvalue::varbinary                  as hashvalue
  , content:deceasedssn_taxid::varchar(15)        as deceasedssn_taxid
  , content:createddate::timestamp                as createddate
  , a.effective_at::date                          as effective_date
  , a._pk::varchar(200)                           as _pk
  , a._client::int                                as _client
  , a._extracted_at                               as _extracted_at
  , {{ col_is_head(reference=source('orion', 'vw_personal'), source_date_col='a.effective_at', reference_date_col='effective_at') }}
  , {{ col_is_current(date_col='a.effective_at::date') }}
  , a._is_full::int                               as _is_full
  , a._created_at                                 as _created_at
  , a._source_file                                as _source_file
  , a._checksum                                   as _checksum
from {{ source('orion', 'vw_personal') }} a
join {{ ref('orion__base_vw_clientinfo') }}   ci
     on a._client::int = ci.pkalclient
