select
    ci.clientname                                  as clientname
    , ci.system_name                               as system_name
    , ci.system_instance                           as system_instance
    , ci.system_key                                as system_key
    , ci.firm_source                               as firm_source
    , a.content:fkalclient::integer                as fkalclient
    , a.content:pkbillaccountitem::integer         as pkbillaccountitem
    , a.content:fkbillaccount::integer             as fkbillaccount
    , a.content:fkbillstatus::integer              as fkbillstatus
    , a.content:fkbilltype::integer                as fkbilltype
    , a.content:fkbillinstance::integer            as fkbillinstance
    , a.content:fkpayforaccount::integer           as fkpayforaccount
    , a.content:fkhighasset::integer               as fkhighasset
    , a.content:cinitialamt::double                as cinitialamt
    , a.content:cbalancedue::double                as cbalancedue
    , a.content:dtcalcdate::date                   as dtcalcdate
    , a.content:isvalid::boolean::int              as isvalid
    , a.content:ctotalmktvalue::double             as ctotalmktvalue
    , a.content:dailyaccrualperc::double           as dailyaccrualperc
    , a.content:dtstartdate::date                  as dtstartdate
    , a.content:dtenddate::date                    as dtenddate
    , a.content:idaysincycle::integer              as idaysincycle
    , a.content:oldreceivableid::integer           as oldreceivableid
    , a.content:asofdate::date                     as asofdate
    , a.content:basis::integer                     as basis
    , a.content:aggregateval::double               as aggregateval
    , a.content:feeperc::double                    as feeperc
    , a.content:error::varchar(250)                as error
    , a.content:feeschedule::varchar(60)           as feeschedule
    , a.content:buildcomplete::boolean::int        as buildcomplete
    , a.content:payforperc::double                 as payforperc
    , a.content:fktempaccountitem::integer         as fktempaccountitem
    , a.content:appliedadj::double                 as appliedadj
    , a.content:daysinyear::integer                as daysinyear
    , a.content:billfrequency::integer             as billfrequency
    , a.content:paymethod::varchar(30)             as paymethod
    , a.content:fkaccountstamp::integer            as fkaccountstamp
    , a.content:flatfee::double                    as flatfee
    , a.content:howbilled::integer                 as howbilled
    , a.content:lastcollectattempt::date           as lastcollectattempt
    , a.content:payoutaggval::double               as payoutaggval
    , a.content:payoutbasis::integer               as payoutbasis
    , a.content:transfermktvalue::double           as transfermktvalue
    , a.content:indirectlink::integer              as indirectlink
    , a.content:receivableguid::varchar(50)        as receivableguid
    , a.content:note::varchar(300)                 as note
    , a.content:fkbilladjtype::integer             as fkbilladjtype
    , a.content:fkbillentity::integer              as fkbillentity
    , a.content:fkbillpayment::integer             as fkbillpayment
    , a.content:cprevbalance::double               as cprevbalance
    , a.content:ccurrbalance::double               as ccurrbalance
    , a.content:cchangeamt::double                 as cchangeamt
    , a.content:dtdateoccured::date                as dtdateoccured
    , a.content:fkpaidforbyaccount::integer        as fkpaidforbyaccount
    , a.content:fkgeneralaccountdetailsrc::integer as fkgeneralaccountdetailsrc
    , a.content:fkgeneralaccountdetailadj::integer as fkgeneralaccountdetailadj
    , a.content:addlannualamt::double              as addlannualamt
    , a.content:addlannualamttype::integer         as addlannualamttype
    , a.content:fktraderequest::integer            as fktraderequest
    , a.content:fktransaction::integer             as fktransaction
    , a.content:billaiediteddate::date             as billaiediteddate
    , a.content:billaieditedby::varchar(200)       as billaieditedby
    , a.content:billaicreateddate::date            as billaicreateddate
    , a.content:billaicreatedby::varchar(200)      as billaicreatedby
    , a.content:islocked::boolean::int             as islocked
    , a.content:createddate::timestamp             as createddate
    , a.effective_at::date                         as effective_date
    , a._pk::varchar(200)                          as _pk

    , a._extracted_at::timestamp_ntz               as _extracted_at
    , {{ col_is_head(reference=source('orion', 'vw_billaccountitem'),
        source_date_col='a.effective_at',
        reference_date_col='effective_at') }}
    , {{ col_is_current(date_col='a.effective_at::date') }}
    , a._is_full::int                              as _is_full
    , a._created_at::timestamp_ntz                 as _created_at
    , a._source_file                               as _source_file
    , a._checksum                                  as _checksum
from {{ source('orion', 'vw_billaccountitem') }} as a
inner join {{ ref('orion__base_vw_clientinfo') }} as ci
    on a.content:fkalclient::int = ci.pkalclient
