
select
   value:c1::string as company_name,
   value:c2::string as last_name,
   value:c3::string as first_name,
   value:c4::string as street,
   value:c5::string as address_2,
   value:c6::string as address_3,
   value:c7::string as address_4,
   value:c8::string as address_5,
   value:c9::string as address_6,
   value:c10::string as city,
   value:c11::string as state,
   value:c12::number as zip_code,
   value:c13::number as ssn,
   value:c14::string as account_number,
   value:c15::string as advisor_id,
   value:c16::string as taxable,
   value:c17::number as phone_number,
   value:c18::number as fax_number,
   value:c19::string as account_type,
   value:c20::string as objective,
   value:c21::string as billing_account_number,
   value:c22::string as default_account,
   value:c23::boolean as state_of_primary_residence,
   value:c24::date as performance_inception_date,
   value:c25::date as billing_inception_date,
   value:c26::string as federal_tax_rate,
   value:c27::string as state_tax_rate,
   value:c28::string as months_in_short_term_holding_period,
   value:c29::string as fiscal_year_end,
   value:c30::decimal(19, 6) as use_average_cost_accounting,
   value:c31::decimal(19, 6) as display_accrued_interest,
   value:c32::decimal(19, 6) as display_accrued_dividends,
   value:c33::decimal(19, 6) as display_accrued_gains,
   value:c34::date as birth_date,
   value:c35::double as discount_rate,
   value:c36::double as payout_rate,
   effective_date::date as effective_date,
   file_type::string as file_type
from {{ source('tda_mwa', 'demographics') }}