select
    id
  , campaign_id
  , user_id
  , salutation
  , first_name
  , last_name
  , email
  , password
  , company
  , website
  , job_title
  , department
  , country
  , address_one
  , address_two
  , city
  , state
  , territory
  , zip
  , phone
  , fax
  , source
  , annual_revenue
  , employees
  , industry
  , years_in_business
  , comments
  , notes
  , score
  , grade
  , is_permanently_deleted
  , last_activity_at
  , recent_interaction
  , crm_lead_fid
  , crm_contact_fid
  , crm_owner_fid
  , crm_account_fid
  , crm_last_sync
  , crm_url
  , prospect_account_id
  , is_do_not_email
  , is_do_not_call
  , opted_out
  , is_reviewed
  , is_starred
  , created_at
  , updated_at
  , _fivetran_deleted
  , custom_contact_record_type
  , custom_salesforce_fid
  , custom_marketing_owner
  , _fivetran_synced
  , custom_digital_marketing_opt_out_retirement_
  , custom_digital_marketing_opt_out_asset_management_
  , custom_digital_marketing_campaigns_wealth_
  , custom_digital_marketing_opt_out_wealth_
  , custom_digital_marketing_options_wealth_
  , custom_marketing_record_type
  , custom_birthdate::date as custom_birthdate
  , custom_tags
  , custom_age::float as custom_age
  , custom_force_sync
  , custom_marketing_account
  , custom_digital_marketing_options_retirement_
  , custom_type_of_retiree_quiz_
  , custom_digital_marketing_campaigns_retirement_
  , custom_drip_campaign_list
  , custom_college
  , custom_date_of_death
  , custom_lead_source_wealth_
  , custom_are_you_a_
  , custom_wealth_contact_lifecycle
  , custom_contact_notes
  , custom_digital_marketing_options_river_point_
  , custom_retirement_contact_lifecycle
  , custom_investment_objectives
  , custom_current_client
  , custom_have_children_you_claim_as_dependents
  , custom_aware_of_the_impact_of_tcja
  , custom_who_prepares_your_taxes
  , custom_age_range::text as custom_age_range
  , custom_tax_bracket
  , custom_any_questions_or_concerns_we_could_answer
  , custom_nickname
  , custom_original_oppty_stage
  , custom_years_until_retirement
  , deleted
from {{ source('pardot', 'prospect') }}