select
    system_name
    , system_instance
    , system_key
    , firm_source
    , location_code
    , office_name
    , client_location_code
    , client_office_name
    , invoice_created_at
    , invoice_date
    , revenue_period_end_date
    , revenue_quarter_end_date
    , invoice_number_source
    , billing_statement_id_source
    , invoice_status
    , is_mid_cycle_invoice
    , client_id_pms
    , advisor_manager_type
    , fee_type
    , client_fee_net
    , sales_tax
    , third_party_calculation
    , billing_frequency
    , billing_style
    , account_class
    , impacted_by_financial_markets
    , coa_segment_1_legal_entity_id
    , coa_segment_2_product_id
    , coa_segment_3_accounting_id
    , coa_segment_4_team_id
    , coa_segment_5_natural_account_id
    , coa_segment_6_initiative_id
    , coa_segment_7_intercompany_id
    , coa_segment_8_future_id
    , coa_account_number
    , revenue_category
    , revenue_type
    , system_name_crm
    , system_instance_crm
    , system_key_crm
    , client_id_crm
    , client_name
    , transaction_type
    , transaction_line_type
    , transaction_line_quantity
    , currency_code
    , currency_conversion_type
    , unit_selling_price
    , is_reversed
    , reversed_date
    , is_excluded
    , excluded_reasons
    , _invoice_key
    , _created_at
    , _source_file
    , _box_file_id
    , is_legacy
    , _extra_fields
from {{ ref('nml_bills_cch') }}
