select
    comment::varchar(100)                                     as comment
  , position_id::varchar(100)                                 as position_id
  , start_date::text                                          as start_date
  , end_date::text                                            as end_date
  , is_deleted::int                                           as is_deleted
  , associate_id::varchar(50)                                 as associate_id
  , employee_id::varchar(50)                                  as employee_id
  , employee_num::varchar(50)                                 as employee_num
  , employment_status::varchar(50)                            as employment_status
  , vol_invol::varchar(50)                                    as vol_invol
  , change_reason_code::varchar(50)                           as change_reason_code
  , change_reason_description::varchar(100)                   as change_reason_description
  , hire_details::varchar(100)                                as hire_details
  , source::varchar(100)                                      as source
  , job_function_code::varchar(100)                           as job_function_code
  , associate_original_hire_date::text                        as associate_original_hire_date
  , associate_rehire_date::text                               as associate_rehire_date
  , associate_final_termination_date::text                    as associate_final_termination_date
  , associate_legal_name_first::varchar(100)                  as associate_legal_name_first
  , associate_legal_name_middle::varchar(100)                 as associate_legal_name_middle
  , associate_legal_name_last::varchar(100)                   as associate_legal_name_last
  , associate_legal_name_full::varchar(100)                   as associate_legal_name_full
  , associate_preferred_name::varchar(100)                    as associate_preferred_name
  , associate_legal_name_suffix::varchar(100)                 as associate_legal_name_suffix
  , associate_birth_date::text                                as associate_birth_date
  , associate_gender_code::varchar(100)                       as associate_gender_code
  , associate_gender_name::varchar(100)                       as associate_gender_name
  , associate_personal_email::varchar(100)                    as associate_personal_email
  , associate_personal_phone::varchar(100)                    as associate_personal_phone
  , associate_personal_cell_phone::varchar(100)               as associate_personal_cell_phone
  , associate_legal_address_line1::varchar(100)               as associate_legal_address_line1
  , associate_legal_address_line2::varchar(100)               as associate_legal_address_line2
  , associate_legal_address_city::varchar(100)                as associate_legal_address_city
  , associate_legal_address_state_abb::varchar(100)           as associate_legal_address_state_abb
  , associate_legal_address_state::varchar(100)               as associate_legal_address_state
  , associate_legal_address_zip_code::varchar(100)            as associate_legal_address_zip_code
  , associate_legal_address_country::varchar(100)             as associate_legal_address_country
  , associate_other_address_line1::varchar(100)               as associate_other_address_line1
  , associate_other_address_line2::varchar(100)               as associate_other_address_line2
  , associate_other_address_city::varchar(100)                as associate_other_address_city
  , associate_other_address_state_abb::varchar(100)           as associate_other_address_state_abb
  , associate_other_address_state::varchar(100)               as associate_other_address_state
  , associate_other_address_zip_code::varchar(100)            as associate_other_address_zip_code
  , associate_other_address_country::varchar(100)             as associate_other_address_country
  , associate_eeo_ethnicity::varchar(100)                     as associate_eeo_ethnicity
  , associate_eeo_identification_method::varchar(100)         as associate_eeo_identification_method
  , associate_education::varchar(100)                         as associate_education
  , associate_work_email::varchar(100)                        as associate_work_email
  , associate_work_phone::varchar(100)                        as associate_work_phone
  , associate_work_cell_phone::varchar(100)                   as associate_work_cell_phone
  , position_company_code::varchar(100)                       as position_company_code
  , position_status_code::varchar(100)                        as position_status_code
  , position_status::varchar(100)                             as position_status
  , position_seniority_hire_date::text                        as position_seniority_hire_date
  , position_start_date::text                                 as position_start_date
  , position_termination_date::text                           as position_termination_date
  , position_change_reason::varchar(100)                      as position_change_reason
  , position_region_code::varchar(100)                        as position_region_code
  , position_region_description::varchar(100)                 as position_region_description
  , position_region_name::varchar(100)                        as position_region_name
  , position_manager_position_id::varchar(100)                as position_manager_position_id
  , position_manager_name::varchar(100)                       as position_manager_name
  , position_primary_job_indicator::varchar(100)::int         as position_primary_job_indicator
  , position_title::varchar(100)                              as position_title
  , position_title_code::varchar(100)                         as position_title_code
  , ee_code::varchar(100)                                     as ee_code
  , position_worker_type::varchar(100)                        as position_worker_type
  , position_benefits_group_code::varchar(100)                as position_benefits_group_code
  , position_benefits_group_class::varchar(100)               as position_benefits_group_class
  , position_flsa::varchar(100)                               as position_flsa
  , position_full_time_equivalent::varchar(100)               as position_full_time_equivalent
  , position_scheduled_hours::varchar(100)                    as position_scheduled_hours
  , position_standard_hours::varchar(100)                     as position_standard_hours
  , position_work_site_location_code::varchar(100)            as position_work_site_location_code
  , position_work_site_location_name::varchar(100)            as position_work_site_location_name
  , position_work_site_address_line1::varchar(100)            as position_work_site_address_line1
  , position_work_site_address_line2::varchar(100)            as position_work_site_address_line2
  , position_work_site_address_line3::varchar(100)            as position_work_site_address_line3
  , position_work_site_address_city::varchar(100)             as position_work_site_address_city
  , position_work_site_address_state_abb::varchar(100)        as position_work_site_address_state_abb
  , position_work_site_address_state::varchar(100)            as position_work_site_address_state
  , position_work_site_address_zip_code::varchar(100)         as position_work_site_address_zip_code
  , position_work_site_address_country::varchar(100)          as position_work_site_address_country
  , home_organizational_units::varchar(100)                   as home_organizational_units
  , home_organizational_units_market_code::varchar(100)       as home_organizational_units_market_code
  , home_organizational_units_market_name_1::varchar(100)     as home_organizational_units_market_name_1
  , home_organizational_units_market_name_2::varchar(100)     as home_organizational_units_market_name_2
  , home_organizational_units_department_code::varchar(100)   as home_organizational_units_department_code
  , home_organizational_units_department_name_1::varchar(100) as home_organizational_units_department_name_1
  , home_organizational_units_department_name_2::varchar(100) as home_organizational_units_department_name_2
  , home_organizational_units_cost_num::varchar(100)          as home_organizational_units_cost_num
  , position_cost_num_legal_code::varchar(100)                as position_cost_num_legal_code
  , position_cost_num_region_code::varchar(100)               as position_cost_num_region_code
  , position_cost_num_market_code::varchar(100)               as position_cost_num_market_code
  , position_cost_num_location_code::varchar(100)             as position_cost_num_location_code
  , position_cost_num_team_code::varchar(100)                 as position_cost_num_team_code
  , position_cost_num_natural_account::varchar(100)           as position_cost_num_natural_account
  , position_cost_num_category::varchar(100)                  as position_cost_num_category
  , occupational_classifications::varchar(100)                as occupational_classifications
  , occupational_classifications_eeo_code::varchar(100)       as occupational_classifications_eeo_code
  , occupational_classifications_eeo_class_p2::varchar(100)   as occupational_classifications_eeo_class_p2
  , occupational_classifications_eeo_class_p1::varchar(100)   as occupational_classifications_eeo_class_p1
  , occupational_classifications_class_code::varchar(100)     as occupational_classifications_class_code
  , occupational_classifications_class::varchar(100)          as occupational_classifications_class
  , position_eeo_class::varchar(100)                          as position_eeo_class
  , position_department_name::varchar(100)                    as position_department_name
  , position_market_name::varchar(100)                        as position_market_name
  , reporting_office::varchar(100)                            as reporting_office
from {{ source('aux', 'employee_overrides') }}