select
    json:COMMENT::VARCHAR(100)                                     as comment
  , json:POSITION_ID::VARCHAR(100)                                 as position_id
  , json:START_DATE::TEXT                                          as start_date
  , json:END_DATE::TEXT                                            as end_date
  , json:IS_DELETED::INT                                           as is_deleted
  , json:ASSOCIATE_ID::VARCHAR(50)                                 as associate_id
  , json:EMPLOYEE_ID::VARCHAR(50)                                  as employee_id
  , json:EMPLOYEE_NUM::VARCHAR(50)                                 as employee_num
  , json:EMPLOYMENT_STATUS::VARCHAR(50)                            as employment_status
  , json:VOL_INVOL::VARCHAR(50)                                    as vol_invol
  , json:CHANGE_REASON_CODE::VARCHAR(50)                           as change_reason_code
  , json:CHANGE_REASON_DESCRIPTION::VARCHAR(100)                   as change_reason_description
  , json:HIRE_DETAILS::VARCHAR(100)                                as hire_details
  , json:SOURCE::VARCHAR(100)                                      as source
  , json:JOB_FUNCTION_CODE::VARCHAR(100)                           as job_function_code
  , json:ASSOCIATE_ORIGINAL_HIRE_DATE::TEXT                        as associate_original_hire_date
  , json:ASSOCIATE_REHIRE_DATE::TEXT                               as associate_rehire_date
  , json:ASSOCIATE_FINAL_TERMINATION_DATE::TEXT                    as associate_final_termination_date
  , json:ASSOCIATE_LEGAL_NAME_FIRST::VARCHAR(100)                  as associate_legal_name_first
  , json:ASSOCIATE_LEGAL_NAME_MIDDLE::VARCHAR(100)                 as associate_legal_name_middle
  , json:ASSOCIATE_LEGAL_NAME_LAST::VARCHAR(100)                   as associate_legal_name_last
  , json:ASSOCIATE_LEGAL_NAME_FULL::VARCHAR(100)                   as associate_legal_name_full
  , json:ASSOCIATE_PREFERRED_NAME::VARCHAR(100)                    as associate_preferred_name
  , json:ASSOCIATE_LEGAL_NAME_SUFFIX::VARCHAR(100)                 as associate_legal_name_suffix
  , json:ASSOCIATE_BIRTH_DATE::TEXT                                as associate_birth_date
  , json:ASSOCIATE_GENDER_CODE::VARCHAR(100)                       as associate_gender_code
  , json:ASSOCIATE_GENDER_NAME::VARCHAR(100)                       as associate_gender_name
  , json:ASSOCIATE_PERSONAL_EMAIL::VARCHAR(100)                    as associate_personal_email
  , json:ASSOCIATE_PERSONAL_PHONE::VARCHAR(100)                    as associate_personal_phone
  , json:ASSOCIATE_PERSONAL_CELL_PHONE::VARCHAR(100)               as associate_personal_cell_phone
  , json:ASSOCIATE_LEGAL_ADDRESS_LINE1::VARCHAR(100)               as associate_legal_address_line1
  , json:ASSOCIATE_LEGAL_ADDRESS_LINE2::VARCHAR(100)               as associate_legal_address_line2
  , json:ASSOCIATE_LEGAL_ADDRESS_CITY::VARCHAR(100)                as associate_legal_address_city
  , json:ASSOCIATE_LEGAL_ADDRESS_STATE_ABB::VARCHAR(100)           as associate_legal_address_state_abb
  , json:ASSOCIATE_LEGAL_ADDRESS_STATE::VARCHAR(100)               as associate_legal_address_state
  , json:ASSOCIATE_LEGAL_ADDRESS_ZIP_CODE::VARCHAR(100)            as associate_legal_address_zip_code
  , json:ASSOCIATE_LEGAL_ADDRESS_COUNTRY::VARCHAR(100)             as associate_legal_address_country
  , json:ASSOCIATE_OTHER_ADDRESS_LINE1::VARCHAR(100)               as associate_other_address_line1
  , json:ASSOCIATE_OTHER_ADDRESS_LINE2::VARCHAR(100)               as associate_other_address_line2
  , json:ASSOCIATE_OTHER_ADDRESS_CITY::VARCHAR(100)                as associate_other_address_city
  , json:ASSOCIATE_OTHER_ADDRESS_STATE_ABB::VARCHAR(100)           as associate_other_address_state_abb
  , json:ASSOCIATE_OTHER_ADDRESS_STATE::VARCHAR(100)               as associate_other_address_state
  , json:ASSOCIATE_OTHER_ADDRESS_ZIP_CODE::VARCHAR(100)            as associate_other_address_zip_code
  , json:ASSOCIATE_OTHER_ADDRESS_COUNTRY::VARCHAR(100)             as associate_other_address_country
  , json:ASSOCIATE_EEO_ETHNICITY::VARCHAR(100)                     as associate_eeo_ethnicity
  , json:ASSOCIATE_EEO_IDENTIFICATION_METHOD::VARCHAR(100)         as associate_eeo_identification_method
  , json:ASSOCIATE_EDUCATION::VARCHAR(100)                         as associate_education
  , json:ASSOCIATE_WORK_EMAIL::VARCHAR(100)                        as associate_work_email
  , json:ASSOCIATE_WORK_PHONE::VARCHAR(100)                        as associate_work_phone
  , json:ASSOCIATE_WORK_CELL_PHONE::VARCHAR(100)                   as associate_work_cell_phone
  , json:POSITION_COMPANY_CODE::VARCHAR(100)                       as position_company_code
  , json:POSITION_STATUS_CODE::VARCHAR(100)                        as position_status_code
  , json:POSITION_STATUS::VARCHAR(100)                             as position_status
  , json:POSITION_SENIORITY_HIRE_DATE::TEXT                        as position_seniority_hire_date
  , json:POSITION_START_DATE::TEXT                                 as position_start_date
  , json:POSITION_TERMINATION_DATE::TEXT                           as position_termination_date
  , json:POSITION_CHANGE_REASON::VARCHAR(100)                      as position_change_reason
  , json:POSITION_REGION_CODE::VARCHAR(100)                        as position_region_code
  , json:POSITION_REGION_DESCRIPTION::VARCHAR(100)                 as position_region_description
  , json:POSITION_REGION_NAME::VARCHAR(100)                        as position_region_name
  , json:POSITION_MANAGER_POSITION_ID::VARCHAR(100)                as position_manager_position_id
  , json:POSITION_MANAGER_NAME::VARCHAR(100)                       as position_manager_name
  , json:POSITION_PRIMARY_JOB_INDICATOR::VARCHAR(100)::INT         as position_primary_job_indicator
  , json:POSITION_TITLE::VARCHAR(100)                              as position_title
  , json:POSITION_TITLE_CODE::VARCHAR(100)                         as position_title_code
  , json:EE_CODE::VARCHAR(100)                                     as ee_code
  , json:POSITION_WORKER_TYPE::VARCHAR(100)                        as position_worker_type
  , json:POSITION_BENEFITS_GROUP_CODE::VARCHAR(100)                as position_benefits_group_code
  , json:POSITION_BENEFITS_GROUP_CLASS::VARCHAR(100)               as position_benefits_group_class
  , json:POSITION_FLSA::VARCHAR(100)                               as position_flsa
  , json:POSITION_FULL_TIME_EQUIVALENT::VARCHAR(100)               as position_full_time_equivalent
  , json:POSITION_SCHEDULED_HOURS::VARCHAR(100)                    as position_scheduled_hours
  , json:POSITION_STANDARD_HOURS::VARCHAR(100)                     as position_standard_hours
  , json:POSITION_WORK_SITE_LOCATION_CODE::VARCHAR(100)            as position_work_site_location_code
  , json:POSITION_WORK_SITE_LOCATION_NAME::VARCHAR(100)            as position_work_site_location_name
  , json:POSITION_WORK_SITE_ADDRESS_LINE1::VARCHAR(100)            as position_work_site_address_line1
  , json:POSITION_WORK_SITE_ADDRESS_LINE2::VARCHAR(100)            as position_work_site_address_line2
  , json:POSITION_WORK_SITE_ADDRESS_LINE3::VARCHAR(100)            as position_work_site_address_line3
  , json:POSITION_WORK_SITE_ADDRESS_CITY::VARCHAR(100)             as position_work_site_address_city
  , json:POSITION_WORK_SITE_ADDRESS_STATE_ABB::VARCHAR(100)        as position_work_site_address_state_abb
  , json:POSITION_WORK_SITE_ADDRESS_STATE::VARCHAR(100)            as position_work_site_address_state
  , json:POSITION_WORK_SITE_ADDRESS_ZIP_CODE::VARCHAR(100)         as position_work_site_address_zip_code
  , json:POSITION_WORK_SITE_ADDRESS_COUNTRY::VARCHAR(100)          as position_work_site_address_country
  , json:HOME_ORGANIZATIONAL_UNITS::VARCHAR(100)                   as home_organizational_units
  , json:HOME_ORGANIZATIONAL_UNITS_MARKET_CODE::VARCHAR(100)       as home_organizational_units_market_code
  , json:HOME_ORGANIZATIONAL_UNITS_MARKET_NAME_1::VARCHAR(100)     as home_organizational_units_market_name_1
  , json:HOME_ORGANIZATIONAL_UNITS_MARKET_NAME_2::VARCHAR(100)     as home_organizational_units_market_name_2
  , json:HOME_ORGANIZATIONAL_UNITS_DEPARTMENT_CODE::VARCHAR(100)   as home_organizational_units_department_code
  , json:HOME_ORGANIZATIONAL_UNITS_DEPARTMENT_NAME_1::VARCHAR(100) as home_organizational_units_department_name_1
  , json:HOME_ORGANIZATIONAL_UNITS_DEPARTMENT_NAME_2::VARCHAR(100) as home_organizational_units_department_name_2
  , json:HOME_ORGANIZATIONAL_UNITS_COST_NUM::VARCHAR(100)          as home_organizational_units_cost_num
  , json:POSITION_COST_NUM_LEGAL_CODE::VARCHAR(100)                as position_cost_num_legal_code
  , json:POSITION_COST_NUM_REGION_CODE::VARCHAR(100)               as position_cost_num_region_code
  , json:POSITION_COST_NUM_MARKET_CODE::VARCHAR(100)               as position_cost_num_market_code
  , json:POSITION_COST_NUM_LOCATION_CODE::VARCHAR(100)             as position_cost_num_location_code
  , json:POSITION_COST_NUM_TEAM_CODE::VARCHAR(100)                 as position_cost_num_team_code
  , json:POSITION_COST_NUM_NATURAL_ACCOUNT::VARCHAR(100)           as position_cost_num_natural_account
  , json:POSITION_COST_NUM_CATEGORY::VARCHAR(100)                  as position_cost_num_category
  , json:OCCUPATIONAL_CLASSIFICATIONS::VARCHAR(100)                as occupational_classifications
  , json:OCCUPATIONAL_CLASSIFICATIONS_EEO_CODE::VARCHAR(100)       as occupational_classifications_eeo_code
  , json:OCCUPATIONAL_CLASSIFICATIONS_EEO_CLASS_P2::VARCHAR(100)   as occupational_classifications_eeo_class_p2
  , json:OCCUPATIONAL_CLASSIFICATIONS_EEO_CLASS_P1::VARCHAR(100)   as occupational_classifications_eeo_class_p1
  , json:OCCUPATIONAL_CLASSIFICATIONS_CLASS_CODE::VARCHAR(100)     as occupational_classifications_class_code
  , json:OCCUPATIONAL_CLASSIFICATIONS_CLASS::VARCHAR(100)          as occupational_classifications_class
  , json:POSITION_EEO_CLASS::VARCHAR(100)                          as position_eeo_class
  , json:POSITION_DEPARTMENT_NAME::VARCHAR(100)                    as position_department_name
  , json:POSITION_MARKET_NAME::VARCHAR(100)                        as position_market_name
  , json:REPORTING_OFFICE::VARCHAR(100)                            as reporting_office
  , json:TITLE_CHANGE_REASON::VARCHAR(100)                         as title_change_reason
  , json:JOB_ID::VARCHAR(100)                                      as job_id
  , json:BU_ALLOCATION::VARCHAR(100)                               as bu_allocation
  , _created_at::timestamp                                         as _created_at
  , _box_file_id::varchar(200)                                     as _box_file_id
from {{ source('aux', 'employee_overrides') }}
