select
FINANCIAL_ACCOUNT_NUMBER
, FINANCIAL_ACCOUNT_NUMBER_CLEAN
, INTERNAL_FINANCIAL_ACCOUNT_NUMBER
, INTERNAL_HOUSEHOLD_NUMBER
, REGISTRANT_NAME
, FINANCIAL_ACCOUNT_NAME
, HOUSEHOLD_NAME
, LOCATION_CODE
, LOCATION_NAME
, TYPE_OF_ACCOUNT
, CUSTODIAN
, SOURCE_SYSTEM_CUSTODIAN
, VERIFIED_CUSTODIAN
, MODEL_INVESTMENT_STRATEGY
, CLIENT_MANAGER
, SOURCE_SYSTEM_CLIENT_MANAGER
, PRIMARY_CLIENT_MANAGER
, FEE_SCHEDULE
, ERISA
, ACCOUNT_ACTIVE
, AUM_CLASSIFICATION_STATUS
, DISCRETION_STATUS
, PROXY_VOTING_STATUS
, COST_BASIS_DISPOSAL_METHOD
, PRIME_BROKER_ENABLED
, ACCOUNT_OPEN_DATE::date as ACCOUNT_OPEN_DATE
, CLOSED_DATE::date as CLOSED_DATE
, SYSTEM_NAME
, UPDATE_DATE::date as UPDATE_DATE
, NOTES
, EFFECTIVE_AT::TIMESTAMPNTZ as EFFECTIVE_AT
, _CREATED_AT::TIMESTAMPNTZ as _CREATED_AT
from {{source('aux', 'hfw_acct_data')}}