name: Build modified models and refresh docs

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-east-2"
  AWS_ROLE_ARN: "arn:aws:iam::436867865803:role/dbt-docs-github-actions"
  DBT_DOCS_BUCKET: "dbt-docs.marinerapi.cloud"
  DBT_USER: ${{ vars.DBT_USER }}
  DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
  DBT_HOST: ${{ vars.DBT_HOST }}
  DBT_STATE: ${{ vars.DB_PROD_ARTIFACTS }}
  DBT_DEFER: True
  DBT_PROFILES_DIR: ${{ vars.DBT_PROFILES_DIR }}
  DBT_TARGET_PATH: ./target
  DBT_TARGET: prod
  PR_NUM: prod


jobs:
  dbt-build:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: [self-hosted]
    concurrency:
      group: deploy-dbt
      cancel-in-progress: false
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Get Python Version
        id: get-python-version
        shell: pwsh
        run: |
          $python_version = python -c "import platform; print(platform.python_version())"
          echo "python version: $python_version"
          echo "PYTHON_VERSION=$python_version" | Out-File -Append -FilePath $env:GITHUB_ENV
          echo "python_version=$python_version" >> $GITHUB_ENV

      - name: Cache venv
        uses: actions/cache@v4
        id: cache-venv
        with:
          path: ./utilities/.venv
          key: dbt-venv-${{ runner.os }}-py${{ env.python_version }}-${{ hashFiles('requirements-ci.txt') }}

      - name: Install python requirements
        shell: pwsh
        run: |
          python -m venv ./utilities/.venv
          ./utilities/.venv/Scripts/Activate.ps1
          echo "cache-hit: ${{ steps.cache-venv.outputs.cache-hit }}"
          if ('${{ steps.cache-venv.outputs.cache-hit }}' -ne 'true') {pip install -r requirements-ci.txt} else {echo "Using cached venv"}

      - name: Cache dbt packages
        uses: actions/cache@v4
        id: cache-dbt-packages
        with:
          path: ./dbt_packages
          key: dbt-packages-${{ runner.os }}-py${{ env.python_version }}-${{ hashFiles('packages.yml') }}

      - name: dbt deps
        shell: pwsh
        run: |
          ./utilities/.venv/Scripts/Activate.ps1
          echo "cache-hit: ${{ steps.cache-dbt-packages.outputs.cache-hit }}"
          if ('${{ steps.cache-dbt-packages.outputs.cache-hit }}' -ne 'true') {dbt deps} else {echo "Using cached dbt packages"}

      - name: dbt build
        shell: pwsh
        run: |
          .\utilities\.venv\Scripts\Activate.ps1
          dbt build --target=$env:DBT_TARGET --select state:modified+1 result:error

      - name: upload dbt artifacts
        shell: pwsh
        run: |
          Write-Host "Copying manifest.json to $($env:DBT_STATE)"
          Copy-Item "./target/manifest.json" -Destination "$($env:DBT_STATE)" -Force
          if (Test-Path -Path "./target/run_results.json" -PathType leaf) {
            Write-Host "Copying run_results.json to $($env:DBT_STATE)"
            Copy-Item "./target/run_results.json" -Destination "$($env:DBT_STATE)" -Force
            } else { Write-Host "run_results.json not found" }
          if (Test-Path -Path "./target/sources.json" -PathType leaf) {
            Write-Host "Copying sources.json to $($env:DBT_STATE)"
            Copy-Item "./target/sources.json" -Destination "$($env:DBT_STATE)" -Force
            } else { Write-Host "sources.json not found" }

  dbt-docs:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: [self-hosted]
    concurrency:
      group: deploy-dbt-docs
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Get Python Version
        id: get-python-version
        shell: pwsh
        run: |
          $python_version = python -c "import platform; print(platform.python_version())"
          echo "python version: $python_version"
          echo "PYTHON_VERSION=$python_version" | Out-File -Append -FilePath $env:GITHUB_ENV
          echo "python_version=$python_version" >> $GITHUB_ENV

      - name: Cache venv
        uses: actions/cache@v4
        id: cache-venv
        with:
          path: ./utilities/.venv
          key: dbt-venv-${{ runner.os }}-py${{ env.python_version }}-${{ hashFiles('requirements-ci.txt') }}

      - name: Install python requirements
        shell: pwsh
        run: |
          echo "cache-hit: ${{ steps.cache-venv.outputs.cache-hit }}"
          if ('${{ steps.cache-venv.outputs.cache-hit }}' -ne 'true') {
            python -m venv ./utilities/.venv
            pip install -r requirements-ci.txt
            ./utilities/.venv/Scripts/Activate.ps1
            } else {echo "Using cached venv"}

      - name: Cache dbt packages
        uses: actions/cache@v4
        id: cache-dbt-packages
        with:
          path: ./dbt_packages
          key: dbt-packages-${{ runner.os }}-py${{ env.python_version }}-${{ hashFiles('packages.yml') }}

      - name: dbt deps
        shell: pwsh
        run: |
          ./utilities/.venv/Scripts/Activate.ps1
          echo "cache-hit: ${{ steps.cache-dbt-packages.outputs.cache-hit }}"
          if ('${{ steps.cache-dbt-packages.outputs.cache-hit }}' -ne 'true') {dbt deps} else {echo "Using cached dbt packages"}

      - name: dbt docs generate
        shell: pwsh
        run: |
          .\utilities\.venv\Scripts\Activate.ps1
          dbt compile --target=$env:DBT_TARGET
          dbt docs generate --target=$env:DBT_TARGET --no-compile

      - name: Upload the docs
        shell: pwsh
        run: |
          .\utilities\.venv\Scripts\Activate.ps1
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          aws s3 sync ./target/ s3://${{ env.DBT_DOCS_BUCKET }}/${{ env.PR_NUM }}/ --delete
