name: Deploy PR DBT Models to Temp Schema in Snowflake

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

env:
  DBT_USER: ${{ vars.DBT_USER }}
  DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
  DBT_HOST: ${{ vars.DBT_HOST }}
  DBT_STATE: ${{ vars.DB_PROD_ARTIFACTS }}
  DBT_DEFER: True
  DBT_PROFILES_DIR: ${{ vars.DBT_PROFILES_DIR }}
  PR_NUM: ${{ github.event.number }}


jobs:
  run:
    if: github.event.pull_request.draft == false
    runs-on: self-hosted
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v4

      # https://paulfry999.medium.com/v0-4-pre-chatgpt-how-to-create-ci-cd-pipelines-for-dbt-core-88e68ab506dd
      # https://www.vantage-ai.com/blog/how-to-use-slim-ci-with-dbt-core
      # https://www.datafold.com/blog/accelerating-dbt-core-ci-cd-with-github-actions-a-step-by-step-guide

      - name: Cache Python virtual environment
        uses: actions/cache@v3
        with:
          path: .\utilities\.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements-ci.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Cache dbt dependencies
        uses: actions/cache@v3
        with:
          path: .dbt
          key: ${{ runner.os }}-dbt-deps-${{ hashFiles('**/dbt_project.yml') }}
          restore-keys: |
            ${{ runner.os }}-dbt-deps-

      - name: Set up environment
        shell: pwsh
        run: |
          python -m venv .\utilities\.venv
          .\utilities\.venv\Scripts\Activate.ps1
          pip install -r requirements-ci.txt

      - name: dbt deps
        shell: pwsh
        run: |
          .\utilities\.venv\Scripts\Activate.ps1
          dbt deps

      - name: dbt run
        shell: pwsh
        run: |
          .\utilities\.venv\Scripts\Activate.ps1
          dbt build --target ci --select state:modified.body+ state:modified.persisted_descriptions+ state:modified.relation+ state:modified.macros+ state:modified.contract+
