# https://paulfry999.medium.com/v0-4-pre-chatgpt-how-to-create-ci-cd-pipelines-for-dbt-core-88e68ab506dd
# https://www.vantage-ai.com/blog/how-to-use-slim-ci-with-dbt-core
# https://www.datafold.com/blog/accelerating-dbt-core-ci-cd-with-github-actions-a-step-by-step-guide

name: Build PR

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - models/**
      - tests/**
      - macros/**
      - snapshots/**
      - seeds/**
      - packages.yml
      - requirements*

env:
  AWS_REGION: "us-east-2"
  AWS_ROLE_ARN: "arn:aws:iam::436867865803:role/dbt-docs-github-actions"
  DBT_DOCS_BUCKET: "dbt-docs.marinerapi.cloud"
  DBT_USER: ${{ vars.DBT_USER }}
  DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
  DBT_HOST: ${{ vars.DBT_HOST }}
  ARTIFACTS_ROOT_DIR: ${{ vars.ARTIFACTS_ROOT_DIR }}
  DBT_STATE: ${{ vars.ARTIFACTS_ROOT_DIR }}/prod_artifacts
  DBT_DEFER: True
  DBT_PROFILES_DIR: ${{ vars.DBT_PROFILES_DIR }}
  DBT_TARGET_PATH: ./target
  DBT_TARGET: ci
  SNOWSQL_USER: ${{ vars.DBT_USER }}
  SNOWSQL_PWD: ${{ secrets.DBT_PASSWORD }}
  SNOWSQL_ACCOUNT: ${{ vars.DBT_HOST }}
  SNOWSQL_DATABASE: DBT
  SNOWSQL_SCHEMA: DBT
  SNOWSQL_ROLE: engineering
  PR_NUM: ${{ github.event.number }}


jobs:
  dbt-build:
    if: (!contains(github.event.pull_request.labels.*.name, 'skip-ci'))
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: [self-hosted]
    concurrency:
      group: pr-${{ github.event.number }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Get Python Version
        id: get-python-version
        shell: pwsh
        run: |
          $python_version = python -c "import platform; print(platform.python_version())"
          echo "python version: $python_version"
          echo "PYTHON_VERSION=$python_version" | Out-File -Append -FilePath $env:GITHUB_ENV
          echo "python_version=$python_version" >> $GITHUB_ENV

      - name: Cache venv
        uses: actions/cache@v4
        id: cache-venv
        with:
          path: ./utilities/.venv
          key: dbt-venv-${{ runner.os }}-py${{ env.python_version }}-${{ hashFiles('requirements-ci.txt') }}

      - name: Install python requirements
        shell: pwsh
        run: |
          $venv_dir = ".\utilities\.venv"
          echo "cache-hit: ${{ steps.cache-venv.outputs.cache-hit }}"
          if ('${{ steps.cache-venv.outputs.cache-hit }}' -ne 'true') {
            if ((Test-Path -Path "$venv_dir" -PathType Container)) {
              Write-Host "Removing existing venv"
              Remove-Item -Path "$venv_dir" -Force -Recurse
            } else {
              Write-Host "Did not detect existing venv $venv_dir"
            }
            Write-Host "Creating venv"
            python -m venv $venv_dir
            Write-Host "Installing requirements"
            & "$venv_dir\Scripts\Activate.ps1"
            pip install -r requirements-ci.txt
          } else {echo "Using cached venv"}

      - name: Cache dbt packages
        uses: actions/cache@v4
        id: cache-dbt-packages
        with:
          path: ./dbt_packages
          key: dbt-packages-${{ runner.os }}-py${{ env.python_version }}-${{ hashFiles('packages.yml') }}

      - name: Set source DB vars
        shell: pwsh
        run: |
          $labelExists = "${{ contains(github.event.pull_request.labels.*.name, 'use-dev-sources') }}"
          if ($labelExists -eq 'true') {
            echo "DBT_DB_RAW_SRC=raw_dev" | Out-File -Append -FilePath $env:GITHUB_ENV
            echo "DBT_DB_DATALAKE_SRC=datalake_dev" | Out-File -Append -FilePath $env:GITHUB_ENV
            echo "DBT_DB_EDW_SRC=edw_dev" | Out-File -Append -FilePath $env:GITHUB_ENV
            }

      - name: Create PR Databases
        shell: pwsh
        run: |
          $sql = @"
          create database if not exists datalake_$($env:PR_NUM);
          create database if not exists edw_$($env:PR_NUM);
          create database if not exists odw_$($env:PR_NUM);
          create database if not exists oracle_fusion_$($env:PR_NUM);
          create schema if not exists dbt.pr_$($env:PR_NUM);
          "@
          Write-Host $sql
          snowsql -q "$sql"

      - name: dbt deps
        shell: pwsh
        run: |
          ./utilities/.venv/Scripts/Activate.ps1
          echo "cache-hit: ${{ steps.cache-dbt-packages.outputs.cache-hit }}"
          if ('${{ steps.cache-dbt-packages.outputs.cache-hit }}' -ne 'true') {dbt deps} else {echo "Using cached dbt packages"}

      - name: dbt clone
        shell: pwsh
        run: |
          .\utilities\.venv\Scripts\Activate.ps1
          dbt clone --target=$env:DBT_TARGET --select state:modified+1,config.materialized:incremental,state:old

      - name: dbt build
        shell: pwsh
        run: |
          .\utilities\.venv\Scripts\Activate.ps1
          dbt build --target=$env:DBT_TARGET --fail-fast -s state:modified.body+1 state:modified.configs state:modified.persisted_descriptions state:modified.macros+1 state:modified.contract

      - name: upload dbt artifacts
        shell: pwsh
        run: |
          $branch = "${{ github.event.pull_request.head.ref }}"
          $dest_dir = "$($env:ARTIFACTS_ROOT_DIR)/$branch"
          if (!(Test-Path -Path "$dest_dir")) {
            New-Item -Path "$dest_dir" -ItemType Directory
          }
          Write-Host "Copying manifest.json to $dest_dir"
          Copy-Item "./target/manifest.json" -Destination "$dest_dir" -Force
          if (Test-Path -Path "./target/run_results.json" -PathType leaf) {
            Write-Host "Copying run_results.json to $dest_dir"
            Copy-Item "./target/run_results.json" -Destination "$dest_dir" -Force
            } else { Write-Host "run_results.json not found" }
          if (Test-Path -Path "./target/sources.json" -PathType leaf) {
            Write-Host "Copying sources.json to $dest_dir"
            Copy-Item "./target/sources.json" -Destination "$dest_dir" -Force
            } else { Write-Host "sources.json not found" }

  dbt-docs:
    if: ((needs.dbt-build.result == 'success') && contains(github.event.pull_request.labels.*.name, 'build-docs'))
    needs: dbt-build
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: [self-hosted]
    concurrency:
      group: pr-${{ github.event.number }}-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Get Python Version
        id: get-python-version
        shell: pwsh
        run: |
          $python_version = python -c "import platform; print(platform.python_version())"
          echo "python version: $python_version"
          echo "PYTHON_VERSION=$python_version" | Out-File -Append -FilePath $env:GITHUB_ENV
          echo "python_version=$python_version" >> $GITHUB_ENV

      - name: Cache venv
        uses: actions/cache@v4
        id: cache-venv
        with:
          path: ./utilities/.venv
          key: dbt-venv-${{ runner.os }}-py${{ env.python_version }}-${{ hashFiles('requirements-ci.txt') }}

      - name: Install python requirements
        shell: pwsh
        run: |
          $venv_dir = ".\utilities\.venv"
          echo "cache-hit: ${{ steps.cache-venv.outputs.cache-hit }}"
          if ('${{ steps.cache-venv.outputs.cache-hit }}' -ne 'true') {
            if ((Test-Path -Path "$venv_dir" -PathType Container)) {
              Write-Host "Removing existing venv"
              Remove-Item -Path "$venv_dir" -Force -Recurse
            } else {
              Write-Host "Did not detect existing venv $venv_dir"
            }
            Write-Host "Creating venv"
            python -m venv $venv_dir
            Write-Host "Installing requirements"
            & "$venv_dir\Scripts\Activate.ps1"
            pip install -r requirements-ci.txt
          } else {echo "Using cached venv"}

      - name: Cache dbt packages
        uses: actions/cache@v4
        id: cache-dbt-packages
        with:
          path: ./dbt_packages
          key: dbt-packages-${{ runner.os }}-py${{ env.python_version }}-${{ hashFiles('packages.yml') }}

      - name: dbt deps
        shell: pwsh
        run: |
          ./utilities/.venv/Scripts/Activate.ps1
          echo "cache-hit: ${{ steps.cache-dbt-packages.outputs.cache-hit }}"
          if ('${{ steps.cache-dbt-packages.outputs.cache-hit }}' -ne 'true') {dbt deps} else {echo "Using cached dbt packages"}

      - name: dbt docs generate
        shell: pwsh
        run: |
          .\utilities\.venv\Scripts\Activate.ps1
          dbt compile --target=$env:DBT_TARGET
          dbt docs generate --target=$env:DBT_TARGET --no-compile

      - name: Upload the docs
        shell: pwsh
        run: |
          .\utilities\.venv\Scripts\Activate.ps1
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          aws s3 sync ./target/ s3://${{ env.DBT_DOCS_BUCKET }}/${{ env.PR_NUM }}/ --delete
