name: Drop PR Schema

on:
  pull_request:
    types: [ closed ]

env:
  AWS_REGION: "us-east-2"
  AWS_ROLE_ARN: "arn:aws:iam::436867865803:role/dbt-docs-github-actions"
  DBT_DOCS_BUCKET: "dbt-docs.marinerapi.cloud"
  ARTIFACTS_ROOT_DIR: ${{ vars.ARTIFACTS_ROOT_DIR }}
  SNOWSQL_USER: ${{ vars.DBT_USER }}
  SNOWSQL_PWD: ${{ secrets.DBT_PASSWORD }}
  SNOWSQL_ACCOUNT: ${{ vars.DBT_HOST }}
  SNOWSQL_DATABASE: DBT
  SNOWSQL_SCHEMA: DBT
  SNOWSQL_ROLE: engineering
  PR_NUM: ${{ github.event.number }}

jobs:
  drop-pr-schema:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: self-hosted
    concurrency:
      group: pr-${{ github.event.number }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: drop pr schema
        shell: pwsh
        env:
          PR_NUM: ${{ github.event.number }}
        run: |
          $drop_sql = "drop schema if exists $($env:SNOWSQL_DATABASE).PR_$($env:PR_NUM);"
          Write-Host $drop_sql
          snowsql -q "$drop_sql"

      - name: Delete the Docs
        run: |
          .\utilities\.venv\Scripts\Activate.ps1
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          aws s3 rm s3://${{ env.DBT_DOCS_BUCKET }}/${{ env.PR_NUM }} --recursive

      - name: Delete artifacts
        shell: pwsh
        run: |
          $dest_dir = "$($env:ARTIFACTS_ROOT_DIR)/pr_$($env:PR_NUM)"
          if (Test-Path -Path "$dest_dir") {
            Write-Host "Deleting $dest_dir"
            rm $dest_dir -r -force
          }
