name: Remove temp schema upon PR closure

on:
  pull_request:
    types: [ closed ]

env:
  DBT_USER: ${{ vars.DBT_USER }}
  DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
  DBT_HOST: ${{ vars.DBT_HOST }}
  DBT_PROFILES_DIR: ${{ vars.DBT_PROFILES_DIR }}

jobs:
  pr_closed:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup env and drop pr schema
        shell: pwsh
        env:
          # set PR_NUM to pass to the python script
          PR_NUM: ${{ github.event.number }}
        run: |
          & python -m venv .\utilities\.venv
          & .\utilities\.venv\Scripts\Activate.ps1
          & pip install -r requirements-ci.txt
          & dbt deps
          & dbt run-operation drop_pr_schema --target=ci
