name: Lint SQL

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - models/**/*sql
      - tests/**/*sql
      - macros/**/*sql
      - snapshots/**/*sql
      - seeds/**/*sql

env:
  VENV_DIR: "./.venv"

jobs:
  lint-changed:
    if: (!contains(github.event.pull_request.labels.*.name, 'skip-lint'))
    runs-on: [self-hosted]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Python Version
        id: get-python-version
        shell: pwsh
        run: |
          $python_version = python -c "import platform; print(platform.python_version())"
          echo "python version: $python_version"
          echo "PYTHON_VERSION=$python_version" | Out-File -Append -FilePath $env:GITHUB_ENV
          echo "python_version=$python_version" >> $GITHUB_ENV

      - name: Setup just
        uses: extractions/setup-just@v1

      - name: Install python requirements
        shell: pwsh
        run: |
          $venv_dir = "$env:VENV_DIR"
          Write-Host "Creating venv"
          uv venv $venv_dir --python 3.12.10
          Invoke-Expression "$venv_dir\Scripts\Activate.ps1"
          Write-Host "Installing requirements"
          uv pip install -r requirements-ci.txt

      - name: Lint changed files
        shell: pwsh
        run: |
          $venv_dir = "$env:VENV_DIR"
          Invoke-Expression "$venv_dir\Scripts\Activate.ps1"
          just lint_changed
